### ISSUE TITLE
Firewalld Config 1.1.1 Error

### ISSUE THREAD

**Issue by gh4wi** [firewalld/firewalld#1004]
Mint 21 Cinnamon Firewalld Config 1.1.1 gives an Error when clicking on Options / Runtime-to-Permanemt.
The Error says "Not_Enabled: enp2s0"
The enp2s0 name & number may be different on you PC.
I have no idea what to add or change.
Please fix ....

**Comment by erig0** [comment]
Duplicate of #976.
