### ISSUE TITLE
use go-dbus to add permanent port occur error

### ISSUE THREAD

**Issue by fengjian1993** [firewalld/firewalld#1008]
**What happened**:
use go-dbus to add permanent port occur error:
Method "addPort" with signature "ss" on interface "org.fedoraproject.FirewallD1.config.zone"

**What you expected to happen**:
no error

**How to reproduce it (as minimally and precisely as possible)**:
obj := conn.Object("org.fedoraproject.FirewallD1", "/org/fedoraproject/FirewallD1/config/zone/public")
err = obj.Call("org.fedoraproject.FirewallD1.config.zone.addPort", 0, port, "tcp").Store(&ret)

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):
root@debian:~/tool# firewall-cmd -V
0.9.3
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 
- OS (e.g: `cat /etc/os-release`):
root@debian:~/tool# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Others:

**Comment by fengjian1993** [comment]
i read from here: https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.config.zone

addPort(s: port, s: protocol) → Nothing
Permanently add (port, protocol) to list of ports of zone. See port tag in [firewalld.zone(5)](https://firewalld.org/documentation/man-pages/firewalld.zone.html). For runtime operation see [org.fedoraproject.FirewallD1.zone.Methods.addPort](https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.zone.Methods.addPort).

Possible errors: ALREADY_ENABLED

**Comment by TorontoMedia** [comment]
`"/org/fedoraproject/FirewallD1/config/zone/public"` is not a valid object path. You must first call the dbus method `getZoneByName` to acquire the valid path, since they are listed as integers.


Example:
```sh
dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply /org/fedoraproject/FirewallD1/config/zone org.freedesktop.DBus.Introspectable.Introspect
```
Output:
```
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <node name="0"/>
  <node name="1"/>
  <node name="10"/>
  <node name="11"/>
  <node name="2"/>
  <node name="3"/>
  <node name="4"/>
  <node name="5"/>
  <node name="6"/>
  <node name="7"/>
  <node name="8"/>
  <node name="9"/>
</node>
```

To get the path to the public zone:
```sh
dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1/config org.fedoraproject.FirewallD1.config.getZoneByName string:"public"
```

Output:
```
/org/fedoraproject/FirewallD1/config/zone/9
```

**Comment by fengjian1993** [comment]
> `"/org/fedoraproject/FirewallD1/config/zone/public"` is not a valid object path. You must first call the dbus method `getZoneByName` to acquire the valid path, since they are listed as integers.
> 
> Example:
> 
> ```shell
> dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply /org/fedoraproject/FirewallD1/config/zone org.freedesktop.DBus.Introspectable.Introspect
> ```
> 
> Output:
> 
> ```
> <!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
> "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
> <node>
>   <node name="0"/>
>   <node name="1"/>
>   <node name="10"/>
>   <node name="11"/>
>   <node name="2"/>
>   <node name="3"/>
>   <node name="4"/>
>   <node name="5"/>
>   <node name="6"/>
>   <node name="7"/>
>   <node name="8"/>
>   <node name="9"/>
> </node>
> ```
> 
> To get the path to the public zone:
> 
> ```shell
> dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1/config org.fedoraproject.FirewallD1.config.getZoneByName string:"public"
> ```
> 
> Output:
> 
> ```
> /org/fedoraproject/FirewallD1/config/zone/9
> 

> `"/org/fedoraproject/FirewallD1/config/zone/public"` is not a valid object path. You must first call the dbus method `getZoneByName` to acquire the valid path, since they are listed as integers.
> 
> Example:
> 
> ```shell
> dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply /org/fedoraproject/FirewallD1/config/zone org.freedesktop.DBus.Introspectable.Introspect
> ```
> 
> Output:
> 
> ```
> <!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
> "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
> <node>
>   <node name="0"/>
>   <node name="1"/>
>   <node name="10"/>
>   <node name="11"/>
>   <node name="2"/>
>   <node name="3"/>
>   <node name="4"/>
>   <node name="5"/>
>   <node name="6"/>
>   <node name="7"/>
>   <node name="8"/>
>   <node name="9"/>
> </node>
> ```
> 
> To get the path to the public zone:
> 
> ```shell
> dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1/config org.fedoraproject.FirewallD1.config.getZoneByName string:"public"
> ```
> 
> Output:
> 
> ```
> /org/fedoraproject/FirewallD1/config/zone/9
> ```

many thanks~
