### ISSUE TITLE
Add Warpinator as a preconfigured service

### ISSUE THREAD

**Issue by q1800** [firewalld/firewalld#1016]
### What would you like to be added

Can you please add a preconfigured service to FirewallD to allow Warpinator to be easier to use with FirewallD.

Warpinator is a Linux Mint application/project. It is also available on other Linux distributions (including Flatpak/Flathub), Windows, Android, and iOS.

Here is a link to the Linux Mint repo for Warpinator.

https://github.com/linuxmint/warpinator

Here is a more specific link to the firewall section of the project README.md that details the ports/protocols that are required.

https://github.com/linuxmint/warpinator#make-sure-your-firewall-is-configured-properly-if-one-is-being-used

**Short Synopsis**

Port 42000 is used for transfers
Port 42001 is used for authentication

In current versions of Warpinator (after 1.2.0), only TCP is required, but you should also allow UDP traffic on the transfer port to allow connections with older Warpinator versions.

### Why is this needed

I believe that adding this preconfigured service to FirewallD would make it a lot easier for people to use Warpinator with FirewallD. Adding this would save people time and frustration with not having to set these ports/protocols manually & troubleshooting when things don't work out of the box the first time.

**Comment by erig0** [comment]
This was fixed via #1021, but the commit omitted the `Fixes` tag.
