### ISSUE TITLE
llmnr-udp service does not allow unicast replies

### ISSUE THREAD

**Issue by yrro** [firewalld/firewalld#1029]
### What happened

I've added `llmnr-udp` to a zone. When I perform an llmnr query with `systemctl resolve hostname`, the firewall is blocking the responses (from a Windows 10 machine):

```
Sep 30 13:50:31 kernel: filter_IN_home_REJECT: IN=enp0s3 OUT= MAC=xx:xx:xx:xx:xx:xx:yy:yy:yy:yy:yy:yy:08:00 SRC=fe80:0000:0000:0000:xxxx:xxxx:xxxx:xxxx DST=fe80:0000:0000:0000:xxxx:xxxx:xxxx:xxxx LEN=104 TC=0 HOPLIMIT=128 FLOWLBL=867507 PROTO=UDP SPT=5355 DPT=5355 LEN=64 
Sep 30 13:50:31 kernel: filter_IN_home_REJECT: IN=enp0s3 OUT= MAC=xx:xx:xx:xx:xx:xx:yy:yy:yy:yy:yy:yy:86:dd SRC=192.0.2.11 DST=192.0.2.15 LEN=72 TOS=0x00 PREC=0x00 TTL=128 ID=36621 PROTO=UDP SPT=5355 DPT=5355 LEN=52 
```

Note that the destination address of the responses is not the LLMNR multicast address; it's the unicast address of the machine that transmitted the query.

### What you expected to happen

The firewall should allow LLMNR responses through when the `llmnr-udp` service is added to a zone.

### How to reproduce it (as minimally and precisely as possible)

In `firewalld.conf`, set `LogDenied=unicast` and restart `firewalld`.

```
# firewall-cmd --zone=public --add-service=llmnr
```

Assuming `somehost` is the name of a host that will respond when it receives an LLMNR query:

```
# resolvectl query somehost
```

Check the log messages:

```
# dmesg | grep -w 5355
```

Responses from `somehost` are logged & hence rejected.

### Anything else we need to know?

The definition of the `llmnr-udp` service only allows packets transmitted to the LLMNR multicast address. But Windows 10 responds with packets transmitted to the unicast address of the querier.

```
# firewall-cmd --info-service=llmnr-udp
llmnr-udp
  ports: 5355/udp
  protocols: 
  source-ports: 
  modules: 
  destination: ipv4:224.0.0.252 ipv6:ff02::1:3
  includes: 
  helpers: 
```

Workaround: add the port `5355/udp` instead of the `llmnr-udp` service.

```
# firewall-cmd --zone=public --add-port=5355/udp
```

### Firewalld Version

1.2.0

### Firewalld Backend

nftables

### Linux distribution

Debian testing/unstable

### Linux kernel version

5.19.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.6-1 (2022-09-01)

### Other information
[RFC 4795 s.2](https://www.rfc-editor.org/rfc/rfc4795#section-2) states "A responder responds to a multicast query by sending a unicast UDP response to the sender." so the correct thing to do is to remove the restriction to the `llmnr-udp` service that causes it to only match multicast packets.

**Comment by erig0** [comment]
Hrm, `llmnr-udp` allows udp queries. But as you note, it's the _reply_ that's not allowed.

[rfc 4795 section 2.3](https://www.rfc-editor.org/rfc/rfc4795#section-2.3) states:
> (b)  Responders MUST direct responses to the port from which the
        query was sent.  When queries are received via TCP, this is an
        inherent part of the transport protocol.  For queries received
        by UDP, the responder MUST take note of the source port and use
        that as the destination port in the response.  Responses MUST
        always be sent from the port to which they were directed.

AFAICS, the source port is arbitrary and determined by the sender. As such, the only way to handle this is with connection tracking. llmnr does not have in kernel conntrack support and firewalld currently lacks support for conntrackd.

Your example looks like the source port happens to be `5355/udp`, but I don't think that's defined by the protocol.

**Comment by erig0** [comment]
I think this requires both conntrackd support AND support for llmnr in conntrackd.

**Comment by yrro** [comment]
I wondered why `llmnr-udp` has destination addresses specified at all? What is the disadvantage to removing it from the service definition?

Same quesion for `mdns` I suppose, which also has multicast destinations specified in its service definition; this doesn't break the normal use case because MDNS responses are specified to be transmitted to the MDNS multicast address, unlike LLMNR; however there are a few scenarios where MDNS responses will be sent to the querier's unicast address, which are also blocked by firewalld, for instance 'legacy' queries which are useful for debugging, as sent with `dig -p 5353 @192.0.2.1 hostname.local`, are blocked by firewall even though the remote host has the `mdns` service added...

**Comment by erig0** [comment]
> I wondered why `llmnr-udp` has destination addresses specified at all? What is the disadvantage to removing it from the service definition?

Well, if you remove the multicast destination scoping then you'll always accept llmnr replies even if the host has not sent a query. You also **do not know which port to accept**. Could be 5355 or any other UDP port as per the protocol/rfc.

> Same quesion for `mdns` I suppose, which also has multicast destinations specified in its service definition; this doesn't break the normal use case because MDNS responses are specified to be transmitted to the MDNS multicast address, unlike LLMNR; however there are a few scenarios where MDNS responses will be sent to the querier's unicast address, which are also blocked by firewalld, for instance 'legacy' queries which are useful for debugging, as sent with `dig -p 5353 @192.0.2.1 hostname.local`, are blocked by firewall even though the remote host has the `mdns` service added...

Right. I don't know if connection tracking can help. It does not know whom to accept the unicast reply from. mbns query/reply works because query and reply is multicast. Conntrack will create an entry using the multicast address. I would guess that llmnr also triggers an entry, but since the reply is unicast it won't match any entry.

You can verify this by looking at the conntrack entries for an UNREPLIED on the llmnr port. e.g. `conntrack -L`.

**Comment by yrro** [comment]
> Well, if you remove the multicast destination scoping then you'll always accept llmnr replies even if the host has not sent a query.

Oh I think I'm starting to understand. While `systemd-resolved` uses the source port 5355, other implementations could use any port. This is why there's a `upnp-client` service that matches on source port. Maybe we need a `llmnr-client` service that matches on source-port `5355/udp`?

**Comment by erig0** [comment]
@yrro, if we can verify that systemd always uses `5355/udp` and Microsoft always uses `62925/udp`, then I suppose we could add a `llmnr-client` service that includes both ports. But outside of that, I don't know how we can address this.

**Comment by yrro** [comment]
`62925/udp` is a red herring, I've run `resolve-dnsname -llmnronly myhost` a few times on a Windows machine and observed different source ports used for each _query_.

But we're talking about matching incoming _responses_ here (which can't be handled by conntrack). These will always be from `5355/udp` (at least, for the usual cast of multicasted queries. Unicasted queries will be handled by regular connection tracking, I think?). So I think the best we can do is follow the example of `upnp-client` and add an `llmnr-client` service, that matches on source port.

**Comment by erig0** [comment]
> So I think the best we can do is follow the example of `upnp-client` and add an `llmnr-client` service, that matches on source port.

Agree. I would merge a PR that adds `llmnr-client`. Please make it clear in the service description that it's specifically to handle _replies_.

**Comment by yrro** [comment]
> May also be worth mentioning it allows all llmnr replies, even unsolicited ones (we didn't send a query).

Good point, I'll make that change.

**Comment by yrro** [comment]
I think the same warning should be applied to upnp-client - shall I apply it there too once we agree on the wording?

**Comment by erig0** [comment]
> I think the same warning should be applied to upnp-client - shall I apply it there too once we agree on the wording?

Yes please.

**Comment by yrro** [comment]
FYI I did a quick search for other llmnr implementations on Linux. I only found `llmnrd`, which is not so active (in a bug report the author suggests that people are probably using `systemd-resolved` these days), is shipped in Debian (but a 5 year old release, with 14 installs reported by [popcon](https://qa.debian.org/popcon.php?package=llmnrd)). Looking through the [llmnr-query.c](https://github.com/tklauser/llmnrd/blob/master/llmnr-query.c) quickly, I don't see any calls to `bind` so it does probably use a random source port which would require the approach of creating a `llmnr-client` service that matches based on source port.

Anyway, I didn't find any other llmnr implementations on Linux. So it may be worth reconsidering whether the disadvantages of the `llmnr-client` approach with a source-port patch are really worth it to support just this one non-mainstream llmnr implementation; as opposed to changing the `llmnr` service to not check the destination address at all...

**Comment by erig0** [comment]
> Anyway, I didn't find any other llmnr implementations on Linux. So it may be worth reconsidering whether the disadvantages of the `llmnr-client` approach with a source-port patch are really worth it to support just this one non-mainstream llmnr implementation; as opposed to changing the `llmnr` service to not check the destination address at all...

So you're saying: Since Linux implementations (except `llmnrd`) always use source port `5355`, we can remove the multicast address match from the `llmnr-udp` service. That will allow replies to be received.

This is an alternative solution to adding an `llmnr-client` service to match the source port.

Both solutions have the con that they will allow unsolicited replies.
Removing the multicast match has the additional con that it could break at some point (as per RFC): different llmnr implementation, or systemd starts using a random port.

Neither is great. I lean toward `llmnr-client`. There is already precedence from `upnp-client`.
