### ISSUE TITLE
How to give a pre created forward zone to firewalld

### ISSUE THREAD

**Issue by IT21092374** [firewalld/firewalld#1032]

**Comment by erig0** [comment]
I'm exactly sure what you're asking. I'm guessing you're asking how to ship a "stock" firewalld policy that allows forwarding between zones.

- any zone/policy/etc. in `/usr/lib/firewalld/` is "stock"
- any zone/policy/etc. in `/etc/firewalld/` is user config

So you can

1. create a policy
2. move it to `/usr/lib`  
e.g.  
```
# mv /etc/firewalld/policy/mypolicy.xml /usr/lib/firewalld/policy/mypolicy.xml
```
3. Do `firewall-cmd --reload`

**Comment by IT21092374** [comment]
Thank you so much


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
