### ISSUE TITLE
firewalld.service won't boot up

### ISSUE THREAD

**Issue by Impeta** [firewalld/firewalld#1047]
### What happened

Just a day or two ago, out of nowhere, my Firewalld won't start up. `firewalld.service` simply won't initialize with the error `Failed to start firewalld - dynamic firewall daemon.`

Have my error log here, as outputted on my terminal with `journalctl -xeu firewalld.service`.
https://privatebin.net/?eed462f12f826f07#6bhLXwGTuavxzsfLM3hswgfGz8x2UBMq7yaNEeXDoRoB

Inputting `/usr/bin/firewalld --nofork --nopid --debug=10` results:
```
2022-11-13 12:15:16 Dropped Linux capabilities to NET_ADMIN, NET_RAW, SYS_MODULE.
Traceback (most recent call last):
  File "/usr/bin/firewalld", line 203, in startup
    from firewall.server import server
  File "/usr/lib/python3.10/site-packages/firewall/server/server.py", line 35, in <module>
    import dbus.service
ModuleNotFoundError: No module named 'dbus.service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/firewalld", line 256, in <module>
    main()
  File "/usr/bin/firewalld", line 251, in main
    startup(args)
  File "/usr/bin/firewalld", line 217, in startup
    except dbus.exceptions.DBusException as e:
AttributeError: module 'dbus' has no attribute 'exceptions'
[user@home ~]$ 
```
Any help is appreciated!

### Firewalld Version

Latest, from Arch's repos. While at it, I noticed package `dbus-python` had just updated yesterday, November 12th. Possibly something about that?

### Firewalld Backend

nftables

### Linux distribution

EndeavourOS

### Linux kernel version

6.0.8-arch1-1

**Comment by erig0** [comment]
This looks like your install is missing `python-dbus` module.

**Comment by TorontoMedia** [comment]
Furthermore, the 'dbus-python' package for Arch Linux is two releases behind and orphaned.
