### ISSUE TITLE
Packaging firewalld for Alpine

### ISSUE THREAD

**Issue by SecT0uch** [firewalld/firewalld#1051]
### What happened

I packaged firewalld for alpine and would like to know if the Fails and Skip of the test results are not critical.
For more info see attached `testsuite.log`

**The fails**:
* **protocols**: It seems some protocols are not found because protocol are harcoded in musl (/etc/protocols is ignored)
* **rich rules good**: Same reason
* **rich rules bad**: Same reason
* **ipset**: I build without ipset suport (`./configure --without-ipset`), so I guess this is normal
* **invalid syntax in xml files**: Reason?
* **unicode in XML**: Reason?
* **service include**: Reason?
* **startup failsafe - invalid xml**: Reason?
* **startup failsafe - bad zone**: Reason?
* **startup failsafe - bad policy**: Reason?
* **startup failsafe - non-existent service**: Reason?
* **startup failsafe - non-existent icmptype**: Reason?
* **startup failsafe - broken stock config**: Reason?

Regarding the skips, is there anything important skipped (eg: dbus api)? 

### How to reproduce it (as minimally and precisely as possible)

* Being on Alpine Edge with community and testing repo uncommented.
* Take this (WIP) `APKBUILD`: 
```bash
# Contributor: Jordan ERNST <SecT0uch@sect0uch.world>
# Maintainer: Jordan ERNST <SecT0uch@sect0uch.world>
pkgname=firewalld
pkgver=1.2.1
pkgrel=0
pkgdesc="A firewall daemon with D-Bus interface providing a dynamic firewall"
url="https://github.com/firewalld/firewalld"
arch="noarch"
license="GPL-2.0-or-later"
# checks produce errors (firewalld needs to be started)
options="!check"
depends="
	dbus
	nftables
	py3-dbus
	py3-gobject3
	py3-nftables
	"
makedepends="
	autoconf
	automake
	desktop-file-utils
	docbook-xsl
	gettext
	glib-dev
	intltool
	libxslt
	"
checkdepends="
	iproute2-minimal
	musl-locales
	"
subpackages="
	$pkgname-bash-completion
	$pkgname-doc
	$pkgname-gui
	$pkgname-lang
	$pkgname-openrc
	$pkgname-zsh-completion
	"
source="https://github.com/firewalld/firewalld/archive/v$pkgver/firewalld-$pkgver.tar.gz
	$pkgname.initd
	"

prepare() {
	default_prepare
	./autogen.sh
}

build() {
	# Disable sytemd and iptables features
	PYTHON=/usr/bin/python3 ./configure \
		--sysconfdir=/etc \
		--disable-systemd \
		--without-systemd-unitdir \
		--disable-rpmmacros \
		--without-iptables \
		--without-ip6tables \
		--without-ebtables \
		--without-ipset \
		--without-iptables-restore \
		--without-ip6tables-restore \
		--without-ebtables-restore
	make dist
}

package() {
	make DESTDIR="$pkgdir" install

	# Remove useless
	rm -rf "$pkgdir"/etc/sysconfig/
	rm -rf "$pkgdir"/etc/rc.d/

	install -Dm 755 "$startdir"/$pkgname.initd "$pkgdir"/etc/init.d/$pkgname
	install -Dm644 COPYING "$pkgdir"/usr/share/licenses/$pkgname/COPYING
}

gui() {
	# Taken here: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-firewall/firewalld/firewalld-1.2.1.ebuild#n181
	pkgdesc="GUI tools and assets for $pkgname"
	mkdir -p "$subpkgdir"/etc/xdg
	mkdir -p "$subpkgdir"/usr/bin
	mkdir -p "$subpkgdir"/usr/share
	mv "$pkgdir"/etc/xdg "$subpkgdir"/etc/
	mv "$pkgdir"/usr/bin/firewall-applet "$subpkgdir"/usr/bin/
	mv "$pkgdir"/usr/bin/firewall-config "$subpkgdir"/usr/bin/
	mv "$pkgdir"/usr/share/applications "$subpkgdir"/usr/share/
	mv "$pkgdir"/usr/share/icons "$subpkgdir"/usr/share/
}


sha512sums="
db8dc65d5036273e9853eec6c894a81c8859329cd9290a06ec480494c7e2304226b83dc647cedbead4916be41189a296b873fc41850b4fe61dd865e677798b31  firewalld-1.2.1.tar.gz
457cda01449f38563e98e1db937fe1c50745eab91797f52687e3ab9f5d94dd42d129740ae6669e99666a3f096d631dd3a44e66010b638b31b9c6ba798362403e  firewalld.initd
"
```
* and this `firewalld.initd`:
```
#!/sbin/openrc-run
# Copyright 1999-2018 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

description="FirewallD"
command=/usr/sbin/firewalld
pidfile=/var/run/firewalld.pid

depend() {
	need dbus
	provide firewall
}
```
* Build: `abuild -r`
* Install: `sudo apk add --repository /home/USER/packages/testing firewalld`
* Install test deps: `sudo apk add musl-locales iproute2-minimal procps`
* Run tests: `cd /tmp && sudo /usr/share/firewalld/testsuite/testsuite`

### Firewalld Version

1.2.1

### Firewalld Backend

nftables

### Linux distribution

Alpine Linux v3.17 

### Linux kernel version

5.15.78-0-virt

### Other information

[testsuite.log](https://github.com/firewalld/firewalld/files/10025062/testsuite.log)

Edit: Updated APKBUILD

**Comment by erig0** [comment]
I merged #1052. Please retest with that commit.

**Comment by SecT0uch** [comment]
> Are you running the testsuite directly? Or are you doing make check ?

I am running `cd /tmp && sudo /usr/share/firewalld/testsuite/testsuite` post-install.

> I made this change in https://github.com/firewalld/firewalld/pull/1052, can you try it please?

Good catch! This completely fixes the `ps` issue.

The last test that fail for a reason I don't understand is **startup failsafe - broken stock config**
See: [testsuite.log](https://github.com/firewalld/firewalld/files/10034411/testsuite.log)

**Comment by erig0** [comment]
> > Are you running the testsuite directly? Or are you doing make check ?
> 
> I am running `cd /tmp && sudo /usr/share/firewalld/testsuite/testsuite` post-install.

That makes sense. With `make check` the testsuite gets the build time paths to iptables, ipset, et al. If you run it as you do above, then it assumes they're in your `$PATH` and just uses the binary name, i.e. `iptables`. So the built firewalld assumes ipset is not usable (as configured), but the testuite finds one at rutime. You can can pass `IPSET=/bin/false` through an environment variable.

> > I made this change in #1052, can you try it please?
> 
> Good catch! This completely fixes the `ps` issue.
> 
> The last test that fail for a reason I don't understand is **startup failsafe - broken stock config** See: [testsuite.log](https://github.com/firewalld/firewalld/files/10034411/testsuite.log)

This test doesn't run as expected if you run the testsuite directly

**Comment by SecT0uch** [comment]
> You can can pass IPSET=/bin/false through an environment variable. Do the same for others disabled an build time: EBTABLES, IPTABLES, and IP6TABLES, EBTABLES_RESTORE, IPTABLES_RESTORE, IP6TABLES_RESTORE.

If i run as root:
`IPSET=/bin/false EBTABLES=/bin/false IPTABLES=/bin/false IP6TABLES=/bin/false EBTABLES_RESTORE=/bin
/false IPTABLES_RESTORE=/bin/false IP6TABLES_RESTORE=/bin/false /usr/share/firewalld/testsuite/testsuite 8
6`
Also fails: [testsuite-086.log](https://github.com/firewalld/firewalld/files/10034813/testsuite-086.log)

>Can you run this test individually with debug enabled?
`# cd /tmp && sudo /usr/share/firewalld/testsuite/testsuite --verbose --debug 190`

See: [testsuite-190.log](https://github.com/firewalld/firewalld/files/10034695/testsuite-190.log)

**Comment by erig0** [comment]
> > You can can pass IPSET=/bin/false through an environment variable. Do the same for others disabled an build time: EBTABLES, IPTABLES, and IP6TABLES, EBTABLES_RESTORE, IPTABLES_RESTORE, IP6TABLES_RESTORE.
> 
> If i run as root: `IPSET=/bin/false EBTABLES=/bin/false IPTABLES=/bin/false IP6TABLES=/bin/false EBTABLES_RESTORE=/bin/false IPTABLES_RESTORE=/bin/false IP6TABLES_RESTORE=/bin/false /usr/share/firewalld/testsuite/testsuite 86` Also fails: [testsuite-086.log](https://github.com/firewalld/firewalld/files/10034813/testsuite-086.log)

But it fails differently. Looks like due to the `/etc/protocols` issue. Below is `nft` output. The expected is different than reality. s/sctp/132/

```
--- -                                                                                 
+++ /tmp/testsuite.dir/at-groups/86/stdout                                            
@@ -2,7 +2,7 @@                                                                       
 set foobar {                                                                         
 type ipv4_addr . inet_proto . inet_service                                           
 flags interval                                                                       
-elements = { 10.10.10.10 . sctp . 1234,                                              
+elements = { 10.10.10.10 . 132 . 1234,                                               
 10.10.10.10 . udp . 1000-1002,                                                       
 20.20.20.20 . tcp . 8080 }                                                           
 }                                                                                    
86. firewall-cmd.at:864: 86. ipset (firewall-cmd.at:864): FAILED (firewall-cmd.at:917)
```

> > Can you run this test individually with debug enabled?
> > `# cd /tmp && sudo /usr/share/firewalld/testsuite/testsuite --verbose --debug 190`
> 
> See: [testsuite-190.log](https://github.com/firewalld/firewalld/files/10034695/testsuite-190.log)

Looks like we shouldn't use the `+=` operator. Check #1053 for a fix.

**Comment by SecT0uch** [comment]
> But it fails differently. Looks like due to the /etc/protocols issue. Below is nft output. The expected is different than reality. s/sctp/132/

Indeed, `python -c "import socket;socket.getprotobyname('sctp')"` --> Protocol not found
[This is where those are hardcoded](https://git.musl-libc.org/cgit/musl/tree/src/network/proto.c).

> Looks like we shouldn't use the += operator. Check https://github.com/firewalld/firewalld/pull/1053 for a fix.

Correct! This is fixed.

It seems to me all the errors except the protocol related ones.

I'm going to finish the APKBUILD, re-test everything and re-open this issue if needed.

Thanks :)

**Comment by erig0** [comment]
> Thanks :)

Thanks you for packaging firewalld!

**Comment by SecT0uch** [comment]
FYI: [Packages available in testing](https://pkgs.alpinelinux.org/packages?name=firewalld*&branch=edge&repo=&arch=x86_64)

**Comment by SecT0uch** [comment]
I am now trying to add direct rules support.

I used: `./configure --sysconfdir=/etc --disable-systemd --without-systemd-unitdir --disable-rpmmacros`

I'm getting several `+Error: INVALID_IPV: 'ipv4' is not a valid backend or is unavailable`

More info: [testsuite.log](https://github.com/firewalld/firewalld/files/10049488/testsuite.log)

**Comment by erig0** [comment]
> I am now trying to add direct rules support.

Did you disable iptables during the build?

**Comment by SecT0uch** [comment]
> Did you disable iptables during the build?

I built with `./configure --sysconfdir=/etc --disable-systemd --without-systemd-unitdir --disable-rpmmacros && make dist`

I'm gonna make a new build and try again, just to be sure.

**Comment by SecT0uch** [comment]
It managed to fix that, but now I'm getting:
`Error: COMMAND_FAILED: '/sbin/iptables-restore -w -n' failed: iptables-restore v1.8.8 (legacy): iptables-restore: unable to initialize table 'security'`.

In the kernel config:
```
CONFIG_NF_TABLES=m
CONFIG_NF_TABLES_INET=y
# CONFIG_IP_NF_SECURITY is not set
# CONFIG_IP6_NF_SECURITY is not set
```

**Comment by erig0** [comment]
Now it looks like the firewalld build has `iptables` enabled, but your running kernel is missing `CONFIG_IP_NF_SECURITY=y` and `CONFIG_IP6_NF_SECURITY=y`. If you want iptables, then you need those kernel options.

If you don't want iptables, then you need to make sure you run the testsuite with `IPTABLES=/bin/false` and `IPTABLES_RESTORE=/bin/false`. Otherwise it will find one at runtime. This also mean `--direct` rules are not usable.

**Comment by SecT0uch** [comment]
No a firewalld issue. Closing.

Using `--direct` is the only way I found to block outgoing traffic using firewalld.
Can that be achieved (using firewalld) without needing iptables ?
