### ISSUE TITLE
Remove application specific service files (at least from main package)

### ISSUE THREAD

**Issue by tebrevik** [firewalld/firewalld#1057]
### What would you like to be added

I would like application specific service defintions to be removed. At least from the main package.

### Why is this needed

Right now there is an open jellyfin issue due to #861:   https://github.com/jellyfin/jellyfin/issues/8587

I get that application specific service files has been implemented for a reason and that there might be good arguments for doing it this way. But in my opinion having application specific service files in the main firewalld package is a mistake. This create strong bindings to the applications that I don't think should be there. It should be (and has been) the application that should distribute this service file. What if the application want to add another port or something, should it then need to delay that release until firewalld service files has been updated? And why do the firewalld project want to take on the responsibilty for opening ports that suddenly might not be used by the next version of the application?

If the firewalld project feels that these service files belong then I suggest that they at least should be separated out into individual package files, like firewalld-jellyfin.rpm. Another option would be to gather the application services in firewalld-services.rpm.

**Comment by erig0** [comment]
If Jellyfin has been shipping a service definition for some time, then we can probably safely revert #861. @cmuellner, any thoughts?

There are advantages and disadvantages to including the service definition in firewalld itself. Some packages prefer to ship them by themselves, others prefer to include them in firewalld.

**Comment by tebrevik** [comment]
I'm just a user of both applications, so worst case you both remove your service defintions...

But my highly personal opinion is that it's a risk for a firewall application to carry service defintions that likely will be outdated or mismatched at some point due to changes in the original application.

**Comment by cmuellner** [comment]
My understanding is, that Podman installation is the preferred installation method on Fedora.
In this case no host configuration for firewalld will be installed for Jellyfin.
And the remote management console (cockpit) benefits from named firewalld configs (that was the use case that I intended to improve with the patch).

So as long as Jellyfin documents installation methods for Fedora that don't install firewalld configs, there will be an inconsistent user experience if we revert the support from firewalld.

Anyway, I don't mind if the change gets reverted.

**Comment by erig0** [comment]
> But my highly personal opinion is that it's a risk for a firewall application to carry service defintions that likely will be outdated or mismatched at some point due to changes in the original application.

As you say, this is your opinion. Others prefer to ship it in via firewalld, e.g. #1009.

If the jellyfin maintainers want to see the service definition reverted in firewalld, then I'll revert. I just need an official word.

**Comment by cmuellner** [comment]
Jellyfin filed a PR that removed that config from the RPM package a few weeks ago: https://github.com/jellyfin/jellyfin/pull/8646
However, that PR was not merged because of unclear reasons.

I fully agree that Jellyfin and firewalld devs should decide how they want to sort this out.
CCing @joshuaboniface as he might be the right person to decide this.

**Comment by joshuaboniface** [comment]
@cmuellner Whatever I did broke the Fedora builds and I am in no way a Fedora expert, so I closed the PR until I could have more time to investigate (which hasn't materialized yet). Unfortunately, Fedora builds are a red-headed stepchild for us: no one on the team, including myself, uses Fedora or is particularly knowledgeable in it, and all of our Fedora build scripts have been slowly hacked together over the years by myself and several other contributors.

I'm personally of the opinion that this should be reverted on the firewalld side, as I agree with all the points the OP made. Our release schedule is extremely random, so making changes like this isn't trivial for us and isn't tied to OS releases. We weren't planning to remove this until the problem came up so IMHO upstream adding a conflict like this is a mistake.

**Comment by cmuellner** [comment]
> I'm personally of the opinion that this should be reverted on the firewalld side, as I agree with all the points the OP made. Our release schedule is extremely random, so making changes like this isn't trivial for us and isn't tied to OS releases. We weren't planning to remove this until the problem came up so IMHO upstream adding a conflict like this is a mistake and an overstep.

PR can be found here: https://github.com/firewalld/firewalld/pull/1058

I will send an email to the maintainers of the firewalld package in Fedora. So that they can include this patch (if they decide to do so).

**Comment by erig0** [comment]
> I will send an email to the maintainers of the firewalld package in Fedora. So that they can include this patch (if they decide to do so).

That's me. I'm going to cut new releases so this propagates faster. I'll release v1.1.4 and v1.2.2 with #1058. I'll rebase f37 and f38 to v1.2.2.

**Comment by joshuaboniface** [comment]
Thanks everyone! I definitely appreciate the attempt at making Jellyfin "official" but we're not quite there yet. Maybe one day 😀

**Comment by mig4** [comment]
I'd urge you to reconsider this as current experience for users running Jellyfin (or any other service that would have its service files removed) under Docker/Podman is that after firewalld gets updated on the host the service stops being accessible, and we have to roll our own service definition to get it restored.

I get apps have their own release schedule, but hopefully the ports don't change on every release, and currently AFAIK there's no way to manage firewalld config from Podman/Docker, i.e. if I want to deploy a service to a host via Podman/Docker, I need to orchestrate firewalld configs out-of-band (outside of Podman container/service definition).
