### ISSUE TITLE
[RFE] zone include other zone (service rules only)

### ISSUE THREAD

**Issue by jcpunk** [firewalld/firewalld#1068]
### What would you like to be added

With the ability to have a service include another service, it would be helpful if zones could perform a similar inclusion to pull in services from an inherited zone.

From a workflow I'd expect the non-IP elements to get cloned over (`services`, `ports`, `rich rules`, `icmp`), `source` and `interface` should not be included.

### Why is this needed

At my site I have the following zones (names simplified for this report):
* Public (drop all)
* Internal (ssh only)
* Backup (ssh + backup port)
* Monitoring (ssh + prometheus exporter ports)
* Database (ssh + database port)

Logically, the Internal zone is "anything internal that isn't one of my special cases".

If I add an extra Internal service, say the prometheus UI, I need to also add it to the three other zones (Backup, Monitoring, Database) or those zones end up with less access that I intend.  As a result I end up with a bunch of zones that are basically identical but may end up with weird drift if I forget to add a service.  It gets even more ugly if I decide to add a service to Public, but forget to sync up the Internal zones.  Suddenly everyone except me can access a service.

**Comment by erig0** [comment]
You could use a policy instead.

This examples is equivalent to adding service `prometheus` to all three zones.

```
# firewall-cmd --permanent --new-policy myPolicy
# firewall-cmd --permanent --policy myPolicy --add-ingress-zone Backup
# firewall-cmd --permanent --policy myPolicy --add-ingress-zone Monitoring
# firewall-cmd --permanent --policy myPolicy --add-ingress-zone Database
# firewall-cmd --permanent --policy myPolicy --add-egress-zone HOST
# firewall-cmd --permanent --policy myPolicy --add-service prometheus
# firewall-cmd --permanent --reload

```

**Comment by erig0** [comment]
IMO, since policies provide a way to do this, this issues is a WONTFIX.

**Comment by jcpunk** [comment]
That makes sense, I'd thought policies were more limited in transport.
