### ISSUE TITLE
nftables support and documentation

### ISSUE THREAD

**Issue by ITwrx** [firewalld/firewalld#107]
I see the nftables support is listed as a "technology preview" that is not enabled by default, in the firewalld wiki. How does one enable it/tell firewalld to use nftables instead of iptables? It also shows work on nftables support extending through version 0.6. Which is more complete, "partly done" or "technology preview"? What is the current state of support?  Any docs, as support is added, would be appreciated. Maybe a wiki page just for nftables support, for instance. I think nftables support would make firewalld really stand out.

thanks in advance

ps. the gtk3 gui is very nice for desktops. a identical/similar ncurses gui would be cool for firewalls/servers, although the existing command line client may be quite usable(haven't tried it yet).

**Comment by t-woerner** [comment]
The nftables support is not in a good state at the moment. There is an unofficial test backend for nftables using {ip,ip6,eb}tables-compat, but it breaks easily with some extensions (and also some options). I hope to be able to spend some more time on nftables support in the next weeks. But at first I need to finish some other things.

About the the tui: I do not have a nice tui for firewalld: I started this a long time ago, but there is not a simple to use curses based library to realize it. Therefore it only advanced slowly and never reached a usable state. I would appreciate if there would be someone that could help with this as I am heavily working on other parts.

**Comment by ITwrx** [comment]
Thanks for the info and your work. I'll keep checking in from time to time on nftables support. Unfortunately, i doubt i'd be any use on the tui as i have no experience in that area, not even with curses. Also, feel free to close this issue if you want.

**Comment by q2dg** [comment]
Hello!
There is any progress in these items (nftables and/or tui)?
Just to know...
Thanks a lot!

**Comment by erig0** [comment]
@q2dg, No. Nothing worth reporting. nftables backend is a high priority task though.

**Comment by ITwrx** [comment]
thanks for your work. this is cool news.
