### ISSUE TITLE
adding a runtime direct rule for port 53 fails

### ISSUE THREAD

**Issue by patman-cp** [firewalld/firewalld#1077]
### What happened

This command fails as follows:

```
# firewall-cmd --direct --add-rule ipv4 raw PREROUTING 10 -s 192.168.1.204 -dport 53 -j DROP
Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: Bad argument `53'
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

```

This works, but will cause firewalld to fail the next time it starts up:

```
# firewall-cmd --permanent --direct --add-rule ipv4 raw PREROUTING 10 -s 192.168.1.204 -dport 53 -j DROP
success
```

### What you expected to happen

The addition of the runtime rule for this should work or the addition of the permanent rule should fail.

### How to reproduce it (as minimally and precisely as possible)

See above

### Firewalld Version

1.2.3

### Firewalld Backend

iptables

### Linux distribution

Fedora 37

### Linux kernel version

6.1.6-200.fc37.x86_64

**Comment by TorontoMedia** [comment]
It is necessary to specify the protocol, and the option should be --dport, which is an alias for --destination-port.
```sh
 firewall-cmd --permanent --direct --add-rule ipv4 raw PREROUTING 10 -s 192.168.1.204 -p tcp --dport 53 -j DROP
```

**Comment by erig0** [comment]
As indicated by iptables, the syntax is invalid.

```
Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: Bad argument `53'
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

Try this instead:
```
# firewall-cmd --direct --add-rule ipv4 raw PREROUTING 10 -s 192.168.1.204 -p udp --dport 53 -j DROP
```

**Comment by patman-cp** [comment]
That command works.

But the firewall-cmd should fail in this case - I had to manually modify direct.xml to get firewalld to even start again, since firewall-cmd would not work when firewalld was down.

And, `firewall-offline-cmd --check-config` reported no issues.

**Comment by erig0** [comment]
It can not. That would require firewalld to fully parse and understand iptables syntax.

**Comment by erig0** [comment]
> to even start again, since firewall-cmd would not work when firewalld was down.

Newer firewalld has a failsafe. It will always start.

**Comment by patman-cp** [comment]
Thanks for the details. 

Also, if you have pointers on how to use or discuss how to use rich-rules for this instead of direct ones, let me know - I tried a rich-rule but it didn't work as expected. I'm just trying to isolate "IOT" or untrusted devices as much as I can without using a separate physical network / VLAN (prevent them from accessing remote systems, yeah I know they can still get to my local systems) on my home network.

The underlying iptables rules looked right, I'm not sure if it's related to ordering of chains / tables with masquerading in place or what.

**Comment by erig0** [comment]
If all you want to do is block port 53 (udp dns) then you can do that natively in firewalld with a policy. I would further improve this by assigning all IoT devices to a separate zone.

```
# firewall-cmd --permanent --new-zone iot-devices
# firewall-cmd --permanent --zone iot-devices --add-source 192.168.1.204

# firewall-cmd --permanent --new-policy blockIOTDNS
# firewall-cmd --permanent --policy blockIOTDNS --add-ingress-zone iot-devices
# firewall-cmd --permanent --policy blockIOTDNS --add-egress-zone ANY
# firewall-cmd --permanent --policy blockIOTDNS --add-rich-rule='rule port port=53 protocol=udp drop'
```

```
[root@vm-local-rhel9 ~]# firewall-cmd --permanent --info-policy blockIOTDNS
blockIOTDNS (active)
  priority: -1
  target: CONTINUE
  ingress-zones: iot-devices
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
        rule port port="53" protocol="udp" drop
```
