### ISSUE TITLE
How to install firewalld(later than version 0.7.0) in RHEL 7?

### ISSUE THREAD

**Issue by kapaiyuanye** [firewalld/firewalld#1081]
Hi, I wanna to use priority of firewalld rich rules in rhel 7. In RHEL 7, the default inside version is newer than 0.6.3.
But the priority first appears in version 0.7.0.  So I wanna update my firewalld by source code(In my test, I update 0.9.3).

I update kernel 5.19.  
Install the Dependencies
Use python2 with configure (also try to use python3)

Still fail. make check also failed

How can I  update firewalld in RHEL7?

[root@redhat79 firewalld-0.9.3]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2023-01-31 23:15:25 CST; 2s ago
     Docs: man:firewalld(1)
  Process: 13497 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS=--debug=10 (code=exited, status=1/FAILURE)
 Main PID: 13497 (code=exited, status=1/FAILURE)

Jan 31 23:15:24 redhat79 systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 31 23:15:25 redhat79 python[13497]: detected unhandled Python exception in '/usr/sbin/firewalld'
Jan 31 23:15:25 redhat79 systemd[1]: firewalld.service: main process exited, code=exited, status=1/FAILURE
Jan 31 23:15:25 redhat79 systemd[1]: Failed to start firewalld - dynamic firewall daemon.
Jan 31 23:15:25 redhat79 systemd[1]: Unit firewalld.service entered failed state.
Jan 31 23:15:25 redhat79 systemd[1]: firewalld.service failed.

## --------------------------- ##

firewall-offline-cmd

  1: basic options                                   FAILED (firewall-cmd.at:17)
  2: get/list options                                FAILED (firewall-cmd.at:34)
  3: default zone                                    FAILED (firewall-cmd.at:47)
  4: user zone                                       FAILED (firewall-cmd.at:60)
  5: zone interfaces                                 FAILED (firewall-cmd.at:108)
  6: zone sources                                    FAILED (firewall-cmd.at:215)
  7: services                                        FAILED (firewall-cmd.at:238)
  8: user services                                   FAILED (firewall-cmd.at:273)
  9: ports                                           FAILED (firewall-cmd.at:376)
 10: source ports                                    FAILED (firewall-cmd.at:422)
 11: protocols                                       FAILED (firewall-cmd.at:454)
 12: masquerade                                      FAILED (firewall-cmd.at:501)
 13: forward                                         FAILED (firewall-cmd.at:580)
 14: forward ports                                   FAILED (firewall-cmd.at:783)
 15: ICMP block                                      FAILED (firewall-cmd.at:822)
 16: user ICMP types                                 FAILED (firewall-cmd.at:861)
 17: ipset                                           FAILED (firewall-cmd.at:887)
 18: user helpers                                    FAILED (firewall-cmd.at:1080)
 19: direct                                          FAILED (firewall-cmd.at:1148)
 20: direct nat                                      FAILED (firewall-cmd.at:1185)
 21: direct passthrough                              FAILED (firewall-cmd.at:1229)
 22: direct ebtables                                 FAILED (firewall-cmd.at:1274)
 23: lockdown                                        FAILED (firewall-cmd.at:1292)
 24: rich rules good                                 FAILED (firewall-cmd.at:1354)
 25: rich rules audit                                FAILED (firewall-cmd.at:1384)
 26: rich rules priority                             FAILED (firewall-cmd.at:1542)
 27: rich rules bad                                  FAILED (firewall-cmd.at:2013)
 28: config validation                               FAILED (firewall-cmd.at:2046)

features (FIREWALL_BACKEND)

 29: RFC3964_IPv4                                    ok
 30: service include                                 FAILED (service_include.at:61)
 31: customer helpers                                FAILED (helpers_custom.at:4)
 32: policy - xml                                    FAILED (policy.at:64)
 33: policy - create                                 FAILED (policy.at:77)
 34: policy - name                                   FAILED (policy.at:94)
 35: policy - list                                   FAILED (policy.at:125)
 36: policy - options                                FAILED (policy.at:230)
...

**Comment by kapaiyuanye** [comment]
Update 0.7.5 with python2 is ok !

Why?

**Comment by erig0** [comment]
firewalld 0.8.0 started using the libnftables JSON interface. Which requires `python3-nftables`. That's probably not available on RHEL-7 so firewalld fails to start.

RHEL-7 in ancient, so you'll have to use an ancient firewalld release.

**Comment by cylonchau** [comment]
@erig0 that is to say, since firewalld 0.8.0 start, firewalld unsupport iptables backend?

**Comment by erig0** [comment]
> @erig0 that is to say, since firewalld 0.8.0 start, firewalld unsupport iptables backend?

No. All firewalld version (even latest) support iptables backend.

**Comment by cylonchau** [comment]
> > @erig0 that is to say, since firewalld 0.8.0 start, firewalld unsupport iptables backend?
> 
> No. All firewalld version (even latest) support iptables backend. However, the code does not conditionally import python3-nftables. See #891.

I got it, thank you Eric Garver
