### ISSUE TITLE
Enable IPv6 masquerade on the external zone

### ISSUE THREAD

**Issue by mohd-akram** [firewalld/firewalld#1084]
### What would you like to be added

Currently, the predefined external zone only has IPv4 masquerade enabled, but not IPv6. It makes sense to have it enabled for both.

### Why is this needed

Users might not easily know the rich rule syntax, and I imagine predefined rules aim to make common configurations easier. IPv6 support should be commonplace and enabled by default.

**Comment by erig0** [comment]
> Currently, the predefined external zone only has IPv4 masquerade enabled, but not IPv6. It makes sense to have it enabled for both.

That is assuming all user want IPv6 masquerading. I don't think we can make that assumption.

**Comment by erig0** [comment]
I welcome improvements to the website and documentation.
