### ISSUE TITLE
GREv6 fault

### ISSUE THREAD

**Issue by phenemenon** [firewalld/firewalld#1085]
### What happened

I created a GREv6 tunnel and it doesn't work. Then I turned on the firewall log and it told me the following:
STATE_INVALID_DROP:  IN=ens33 OUT= MAC=00:0c:29:ad:a8:3f:00:0c:29:b0:7a:74:86:dd SRC=fd00:0000:0000:0000:0000:0000:0000:0100  DST=fd00:0000:0000:0000:0000:0000:0000:0101 LEN=156 TC=0 HOPLIMIT=64 FLOWLBL=413508 PROTO=47
However, I have enabled gre service support in the firewall:
firewall-cmd --permanent --add-service=gre
Now I am using version 1.3.0. How can I fix it?

### Firewalld Version

1.3.0

### Firewalld Backend

iptables

**Comment by phenemenon** [comment]
i use this rich-rule:
firewall-cmd --permanent --add-rich-rule='rule protocol value="47" accept'
but it still doesn't work

**Comment by phenemenon** [comment]
oh...i  found this problem in the 4.19 kernel

**Comment by erig0** [comment]
> oh...i found this problem in the 4.19 kernel

Can you clarify? Are you saying this is a kernel bug? Can we close this firewalld issue?

**Comment by phenemenon** [comment]
I'm not sure if it's a kernel problem, but it worked fine after I switched to kernal 5.10

**Comment by erig0** [comment]
> I'm not sure if it's a kernel problem, but it worked fine after I switched to kernal 5.10

Then perhaps this was actually a conntrack bug in the kernel that has since been fixed.

Closing this bug. FWIW, firewalld-1.0.0+ [requires kernel 5.3 or later](https://github.com/firewalld/firewalld#dependencies).
