### ISSUE TITLE
Add ip black list for only outgoing connections

### ISSUE THREAD

**Issue by Stevemoretz** [firewalld/firewalld#1087]
### What would you like to be added

I know it's possible to add a ip list from a file to block but it blocks all incoming and outgoing sometimes you'd like to do that only for outgoing or incoming, it's important to have this feature since doing it on a for loop caused my machine to freeze after a few lines.... 

### Why is this needed

Sometimes you want to block only outgoing, sometimes only incoming like I don't want China to access my server, but I like to acess Chinese websites on my server, so I only need to block incoming, or vice vercia.

**Comment by erig0** [comment]
I think you're asking to block outgoing connection to a specific destination, e.g. a country. This is already possible with firewalld.

First use an ipset as a source to your drop zone. This will drop _incoming_ connections from source in the ipset.

```
# firewall-cmd --permanent --new-ipset block_country --type hash:net
# firewall-cmd --permanent --ipset --add-entry ...
# firewall-cmd --permanent --ipset --add-entry ...

# firewall-cmd --permanent --zone drop --add-source block_country
```

You can then use a policy to block _outgoing_ connections destined for the drop zone (ipset block_country).

```
# firewall-cmd --permanent --new-policy out_block_country
# firewall-cmd --permanent --policy out_block_country --add-ingress-zone HOST
# firewall-cmd --permanent --policy out_block_country --add-egress-zone drop
# firewall-cmd --permanent --policy out_block_country --set-target DROP
```

Then reload firewalld.

```
# firewall-cmd --reload
```
