### ISSUE TITLE
Restarting firewalld does not respect interface placement

### ISSUE THREAD

**Issue by fs30000** [firewalld/firewalld#1088]
Hello, i'm puzzled about this.

Rocky 9.1
firewalld-1.1.1-3.el9.noarch

I'm doing this in a playbook, but same results on the command line:

- Removed interfaces ens192 and ens224 from Public zone.
- Added ens192 to the Internal and ens224 to External, immediately and permanently.
- Restarted and also reloaded the firewalld service.

Both interfaces are back to Public! Even tough the .xml for the respective zones are according to above steps. Even after a reboot.

Am i missing something obvious?

**Comment by erig0** [comment]
Do you happen to have NetworkManager? If so, the check the `ZONE` settings. At runtime, NM may override firewalld's permanent assignment of the interface, i.e. it does `--change-interface`.

**Comment by erig0** [comment]
I don't know what your playbook is doing. Is it calling `firewall-cmd` or is it using the firewalld client libraries directly?

**Comment by fs30000** [comment]
Yeah, noticed later. I do have NM running, seems it is needed to add a `zone=external` on the connection's file in order for it  to assume the new interfaces on the zones.
/etc/NetworkManager/system-connections/ens224.nmconnection

_[connection]
id=ens224
uuid=5c2953f4-79de-3f13-be0e-28c6b70150ce
type=ethernet
autoconnect-priority=-999
interface-name=ens224
timestamp=1677268712
zone=external_


I was using ansible firewalld module. I tried  with the system role rhel-system-roles.firewall and it does add the` zone=` parameter to the connection's file. So it looks a more complete solution. Pitty it doesn't support policies yet. Gotta add them manually then.

**Comment by erig0** [comment]
> I do have NM running, seems it is needed to add a zone=external on the connection's file in order for it to assume the new interfaces on the zones.

Thanks for confirming. Closing this as `3rdparty`.

The NM interactions actually happen in the client, e.g. firewall-cmd or the ansible role. This has the advantage that NM handles the authorization as the user (instead of the firewalld daemon).

> Pitty it doesn't support policies yet.

Please file an RFE with the system-role.
