### ISSUE TITLE
Do not clear iptables rules when reloading firewalld

### ISSUE THREAD

**Issue by unknowndevQwQ** [firewalld/firewalld#1099]
### What would you like to be added

There is a way to tell firewalld not to touch iptables rules that are not generated by firewalld when reloading.

### Why is this needed

When using docker or netavark, firewalld reloads to increase their zone. rules generated by themselves or other tools still using iptables are cleared during this time, which causes them to resume working properly only if they are restarted or notified to reload the rules.

**Comment by erig0** [comment]
See issue #863 pr #1082. I think this is already implemented.

**Comment by unknowndevQwQ** [comment]
> See issue #863 pr #1082. I think this is already implemented.
> 
> Edit: If you disagree then we can reopen.

I'll try it again later in a clean environment.

**Comment by unknowndevQwQ** [comment]
> See issue #863 pr #1082. I think this is already implemented.
> 
> Edit: If you disagree then we can reopen.

I tried it and it doesn't work.
Either changing log-denied or simply reloading will cause the iptables rule to be cleared.

**Comment by unknowndevQwQ** [comment]
> > > See issue #863 pr #1082. I think this is already implemented.
> > > Edit: If you disagree then we can reopen.
> > 
> > 
> > I tried it and it doesn't work. Either changing log-denied or simply reloading will cause the iptables rule to be cleared.
> 
> Do you have `--direct` rules?

No, that's a rule added directly by other programs using iptables.

**Comment by erig0** [comment]
Are you using the iptables backend? Can you share you firewalld configuration?

**Comment by unknowndevQwQ** [comment]
> 

I am using the nftables backend.
[fwd.conf.md](https://github.com/firewalld/firewalld/files/11045928/fwd.conf.md)

**Comment by unknowndevQwQ** [comment]
> > When using docker or netavark, firewalld reloads to increase their zone.
> 
> Docker may add `--direct` rules via firewalld. That will trigger an iptables flush the first time a rule is added and again during `--reload` (because there are direct rules).
> 
> docker, et al. would have to listen for the firewalld `Reloaded()` dbus event and re-add it's rules. I thought this was already the case.
> 
> Can you give a sequence of commands to reproduce this?

```
# iptables -N nope && iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N nope
```
```
# firewall-cmd --reload && iptables -S
success
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

That's it, maybe it's not actually in effect?

**Comment by erig0** [comment]
Are you using the latest code from the master branch? Or a release? The fix I mentioned above is not yet in a release.

**Comment by unknowndevQwQ** [comment]
> Are you using the latest code from the master branch? Or a release? #1082 I mentioned above is not yet in a release.

```
$ pacman -Qi firewalld
Name            : firewalld
Version         : 1.3.0-2
Description     : Firewall daemon with D-Bus interface
```

**Comment by erig0** [comment]
That explains it then. #1082 will be in the next feature release, e.g. 1.4.0.

**Comment by unknowndevQwQ** [comment]
> 

What day will it be?
