### ISSUE TITLE
nft_compat deprecation warning when using firewalld direct rules with nftables backend on Centos 9 Stream

### ISSUE THREAD

**Issue by ishimko** [firewalld/firewalld#1111]
### What happened

Adding `--direct` rules via `firewall-cmd` on Centos 9 Stream (and most likely other RHEL 9 based distributions) triggers warning about nft_compat deprecation in logs (rules work as expected):
```
kernel: Warning: Deprecated Driver is detected: nft_compat will not be maintained in a future major release and may be disabled
```

### What you expected to happen

No warning about nft_compat when using direct rules.

### How to reproduce it (as minimally and precisely as possible)

Centos 9 Stream (or other RHEL 9 based distribution):

1. Add direct rule, i.e.:
```
firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 192.168.1.3
```
2. Observe warning in logs: `grep nft_compat /var/log/messages*`:
```
kernel: Warning: Deprecated Driver is detected: nft_compat will not be maintained in a future major release and may be disabled
```

### Anything else we need to know?

Seems like the reason is https://access.redhat.com/documentation/ru-ru/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_networking. 

Are there any workarounds available to use nftables syntax and get rid of this warning?

### Firewalld Version

1.2.1

### Firewalld Backend

nftables

### Linux distribution

Centos 9 Stream

### Linux kernel version

5.14.0-293.el9.x86_64

**Comment by erig0** [comment]
This is a deprecation warning coming from the kernel. Additionally it's specific to RHEL and derivatives.

You should use firewalld's policies and rich rules where possible (avoid `--direct` rules). However, your example does not have native firewalld support; there is no support for SNAT `--to` option.

firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 192.168.1.3

**Comment by amessina** [comment]
> This is a deprecation warning coming from the kernel. Additionally it's specific to RHEL and derivatives.
> 
> You should use firewalld's policies and rich rules where possible (avoid `--direct` rules). However, your example does not have native firewalld support; there is no support for SNAT `--to` option. If `--to` is not needed, then you can probably replace with native policies.
> 
>     * https://firewalld.org/2020/09/policy-objects-introduction
> 
>     * https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic
> 
>     * https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/using-and-configuring-firewalld_configuring-and-managing-networking

I, too, would like to stop using direct rules, but firewalld doesn't have a way to jump to an xtables target (RTPENGINE) without them that I can see.  Also, it seems that direct rules are still the only way to get ahead of "RELATED,ESTABLISHED"

https://lists.fedorahosted.org/archives/list/firewalld-users@lists.fedorahosted.org/thread/JMXNSG7TT4Z3L773KEXO7J6MARTEEML6/

https://github.com/firewalld/firewalld/issues/44

https://github.com/firewalld/firewalld/issues/191

https://github.com/sipwise/rtpengine/issues/984

**Comment by erig0** [comment]
Closing as this is an issue introduced by downstream changes. The issue does not exist in upstream firewalld.
