### ISSUE TITLE
Console rule creation works, UI rule doesn't, doesn't even allow to edit or save it

### ISSUE THREAD

**Issue by birdie-github** [firewalld/firewalld#1120]
### What happened

This works: `firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address='162.255.226.75' reject"`

This doesn't (this is me trying to edit the just created rule) - cannot even save it, because `[ OK ]` is not active and shows an error.

![UI](https://github.com/firewalld/firewalld/assets/4958603/175d968a-da54-4541-a48a-d02589a4622a)

No idea what's going on.

Using fully updated Fedora 38.

### Firewalld Version

firewalld-1.3.1-1.fc38.noarch

### Firewalld Backend

nftables

### Linux distribution

Fedora release 38 (Thirty Eight)

### Linux kernel version

6.2.14-200.fc37.x86_64

**Comment by erig0** [comment]
Fixed in #1143. I'll merge after CI completes.
