### ISSUE TITLE
ipset deprecated warning

### ISSUE THREAD

**Issue by kees-closed** [firewalld/firewalld#1130]
### What would you like to be added

According to [this RHEL 9 article](https://access.redhat.com/solutions/6974000):

> Ipset is deprecated in RHEL9 and the message is a warning notification so that customers can reconfigure systems to use nftables equivalent rules to avoid ipset rules not working when the ipset command is eventually removed.

Is firewalld working on a native replacement? It would be great to soon switch to RHEL9 without issues. firewalld is great because it's a wrapper, so changing the underlying tooling should be something firewalld is great at. Such as switching from `iptables` to `nftables`. Can this also be done soon for `ipset`? Which is part of `iptables` by the way.

Is there some kind of roadmap about this upcoming change?

### Why is this needed

To retain `ipset` functionality, which enables more efficient processing of large IP sets.

**Comment by erig0** [comment]
> Is firewalld working on a native replacement?

When `FirewallBackend=nftables` firewalld will use native nftables sets. However, due to `--direct` rules the ipsets are also added to the native `ipset`.

Since v1.3.0 firewalld can completely avoid using `ipset` when `FirewallBackend=nftables`.

**Comment by erig0** [comment]
I'm closing this as it is already implemented.
