### ISSUE TITLE
nftables backend tries to mix ipv6 addresses and ipv4 addresses in the same rule

### ISSUE THREAD

**Issue by TheBigK02** [firewalld/firewalld#1146]
### What happened

I upgraded my raspberrypi to Debian bookworm a couple days ago. Since then firewalld upgraded to version 1.3.0-1. Since then the Forwarding of packets to different zones worked differently? So I decided to add polices to accept those forwarded packages.

### How to reproduce it (as minimally and precisely as possible)

put in ipv4 addresses and ipv6 addresses as sources into the same zone.
use nftables as backend
Create a Policy to accept forwarding packets:

firewall-cmd --permanent --new-policy inToTrusted
firewall-cmd --permanent --policy=intToTrusted --add-egress-zone=trusted
firewall-cmd --permanent --policy=intToTrusted --add-ingress-zone=internal

### Firewalld Version

1.3.0

### Firewalld Backend

nftables

### Linux distribution

Debian GNU/Linux 12 bookworm

### Linux kernel version

6.1.0-9-arm64

### Other information

[Pastebin1](https://paste.debian.net/1282889/)
[Pastebin2](https://paste.debian.net/1282889/)

**Comment by erig0** [comment]
Note: This is fixed on current code (master branch), but affects stable release: 1.2.z, 1.3.z. We should fix it on those stable releases.

#1147 has a new test to trigger this bug.
