### ISSUE TITLE
some man pages refer to stale fedoraproject.org/wiki/FirewallD

### ISSUE THREAD

**Issue by HughR** [firewalld/firewalld#1183]
### What happened

man pages like firewalld.policy(5) point to http://fedoraproject.org/wiki/FirewallD
This is obsolete and predates policy objects.

### How to reproduce it (as minimally and precisely as possible)

` $ man firewalld.policy`

### Anything else we need to know?

github finds two references to this wiki.
doc/xml/notes.xml line 39
doc/xml/firewall-cmd.xml.in line 2671

### Linux distribution

Fedora Linux 38

### Linux kernel version

not relevant

### Other information

I raised this on the mailing list.  Eric Garver requested that I file an issue here.

**Comment by thom311** [comment]
fixed by 2f14edf848f05e560d8cfd8daf5a3f2bb2f92087. Thanks for the report!
