### ISSUE TITLE
The memory usage of firewalld increases sharply when a large number of routes are added

### ISSUE THREAD

**Issue by lbo874** [firewalld/firewalld#1232]
### What happened

 When I run the ip route add command to add routes for 100,000 times, the firealld process starts to increase(to 3g and then oom) and the CPU usage is high. After the route adding operation is stopped, the memory usage of firewalld does not decrease, but does not increase. If you continue to add or delete routes cyclically, the memory usage continues to increase. Oddly, no information is recorded in the debug log file.

### What you expected to happen

The firewalld main process is not affected, and the memory usage does not increase.

### How to reproduce it (as minimally and precisely as possible)

  Run the following script to add a route:
 for (( a = 0; a < 8; a++ )); do
        for (( b = 0; b < 5; b++ )); do
            for (( c = 0; c < 5; c++ )); do
                for (( d = 0; d < 5; d++ )); do
                    for (( e = 0; e < 5; e++ )); do
                        for (( f = 0; f < 5; f++ )); do
                            for (( i = 0; i < 4; i++ )); do
                                ip route add/dev 1$i.1$f$a.1$d$e.1$b$c dev eth0
                            done
                        done
                    done
                done
            done
        done
    done

### Anything else we need to know?

The configuration is as follows:
DefaultZone=public
CleanupOnExit=yes
CleanupModulesOnExit=no
Lockdown=no
IPv6_rpfilter=yes
IndividualCalls=no
LogDenied=off
FirewallBackend=nftables
FlushAllOnReload=yes
RFC3964_IPv4=yes

### Firewalld Version

1.0.2-5

### Firewalld Backend

nftables

### Linux distribution

/

### Linux kernel version

5.10.0-136

### Other information

Startup parameters:python3 -s /usr/sbin/firewalld --nofork --nopid
rules:
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: dhcpv6-client mdns ssh
  ports: 45689/tcp
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

**Comment by lbo874** [comment]
We have found that adding a large number of routing tables after firewalld reload causes firewalld memory to increase. Networkmanger-related code is found in the reload code. (https://github.com/firewalld/firewalld/blob/f5f78baa5ae62177e65881550d876ee9bcc52d8b/src/firewall/core/fw.py#L1330). If we comment out the following lines of code, the problem will not occur. So would like to ask, what is the function of this code, can be optimized?@erig0 Please give us some advice.

**Comment by erig0** [comment]
NetworkManager has a `ZONE` configuration option for each connection. This zone assignment is communicated to firewalld over dbus. It effectively does `--zone ZONE --change-zone-of-interface <interface>`.

This code is necessary on reload to restore those bindings as NetworkManger does not push them to firewalld again after reload. Firewalld must query NetworkManager for them.

Since you have a very large number of interface the growing memory may simply be related to fetching these and python garbage collection.

Does the memory usage ever cap? Say around 128MB? 256? Something round like that? Python will "hold" on to memory within certain limits instead of giving it back to the operating system.

**Comment by thom311** [comment]
hm. I am not yet able to reproduce this. I issued a `firewall-cmd --change-interface=eth1 --permanent` to make sure that firewalld talks to NetworkManager (at least once). After ran the script with the for-loops. The memory consumption does not increase.

Could you provide more information about how to reproduce this. Are you using packages from your distribution? Which distribution? Which package versions of firewalld+NetworkManager?

**Comment by chengyechun** [comment]
> hm. I am not yet able to reproduce this. I issued a `firewall-cmd --change-interface=eth1 --permanent` to make sure that firewalld talks to NetworkManager (at least once). After ran the script with the for-loops. The memory consumption does not increase.
> 
> Could you provide more information about how to reproduce this. Are you using packages from your distribution? Which distribution? Which package versions of firewalld+NetworkManager?

firewalld v1.0.2 NetworkManager 1.32.12，This problem occurs only ran the script with the for-loops after the reload process（systemctl reload firewalld）. 
firewalld.service:
[Unit]
Description=firewalld - dynamic firewall daemon
Before=network-pre.target
Wants=network-pre.target
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service nftables.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1
KillMode=mixed
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=dbus-org.fedoraproject.FirewallD1.service


The related code is also mentioned above, and it is found that as long as the code is commented out, the problem is gone. After analysis, it is found that the dbus name of NetworkManager is set in settings["interface"][interface_id][sender]. However, it is not clear how firewalld is triggered and the memory usage increases during script running. Maybe it's related to the dbus message of the NM, but I can't find the code.

**Comment by thom311** [comment]
> Maybe it's reproducible on older firewalld ? Report is v1.0.2.

I tested 1.0.2 (upstream build). But clearly I did something wrong, as I didn't reproduce it.

I will try again, with SIGHUP (and `firewall-cmd --reload`, which should do the same as SIGHUP).

> firewalld v1.0.2 NetworkManager 1.32.12

What distro is  this? Are these distro packages? Which exact version?

**Comment by chengyechun** [comment]
> > Maybe it's reproducible on older firewalld ? Report is v1.0.2.
> 
> I tested 1.0.2 (upstream build). But clearly I did something wrong, as I didn't reproduce it.
> 
> I will try again, with SIGHUP (and `firewall-cmd --reload`, which should do the same as SIGHUP).
> 
> > firewalld v1.0.2 NetworkManager 1.32.12
> 
> What distro is this? Are these distro packages? Which exact version?
NetworkManager is version 1.32.12 of fedora f35, and firewalld is version 1.0.2 of this community.

**Comment by lbo874** [comment]
> We have found that adding a large number of routing tables after firewalld reload causes firewalld memory to increase. Networkmanger-related code is found in the reload code. (
> 
> https://github.com/firewalld/firewalld/blob/f5f78baa5ae62177e65881550d876ee9bcc52d8b/src/firewall/core/fw.py#L1330
> 
> ). If we comment out the following lines of code, the problem will not occur. So would like to ask, what is the function of this code, can be optimized?@erig0 Please give us some advice.



We tested it on fedora 36 and there was no problem. Guess it's a problem with other software packages or kernels on our machine. 
When we tried to solve this problem, we found that the nm_get_interfaces_in_zone method on line 1082, followed by a call to nm_get_interfaces_in_zone->nm_get_zone_of_connection->nm_get_client . The global variable _nm_client is defined in nm_get_client. We tried to free the variable after reload was complete, and the problem was solved. 
Therefore, I would like to ask if there is any problem with modifying the code in this way and what is the purpose of defining _nm_client as a global variable? @erig0 @thom311

**Comment by thom311** [comment]
> We have found that adding a large number of routing tables after firewalld reload causes firewalld memory to increase.
> ...
> This problem occurs only ran the script with the for-loops after the reload process（systemctl reload firewalld

right, thanks. After `firewall-cmd --reload` it reproduces (also on stock F39, or on F39 with firewalld from git).


---

Keeping `_nm_client` around in a global variable is not necessarily wrong. It contains a cache of the NetworkManager objects, and you may keep it. But clearly there is something wrong in this regard...


Investigating...

---

Btw, as you are probably aware, Fedora 35 and Fedora 36 are long end of life. It's a bad idea to use software out of support.

**Comment by thom311** [comment]
I think there is no leak in firewalld itself.

firewalld uses libnm/NMClient, just like (for example) `nmcli`.

If you run `nmcli monitor`, you can see the memory grow in a similar manner (very excessively!).

NMClient keeps those routes in memory, so it's clear that keeping 100k of routes requires some memory. But consuming Gigabytes of it is of course very wrong.

It's also clear, if 100k routes consume e.g. N GB of memory, then even after `ip route flush` this memory is unlikely returned to the Operating System. What however should at least happen, if you then re-add 100k routes, that the memory does not grow further. What then would be expected, is that although the memory is fragmented, NMClient should be able to track the new routes with the memory is has already requested from the OS. But that also does not happen, and the memory grows further -- as if there was really a leak (not just some problem with fragmentation).

See also the NetworkManager issue: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1423


Status: Investigating...

**Comment by thom311** [comment]
ok, so what happens....


NMClient uses glib for D-Bus. glib has a separate worker thread. When you add 100k routes one-by-one, NetworkManager is very busy sending updates about those routes, as the list of route grows (`PropertiesChanged` signals, that contain the growing list of routes). The worker thread queues them, and the main thread is too slow to process them. The memory piles up (excessively). When burst of adding 100k routes is finished, the memory gets free, however the libc allocator does not return it to the operating system.

I think the solution is to not expose so much data on D-Bus (https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1799).

A sensible workaround in firewalld is https://github.com/firewalld/firewalld/pull/1244

Another workaround could be to create those routes with another protocol, for example `ip route add 1.2.3.4/32 proto 55 dev eth0`. NetworkManager (at least on recent versions) ignores such routes and does not expose them on D-Bus (avoiding the problem).
