### ISSUE TITLE
firewall-cmd: error: unrecognized arguments: --add-source-ipset=

### ISSUE THREAD

**Issue by akama-aka** [firewalld/firewalld#1249]
### What happened

I wanted to add a ipset to one of my zones but I get everytime this error and it also worked a few months ago was it removed in a update or what happened?

### What you expected to happen

The ipset list added to the dmz zone

### How to reproduce it (as minimally and precisely as possible)

Create a new ipset and add some things into it and try to apply it with 
`sudo firewall-cmd --permanent --zone=dmz --add-source-ipset=`

### Firewalld Version

0.0.0

### Firewalld Backend

nftables

### Linux distribution

Debian 12

### Linux kernel version
Linux, 5.10.0-0.deb10.26-cloud-amd64

### Other information

Firewalld and Linux Kernel version is unknown and also cant access to it rn I'll update during the day but both should be the latest. It was re installed to fix a different issue that also should work but doesnt worked and then everything was gone somehow. (I added it permanent)

**Comment by erig0** [comment]
That's because this is not a valid argument. You want `--add-source ipset:<ipset>`.
