### ISSUE TITLE
firewall-offline-cmd ignores the IP family when creating a new IP set

### ISSUE THREAD

**Issue by vgaetera** [firewalld/firewalld#1264]
### What happened

firewall-offline-cmd ignores the IP family when creating a new IP set.

### What you expected to happen

firewall-offline-cmd should respect the IP family when creating a new IP set.

### How to reproduce it (as minimally and precisely as possible)

```sh
sudo firewall-offline-cmd --new-ipset=test --family=inet6 --type=hash:net
sudo firewall-offline-cmd --ipset=test --add-entry=fe80::/10
sudo firewall-offline-cmd --info-ipset=test
```

### Firewalld Version

2.0.2

### Firewalld Backend

nftables

### Linux distribution

Fedora Linux 39

### Linux kernel version

6.6.6-200.fc39.x86_64

**Comment by erig0** [comment]
Indeed. Thanks for reporting.

**Comment by shaneshort** [comment]
I was doing some evaluation of firewalld and I think it's also doing the same for the type as well. I can see the XML files were created properly, but the live ipsets were created as hash:ip, not hash:net. A restart of firewalld seemed to restore them correctly.

**Comment by erig0** [comment]
> I was doing some evaluation of firewalld and I think it's also doing the same for the type as well. I can see the XML files were created properly, but the live ipsets were created as hash:ip, not hash:net. A restart of firewalld seemed to restore them correctly.

`firewall-offline-cmd` does not modify live ipsets. It only changes the XML.
