### ISSUE TITLE
Firewalld 2.0: Error from removeSource Call

### ISSUE THREAD

**Issue by mheon** [firewalld/firewalld#1278]
### What happened

After upgrade to firewalld 2.0, Podman + Netavark is seeing the following error messages when removing containers:

```
Jan 15 13:51:52 IronDuke firewalld[13336]: ERROR: UNKNOWN_ERROR: rule ref count bug, missing ref count: rule_key '{"%%POLICY_SORT_KEY%%": [0, 1, "netavark_zone", "10.88.0.0/16", "", 0, 1, "netavark_zone", "10.88.0.0/16", "", 0, -1], "chain": "filter_FORWARD_POLICIES", "expr": [{"match": {"left": {"payload": {"field": "saddr", "protocol": "ip"}}, "op": "==", "right": {"prefix": {"addr": "10.88.0.0", "len": 16}}}}, {"match": {"left": {"payload": {"field": "daddr", "protocol": "ip"}}, "op": "==", "right": {"prefix": {"addr": "10.88.0.0", "len": 16}}}}, {"jump": {"target": "filter_FWD_policy_netavark_policy"}}], "family": "inet", "table": "firewalld"}'
Jan 15 13:51:52 IronDuke firewalld[13336]: ERROR: COMMAND_FAILED: UNKNOWN_ERROR: rule ref count bug, missing ref count: rule_key '{"%%POLICY_SORT_KEY%%": [0, 1, "netavark_zone", "10.88.0.0/16", "", 0, 1, "netavark_zone", "10.88.0.0/16", "", 0, -1], "chain": "filter_FORWARD_POLICIES", "expr": [{"match": {"left": {"payload": {"field": "saddr", "protocol": "ip"}}, "op": "==", "right": {"prefix": {"addr": "10.88.0.0", "len": 16}}}}, {"match": {"left": {"payload": {"field": "daddr", "protocol": "ip"}}, "op": "==", "right": {"prefix": {"addr": "10.88.0.0", "len": 16}}}}, {"jump": {"target": "filter_FWD_policy_netavark_policy"}}], "family": "inet", "table": "firewalld"}'
```

We also get the same message back as over dbus as an error. After some tracing, this is specifically removing a subnet (in this case, 10.88.0.0/16) from the `netavark_zone` zone via the `removeSource` dbus call. After this occurs, I am also unable to remove the source via `firewall-cmd` (`firewall-cmd --zone netavark_zone --source 10.88.0.0/16`) with an identical error message.

The zone has no special configuration, beyond being mentioned by policy. It and the source in it were added by us via dbus.

### What you expected to happen

The subnet should be removed from the zone, and no error message should occur.

### How to reproduce it (as minimally and precisely as possible)

We're reproducing with Podman + Netavark right now (`sudo NETAVARK_FW=firewalld podman run -t -i --rm fedora ls /` is enough to trigger).

### Anything else we need to know?

This seems new to firewalld 2.0. I have a desktop still on F38  with firewalld 1.3.4 and it does not exhibit the bug.

### Firewalld Version

firewalld-2.0.2-1.fc39.noarch

### Firewalld Backend

nftables

### Linux distribution

F38

### Linux kernel version

kernel-6.6.9-200.fc39.x86_64

**Comment by mheon** [comment]
Slight update: This occurs on all Podman + Netavark invocations, even not using the firewalld driver - presumably because we're adding 10.88.0.0/16 to the trusted zone, and then removing it on teardown.

**Comment by erig0** [comment]
I was able to reproduce this. Thank you for reporting.

**Comment by erig0** [comment]
Actually I hit a different bug, but not what you're reporting. Can you share your zone and policy configurations?

**Comment by mheon** [comment]
Sure. Simplest reproducer I have (`podman run` after a `firewall-cmd --reload`):

Zones:
<details>
FedoraServer
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

FedoraWorkstation (default, active)
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: enp36s0u1 wlp0s20f3
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 1025-65535/udp 1025-65535/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

block
  target: %%REJECT%%
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

dmz
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

drop
  target: DROP
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

external
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

home
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

internal
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns samba-client ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

libvirt
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcp dhcpv6 dns ssh tftp
  ports: 
  protocols: icmp ipv6-icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject

libvirt-routed
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

netavark_zone
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: 
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

nm-shared
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcp dns ssh
  ports: 
  protocols: icmp ipv6-icmp
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule priority="32767" reject

public
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

trusted (active)
  target: ACCEPT
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 10.88.0.0/16
  services: 
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

work
  target: default
  ingress-priority: 0
  egress-priority: 0
  icmp-block-inversion: no
  interfaces: 
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
</details>

Policies:
<details>
allow-host-ipv6 (active)
  priority: -15000
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: HOST
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv6" icmp-type name="neighbour-advertisement" accept
	rule family="ipv6" icmp-type name="neighbour-solicitation" accept
	rule family="ipv6" icmp-type name="router-advertisement" accept
	rule family="ipv6" icmp-type name="redirect" accept

libvirt-routed-in
  priority: -1
  target: ACCEPT
  ingress-zones: ANY
  egress-zones: libvirt-routed
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

libvirt-routed-out
  priority: -1
  target: ACCEPT
  ingress-zones: libvirt-routed
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

libvirt-to-host
  priority: -1
  target: REJECT
  ingress-zones: libvirt-routed
  egress-zones: HOST
  services: dhcp dhcpv6 dns ssh tftp
  ports: 
  protocols: icmp ipv6-icmp
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

netavark_host_fwd (active)
  priority: -2
  target: CONTINUE
  ingress-zones: HOST
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

netavark_policy
  priority: -1
  target: ACCEPT
  ingress-zones: netavark_zone
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

netavark_portfwd (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services: 
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
</details>

Should be completely default aside from a single subnet added to the trusted zone.

**Comment by erig0** [comment]
@mheon, do you need this in Fedora ASAP? I could cut a patch release if yes.

**Comment by mheon** [comment]
That would definitely be appreciated if possible!

**Comment by erig0** [comment]
Okay. I'll put it on my TODO for next week.

**Comment by erig0** [comment]
This is now in f40 and f39 (https://bodhi.fedoraproject.org/updates/FEDORA-2024-e3e17773c5).

**Comment by mheon** [comment]
Thank you!
