### ISSUE TITLE
Policy and IPv6

### ISSUE THREAD

**Issue by SecT0uch** [firewalld/firewalld#1297]
### What happened

I'm using a Policy to DROP all outbound traffic except specified services.
This works as expected on IPv4, but not on IPv6.

### What you expected to happen

Policy works on both IPv4 and 6

### How to reproduce it (as minimally and precisely as possible)

```bash
firewall-cmd --permanent --new-policy output-policy
firewall-cmd --permanent --policy output-policy --add-ingress-zone HOST
firewall-cmd --permanent --policy output-policy --add-egress-zone ANY
firewall-cmd --permanent --policy output-policy --set-target DROP
firewall-cmd --permanent --policy output-policy --add-service dns
firewall-cmd --permanent --policy output-policy --add-service http
firewall-cmd --permanent --policy output-policy --add-service https
firewall-cmd --permanent --policy output-policy --add-service ntp
firewall-cmd --reload
```

`curl https://www.google.com/` works.
`curl https://www.google.com/ -6` doesn't work.

When the policy is disabled everything works fine.

### Anything else we need to know?

Am I even using policies the right way ?

### Firewalld Version

2.1.1

### Firewalld Backend

nftables

### Linux distribution

Alpine Linux edge

### Linux kernel version

6.6.15-0-lts

**Comment by erig0** [comment]
Probably because you're also blocking ICMPv6. Try adding this:
```
firewall-cmd --permanent --policy output-policy --add-protocol ipv6-icmp
```

**Comment by SecT0uch** [comment]
Indeed, thanks ! :)

**Comment by erig0** [comment]
To have a happy network. You should also add ICMPv4.

```
firewall-cmd --permanent --policy output-policy --add-protocol icmp
```
