### ISSUE TITLE
--runtime-to-permanent removing public zone from active zones 

### ISSUE THREAD

**Issue by devnullsecurity** [firewalld/firewalld#1307]
### What happened

I wrote this up but then did some more testing.  I initially noticed this behavior when adding sources to the internal zone, but later I tested removing some services from the public zone and had the same behavior.

Desired result is for SSH to be allowed for internal sources and other traffic to continue through the public zone.  This is the setup I used on centOS 7 and am currently trying to implement on Alma 9. Add the source to the internal zone and firewall-cmd --get-actives-zones still shows ens192 on the public zone, but after I run firewall-cmd --runtime-to-permanent the public zone is no longer visible in firewall-cmd --get active zones, however, if I restart firewalld it comes back:

[root@rbe0000 zones]# firewall-cmd --zone=internal --add-source=192.168.240.103
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
internal
  sources: 192.168.240.103
public
  interfaces: ens192
[root@rbe0000 zones]# firewall-cmd --runtime-to-permanent
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
internal
  sources: 192.168.240.103
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all --permanent
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --get-active-zones
internal
  sources: 192.168.240.103
[root@rbe0000 zones]# systemctl restart firewalld
[root@rbe0000 zones]# firewall-cmd --get-active-zones
internal
  sources: 192.168.240.103
public
  interfaces: ens192

### What you expected to happen

I expected the active zones would not be changed by running firewall-cmd --runtime-to-permanent and ens192 would still be associated with the public zone

### How to reproduce it (as minimally and precisely as possible)

Add a source to the internal zone (192.168.240.103 in my case).
Check active-zones and see that public is there with ens192
run firewall-cmd --runtime-to-permanent
Check active zones and see that public is not there.
Restart firewalld
Check active zones and see that public is back

firewall-cmd --zone=internal --add-source=192.168.240.103
firewall-cmd --get-active-zones
firewall-cmd --runtime-to-permanent
firewall-cmd --get-active-zones
systemctl restart firewalld
firewall-cmd --get-active-zones

### Anything else we need to know?

If I add the source to the permanent config and then restart or reload it works as expected:

[root@rbe0000 zones]# firewall-cmd --zone=internal --add-source=192.168.240.103 --permanent
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
public
  interfaces: ens192
[root@rbe0000 zones]# firewall-cmd --reload
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
internal
  sources: 192.168.240.103
public
  interfaces: ens192

### Firewalld Version

1.25

### Firewalld Backend

nftables

### Linux distribution

Alma Linux 9.3

### Linux kernel version

5.14.0-362.18.1.el9_3.x86_64

### Other information

I noticed similar behavior if I removed services from the public zone and the save the runtime config to permanent:

[root@rbe0000 zones]# firewall-cmd --zone=public --remove-service=dhcpv6-client
success
[root@rbe0000 zones]# firewall-cmd --zone=public --remove-service=cockpit
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
public
  interfaces: ens192
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all --permanent
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --runtime-to-permanent
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --zone=public --list-all --permanent
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: ssh
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
[root@rbe0000 zones]# firewall-cmd --reload
success
[root@rbe0000 zones]# firewall-cmd --get-active-zones
public
  interfaces: ens192

**Comment by erig0** [comment]
Hi, I think this was fixed by 84d4ed7c0686311b6db6c9ed018775a01141d12d which is in v1.2.7.

**Comment by devnullsecurity** [comment]
Ok.  Thanks.
