### ISSUE TITLE
Should `https.xml` include `http3.xml`?

### ISSUE THREAD

**Issue by jcpunk** [firewalld/firewalld#1309]
### What would you like to be added

Have the `https.xml` include the ports necessary for `http3`.

### Why is this needed

HTTP3 runs over port 443/udp.  When enabling HTTPs, I wonder if it makes sense to have `http3` automatically enabled.

**Comment by erig0** [comment]
No. I don't think so. At least not yet.

Apache does not support http3.
nginx has experimental support.
HAProxy support http3, but takes some configuration [1].

[1]: https://www.haproxy.com/documentation/haproxy-configuration-tutorials/load-balancing/http/#http%2F3
