### ISSUE TITLE
Feature request: Add a functionality for services/ports/protocols to be filtered first and then source IP

### ISSUE THREAD

**Issue by ku4eto** [firewalld/firewalld#1327]
### What would you like to be added

Feature request: Add a functionality for services/ports/protocols first and then source IP

A feature that would allow us to first filter incoming requests based on their service, port and/or protocol would be most welcome. 
This should also allow for multiple source IPs and ranges to be specified in the zones.

### Why is this needed

Currently strictly interface/source IP are the first ones to be filtered.
This is very problematic, when you have more than 1 service that you wish to allow across multiple source addresses, especially so when there are conflicting ones (allow for Service X, do not allow for Service Y). This would lead to the need to create a separate zone/rich rule for _EVERY_ single source IP.
Which kind of defeats the purpose of FirewallD being easily manageable, by having tens/hundreds/thousands of zones or rich rules.

Example:
We have a sevrer with 3 services - DNS, NTP and SSH running.
We want to allow IPs 1 to 10 (thats example) to the DNS service.
We want to allow IPs 5 to 15 to the NTP service.
We want to allow IPs 1,5,10,15,20 to the SSH service.

Easiest solution would be having 3 zones, 1 for each service with the source IPs described in each of them - which in fact we cant, since 1 source IP address or range can be defined ONLY once across all zones combined. Even if we could, if a zone matches the source IP, none of the other zones having the same Source IP will be traversed.

We are forced to either create multiple zones or a large amount of rich rules. Neither of the 2 are sane and healthy variants for managing large amounts of source IPs.

The example from above according to me would need at least 5 zones (maybe around 7).

If you increase the Source IPs, depending on the amount of overlapping IPs per service/port/protocol, the needed zones/rich rules skyrocket quite fast.

Current Zone (policy) priority cannot be used as a means of escaping the huge amount of source zones/rich rules from the example scenario, due to the same constriction of having only 1 Source IP being specified across all zones.

But Zone (policy) priority can be required to determine which service zone to be ingressed first (unless its in lexical order).

If there is similar solution, that may be implemented to allow similar scenarios to be a lot less painful experience with FirewallD, i would be fine with it as well.
Although i have the feeling the community may prefer this (due to the entire epic that was around AllowZoneDrifting).

**Comment by erig0** [comment]
> This would lead to the need to create a separate zone/rich rule for EVERY single source IP.

Are you aware that you can use an ipset with a rich rule?

e.g.

```
# firewall-cmd --permanent --add-rich-rule='rule family=ipv4 source ipset=ssh_ipset port port=ssh accept
```

**Comment by erig0** [comment]
Closing. As per above this is possible by using ipsets.

**Comment by ku4eto** [comment]
Coming a bit late to respond (personal stuff and other higher priority things) : this is not a solution.
We tried it extensively and `ipsets` face the same issues with overlapping IP addresses or ranges.
Regardless if `AllowZoneDrifting` is enabled, once a rule(zone) has been processed, all subsequent rules(zones) are ignored, even if they have different IP set attached to them.

**Comment by ku4eto** [comment]
`What you're asking for is [disallowed by design](https://firewalld.org/2020/01/allowzonedrifting) and eventually [removed](https://firewalld.org/2021/06/the-upcoming-1-0-0).`
I am not asking for `AllowZone Drifting`. I am asking for a way for firewalld to manage ingress traffic first based on port+protocol AND THEN based on source IP address.
The justification for this is ,that if you have multiple services, that make use of somewhat overlapping IP addresses and ranges, you will end up with basically a zone for every IP address/range, which can become thousands.
Meanwhile you can have only 3 services (ports+protocols), that you need to filter the traffic to.
So it makes more sense to have 3 zones that manage the traffic.
Otherwise we end up in exactly the same situation with `iptables` - absolutely painful management of big rule sets.
PS: Can you open the issue, so other people can have more visibility to it?

**Comment by ku4eto** [comment]
@erig0 4 months have passed since your last reply. Can you please address my last comment (the one above this)? 
Otherwise we will have no choice but to drop the use of `firewalld` in our company.

**Comment by erig0** [comment]
The answer is no. I will not develop this feature request. It is counter to firewalld's design.

https://firewalld.org/documentation/concepts.html
