### ISSUE TITLE
PolicyKit authentication attempt on startup of firewall-config times out after 25 seconds

### ISSUE THREAD

**Issue by AdamWill** [firewalld/firewalld#1328]
### What happened

If you start firewall-config and don't successfully complete PolicyKit authentication within 25 seconds, it times out, and shows a dialog:

Error
Authorization failed.

with OK and Quit buttons:

![screenshot of the dialog in question](https://github.com/firewalld/firewalld/assets/916551/8bc8af71-02ea-45f5-9592-9cbb0d3d6fac)

We hit this in openQA testing of Fedora KDE, because we use quite a long password for the test user ("weakpassword") and we type it intentionally slowly (because automated typing into laggy graphical UIs is flaky), and it's taking just longer than 25 seconds to type. But you could also hit it fairly easily in real usage by just launching the app then being distracted for a few seconds. 25 seconds isn't very long.

### What you expected to happen

When waiting for interactive authentication, the app should wait forever until the user succeeds, fails or quits the authentication workflow. A timeout is not useful.

### How to reproduce it (as minimally and precisely as possible)

1. Launch firewall-config, in a configuration where interactive PolicyKit authentication is required (e.g. a default Fedora 40 KDE or Workstation install)
2. Wait on the authentication UI (password entry dialog, fingerprint request, whatever) for 25 seconds

### Anything else we need to know?

This is happening way more often to the Fedora openQA test lately, but I'm not sure why. It's possible firewall-config winds up using some kind of default dbus timeout and that has been lowered recently, or something.

### Firewalld Version

2.1.2

### Firewalld Backend

irrelevant

### Linux distribution

Fedora 40

### Linux kernel version

6.8.5-301.fc40.x86_64

**Comment by erig0** [comment]
The 25 seconds you're seeing is the default dbus timeout.

Firewalld calls polkit's dbus method `CheckAuthorization`. It looks like this accepts a `timeout` argument that firewalld is not specifying. Unfortunately firewalld is calling this in blocking mode. A long auth/delay would completely block firewalld (it's already blocked for up to 25 seconds!!).

I think it's possible to increase this timeout. Is there functionally a difference between the daemon blocking for 25 seconds or 60 or 120? IMO, 25 is already an eternity.

**Comment by AdamWill** [comment]
The app is entirely useless if the user doesn't auth, so I think blocking as long as possible is sensible. If you fail the auth, firewalld just shows a dialog "Error Authorization failed." with OK and Quit buttons (this dialog is also blocking). Quit quits the app. OK re-tries the auth. You cannot use the app unless you auth successfully.

Given that, I think it should just set the timeout to 0 (if that means wait forever) or MAXINT otherwise. This is what wound up happening for a similar issue we happened to also run into recently with the GNOME XDG portal - https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/152 .

**Comment by AdamWill** [comment]
There is definitely a functional difference so far as our tests are concerned, because I can't quite make the test type the password 'very safely' (that's an approach that involves typing slowly and waiting the screen to change between each keypress) within 25 seconds. I've had to make the test type it less safely (still below its max typing rate, but faster than 'very safely', and without the screenshot checks), which is more prone to blip failures if it types too fast for the VM to keep up with, to work around this issue. Bumping the timeout a bit would mean we could have the test go back to typing 'very safely' without running into the timeout.

How significant it is to regular users...I dunno. Not everyone types very fast. people do launch apps then get distracted for a second. 25 secs does seem pretty short. I think there's a case for 60.

**Comment by erig0** [comment]
Yes. It's unfortunate. I don't know why this code is blocking. It has the effect that it'll block any other dbus activity while waiting on auth. That being said, the different between 25 seconds and 120 is... nothing; it's still an eternity for a daemon.

https://github.com/firewalld/firewalld/blob/9bc43fced6387799520c7239704e593db9b032b3/src/firewall/server/decorators.py#L232-L238

**Comment by erig0** [comment]
I would be okay with 60 seconds.

**Comment by erig0** [comment]
You could try this patch. Based on other code I've seen the `timeout` keyword should work. I have not tested it though.

```diff
diff --git a/src/firewall/server/decorators.py b/src/firewall/server/decorators.py
index 99b30306cfc2..22e607eba445 100644
--- a/src/firewall/server/decorators.py
+++ b/src/firewall/server/decorators.py
@@ -232,7 +232,7 @@ class dbus_polkit_require_auth:
                 # use polkit if it's available
                 if type(self)._interface_polkit:
                     (result, _, _) = type(self)._interface_polkit.CheckAuthorization(
-                        ("system-bus-name", {"name": sender}), action_id, {}, 1, ""
+                        ("system-bus-name", {"name": sender}), action_id, {}, 1, "", timeout=60
                     )
                     if not result:
                         raise NotAuthorizedException(action_id, "polkit")
```

**Comment by erig0** [comment]
Long term the auth should be converted to an async call. But that requires other changes to make it work.

**Comment by erig0** [comment]
Okay. I looked into making this async. It's non-trivial. The problem is the firewalld daemon implements service methods [1], but they themselves are not async. This is a prerequisite before we can call polkit asynchronously.

Today it looks like this:
```
[client] sync -- sync [firewalld] sync -- [polkit]
```

Changing the `CheckAuthorization()` to async would look like this:
```
[client] sync -- sync [firewalld] async -- [polkit]
```
However, this doesn't help because firewalld still has to block waiting on polkit so it can do the synchronous reply to the client.

We'd have to get to this point first:
```
[client] sync -- async [firewalld] async -- [polkit]
```

[1]: https://dbus.freedesktop.org/doc/dbus-python/dbus.service.html?highlight=method#dbus.service.method

**Comment by erig0** [comment]
@AdamWill , I gave up on the async changes for now. I simply bumped the timeout to 60 in #1335. I'll merge it after CI.
