### ISSUE TITLE
firewall-offline-cmd fails to enable/disable lockdown

### ISSUE THREAD

**Issue by vgaetera** [firewalld/firewalld#1336]
### What happened

firewall-offline-cmd fails to enable/disable lockdown:
```sh
> sudo firewall-offline-cmd --lockdown-on
'Firewall' object has no attribute 'enable_lockdown'

> sudo firewall-offline-cmd --lockdown-off
'Firewall' object has no attribute 'disable_lockdown'
```

### What you expected to happen

```sh
> firewall-offline-cmd --help | grep -e --lockdown
  --lockdown-on        Enable lockdown.
  --lockdown-off       Disable lockdown.
```

### How to reproduce it (as minimally and precisely as possible)

```sh
sudo firewall-offline-cmd --lockdown-on
sudo firewall-offline-cmd --lockdown-off
```

### Firewalld Version

2.1.2

### Firewalld Backend

nftables

### Linux distribution

Fedora Linux 40 (Forty)

### Linux kernel version

6.8.8-300.fc40.x86_64

**Comment by erig0** [comment]
This feature has been deprecated (#1269) and removed (#1275). As such, this bug is a won't fix.
