### ISSUE TITLE
firewalld reload/restart flushes tables not part of firewalld rules on version: 0.9.11 

### ISSUE THREAD

**Issue by toah-nc** [firewalld/firewalld#1340]
### What happened

When reloading or restarting firewalld, it will drop all existing iptables/nftables rules that are not a part of the firewalld chain.
The issue is mentioned here: https://github.com/firewalld/firewalld/issues/863 and fixed on some versions, but on Oracle Linux 8.9 with the newest firewalld version available (0.9.11) the issue is still occuring.

I tried Oracle Linux 9.3 running firewalld version: firewalld-1.2.5-2.0.1.el9_3.noarch and the issue is not present anymore. This is an issue if it's not possible upgrade to Oracle Linux 9 at the moment, which causes the firewalld to be unusable. 

### What you expected to happen

I would expect that firewalld only flush and reload the rules managed by firewalld.

### How to reproduce it (as minimally and precisely as possible)

The issue can be replicated by running below commands on OL8 with the newest available firewalld version from Oracles Yum repository:

Check that the Iptables rule is created:
iptables -L
iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT
iptables -L

Reload firewalld and it breaks:

systemctl reload firewalld
iptables -L

### Firewalld Version

0.9.11-1.0.1.el8_8

### Firewalld Backend

nftables

### Linux distribution

Oracle Linux 8.9

### Linux kernel version

5.15.0-203.146.5.1.el8uek.x86_64

**Comment by toah-nc** [comment]
> This issue is fixed on current code. Upstream no longer support the 0.9.z releases. I don't know what you want from filing this issue.

The purpose of the issue was to hopefully bring attention on the issue with the major vendors have "frozen" their yum repositories on version 0.9.z, so I assumed the 0.9.z would had a hotfix with the fixes that could be incorporated into the RHEL/Oracle yum repositories.

I tried on OL8 to manually build the RPM files for version (firewalld-1.2.5, firewalld-1.2.7, firewalld-1.3.4, firewalld-2.1.2) and it seems only the 2.x firewalld version was able to be reloading without dropping existing iptables rules.
So I assume no other versions receive the fixed code?

So the only alternative to solve the issue is building the latest firewalld version, since there are no yum repositories to my understanding serving the newest RPM files for firewalld.

**Comment by erig0** [comment]
> So the only alternative to solve the issue is building the latest firewalld version

I suggest looking at the --direct rules.

**Comment by toah-nc** [comment]
> > So the only alternative to solve the issue is building the latest firewalld version
> 
> I suggest looking at the --direct rules.

Thank you - I will look into that and we will just have to build the RPM files in case we can't stay on the 0.9.z version.

I will close the issue.
