### ISSUE TITLE
Error: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory

### ISSUE THREAD

**Issue by rcfa** [firewalld/firewalld#1370]
### What happened

Firewall doesn’t work as expected:

```
# firewall-cmd --check-config                                         
success

```

but:

```
# firewall-cmd --complete-reload                                      
Error: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory


JSON blob:
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_FORWARD_POLICIES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "eth0"}}, {"counter": null}, {"reject": {"type": "icmpx", "expr": "admin-prohibited"}}], "index": 0}}}]}

```

Switching the backend from nftables to iptables "fixes" the problem, but that’s not a real solution given firewalld.conf states:

```
# Note: The iptables backend is deprecated. It will be removed in a future
# release.

```

The rather minimal configuration that triggers this here, is attached:

[firewalld-config.zip](https://github.com/user-attachments/files/16401152/firewalld-config.zip)

Default zone is public.

### Firewalld Version

2.1.2-2

### Firewalld Backend

nftables

### Linux distribution

Kali GNU/Linux Rolling

### Linux kernel version

Linux 5.15.44-Re4son-v8l+ #1 SMP PREEMPT Debian kali-pi (2022-07-03) aarch64 GNU/Linux

**Comment by rcfa** [comment]
With my regular config, the message looks a bit different (IP address replaced with dummy), but it’s the same: works with iptables, fails with nftables:

```
# firewall-cmd --version               
2.1.2

# firewall-cmd --check-config                                           
success

# firewall-cmd --complete-reload
success

# nano firewalld.conf

# diff firewalld.conf firewalld.conf.old
59c59
< FirewallBackend=nftables
---
> FirewallBackend=iptables

# firewall-cmd --complete-reload
Error: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory


JSON blob:
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"rule": {"family": "inet", "table": "firewalld", "chain": "filter_FORWARD_POLICIES", "expr": [{"match": {"left": {"meta": {"key": "iifname"}}, "op": "==", "right": "eth0"}}, {"match": {"left": {"payload": {"protocol": "ip", "field": "daddr"}}, "op": "==", "right": {"prefix": {"addr": "123.45.67.0", "len": 24}}}}, {"counter": null}, {"reject": {"type": "icmpx", "expr": "admin-prohibited"}}], "index": 1}}}]}
                                                                                                                                    
# firewall-cmd --check-config                                           
success

```

**Comment by erig0** [comment]
What is your nftables version? There was a recent bug that caused similar symptoms. See #1366.

**Comment by rcfa** [comment]
nftables version as per apt database: 1.1.0-2
as per command:
```
# nft -v           
nftables v1.1.0 (Commodore Bullmoose)

```

**Comment by rcfa** [comment]
looks like the push of 1.1.0-2 over 1.1.0 might have fixed it for now. Given the discussion at the referenced bug #1366 , this may not have been the last word, but it looks likely that what I’m experiencing is/was the same issue.
So I’ll close this for now. Hope it doesn’t need to be reopened...

**Comment by bckelley** [comment]
still having this issue `nft -v nftables v1.1.5 (Commodore Bullmoose #6)`

**Comment by minerharry** [comment]
Issue occurs sporadically for me too, usually fixed on restart but not always. (First triggers when I try to start the default libvirt network with `virsh net-start default`, then on complete-reload and further attempts to activate). By running `sudo python -m pdb /usr/bin/firewalld --nofork --pid --debug` (and adding a breakpoint where the error is caught) I could see the list of commands sent to python-nftables, and running them manually reveals the following command JSON is what raises the error:
```[{'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'reject': {'type': 'icmpx', 'expr': 'admin-prohibited'}}]}}}]
```
which in CLI corresponds to `nft add rule inet firewalld filter_INPUT reject with icmpx type admin-prohibited`. Changing the type or expression values to different (allowed) values doesn't change the error, nor does leaving them blank with {'reject':{}}. Using a different expression other than reject works fine. 

The immediately preceding JSON commands successfully create and add to filter_INPUT, so the chain definitely exists:
```
{'add': {'chain': {'family': 'inet',
    'table': 'firewalld',
    'name': 'filter_INPUT',
    'type': 'filter',
    'hook': 'input',
    'prio': 10}}},
{'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'match': {'left': {'ct': {'key': 'state'}},
       'op': 'in',
       'right': {'set': ['established', 'related']}}},
     {'accept': None}]}}}, 
 {'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'match': {'left': {'ct': {'key': 'status'}},
       'op': 'in',
       'right': 'dnat'}},
     {'accept': None}]}}},
 {'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'match': {'left': {'meta': {'key': 'iifname'}},
       'op': '==',
       'right': 'lo'}},
     {'accept': None}]}}},
 {'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'match': {'left': {'ct': {'key': 'state'}},
       'op': 'in',
       'right': {'set': ['invalid']}}},
     {'drop': None}]}}},
 {'add': {'chain': {'family': 'inet',
    'table': 'firewalld',
    'name': 'filter_INPUT_POLICIES'}}},
 {'add': {'rule': {'family': 'inet',
    'table': 'firewalld',
    'chain': 'filter_INPUT',
    'expr': [{'jump': {'target': 'filter_INPUT_POLICIES'}}]}}}
```
corresponding to the following commands:
```
nft 'add chain inet firewalld filter_INPUT { type filter hook input priority 10 ; }'
nft add rule inet firewalld filter_INPUT ct state { established, related } accept
nft add rule inet firewalld filter_INPUT ct status dnat accept
nft add rule inet firewalld filter_INPUT iifname "lo" accept
nft add rule inet firewalld filter_INPUT ct state invalid drop
nft add chain inet firewalld filter_INPUT_POLICIES
nft add rule inet firewalld filter_INPUT jump filter_INPUT_POLICIES
```

Running these commands, and then the offending command above, does not cause any errors on its own with a blank inet firewalld table. It's unclear to me why exactly this is failing, or why a reject command would trigger a no such file or directory error.
