### ISSUE TITLE
How can I set a rule / policy to allow traffic from one zone to another zone?

### ISSUE THREAD

**Issue by kind03** [firewalld/firewalld#1376]
I have reviewed the related documents and manual such as the https://firewalld.org/documentation/man-pages/firewalld.policies.html but cannot find an answer... Could you guys please help. Thanks!

**Comment by erig0** [comment]
Did you read the [concepts page](https://firewalld.org/documentation/concepts.html) ? It gives an example.

> In this example, myPolicy will filter forwarded traffic originating from the internal ingress zone and destined for the external egress zone.

```
# firewall-cmd --permanent --new-policy myPolicy
# firewall-cmd --permanent --policy myPolicy --add-ingress-zone internal
# firewall-cmd --permanent --policy myPolicy --add-egress-zone external
# firewall-cmd --permanent --policy myPolicy --set-target ACCEPT
# firewall-cmd --reload
```
