### ISSUE TITLE
Podman and Firewalld: Port Forwarding through the Firewall

### ISSUE THREAD

**Issue by mheon** [firewalld/firewalld#1380]
### What would you like to be added

Podman has the ability to run containers with ports forwarded to them (e.g. `podman run -p 8080:80 ...` starts a container with port 8080 on the host forwarded to port 80 in the container). We accomplish this with firewall rules (directly using iptables or nftables, or direct addition to firewalld via DBus API). Right now, when a port is forwarded, it is immediately accessible from the outside world without any action on the firewalld side. This has obvious security implications; containers are punching holes in the system firewall, and worst of all the forwarded ports won't even be visible in firewalld's config if using the Podman iptables/nftables firewall backends. This is probably OK for a developer desktop but not really acceptable for a server machine.

It would be nice to have a way to force all port forwarding to require an explicit firewalld rule. We could potentially do this on the Podman side by just not creating firewall rules, but out port-forward configs can be sufficiently complex that I wouldn't want to force users to implement them manually in firewalld with rich rules. Another way could be a firewalld configuration option which would mark non-firewalld traffic in such a way that it would not be allowed through the firewall without an explicit allow rule added by the administrator. This could be enabled by default on server distributions but not desktop ones, which I think matches expected behavior (e.g. Fedora Server/RHEL require explicit admin action to forward ports, Fedora Desktop does not).

**Comment by erig0** [comment]
So here is what I'm thinking:

  - add `StrictForwardPorts` knob in `/etc/firewalld/firewalld.conf`
  - with `StrictForwardPorts=no` we keep the top-level `ct state dnat
    accept` rule
    - this is what's currently creating the "hole" in firewalld
  - with `StrictForwardPorts=yes` we replace the top-level `ct` rule
    with a rule per forward port that matches the original tuple's
    destination port, i.e. the forwarded port
    - rules will look like `ct state dnat ...  ct proto-dst <original
      dest port>`
  - modern podman has direct firewalld integration so it will add the
    forward port through firewalld
    - as such; firewalld has no way to distinguish podman vs non-podman
      NAT'd packets
    - *Podman will have to read this value and determine whether or not
      to send the publish/forward-port to firewalld*
  - needs documentation on both ends to make this clear to users

I think this covers all of our bases; including Docker.

**Comment by mheon** [comment]
This plan SGTM. Querying a config value on our end seems like a perfectly viable solution.
