### ISSUE TITLE
game access

### ISSUE THREAD

**Issue by Birdie377** [firewalld/firewalld#151]
I am no longer able to see some of my games on Facebook or get into some of them because of this firewall 
It is very frustrating and I want to remove it please assist me with this matter

**Comment by t-woerner** [comment]
I am really not sure what could case this.
Which distribution and firewalld version are you using?

**Comment by Birdie377** [comment]
firewall=config 0.4.0 website
(c)2010 Red Hat,Inc.

**Comment by t-woerner** [comment]
Is the access working if firewalld is temporarily turned off?

**Comment by Birdie377** [comment]
no it still is unaccessible so now I have upgraded my Linux and Ubuntu systems plus the Facebook plug ins for the apps to see if that makes a difference have to try this now..

**Comment by t-woerner** [comment]
If it is not working with firewalld deactivated either, how can this then be a firewalld issue?

**Comment by Birdie377** [comment]
it was working fine before I installed this firewall that's why?

**Comment by Birdie377** [comment]
How do I get this firewall out of my computer the easy way?
