### ISSUE TITLE
Wishlist: Easier service-from-source syntax

### ISSUE THREAD

**Issue by da2x** [firewalld/firewalld#165]
Rich-rules are great. But they’re a pain to remember. All I ever use them for is limiting some services to the local network by source address/mask. Can we please get an easier syntax for this?

Current:

    firewall-cmd --permanent --add-rich-rule=' rule family="ipv4" source address="10.0.0.0/8" service name="https" accept'
    firewall-cmd --permanent --add-rich-rule=' rule family="ipv6" source address="2001:a11:beef::7ac0/64" service name="https" accept'

Proposal:

    firewall-cmd --permanent --add-service=https --from-source=10.0.0.0/8,2001:a11:beef::7ac0/64

Competition (Ubuntu):

    ufw allow https/tcp from 10.0.0.0/8,2001:a11:beef::7ac0/64

This is most useful in single-interface workstation setups where you want `kde-connect, mdns, icecream` to be accessible from the local network only but are perfectly happy with exposing `ssh, https` to the internet. This will just become more and more useful going forward with the ever growing adoption of IPv6 with the minimum protection offered by the home IPv4 NAT router quickly ebbing away.

**Comment by erig0** [comment]
We're not going to change the syntax as that would cause lots of compatibility issues.
