### ISSUE TITLE
Increase usability of the UI (firewall-config)

### ISSUE THREAD

**Issue by jv-barsuk** [firewalld/firewalld#170]
I think the UI is not very straight forward. My suggestions to make it better are:
- Remove the explanation text and make it available via help. The one below zones and the one below services,...
- Set the default configuartion to permanent
- give a possibility to set the default zone via selecting it, right click, set as default
- Grayout Options -> connection zones if empty
- Reduce the number of predefined zones (e.g. home, work, public, block)
- make the default target available under an easier to reach menu (e.g. context menu)
- Reduce the amount of password requests. Maybe use a save button to write all the changes at once and only than ask for the password. Or force the application to start always with root privileges

**Comment by erig0** [comment]
This is a vague request and as such has nothing actionable. Take a look at [cockpit](https://cockpit-project.org/) for an alternative and simple GUI.
