### ISSUE TITLE
Run interface rules even when NetworkManager is active

### ISSUE THREAD

**Issue by AndersBlomdell** [firewalld/firewalld#182]
When NetworkManager is active some firewall commands are filtered out, a quick fix
is found in https://github.com/t-woerner/firewalld/pull/180

**Comment by AndersBlomdell** [comment]
Small test program, run with interface as argument:

  chmod +x nm_firewall.txt
  ./nm_firewall.txt eth0


[nm_firewall.txt](https://github.com/t-woerner/firewalld/files/640105/nm_firewall.txt)

**Comment by t-woerner** [comment]
I am sorry, but I do not see any difference with and without NetworkManager. Which distribution and firewalld and NetworkManager versions are you using?

**Comment by AndersBlomdell** [comment]
Fedora 23:
  firewalld-0.4.3.2-1
  NetworkManager-1.0.12-2

Fedora-24:
  firewalld-0.4.4.2-1
  NetworkManager-1.2.4-3

Find very abusive test attached (it shows that under some circumstances, needed rules are NOT added to iptables).

[nm_firewall.txt](https://github.com/t-woerner/firewalld/files/645693/nm_firewall.txt)

**Comment by AndersBlomdell** [comment]
NB: The patch also changes the ternary return values 

  nm_is_imported() -> nm_get_connection_of_interface(interface) -> True
  nm_is_imported() -> !nm_get_connection_of_interface(interface) -> False
  !nm_is_imported() -> None

If the ternary logic is intended, feel free to change back the indentation.

**Comment by erig0** [comment]
Fixed by 99e1c79, and indicated in pr #180.
