### ISSUE TITLE
RFE: Support client side conntrack helpers

### ISSUE THREAD

**Issue by aalba6675** [firewalld/firewalld#185]
Issue: --add-service tftp-client doesn't seem to help TFTP connections **from** this device as the rule goes into PREROUTING instead of OUTPUT.

Question: Is this the intended behaviour? Perhaps the documentation could be clearer that this is meant for the device acting as a NAT+router not TFTP client? Then won't we need nf_nat_tftp as well?

For "--add-service tftp-client" the rule

-j CT -p udp -m udp --dport 69 --helper tftp 

goes into PRE_$INZONE_allow. This helps TFTP connections **through** this device but not **from** this device, right? This still won't work without enabling nf_nat_tftp (if device is doing NAT as well as routing).

If I wanted to enable tftp-client **from** this device, I would need

firewall-cmd --direct --add-rule -j CT ipv4 raw OUTPUT 0 -o $OFACE -p udp -m udp --dport 69 --helper tftp 

which is not obvious.

**Comment by aalba6675** [comment]
Clean Fedora 25 install with firewalld-0.4.4.2. Sure had a hard time getting the TFTP client to work because I didn't  realise that "--add-service tftp-client" was inserting a rule in PREROUTING not OUTPUT (as per the documentation). The return TFTP connection was still being blocked.

Mismatch in expectation because "--add-service tftp-client" sounds like "enables TFTP client from this machine through this zone".

**Comment by erig0** [comment]
In order to support this, firewalld first needs real OUTPUT support. Once that is done we can attach the helpers to the OUTPUT chains.
