### ISSUE TITLE
IPv6 Source with mask

### ISSUE THREAD

**Issue by TriMoon** [firewalld/firewalld#193]
When one tries to add an IPv6 source with mask to a chain the source is added without the mask.

Example:
1) Add ``ff80::/10`` as source to lets say the **dmz** chain using the UI of firewalld
2) This will result in ``ff80::`` being used as source in the firewall rules.
You can check this using ``sudo ip6tables -nL|less``

The only workaround for this problem is using an ipset as source, containing ``ff80::/10`` as member.

**Comment by t-woerner** [comment]
Which firewalld version are you using?

**Comment by t-woerner** [comment]
This has been fixed: https://github.com/t-woerner/firewalld/commit/fe3fbf3b4d86467a5864f711e2d4ddceb7ee7a75

A new release with this fix will be available soon.

**Comment by TriMoon** [comment]
No idea which version i used when posting this issue, but i'm on the testing branch of debian and update multiple times a day as updates are available....
It says 0.4.4.2-1 (testing) at moment...
