### ISSUE TITLE
Error entering IPv4 source with mask in firewall-config

### ISSUE THREAD

**Issue by hbien** [firewalld/firewalld#198]
Using firewall-config, you cannot enter a IPv4 address with mask as a source.

Steps to reproduce:
1) Start firewall-config (v0.4.3.2)
2) Select any zone
3) Choose 'Sources' tab
4) Select 'Add'
5) Choose 'IP' as type and click on blank address
6) Enter an IPv4 address with mask, e.g. 192.168.0.0/24
7) Click 'OK'
8) You now see a dialog with 'IP' and your IP address with mask, as expected
9) You cannot hit 'OK' - only 'Cancel'.

I suspect UI code for validation is not validating IPv4 with mask. It validates a single IPv4 address just fine, and even permits invalid single IPs such as '192.168.0.0'. Examining the source code, it's hard to tell, but the validation for entering a IPv4 with mask in entering an IP address is ok (the second dialog box for entering new address), but then the selection of source IP addresses (first dialog box) fails to validate when mask is present. However, first glance through source code appears that both call the same validation function (functions.IP4nMask), so not sure why there should be a discrepancy.

Workaround: use firewall-cmd -zone=<ZONE> --add-source=<IP/mask>

**Comment by t-woerner** [comment]
This has been fixed: https://github.com/t-woerner/firewalld/commit/fe3fbf3b4d86467a5864f711e2d4ddceb7ee7a75

A new release with this fix will be available soon.
