### ISSUE TITLE
Accept/Reject/Drop Forwarding packets

### ISSUE THREAD

**Issue by jonramc** [firewalld/firewalld#2]
It would be a great deal if there was the option of creating a rule for forwarding packets within any zone.

For example: firewall-cmd --zone=internal --add-rich-rule='rule family="ipv4" source address="192.168.100.0/24" service name="http" type="forward" drop'

This way you can control any forwarding traffic coming from your LAN to the Internet or any other Interface.

**Comment by t-woerner** [comment]
Yes, this needs to be implemented. A limitation of rules to INPUT or FORWARD would be good to have.

**Comment by mailinglists35** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=929426
