### ISSUE TITLE
Problem with vnc port: gets blocked automatically...

### ISSUE THREAD

**Issue by petasis** [firewalld/firewalld#202]
Hi all,

I am using fedora 25, and I have problem: while the port for vnc is open, I cannot connect.
In order to connect, I have to login as root, restart firewalld daemon, and connect with vnc.
But after a (random) amount of time, the port gets closed again.

How to debug this?

**Comment by t-woerner** [comment]
How have you opened the port for vnc? Please verify with `iptables-save | grep 5900` if there is a rule to allow this port after restarting and also if the issue appears.
