### ISSUE TITLE
RabbitMQ support

### ISSUE THREAD

**Issue by mhalano** [firewalld/firewalld#208]
RabbitMQ is a very popular message queue system. There is a lot of open ports depending of whats services you use. The full list are:
4369 (epmd)
5672, 5671 (AMQP 0-9-1 and 1.0 without and with TLS)
25672. This port used by Erlang distribution for inter-node and CLI tools communication and is allocated from a dynamic range (limited to a single port by default, computed as AMQP port + 20000).
15672 (if management plugin is enabled)
61613, 61614 (if STOMP is enabled)
1883, 8883 (if MQTT is enabled)
May be create subservices like rabbitmq, rabbitmq-management, etc.

Documentation: https://www.rabbitmq.com/networking.html

**Comment by MichaelAnckaert** [comment]
I think you can create a custom services definition file for RabbitMQ in /usr/lib/firewalld/services that looks something like this:

`<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>RabbitMQ</short>
  <description>RabbitMQ is an open source message broker</description>
  <port protocol="tcp" port="4369"/>
  <port protocol="tcp" port="5671"/>
  <port protocol="tcp" port="5672"/>
</service>`

I would create a pull request but the change is pretty trivial. If you can help complete the definition (maybe add more services) I'm sure of the maintainers can add it. I would do it but I'm not familiar enough with RabbitMQ to make a good call on what makes sence from a firewall management point of view.

**Comment by erig0** [comment]
This is covered by the generic amqp service/amqps service definitions added in a4568dd.
