### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by bltnkl** [firewalld/firewalld#222]
http://www.firewalld.org/documentation/configuration/runtime-versus-permanent.html
Has typo in the last sentence:
"If the firewall setup is not working, a simple firewalld reload/restart will reapply the workgin permanent configuration." - workING, not workGIN.

http://www.firewalld.org/documentation/utilities/firewall-applet.html
Has typo in the last sentence in "firewall-applet" titled paragraph:
"The applet has ben ported over to Qt4 as the StatusIcon support in Gtk3 has been deprecated." - "has BEEN", not "has BEN".

http://www.firewalld.org/documentation/zone/options.html
Has typo in paragraph describing "service" tag:
"The name of the service to be enabled. To get a list of valid service names firewall-cmd --list=services can be used." - "--list-services", not '--list=services".

http://www.firewalld.org/documentation/zone/options.html
Has typo in paragraph describing "icmp-block" tag:
"The name of the Internet Control Message Protocol (ICMP) type to be blocked. To get a list of valid ICMP types firewall-cmd --list=icmptypes can be used." - "--list-icmptypes", not "--list=icmptypes".

http://www.firewalld.org/documentation/zone/options.html
Has redundancy in parahraph describing "forward-port" tag:
"The destination IPv4 IP address." - "IPv4 address", not "IPv4 IP address".

http://www.firewalld.org/documentation/zone/options.html
Has typo in the very last sentence on the page:
"For a full description on rich language rules, please have a look at firewalld.richlanguage(5)." - "description OF", not "description ON".

http://www.firewalld.org/documentation/service/options.html and in several other pages describing options:
Has too much lax register in the paragraph titled "Options":
"The config can contain these tags and attributes. " - "service configuration file", not "config".

http://www.firewalld.org/documentation/service/options.html
Has typo in the paragraph describing "short" tag:
"Is an optional start and end tag and is used to give a ervice a more readable name." - "service", not "ervice".

http://www.firewalld.org/documentation/howto/open-a-port-or-service.html
Has typo in the last sentence of the paragraph titled "How to open port 80/tcp with firewall-cmd:":
"This means the port will be open also after a system reboot or firewalld serice reload." - "service", not "serice".

http://www.firewalld.org/documentation/howto/add-a-service.html
"There are different ways to a add a new service. A new service will only be visible in the runtime environment after it has been added. To be able to use it also in the run time environment, you need to reload firewalld." -  seems that it should be:
"There are different ways to a add a new service. A new service will only be visible in the PERMANENT environment after it has been added. To be able to use it also in the RUNTIME environment, you need to reload firewalld."

http://www.firewalld.org/documentation/howto/add-a-service.html
"This adds a new service using all settings from the file including the servie name.", should be:
"This adds a new service using all settings from the file including the serviCe name."

http://www.firewalld.org/documentation/howto/add-a-service.html
"The original service will be effective in the run time environment only after a reload.", should 
be: "The original service will be effective in the ruNTime environment only after reload."
"A package that is placing the service in the /usr/lib/firewalld/services diretory should require the firewalld package or sub package that is providing the path.", should be:
"A package that PLACES the service in the /usr/lib/firewalld/services direCtory should require the firewalld package or suBPackage that is providing the path."

http://www.firewalld.org/documentation/howto/debug-firewalld.html
"This file does not exist in all distributions. In Fedora or RHEL based distributions it usable:", should be:
"This file does not exist in all distributions. In Fedora or RHEL based distributions it IS usable:"

Thanks.

**Comment by erig0** [comment]
The website contents are in repository firewalld/firewalld.github.io.
I'm going to close this here, and open one over there - firewalld/firewalld.github.io#2.
