### ISSUE TITLE
Default ordering of firewall rules

### ISSUE THREAD

**Issue by EinerPetersen** [firewalld/firewalld#224]
1) in the zone/source --- would like to see the IP addresses sorted in
the same fashion as sort -r -V (Version type of sort in reverse sort
order .. descending order) this would group the ip addresses together
.... 192.168.1.0/32 would be before 192.168.1.0/24 for example .... it
would tend to put the more specific range before the lesser

2) save the order of the IP addresses as seen in the Firewall-Config in
the same order in the XML file for the zone ---- makes it easier to see
what order the rules are going to be processed

3) in the zone/rich rules --- would like to be able to specify the order
I want the rules to be processed ---- like process this rule (allow ssh
for this IP/IP range, let's say it's a /24 within a /16 of the next rule
for example) then process the next rule (don't allow anything for the
rest of this /16).  This would also make it easier to put a last rule as
the default for the zone (that's easy to see :-)) ...... How about the
most specific rule before the least specific by IP range as the default?
(then it would work similar to what ipsets does when specifying
hash:net)

4) Since #3 would be an "Exception" to the default sort order, tag it visually so we remember we did that :-)

**Comment by t-woerner** [comment]
1. Also applies for port forwarding in rich rules with more generic and more specific addresses.
