### ISSUE TITLE
Add a note relative to using IPSET rules

### ISSUE THREAD

**Issue by EinerPetersen** [firewalld/firewalld#225]
You might want to put a visible note somewhere that tells the user "If you have a whole lot of
IP addresses or big IP address ranges specified in ipsets, you should
use hash:net vs hash:ip" ...... kind of found that out the hard way  ..... :-)

**Comment by erig0** [comment]
I think adding notes about all the different ipset types would only clutter the UI. Users should reference the ipset docs.
