### ISSUE TITLE
Is it 'source not' or is it 'source invert=true'?

### ISSUE THREAD

**Issue by bashtheshell** [firewalld/firewalld#229]
I'm confused with which one is the correct way of configuring the inverse rule.

I'm running CentOS 7.3 with firewalld version 0.4.3.2.

In [firewalld.zone(5)](http://www.firewalld.org/documentation/man-pages/firewalld.zone.html) man-page, I see:

```
 [ <source address="address[/mask]"|mac="MAC"|ipset="ipset" [invert="True"]/> ]
```

Yet, in [firewalld.richlanguage(5)](http://www.firewalld.org/documentation/man-pages/firewalld.richlanguage.html) man-page, I'm getting the following:

```
source [not] address="address[/mask]"|mac="mac-address"|ipset="ipset"
```

**Comment by bashtheshell** [comment]
After doing further investigation, I can confirm `source invert=true` was the original implementation in vanilla CentOS Linux release 7.0.1406 (Core).

In firewalld.zone(5) man-page from the above release I get the following:

```
               [ <source address="address[/mask]" [invert="bool"]/> ]
```

And in firewalld.richlanguage(5) man-page, the original line was:

```
source address="address[/mask]" [invert="True"]
```

Will `source invert=true` no longer work?

**Comment by erig0** [comment]
For rich rules they're both acceptable. However using the "not" prefix is preferred.
See 7d3ae9f6881c5eb251f4f21da35b4cbe35527c51 for reference.

**Comment by erig0** [comment]
I believe that answers your question. If not, please reopen.
