### ISSUE TITLE
firewall-cmd equivalent of: "iptables -I FORWARD 1 -m physdev --physdev-is-bridged -j ACCEPT"

### ISSUE THREAD

**Issue by sjlongland** [firewalld/firewalld#238]
Hi all,

I tried asking on the mailing list, but it refuses to let me sign up directly or via Github, and I don't have accounts on the other services… anyway.  I am running `firewalld` 0.4.3.3 on Gentoo.

I am trying to permanently do this:
```
iptables -I FORWARD 1 -m physdev --physdev-is-bridged -j ACCEPT
```

so that my containers and VMs have local network access without being firewalled.

Best I can figure out from the documentation is to do this…

```
vk4msl-ws ~ # firewall-cmd --permanent --zone=public --add-rule ipv4 filter 1 -m physdev --physdev-is-bridged -j ACCEPT
usage: see firewall-cmd man page
Wrong usage of 'direct' options.
```

What is the right "usage of 'direct' options" to do this?

**Comment by erig0** [comment]
You need to use "--direct" and also specify the chain.

How about this command:
  # firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT 1 -m physdev --physdev-is-bridged -j ACCEPT

**Comment by sjlongland** [comment]
Yeah, that worked but it put it on the INPUT chain not FORWARD.  I think I see what I need to substitute though.

**Comment by sjlongland** [comment]
Okay, after running these commands:
```
RC=0 rikishi stuartl $ firewall-cmd --permanent --direct --remove-rule ipv4 filter INPUT 1 -m physdev --physdev-is-bridged -j ACCEPTsuccess
RC=0 rikishi stuartl $ firewall-cmd --permanent --direct --remove-rule ipv6 filter INPUT 1 -m physdev --physdev-is-bridged -j ACCEPT 
success
```

and correcting the earlier rule set, I think that's done it.  Thanks. :-)
