### ISSUE TITLE
Conntrack Modules unloaded at firewalld restart/complete-reload

### ISSUE THREAD

**Issue by sll552** [firewalld/firewalld#242]
Hi,

I am using firewalld on Centos 7 in combination with ipsec tunnels and gre. Ipsec was no probem to configure with the predefined services, but gre gave me some headache to get it working.

- First I needed to add the protocol to the respective zone (after this gre packages did not get rejected anymore). But after this I received tons of STATE_INVALID drops on the gre packages.

- To resolve this I manually loaded the nf_conntrack_proto_gre kernel module. This resolves the drops but is only temporary as every time firewalld is restarted the module is unloaded and the firewall starts blocking all traffic from the tunnel.

How can I configure firewalld to either load the required module or at least stop it from unloading the needed module?

Best regards

**Comment by erig0** [comment]
You can create a new service for GRE that loads the correct kernel module (--add-module). Then add this service to your zone like normal.
http://www.firewalld.org/documentation/howto/add-a-service.html

**Comment by sll552** [comment]
Thanks it worked perfectly.
I was not aware that i could configure a service without ports. 
Anyway the behavior of unloading modules seems a little strange to me.
