### ISSUE TITLE
Firewalld problem after putting back disk image

### ISSUE THREAD

**Issue by pcoenen** [firewalld/firewalld#243]
Hallo,

Yesterday I put back a disk image of my server, since then I'm unable to start firewalld.

I get the following errors:

`sep 04 13:11:46 Plutus systemd[1]: Starting firewalld - dynamic firewall daemon...
sep 04 13:11:54 Plutus systemd[1]: Started firewalld - dynamic firewall daemon.
sep 04 13:11:55 Plutus firewalld[439]: WARNING: ipset not usable, disabling ipset usage in firewall.
sep 04 13:11:57 Plutus firewalld[439]: WARNING: iptables not usable, disabling IPv4 firewall.
sep 04 13:11:57 Plutus firewalld[439]: WARNING: ip6tables not usable, disabling IPv6 firewall.
sep 04 13:11:57 Plutus firewalld[439]: WARNING: ebtables not usable, disabling ethernet bridge firewall.
sep 04 13:11:57 Plutus firewalld[439]: FATAL ERROR: No IPv4 and IPv6 firewall.
sep 04 13:11:57 Plutus firewalld[439]: ERROR: Raising SystemExit in run_server`

When I run `iptables -L` get:

`iptables v1.4.21: can't initialize iptables table 'filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.`

`uname -a`gives me:

`Linux Plutus 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

I tried almost everything you can find on the internet about this issue.

**Comment by erig0** [comment]
Sounds like the kernel modules are missing. Can you load ip_tables?
`# modprobe -r ip_tables; modprobe ip_tables`

Also verify you have modules for the running kernel:
`# ls /lib/modules/$(uname -r)`
