### ISSUE TITLE
firewalld-applet no longer works with Gnome 3.26

### ISSUE THREAD

**Issue by benjamindaines** [firewalld/firewalld#246]
With the release of 3.26, Gnome is no longer including the legacy tray, where the applet would normally live.  The current solution is for users to install Topicons Plus extension or AppIndicator Support extension.  

However, the firewalld-applet does not display in either of these.  

This is also an issue with programs such as Discord.  However, at launch they can be run with "env XDG_CURRENT_DESKTOP=Unity" in order to have their icons displayed properly via the KStatusNotification (AppIndicator extension).  This integrates better with the shell and would be preferred.

The same thing should be able to be applied to the firewalld-applet.

**Comment by benjamindaines** [comment]
The applet works in wayland, not xorg.

**Comment by erig0** [comment]
Close as per this bug and explanation: https://bugzilla.redhat.com/show_bug.cgi?id=1791860#c15
