### ISSUE TITLE
MAC address ipset not working with rich rule in CentOS 7.4.1708?

### ISSUE THREAD

**Issue by yellowsoar** [firewalld/firewalld#250]
Here's my problem:
All my other rich rules work fine with ipsets which based on IPs.
Except this one below which based on MAC address:

Ipset xxxxx:
```
<?xml version="1.0" encoding="utf-8"?>
<ipset type="hash:mac">
  <entry>11:22:33:44:55:66</entry>
</ipset>
```

Rich rule:
`rule family="ipv4" source ipset="xxxxx" port port="12345" protocol="tcp" accept`

Here's my envs:
CentOS 7.4.1708
firewalld 0.4.4.4

**Comment by erig0** [comment]
Are there any errors? Please check logs.
`systemctl status firewalld`

**Comment by yellowsoar** [comment]
Sorry for missing errors..
I got these errors:
```
ERROR: Failed to create ipset 'xxxxx'
ERROR: '/usr/sbin/ipset restore' failed: ipset v6.29: Error in line 1: Kernel error received: set type not supported
```

**Comment by yellowsoar** [comment]
For supported ipset types by  
`$ firewall-cmd --get-ipset-types`:
```
hash:ip
hash:ip,mark
hash:ip,port
hash:ip,port,ip
hash:ip,port,net
hash:mac
hash:net
hash:net,iface
hash:net,net
hash:net,port
hash:net,port,net
```

**Comment by erig0** [comment]
@yellowsoar, this is actually an issue with userland ipset supporting hast:mac, but no the running kernel. See https://bugzilla.redhat.com/show_bug.cgi?id=1541064. This is not a bug in firewalld.

**Comment by yellowsoar** [comment]
Oh... So sad....
It seems won't be fixed recently...
Thank you for your time @erig0 !
