### ISSUE TITLE
firewalld-0.4.4.4-6.el7.noarch Error ICMP type, 

### ISSUE THREAD

**Issue by deprito** [firewalld/firewalld#251]
Anyone have error same like me?

`Oct 04 10:43:54 my.host firewalld[12116]: WARNING: INVALID_HELPER: iptable_filter
Oct 04 11:01:48 my.host systemd[1]: Reloaded firewalld - dynamic firewall daemon.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: ICMP type 'beyond-scope' is not supported by the kernel for ipv6.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: beyond-scope: INVALID_ICMPTYPE: No supported ICMP type., ignoring for run-time.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: ICMP type 'failed-policy' is not supported by the kernel for ipv6.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: failed-policy: INVALID_ICMPTYPE: No supported ICMP type., ignoring for run-time.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: ICMP type 'reject-route' is not supported by the kernel for ipv6.
Oct 04 11:01:49 my.host firewalld[12116]: WARNING: reject-route: INVALID_ICMPTYPE: No supported ICMP type., ignoring for run-time.
`

This error show on firewalld version **firewalld-0.4.4.4-6.el7.noarch.**

**Comment by erig0** [comment]
This was addressed by a6f0c40b.
