### ISSUE TITLE
Possible to change default target?

### ISSUE THREAD

**Issue by dotdigital-digital** [firewalld/firewalld#252]
From firewalld man page:

> –permanent [–zone=zone] --set-target=target Set the target of a permanent zone. target is one of: default, ACCEPT, DROP, REJECT

The default target is REJECT. Is it possible to change the default target to DROP? If not, why does a default option exist if it cannot be anything but REJECT?

I am using CentOS 7.4

I understand that I can configure firewalld any way I'd like without being able to change the default target, but I'd like to know how to change it if possible.

Apologies if I overlooked how to do this. I read over the man page several times.

**Comment by erig0** [comment]
It is not possible to change the default target - it's hardcoded. It's possible "default" was included so we could potentially introduce a "--set-default-target" option in the future, but I'm just speculating.

The only difference I see between using "REJECT" and "default" is that with "default" the packet may eventually fallback to the INPUT chain and hit the check for invalid conntrack state. e.g.

```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
....
  198 46736 INPUT_ZONES  all  --  any    any     anywhere             anywhere            
    0     0 DROP       all  --  any    any     anywhere             anywhere             ctstate INVALID
    0     0 REJECT     all  --  any    any     anywhere             anywhere             reject-with icmp-host-prohibited
```

**Comment by dotdigital-digital** [comment]
Thanks! That answers my question.
