### ISSUE TITLE
issues with nvidia drivers on ubuntu

### ISSUE THREAD

**Issue by pgera** [firewalld/firewalld#255]
I have this weird issue where if I install nvidia drivers, firewalld is somehow killed off early in the boot process on ubuntu 16.04. firewalld's version is 0.4.0-1. I am able to start it manually, but I have no idea why it is being killed. There is something in the mix of nvidia, systemd and firewalld that is causing this. I created an ubuntu bug for this (https://bugs.launchpad.net/nvidia-drivers-ubuntu/+bug/1719163). Is there some way to figure out what is killing it ? This also appears to be ubuntu specific, and doesn't happen on fedora. My journal has the following messages:

```
Oct 11 22:07:47 plum systemd[1]: Started Flush Journal to Persistent Storage.
Oct 11 22:07:47 plum qemu-kvm[349]:  * Configuring kvm qemu-kvm
Oct 11 22:07:47 plum qemu-kvm[349]:    ...done.
Oct 11 22:07:47 plum systemd[1]: Started LSB: QEMU KVM module loading script.
Oct 11 22:07:47 plum systemd[1]: Stopped firewalld - dynamic firewall daemon.
Oct 11 22:07:47 plum systemd[1]: Started Braille Device Support.
Oct 11 22:07:47 plum systemd[1]: Mounted Mount unit for canonical-livepatch.
Oct 11 22:07:47 plum systemd[1]: Mounted Mount unit for core.
Oct 11 22:07:47 plum systemd[1]: Mounted Mount unit for core.
Oct 11 22:07:47 plum systemd[1]: Mounted Mount unit for core.
Oct 11 22:07:47 plum systemd[1]: Mounted Mount unit for canonical-livepatch.
Oct 11 22:07:47 plum systemd[1]: Started udev Coldplug all Devices.

```
```
systemctl status firewalld.service
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead)

Oct 11 22:07:47 plum systemd[1]: Stopped firewalld - dynamic firewall daemon.
```

**Comment by erig0** [comment]
Logs don't indicate anything wrong. It looks like something is gracefully stopping firewalld. Seems like an issue with Ubuntu init - as such I'm closing this report. Please track the Ubuntu report.

**Comment by pgera** [comment]
Installing nvidia drivers enables ebtables, which conflicts with firewalld. If I disable ebtables, firewalld starts as expected. I don't know what the connection between nvidia and ebtables is.
