### ISSUE TITLE
logging in LXD containers - ulogd?

### ISSUE THREAD

**Issue by niksfirefly** [firewalld/firewalld#259]
Is it possible (or in roadmap) to use ulogd/nflog in rich rules logging ?
LXD containers cannot use default log rules

**Comment by rkarlsba** [comment]
ULOG is probably out in the cold, and IIRC it's not even available in rhel/centos7. NFLOG was introduced in kernel 2.6 and is preferred. Still not supported in firewalld, though.

**Comment by erig0** [comment]
Closing. ulog is deprecated. `ulogd2` can use `nflog` which is being implemented in #720.
