### ISSUE TITLE
Logging with ULOG?

### ISSUE THREAD

**Issue by rkarlsba** [firewalld/firewalld#268]
Hi all

It's good to have logging working, indeed, but I wonder why firewalld doen't support using the ULOG target instead of LOG. This may not be everyone's choice, but for some it can be a good way to get the firewall logs away from potentially more important logs to be practically visible, for instance in the dmesg command.

I looked at the code, and couldn't find any traces of ULOG, and nothing on google either.

So - has this been discussed?

**Comment by erig0** [comment]
dupe of #259.
