### ISSUE TITLE
 Set up firewalld on CentOS before starting it

### ISSUE THREAD

**Issue by got3nks** [firewalld/firewalld#270]
If we use firewall-cmd to open a port before starting the firewalld service, it will fail:
`FirewallD is not running`

If I start firewalld I'm getting disconnected from the remote server, I'm running SSH on a different port than 22.

How am I supposed to configure a remote server without losing connection to it?

I think the --permanent option should work even if the firewall is currently disabled.

**Comment by erig0** [comment]
Use firewall-offline-cmd.
