### ISSUE TITLE
Can a service include another service?

### ISSUE THREAD

**Issue by jcpunk** [firewalld/firewalld#273]
Looking at https://github.com/firewalld/firewalld/blob/master/config/services/RH-Satellite-6.xml

I was wondering if it might make more sense to include the bundled services rather than their port numbers.

This way, if for example, puppet changes its port list Sat6 will automatically inherit the new ports without requiring a second commit.

**Comment by erig0** [comment]
I agree it would be a nice feature. I would welcome any PRs. :)

**Comment by jcpunk** [comment]
I'll add it to my project list.

Would you prefer I create an 'application' schema or permit 'services' to load recursively?

I lean slightly towards creating an 'application' schema that can only read in 'services' or other 'applications'.  In theory this should help avoid having a A->B->C->A loops.

Thoughts?

**Comment by jcpunk** [comment]
.... this looks a bit more involved than expected.... I'm not sure I can actually do it.

To just extend the service schema there look to be changes required in `src/firewall/core/io/service.py` and `src/firewall/server/config_service.py`.  But that seems to touch on some dbus bits which I'm not familiar with.

And that doesn't even get around to exposing this to `firewall-cmd` or `firewallctl`....

**Comment by erig0** [comment]
> Would you prefer I create an 'application' schema or permit 'services' to load recursively?

I like the simplicty of allowing services to load services. We'll just limit the depth to 1.

> .... this looks a bit more involved than expected.... I'm not sure I can actually do it.

If it's too much, then I'll add it to my TODO list.

**Comment by jcpunk** [comment]
I'm afraid I'll have to ask for it to land on your TODO list... there seems to be a fair potential for weirdness that I'm not in a position to address.

**Comment by erig0** [comment]
@jcpunk, I'm currently holding a [series](https://github.com/firewalld/firewalld/compare/master...erig0:service-include) to implement this. Syntax looks like below. It will handle multiple level and recursive includes.

```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>my-service-with-include</short>
  <description>This service includes other services</description>
  <port protocol="tcp" port="12345"/>
  <include service="ssdp"/>
  <include service="mdns"/>
</service>
```

What do you think?

**Comment by jcpunk** [comment]
I really like the look of this!
