### ISSUE TITLE
firewalld does not reload correctly when active zone is removed

### ISSUE THREAD

**Issue by pes-soft** [firewalld/firewalld#276]
When active source zone is removed and firewall is reloaded, firewalld does not reload correctly: ACCEPT policy is not set and chains default to DROP policy. This usually results to firewall effectively dropping all new connections.

### How to reproduce:
1) Create new zone
2) Add source to the new zone
3) Restart firewall 
4) Delete the new zone
5) Reload firewall

Or reproduce via command line:
```
firewall-cmd --permanent --new-zone=newzone
firewall-cmd --permanent --zone=newzone --add-source=192.168.192.0/24
/etc/init.d/firewalld restart
sleep 10
firewall-cmd --permanent --delete-zone=newzone
/etc/init.d/firewalld reload
```

### Expected result:
Zone is deleted and firewall is running as configured.

### Actual result:
Zone is deleted, but firewall is running with default DROP policy on chains (INPUT, FORWARD, OUTPUT in filter table).

This also occurs when active source zone is renamed in firewall-config UI. Restart of firewall fixes the issue.

### Update 1:
Initially I've found this issue with firewall-config UI, but because it occurs also independently on UI, I've updated issue's title and description.

**Comment by erig0** [comment]
Closing as per comment in pr #285.
