### ISSUE TITLE
Firewalld Error Msg ?

### ISSUE THREAD

**Issue by gh4wi** [firewalld/firewalld#289]
OS = Linux Mint 18.3 Cinnamon x64 bit, /w firewalld v 0.4.0

When I execute "systemctl status firewalld"
I see the following output ...

● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-02-04 14:08:54 CST; 17min ago
 Main PID: 1159 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─1159 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid

Feb 04 14:08:53 HARE systemd[1]: Starting firewalld - dynamic firewall daemon...
Feb 04 14:08:54 HARE systemd[1]: Started firewalld - dynamic firewall daemon.
Feb 04 14:08:54 HARE /firewalld[1159]: ERROR: ipset not usable, disabling ipset usage in firewall.
Feb 04 14:08:54 HARE /firewalld[1159]: ERROR: ebtables not usable, disabling ethernet bridge firewall.

Also ....
$ firewall-cmd --state reports that it is running.

Please advise if these 2 ERROR prevent the firewall from working correctly.
As an end user, I could use some help understanding what should be done, if anything.

Thanks.

**Comment by erig0** [comment]
> Please advise if these 2 ERROR prevent the firewall from working correctly.

Unless you're using the ipset features or the --direct (see firewalll-cmd man page), then it may be okay. Although to be safe you should install ipset and ebtables through your distributions package manager. These are typically hard dependencies for firewalld - I don't know why they're not available on your system.
