### ISSUE TITLE
ipv6 nat

### ISSUE THREAD

**Issue by fkooman** [firewalld/firewalld#29]
Hi,

It seems IPv6 NAT should be supported as listed on http://www.firewalld.org/, but it doesn't seems to work on CentOS7 (i.e.: putting the external interface in the 'external' zone is not enough to get it working. IPv4 NAT does work perfectly fine.

This forum post http://forums.fedoraforum.org/showthread.php?t=301894 tries to get it to work and I can replicate the working ping, but I am unable to get any traffic other than ICMP working.

What is the correct way to get IPv6 NAT working? Will it also set `net.ipv6.conf.<EXTERNAL>.forwarding`  to 1?

**Comment by t-woerner** [comment]
Yes, there seems to be an issue with the sysctl setting for ipv6 forwarding. I need to have a look again how to enable forwarding - maybe also per interface.

**Comment by fkooman** [comment]
Thanks! 

Enabling the sysctl forwarding doesn't seem to be the only problem though as doing that manually (as described above) makes ICMP echo work eventually, but not any other traffic... there currently is also still the need for the rich rule as shown in the forum post...

Do you have a hint to get NAT for IPv6 working at this time?

**Comment by 53c70r** [comment]
Problem still persists for me too.
I know ipv6 isn't meant for nating but there are specific circumstances i can't get around ipv6 nating.

**Comment by erig0** [comment]
To get IPv6 masquerading you must use a rich rule. This is as per the man page, `FIREWALL-CMD(1)`.

```
[--permanent] [--zone=zone] --add-masquerade [--timeout=timeval]
    Enable IPv4 masquerade for zone. If zone is omitted, default zone
[...]
    For IPv6 masquerading, please use the rich language.
```

**Comment by fkooman** [comment]
> To get IPv6 masquerading you must use a rich rule. 

Is there a reason firewalld does not take care of this in the same manner as for IPv4? In the end the iptables/ip6tables rules are exactly the same...

**Comment by erig0** [comment]
Probably because:
1) It was initially implemented to do IPv4 only. Changing it to do both would change behavior and there be a breaking change.
2) NAT IPv6 is the exception, not the norm. Most users don't want to NAT IPv6.

**Comment by fkooman** [comment]
Okay, I understand, the `--add-masquerade` would then apply to both IPv4 and IPv6 which could result in possibly unwanted IPv6 NAT... 

However, it would be cool to be able to have IPv6 working out of the box from GNOME Boxes :-)

**Comment by erig0** [comment]
On Tue, Apr 28, 2020 at 02:03:16AM -0700, François Kooman wrote:
> Okay, I understand, the `--add-masquerade` would then apply to both IPv4 and IPv6 which could result in possibly unwanted IPv6 NAT... 
> 
> However, it would be cool to be able to have IPv6 working out of the box from GNOME Boxes :-)

By "IPv6 working" do you mean simple IPv6 connectivity or IPv6 NAT?

IPv6 connectivity should work out of the box.

**Comment by fkooman** [comment]
The thing about IPv6 in Boxes was very much off topic here as it would also require changes to (the default) libvirt/Boxes/switch configuration to actually assign IPv6 addresses to guests/virtual switch. It currently doesn't do that (at all). So that would need to be fixed first before looking at IPv6 NAT. It could even do IPv6 PD (prefix delegation) if the home router supports that, which mine happens to do, firewalld is only a (small) part of the puzzle here... Thanks again for responding!

**Comment by 53c70r** [comment]
Masquerading "out of the box" could be something like
`firewall-cmd --zone=XYZ --add-rich-rule='rule family="ipv6" source address="X::0/118" masquerade'`

**Comment by 53c70r** [comment]
Also don't forget to disable IPv6_rpfilter in /etc/firewalld/firewalld.conf
