### ISSUE TITLE
firewalld fails SILENTLY to load /etc/firewalld/direct.xml file

### ISSUE THREAD

**Issue by hlovdal** [firewalld/firewalld#290]
Do you think that it is OK that a program whose purpose is 100% to provide security to *silently* fail to fulfil its duties? Neither do I.

I had an /etc/firewalld/direct.xml file with invalid xml content<sup>1</sup> which made firewalld not load it. The invalid content is my fault and I am not complaining about firewalld not loading files with invalid content. What I do complain about it that firewalld failed to load it silently!

When I put files in the `/etc/firewalld` directory I expect firewalld to process them and if it cannot do so it should make extraordinary efforts to inform me that, sorry I cannot do so.

By chance I discovered that `nonet` group processes still could access the network and only when reverse engineering the command line started by firewalld.service and adding a `--debug` option do I get information of what is happening:

```
    2018-02-07 20:00:01 DEBUG1: Failed to load direct rules file '/etc/firewalld/direct.xml': INVALID_TYPE: Not a valid file: not well-formed (invalid token): line 8, column 67
```

This is unacceptable. This should have been printed as an error message, which then would have ended up in syslog as opposed to debug messages which do not (and even if both were forwarded to syslog it is undeniably an error condition and should be reported as such).

This is partly done correctly, but mostly not. Please fix this and other corresponding cases.

```
$ack "Failed to load direct rules file"
src/firewall/core/fw_test.py
255:                log.debug1("Failed to load direct rules file '%s': %s",

src/firewall/core/fw.py
373:                log.debug1("Failed to load direct rules file '%s': %s",

src/firewall/server/config.py
287:                log.error("Failed to load direct rules file '%s': %s" % (name,
```

---------

<sup>1</sup>
The option double dashes starts/stops xml comments unintendedly.
I did not notice/think about it when commenting the line.

```
<?xml version="1.0" encoding="utf-8"?>
<direct>
        <chain table="filter" chain="NONET_DENY" ipv="ipv4"/>

        <rule table="filter" chain="NONET_DENY" ipv="ipv4" priority="0">--match owner '!' --gid-owner nonet --jump RETURN</rule>
        <rule table="filter" chain="NONET_DENY" ipv="ipv4" priority="1">--destination 127.0.0.1 --jump RETURN</rule>
<!--
        <rule table="filter" chain="NONET_DENY" ipv="ipv4" priority="2">--match limit --limit 20/min --jump LOG --log-prefix 'iptables:nonet_deny ' --log-level 7</rule>
-->
        <rule table="filter" chain="NONET_DENY" ipv="ipv4" priority="3">--jump DROP</rule>

        <rule table="filter" chain="OUTPUT_direct" ipv="ipv4" priority="0">--jump NONET_DENY</rule>
```

**Comment by erig0** [comment]
I agree a DEBUG log is inappropriate. It should be ERROR.
FWIW, as of 9fae7f029 an error message will be propagated to `firewall-cmd --reload`. This case is slightly different since it's loading on a real firewalld restart.
