### ISSUE TITLE
spelling mistake :)

### ISSUE THREAD

**Issue by r-a-z-v-a-n** [firewalld/firewalld#293]
http://www.firewalld.org/documentation/zone/connections-interfaces-and-sources.html
 
_Second Section :_ 

Network connections handled by NetworkManager

_First sentence_

The firewall in the linux kernel is not able to handle network connections with the name shown by NetworkManager, it can only handle the network interfaces used by the **conneciton**. 

-----
 Not So Important Grammar Mistake : P .. might as well fix it while you're editing the others

http://www.firewalld.org/documentation/zone/use-of-zones.html

_Second Section_

How to configure or add zones?

_First sentence_

To configure or add zones **[insert comma here]** you can either use one of the firewalld interfaces to handle and change the configuration.

**Comment by erig0** [comment]
@r-a-z-v-a-n , Thank you! I really appreciate you're help finding errors in the documentation.
