### ISSUE TITLE
Ubuntu 17.10 "make" fails with error during install

### ISSUE THREAD

**Issue by courtens** [firewalld/firewalld#297]
I am trying to install the latest build firewalld 0.5.1 release - but using "make" I get this error:

    nathaniel@cubiblack:~/Desktop/file$ make
    Making all in config
    make[1]: Entering directory '/home/nathaniel/Desktop/file/config'
    Makefile:984: *** missing separator.  Stop.
    make[1]: Leaving directory '/home/nathaniel/Desktop/file/config'
    Makefile:389: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1
    nathaniel@cubiblack:~/Desktop/file$

What am I doing wrong?

The line of code in file make is:

    @GSETTINGS_RULES@

**Comment by erig0** [comment]
You need to install libglib2.0-dev to get the GSETTINGS_RULES macro.

**Comment by courtens** [comment]
Thank you for taking the time to have answered my inquire.  Now I have a new problem. This is what I am getting trying to install the missing libglib2.0-dev library:

   ```
 nathaniel@cubiblack:~$ sudo apt-get install libglib2.0-dev
    [sudo] password for nathaniel:
    Reading package lists... Done
    Building dependency tree      
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
```

What I really just need is for the program to keep the designated Zone, and not for it to jump to the defined default Zone after a reboot.

I know this bug has been fixed, but the Ubuntu "Store" (17.10) offers only version 0.4.4.5 where the bug is still present. (I have two cards.)

**Comment by erig0** [comment]
@courtens, perhaps you need to update your system first. `apt update && apt upgrade`. Beyond that I'm afraid I can't help. Maybe you could file a ticket with Ubuntu to backport the fix or update the package.

**Comment by courtens** [comment]
Thank you for the suggestion. I ran that - and there is nothing new to install / update / upgrade.

Now it feels a bit like I'm chasing my tail -- things are going around and around. Some dependencies are asked for that apparently are installed but not recognized. Is it because they are too new that it can't find them? I am running Ubuntu 17.10 (not 17.04). Also, I used to have Ubuntu MATE on the same system but are now using 17.10. Could this Ubuntu MATE be interfering the updates/upgrades?

This is what I am getting:
> nathaniel@cubiblack:$ sudo apt-get install libglib2.0-dev
> [sudo] password for nathaniel: 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> The following packages have unmet dependencies:
>  libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> nathaniel@cubiblack:$ sudo apt-get install libpcre3-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> The following packages have unmet dependencies:
>  libpcre3-dev : Depends: libpcre3 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> Depends: libpcre16-3 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> Depends: libpcrecpp0v5 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> E: Unable to correct problems, you have held broken packages.
> nathaniel@cubiblack:$ sudo apt-get install libpcre3
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libpcre3 is already the newest version (2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> nathaniel@cubiblack:$ sudo apt-get install libpcre16-3
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libpcre16-3 is already the newest version (2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> nathaniel@cubiblack:$ sudo apt-get install libpcrecpp0v5
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libpcrecpp0v5 is already the newest version (2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3).
> libpcrecpp0v5 set to manually installed.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> nathaniel@cubiblack:$ sudo apt-get install libpcre3-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> The following packages have unmet dependencies:
>  libpcre3-dev : Depends: libpcre3 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> Depends: libpcre16-3 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> Depends: libpcrecpp0v5 (= 2:8.39-5ubuntu3) but 2:8.41-1.1+ubuntu17.04.1+deb.sury.org+3 is to be installed
> E: Unable to correct problems, you have held broken packages.
> nathaniel@cubiblack:$

**Comment by erig0** [comment]
It looks like apt is pulling packages from a PPA that has _newer_ packages than the ones in the base repositories. Unfortunately it's pulling older -dev packages for some reason. That's something I would expect if you the apt cache was out of date or if you had recently disabled a PPA.

**Comment by courtens** [comment]
It looks like apt cache is up to date:
> nathaniel@cubiblack:~$ stat -c %z /var/lib/apt/periodic/update-success-stamp
> 2018-02-25 17:19:03.971736630 -0800

I do not remember having recently disabled a PPA. except for bitcoin. What PPA would by tied to this problem? Link to PPAs [screen shot A](https://courtens.org/temp/a.png) and [screen shot B](https://courtens.org/temp/b.png)

**Comment by erig0** [comment]
The package name indicates https://launchpad.net/~ondrej/+archive/ubuntu/php/

**Comment by courtens** [comment]
Thank you erig0 fall all the help. 

I added the package and was able to install libglib2.0-dev. 
I did a `sudo apt update && sudo apt upgrade` and rebooted. 
I ran the `make` call and got the same error as above. 

So I re-extracted the tar.gz download, and ran into now a new error:

> nathaniel@cubiblack:~/Desktop/firewalld-0.5.1$ ./autogen.sh
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force 
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: configure.ac: not using Autoheader
> autoreconf: running: automake --add-missing --force-missing
> configure.ac:14: installing './install-sh'
> configure.ac:14: installing './missing'
> autoreconf: Leaving directory `.'
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '1000' is supported by ustar format... yes
> checking whether GID '1000' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking whether ln -s works... yes
> checking for a sed that does not truncate output... /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for gawk... (cached) gawk
> checking whether make sets $(MAKE)... (cached) yes
> checking for python... /usr/bin/python
> checking for python version... 2.7
> checking for python platform... linux2
> checking for python script directory... ${prefix}/lib/python2.7/dist-packages
> checking for python extension module directory... ${exec_prefix}/lib/python2.7/dist-packages
> checking for xsltproc... no
> checking for kill... /bin/kill
> checking for modinfo... /sbin/modinfo
> checking for modprobe... /sbin/modprobe
> checking for rmmod... /sbin/rmmod
> checking for sysctl... /sbin/sysctl
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.16... yes
> checking for iptables... /sbin/iptables
> checking for iptables-restore... /sbin/iptables-restore
> checking for ip6tables... /sbin/ip6tables
> checking for ip6tables-restore... /sbin/ip6tables-restore
> checking for ebtables... /sbin/ebtables
> checking for ebtables-restore... /sbin/ebtables-restore
> checking for ipset... /sbin/ipset
> checking whether NLS is requested... yes
> checking for intltool >= 0.35.0... 0.51.0 found
> checking for intltool-update... /usr/bin/intltool-update
> checking for intltool-merge... /usr/bin/intltool-merge
> checking for intltool-extract... /usr/bin/intltool-extract
> checking for xgettext... /usr/bin/xgettext
> checking for msgmerge... /usr/bin/msgmerge
> checking for msgfmt... /usr/bin/msgfmt
> checking for gmsgfmt... /usr/bin/msgfmt
> checking for perl... /usr/bin/perl
> checking for perl >= 5.8.1... 5.26.0
> checking for msgfmt... (cached) /usr/bin/msgfmt
> checking for gmsgfmt... (cached) /usr/bin/msgfmt
> checking for xgettext... (cached) /usr/bin/xgettext
> checking for msgmerge... (cached) /usr/bin/msgmerge
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating doxygen.conf
> config.status: creating config/Makefile
> config.status: creating doc/Makefile
> config.status: creating doc/man/Makefile
> config.status: creating doc/man/man1/Makefile
> config.status: creating doc/man/man5/Makefile
> config.status: creating doc/xml/Makefile
> config.status: creating po/Makefile.in
> config.status: creating shell-completion/Makefile
> config.status: creating src/firewall/config/__init__.py
> config.status: creating src/Makefile
> config.status: creating src/tests/Makefile
> config.status: creating src/icons/Makefile
> config.status: executing src/tests/atconfig commands
> config.status: executing po-directories commands
> config.status: creating po/POTFILES
> config.status: creating po/Makefile
> config.status: executing xsl-cleanup commands
> config.status: executing po/stamp-it commands


> nathaniel@cubiblack:~/Desktop/firewalld-0.5.1$ make
> Making all in config
> make[1]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po firewall-config.desktop.in firewall-config.desktop
> Generating and caching the translation database
> Merging translations into firewall-config.desktop.
> LC_ALL=C /usr/bin/intltool-merge  -x -u --no-translations firewall-config.appdata.xml.in firewall-config.appdata.xml
> Merging translations into firewall-config.appdata.xml.
> CREATED firewall-config.appdata.xml
> LC_ALL=C /usr/bin/intltool-merge  -d -u -c ../po/.intltool-merge-cache ../po firewall-applet.desktop.in firewall-applet.desktop
> Found cached translation database
> Merging translations into firewall-applet.desktop.
> LC_ALL=C /usr/bin/intltool-merge  -x -u -c ../po/.intltool-merge-cache ../po org.fedoraproject.FirewallD1.server.policy.in org.fedoraproject.FirewallD1.server.policy
> Found cached translation database
> Merging translations into org.fedoraproject.FirewallD1.server.policy.
> CREATED org.fedoraproject.FirewallD1.server.policy
> LC_ALL=C /usr/bin/intltool-merge  -x -u -c ../po/.intltool-merge-cache ../po org.fedoraproject.FirewallD1.desktop.policy.in org.fedoraproject.FirewallD1.desktop.policy
> Found cached translation database
> Merging translations into org.fedoraproject.FirewallD1.desktop.policy.
> CREATED org.fedoraproject.FirewallD1.desktop.policy
> sed -e 's|@bindir[@]|/usr/bin|g' -e 's|@sbindir[@]|/usr/sbin|g' -e 's|@sysconfdir[@]|/usr/etc|g' -e 's|@localstatedir[@]|/usr/var|g' -e 's|@MODPROBE[@]|/sbin/modprobe|g' -e 's|@SYSCTL[@]|/sbin/sysctl|g' firewalld-sysctls.conf.in >firewalld-sysctls.conf
> sed -e 's|@bindir[@]|/usr/bin|g' -e 's|@sbindir[@]|/usr/sbin|g' -e 's|@sysconfdir[@]|/usr/etc|g' -e 's|@localstatedir[@]|/usr/var|g' -e 's|@MODPROBE[@]|/sbin/modprobe|g' -e 's|@SYSCTL[@]|/sbin/sysctl|g' firewalld.service.in >firewalld.service
> LC_ALL=C /usr/bin/intltool-merge  -x -u --no-translations org.fedoraproject.FirewallConfig.gschema.xml.in org.fedoraproject.FirewallConfig.gschema.xml
> Merging translations into org.fedoraproject.FirewallConfig.gschema.xml.
> CREATED org.fedoraproject.FirewallConfig.gschema.xml
> make  all-am
> make[2]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> /usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas --strict --dry-run  --schema-file=org.fedoraproject.FirewallConfig.gschema.xml && mkdir -p . && touch org.fedoraproject.FirewallConfig.gschema.valid
> make[2]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[1]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> Making all in doc
> make[1]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc'
> Making all in xml
> make[2]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/xml'
> sed -e 's|\@PREFIX\@|/usr|' -e 's|\@SYSCONFDIR\@|/usr/etc|' -e 's|\@PACKAGE_STRING\@|firewalld 0.5.1|' -e 's|\@IFCFGDIR\@|/etc/sysconfig/network-scripts|' transform-man.xsl.in >transform-man.xsl
> xsltproc -o ../man/man1/firewall-applet.1 --nonet --xinclude  transform-man.xsl firewall-applet.xml
> /bin/bash: xsltproc: command not found
> Makefile:617: recipe for target '../man/man1/firewall-applet.1' failed
> make[2]: *** [../man/man1/firewall-applet.1] Error 127
> make[2]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/xml'
> Makefile:355: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1


> nathaniel@cubiblack:~/Desktop/firewalld-0.5.1$ sudo make install
> [sudo] password for nathaniel: 
> Making install in config
> make[1]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make  install-am
> make[2]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[3]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[3]: Nothing to be done for 'install-exec-am'.
>  /bin/mkdir -p '/usr/share/appdata/'
>  /usr/bin/install -c -m 644 firewall-config.appdata.xml '/usr/share/appdata/'
>  /bin/mkdir -p '/usr/etc/xdg/autostart'
>  /usr/bin/install -c -m 644 firewall-applet.desktop '/usr/etc/xdg/autostart'
> /bin/mkdir -p /usr/etc/firewalld
> /bin/mkdir -p /usr/etc/firewalld/icmptypes
> /bin/mkdir -p /usr/etc/firewalld/ipsets
> /bin/mkdir -p /usr/etc/firewalld/services
> /bin/mkdir -p /usr/etc/firewalld/zones
> /bin/mkdir -p /usr/etc/firewalld/helpers
> /bin/mkdir -p /usr/lib/firewalld
> cp -r icmptypes /usr/lib/firewalld
> cp -r ipsets /usr/lib/firewalld
> cp -r services /usr/lib/firewalld
> cp -r zones /usr/lib/firewalld
> cp -r helpers /usr/lib/firewalld
> /bin/mkdir -p /usr/etc/modprobe.d
> /usr/bin/install -c -m 644 firewalld-sysctls.conf /usr/etc/modprobe.d/firewalld-sysctls.conf
> /bin/mkdir -p /usr/etc/sysconfig
> /usr/bin/install -c -m 644 ./firewalld.sysconfig /usr/etc/sysconfig/firewalld
> /bin/mkdir -p /usr/lib/systemd/system
> /usr/bin/install -c -m 644 firewalld.service /usr/lib/systemd/system/firewalld.service
>  /bin/mkdir -p '/usr/share/applications'
>  /usr/bin/install -c -m 644 firewall-config.desktop '/usr/share/applications'
>  /bin/mkdir -p '/usr/etc/firewall'
>  /usr/bin/install -c -m 644 applet.conf '/usr/etc/firewall'
>  /bin/mkdir -p '/usr/etc/dbus-1/system.d'
>  /usr/bin/install -c -m 644 FirewallD.conf '/usr/etc/dbus-1/system.d'
>  /bin/mkdir -p '/usr/etc/firewalld'
>  /usr/bin/install -c -m 644 firewalld.conf lockdown-whitelist.xml '/usr/etc/firewalld'
>  /bin/mkdir -p '/usr/lib/firewalld/xmlschema'
>  /usr/bin/install -c -m 644 xmlschema/icmptype.xsd xmlschema/ipset.xsd xmlschema/service.xsd xmlschema/zone.xsd '/usr/lib/firewalld/xmlschema'
>  /bin/mkdir -p '/usr/lib/firewalld/xmlschema'
>  /usr/bin/install -c xmlschema/check.sh '/usr/lib/firewalld/xmlschema'
>  /bin/mkdir -p '/usr/share/polkit-1/actions'
>  /usr/bin/install -c -m 644 org.fedoraproject.FirewallD1.server.policy org.fedoraproject.FirewallD1.desktop.policy '/usr/share/polkit-1/actions'
> if test -n "org.fedoraproject.FirewallConfig.gschema.xml"; then \
> 	test -z "/usr/share/glib-2.0/schemas" || /bin/mkdir -p "/usr/share/glib-2.0/schemas"; \
> 	/usr/bin/install -c -m 644 org.fedoraproject.FirewallConfig.gschema.xml "/usr/share/glib-2.0/schemas"; \
> 	test -n "" || /usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas /usr/share/glib-2.0/schemas; \
> fi
> make  install-data-hook
> make[4]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> cd /usr/share/polkit-1/actions && \
> 	mv org.fedoraproject.FirewallD1.server.policy org.fedoraproject.FirewallD1.server.policy.choice && \
> 	mv org.fedoraproject.FirewallD1.desktop.policy org.fedoraproject.FirewallD1.desktop.policy.choice && \
> 	rm -f org.fedoraproject.FirewallD1.policy && \
> 	ln -s org.fedoraproject.FirewallD1.server.policy.choice org.fedoraproject.FirewallD1.policy
> make[4]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[3]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[2]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> make[1]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/config'
> Making install in doc
> make[1]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc'
> Making install in xml
> make[2]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/xml'
> make[2]: Nothing to be done for 'install'.
> make[2]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/xml'
> Making install in man
> make[2]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/man'
> Making install in man1
> make[3]: Entering directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/man/man1'
> make[3]: *** No rule to make target 'firewall*.1', needed by 'all-am'.  Stop.
> make[3]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/man/man1'
> Makefile:355: recipe for target 'install-recursive' failed
> make[2]: *** [install-recursive] Error 1
> make[2]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc/man'
> Makefile:355: recipe for target 'install-recursive' failed
> make[1]: *** [install-recursive] Error 1
> make[1]: Leaving directory '/home/nathaniel/Desktop/firewalld-0.5.1/doc'
> Makefile:395: recipe for target 'install-recursive' failed
> make: *** [install-recursive] Error 1
> nathaniel@cubiblack:~/Desktop/firewalld-0.5.1$

**Comment by erig0** [comment]
> /bin/bash: xsltproc: command not found

    apt install xsltproc docbook-xsl

**Comment by courtens** [comment]
xsltproc docbook-xsl was missing. Now it looks like there is no more errors ... but the program is not running any more. What am I suppose to do? 
[calls.txt](https://github.com/firewalld/firewalld/files/1764255/calls.txt)

**Comment by egberts** [comment]
For Debain 10, you can resolve this GLIB_GSETTINGS m4 macro by package installing:

    apt install libglib2.0-dev
