### ISSUE TITLE
website http://www.firewalld.org/community.html linking to lists.fedorahosted.org which is not working

### ISSUE THREAD

**Issue by courtens** [firewalld/firewalld#298]
Login/sign-up is not working
https://lists.fedorahosted.org/archives/list/firewalld-users@lists.fedorahosted.org/

Also,

email address firewalld@freenode.org on this page http://www.firewalld.org/community.html bounced back with:
Delivery to the following recipients failed permanently:
   * firewalld@freenode.org
Reason: 554 5.7.1 <firewalld@freenode.org>: Relay access denied

**Comment by erig0** [comment]
> Login/sign-up is not working

You need to login first. You can use many methods; FAS (fedora), google, OpenID. etc.

> email address firewalld@freenode.org on this page http://www.firewalld.org/community.html bounced

That's not an email address. It's #firewalld channel @ freenode.org IRC.
