### ISSUE TITLE
firewall-config: Infinite wait loop when firewalld is stopped

### ISSUE THREAD

**Issue by hwoarang** [firewalld/firewalld#299]
When the `firewalld` service is stopped and we try to run the `firewall-config` UI, then it keeps waiting for connection with the `firewalld` daemon indefinitely. This is slightly annoying and it should really just timeout after a while or perhaps offer to start the `firewalld` service as an option.

**Comment by erig0** [comment]
@hwoarang, If you can reproduce could you check `ps aux` for instances of rmmod? It's possible you're seeing this bug:

-   https://bugzilla.redhat.com/show_bug.cgi?id=1531485
-   https://bugzilla.redhat.com/show_bug.cgi?id=1294415

**Comment by hwoarang** [comment]
@erig0 yeah I can reproduce but it's not about shutdown or anything. In a running system, try to stop the `firewalld` service and then run `firewall-config`. I am checking the code right now and indeed there is no timeout for the `Trying to connect to firewalld, waiting...` window. The pop up is stuck there until `self.fw.connected` becomes true, and if you never start the `firewalld` service this never happens and the `spinner` is stuck there.

**Comment by erig0** [comment]
@hwoarang right. Sorry. I guess I read your report too quickly and missunderstood.
Agreed, firewall-config should time out after a reasonable time.
