### ISSUE TITLE
Implement forward-port directive in service

### ISSUE THREAD

**Issue by IlyaIndigo** [firewalld/firewalld#302]
Is it possible in firewalld using service to redirect a local port?
```
<?xml version="1.0" encoding="utf-8"?>
<service>
   <short>Direct Connect server (PtokaX)</short>
   <description>Opens ports for P2P Direct Conect server PtokaX</description>
   <forward-port port="411" protocol="tcp" to-port="4111"/>
   <forward-port port="411" protocol="udp" to-port="4111"/>
</service>
```
In the zone, the forward-port directive works, but the service does not work. It is necessary to add this rule to the rpm-package so that it is added and deleted together with the corresponding daemon.
How to be?

http://www.firewalld.org/documentation/man-pages/firewalld.service.html

**Comment by erig0** [comment]
> Is it possible in firewalld using service to redirect a local port?

No. Services do not support forward-ports.
In general we only want IANA assigned ports in service definitions.

> It is necessary to add this rule to the rpm-package so that it is added and deleted together with the corresponding daemon.

Why does the daemon needs forward-ports? It can start as root, listen on 411, then drop privileges to another user.

Alternatively, firewalld has a dbus interface with which the daemon could create forward-ports for the zone. Authentication is through policykit.

**Comment by IlyaIndigo** [comment]
Perhaps this is only necessary for DC ++ hubs (PtokaX and VerlyHub), whose 411 port is standard, but initially designed under windows and can not reset privileges, as it does, for example, httpd.

And from root run the hub, which still runs lua scripts I do not want.

Can I use your proposed methods without upgrading the software (PtokaX)?
