### ISSUE TITLE
Missing Notification Messages ?

### ISSUE THREAD

**Issue by gh4wi** [firewalld/firewalld#304]
OS = Linux Mint 18.3 Cinnamon x64 & Firewalld 0.4.0.
With older AMD CPU's (Phenom & FX), I see a notification message when I connect ExpressVPN to a server (That's good).
With newer AMD CPU's ( APU's A8, A10), I do NOT see a notification message when I connect ExpressVPN to a server (That's bad).
In both cases I do see the initial Firewall Applet Connection to Firewalld Established message.
Please advise. Thank you.

**Comment by erig0** [comment]
Please provide more information. What notification are you expecting from firewall-applet?

It sounds like you're using two different machines. Can you verify they software versions they're using?

**Comment by gh4wi** [comment]
Eight PC's running Mint 18.3 & same version of Firewalld & latestest ExpressVPN.
All display initial Firewalld Applet Connection to Firewalld Established message.
On PC's /w older AMD CPU's Firewalld Applet displays a message to show that ExpressVPN has connected to Firewalld. On PC's /w newer AMD CPU's Firewalld Applet does NOT display a message
to show that ExpressVPN has connect to Firewalld. ExpressVPN useage is the same on
all PC's & status appears normal, but is Firewalld processing ?

**Comment by gh4wi** [comment]
I suspect that on newer PC's, ExpressVPN is encrypting/decrypting w/o Firewalld protection.
Thus incoming messages are decrypted & passed to OS w/o Firewalld protection.
Since older PC's display the above connection message showing ExpressVPN has connected to Firewalld, they may work ok. But newer PC's don't display the same message, so they may not have Firewalld protection. I suggest Firewalld needs a display to show a running count of messages processed (LAN In/Out).
