### ISSUE TITLE
refresh po files

### ISSUE THREAD

**Issue by stanislav-brabec** [firewalld/firewalld#311]
firewalld-0.5.1 contains:
<property name="label">Please enter an interface name:</property>

Everything is correctly configured, but nobody updated po files:
POT-Creation-Date: 2017-05-31 13:12+0200

As a result, some strings are not translated.

Please refresh po files regularly.

**Comment by erig0** [comment]
Translations can be improved via Zanata:

    https://fedora.zanata.org/iteration/view/firewalld/master?dswid=2157

**Comment by piotrdrag** [comment]
The commit updated the .pot file, but didn’t actually pull updated translations from Zanata. As a result, 0.5.2 has outdated translations.

**Comment by erig0** [comment]
@piotrdrag, Yes. I see there have been translations done since I pushed the new pot to Zanata. I will pull the translations again for the next release.

**Comment by piotrdrag** [comment]
Thank you!
