### ISSUE TITLE
"destination ipset=<ipset>" syntax does not work

### ISSUE THREAD

**Issue by garethhumphriesmoh** [firewalld/firewalld#314]
I'm trying to setup some rules with multiple destination addresses (in this case for egress filtering, but we also have multiple NICs on most boxes, and want to apply the same rules to several of them).

I've created an ipset and can use it fine as a source parameter ('source ipset="someips"'), however if I try to do the same thing with the destination specification ('destination ipset="someips"'), I get the following error:
`Error: INVALID_RULE: attribute 'ipset' outside of any element. Use 'rule <element> ipset= ...'.`

This should be a valid destination specification.  If there's a valid reason for it not to be, there needs to be a documentation change, as right now it says 

> 'The destination address is using the same syntax as the source address. '

**Comment by erig0** [comment]
> This should be a valid destination specification. If there's a valid reason for it not to be, there needs to be a documentation change, as right now it says
> > 'The destination address is using the same syntax as the source address. '

Right above that it gives the full syntax:

> destination [not] address="address[/mask]"

This makes it clear `ipset=` is not supported for destination matching. I think the statement  'The destination address is using the same syntax as the source address. ' refers to  the `address=` portion of the syntax.

**Comment by garethhumphriesmoh** [comment]
Ok, my mistake.  I saw that sentence and got excited, should have read closer.

Documentation is fine, but is there a reason it isn't supported?  I've started looking at the code and haven't yet a seen a technical limitation that would prevent it, though I'm a long away from being able to state that confidently.  If it's just a matter of 'no-ones written it yet' I'm happy to help work on it, but if it will never get merged I won't waste my time.

**Comment by erig0** [comment]
I don't know of any technical reasons it can't be implemented.

**Comment by ikr0m** [comment]
Multiple destinations are really wanted feature! Consider following service:
```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <port protocol="tcp" port="100"/>
  <port protocol="udp" port="100"/>
  <destination ipv4="10.10.10.10"/>
  <destination ipv4="10.10.10.11"/>
</service>
```
Above produces warning log `"WARNING: Destination address for 'ipv4' already set, ignoring"` which means it is ignoring `<destination ipv4="10.10.10.11"/>` line. To support it I have to create 2 xml files like this:
**service1.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <port protocol="tcp" port="100"/>
  <port protocol="udp" port="100"/>
  <destination ipv4="10.10.10.10"/>
</service>
```
**service2.xml**
```
<?xml version="1.0" encoding="utf-8"?>
<service>
  <port protocol="tcp" port="100"/>
  <port protocol="udp" port="100"/>
  <destination ipv4="10.10.10.11"/>
</service>
```
I hope supporting multiple destinations or something similar it will be implemented in firewalld. 
Thanks.

**Comment by erig0** [comment]
@ikr0m, please file a separate issue explicitly for multiple destinations in service definitions.

**Comment by erig0** [comment]
@ikr0m, perhaps you could get the behavior you want with zone sources, as that supports ipsets.

**Comment by ikr0m** [comment]
@erig0 reported the issue https://github.com/firewalld/firewalld/issues/336 
Thanks for zone sources advice, I'll look into it

**Comment by brad2014** [comment]
The only workaround I could figure out for blocking all traffic at the router to/from a specific ipset was to resort to 8 direct rules:
```

# firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter INPUT 0 -m set --match-set my_set_ipv4 src -j DROP
# firewall-cmd --permanent --zone=public --direct --add-rule ipv6 filter INPUT 0 -m set --match-set my_set_ipv6 src -j DROP

# firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter FORWARD 0 -m set --match-set my_set_ipv4 src -j DROP  
# firewall-cmd --permanent --zone=public --direct --add-rule ipv6 filter FORWARD 0 -m set --match-set my_set_ipv6 src -j DROP  
# firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter FORWARD 0 -m set --match-set my_set_ipv4 dst -j DROP  
# firewall-cmd --permanent --zone=public --direct --add-rule ipv6 filter FORWARD 0 -m set --match-set my_set_ipv6 dst -j DROP  

# firewall-cmd --permanent --zone=public --direct --add-rule ipv4 filter OUTPUT 0 -m set --match-set my_set_ipv4 dst -j DROP
# firewall-cmd --permanent --zone=public --direct --add-rule ipv6 filter OUTPUT 0 -m set --match-set my_set_ipv6 dst -j DROP

```
