### ISSUE TITLE
 Firewall-applet does not allow to use KDE network connection editor

### ISSUE THREAD

**Issue by fkru** [firewalld/firewalld#315]
Using KDE with plasma-nm5 and firewalld (openSUSE Tumbleweed/Leap), one has to use GNOME's nm-connection-editor in order to change the corresponding settings through the firewall-applet. Looking at /usr/bin/firewall-applet reveals

_NM_CONNECTION_EDITOR = ""
for binary in [ "/usr/bin/nm-connection-editor",
                    "/bin/nm-connection-editor",
                "/usr/bin/kde5-nm-connection-editor",
                    "/bin/kde5-nm-connection-editor",
                "/usr/bin/kde-nm-connection-editor",
                    "/bin/kde-nm-connection-editor" ]:
if os.path.exists(binary):
NM_CONNECTION_EDITOR = binary_

where kde(5)-nm-connection-editor does not exist (it was replaced by a KCM some time ago). To open the network connection editor within KDE Plasma 5 one has to use "kcmshell5 kcm_networkmanagement". See the corresponding bug report at https://bugzilla.suse.com/show_bug.cgi?id=1086752#c1 for further details. A bug report for plasma-nm5 and its missing functionality has already been opened at https://bugs.kde.org/show_bug.cgi?id=392351.

**Comment by fkru** [comment]
Since this bug report has not been touched/assigned for almost one and a half months, I presume that the issue willl not be addressed at the firewalld side.

**Comment by erig0** [comment]
@fkru, it seems valid to fix this in firewalld. I'm just very busy with other items.
Perhaps someone could open a PR? Paging @hwoarang. :)

**Comment by hwoarang** [comment]
@fkru @erig0 yep I will look into this

**Comment by hwoarang** [comment]
We still need to see some progress on https://bugs.kde.org/show_bug.cgi?id=392351 in order to resolve this properly.

**Comment by fkru** [comment]
> We still need to see some progress on https://bugs.kde.org/show_bug.cgi?id=392351 in order to resolve this properly.
Seems to be fixed at KDE's side.

**Comment by Zesko** [comment]
It is done in #1086
