### ISSUE TITLE
man firewalld.richlanguage - Paragraph related to Destination 

### ISSUE THREAD

**Issue by ivab-test** [firewalld/firewalld#318]
It seems that the following paragraph must be under the "Destination" section instead of "Service" in the firewalld.richlanguage manual:
```
       If a service provides a destination address, it will
       conflict with a destination address in the rule and will
       result in an error. The services using destination
       addresses internally are mostly services using multicast.
```

**Comment by erig0** [comment]
The man page is correct. Service definitions allow a "destination" element. These can conflict with the "destination" in a rich rule.
