### ISSUE TITLE
Minor Firewalld German Language Issue

### ISSUE THREAD

**Issue by fkru** [firewalld/firewalld#319]
There is a minor bug in the German language package for firewalld, i.e., in  firewalld.mo the entry "Firwall-Einstellungen..." should read "Fir**e**wall-Einstellungen..."

**Comment by erig0** [comment]
Thanks for reporting. I updated this in Zanata. It will make it's way into the next release when I sync the translations.

https://fedora.zanata.org/webtrans/translate?project=firewalld&iteration=master&localeId=de&locale=en-US&dswid=-9747#view:doc;doc:po/firewalld;textflow:2198142

**Comment by erig0** [comment]
Translations have been updated since my above comment.
