### ISSUE TITLE
After the installation, firewalld doesn't start!

### ISSUE THREAD

**Issue by Warmuser** [firewalld/firewalld#332]
I use Fedora 27 with the latest updates + kernel.

**Comment by Warmuser** [comment]
Ok, I solved the problem by installing the firewall-applet. 
For those could encounter my same problem, run the command: "sudo dnf install firewall-applet". Bye

**Comment by erig0** [comment]
> Ok, I solved the problem by installing the firewall-applet.

firewalld should be independent of firewall-applet.
Any error messages/logs that you have would be helpful.

**Comment by Warmuser** [comment]
Ok, anyway I din't encounter any error message after the installation of firewall-applet. My intent was to use the gui version of these program.
