### ISSUE TITLE
sysctl 'ip_forward' is set unconditionally, undocumented

### ISSUE THREAD

**Issue by xrg** [firewalld/firewalld#335]
On a CentOS7 box, have been trying to debug why net.ipv4.ip_forward would turn to 1, although `sysctl.d` had a policy to keep it at 0. 
Then discovered that firewalld , fw_zone.py would call `enable_ip_forward()` whenever there is any port forwarding. 
IMHO, there is two issues with that:
 1. it is undocumented. Whenever firewalld would touch any other setting than the expected iptables or nf_tables, this should be mentioned in the docs.
 2. it may be undesired. Like in my case, that the box has a strict no-forwarding policy. Port redirections on the same box (without to-addr) are possible and don't mean that the box should necessarily be a router.

What is your opinion on that, please? 
Shall we do the following two changes:
 a. Only enable ip_forward if there is a forwarding rule with to-address 
 b. Clearly document this behavior.
?

**Comment by erig0** [comment]
@xrg, I agree that both should be done. There is definitely no reason to enable forwarding IP if the destination is the localhost.

**Comment by xrg** [comment]
Bump. Any thoughts on tackling this, please?

**Comment by erig0** [comment]
> Bump. Any thoughts on tackling this, please?

I'm hoping to address it by the next release.
