### ISSUE TITLE
Add A Service Documentation

### ISSUE THREAD

**Issue by chrisrwilkinson** [firewalld/firewalld#338]
There appears to be a typo in the "Add A Service" documentation [http://www.firewalld.org/documentation/howto/add-a-service.html]

When using the firewall-cmd or the firewall-offline-cmd command, the new service is declared as "myservice" but subsequent commands to modify the service specify --service=service.

Should it be "--service=myservice" instead.

Thanks

**Comment by erig0** [comment]
Fixed! Thanks for reporting!
