### ISSUE TITLE
SSL Cert for https://www.firewalld.org/ exipred

### ISSUE THREAD

**Issue by carslen** [firewalld/firewalld#343]
Hi,
your LetEncrypt SSL Cert for https://www.firewalld.org/ has expired. Please renew :-) 
![firewalld](https://user-images.githubusercontent.com/28647218/40736007-0ae671e4-643d-11e8-92e7-b8e29db6f372.PNG)

**Comment by erig0** [comment]
@carslen, thanks for reporting. I'll get to it ASAP.

**Comment by erig0** [comment]
This has been fixed. It required making DNS changes so it make take up to 24 hours to propagate.

I also enabled "enforce HTTPS" so even HTTP requests should be upgraded to HTTPS.

**Comment by erig0** [comment]
Github got back. They only support certs for exactly one domain (as specified in the repository settings, in firewalld's case this is `firewalld.org`). They do not support certs on subdomains. As such, please use https://firewall.org.

The following work:
* http://firewalld.org
* http://www.firewalld.org
* http://firewalld.github.io
* https://firewalld.org
* https://firewalld.github.io

However the following will _not_ work:
* https://www.firewalld.org
