### ISSUE TITLE
Issue when creating a new rich rule with custom prefix

### ISSUE THREAD

**Issue by SevM** [firewalld/firewalld#355]
firewalld 0.4.4.4 

[usr@host~]$ sudo firewall-cmd --permanent --add-rich-rule="rule family="ipv4" service name="ssh" log prefix="SSH Logging on Host " level="info" "
[sudo] password for usr: 
usage: see firewall-cmd man page
firewall-cmd: error: unrecognized arguments: Logging on Host  level=info 

Doing that same command works with single quotes when entering the prefix. Just a heads up not sure if anyone has seen this already.

Regards,

SevM

**Comment by erig0** [comment]
This is due to how a shell handles quotations. This is not something firewalld can fix on it's end.

You must either escape the internal quotes:

    $ sudo firewall-cmd --permanent --add-rich-rule="rule family=\"ipv4\" service name=\"ssh\" log prefix=\"SSH Logging on Host \" level=\"info\" "

or use single quotes on the outside:

    sudo firewall-cmd --permanent --add-rich-rule='rule family="ipv4" service name="ssh" log prefix="SSH Logging on Host " level="info" '
