### ISSUE TITLE
File conflict with cockpit / both ship /usr/lib/firewalld/services/cockpit.xml

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#359]
Hi,

I noticed that cockpit and firewalld both ship a service description file for cockpit:

https://github.com/firewalld/firewalld/blob/master/config/services/cockpit.xml
https://github.com/cockpit-project/cockpit/blob/master/src/ws/cockpit.xml

E.g. on Debian this leads to a file conflict and dpkg refusing to install both packages at the same time.

Either cockpit or firewalld should thus drop this file. I'm filing this issue against cockpit seeking guidance whether firewalld prefers that 3rd party packages ship their own service config files or if firewalld prefers to ship its own set of service descriptions.

**Comment by erig0** [comment]
This was handled in Fedora [0] by dropping the file from the cockpit package. It was also dropped upstream in cockpit, see cockpit-project/cockpit@d8b628507.

[0] https://bugzilla.redhat.com/show_bug.cgi?id=1609393

**Comment by mbiebl** [comment]
Thanks, will poke the Debian maintainer of cockpit to include this change in the cockpit-ws package.

**Comment by mbiebl** [comment]
Hm, I don't see a proper upstream fix here. The file was not really removed upstream. It's simply ```rm-ed``` in the spec file. This means any distro not using that upstream .spec file will run into this problem.
@martinpitt what do you think about dropping this file completely?

**Comment by martinpitt** [comment]
@mbiebl: In upstream cockpit we still need to support operating systems which have firewalld < 0.6 (like Debian stable, Ubuntu 16.04 and 18.04, RHEL/CentOS 7). So it cannot be dropped upstream yet, but we need to conditionally install or remove it in the .spec and tools/debian packaging.

**Comment by martinpitt** [comment]
@mbiebl: Sorry, of course firewalld needs to replaces/breaks: cockpit-ws.
