### ISSUE TITLE
As soon as I built and upgraded from firewalld 0.5.3 => 0.6.0, Lost all existing rules

### ISSUE THREAD

**Issue by EinerPetersen** [firewalld/firewalld#364]
I downloaded, built and upgraded from firewalld 0.5.3 => 0.6.0, on restart of firewalld, I lost all of my rules ..... Zones were left intact .... empty ......
Fixed by downgrading back to firewalld 0.5.3 and everything works again

Yes, I tried setting firewalld.conf to use iptables instead of nftables .... that did not work either

Einer

**Comment by erig0** [comment]
> I lost all of my rules

Can you provide output? Did you check "nft list ruleset" ? Were there any errors in firewalld's log?

> Yes, I tried setting firewalld.conf to use iptables instead of nftables .... that did not work either

Did you restart firewalld after making this change?

**Comment by EinerPetersen** [comment]
as soon as I downgraded back to 0.5.3 ..... no more errors and everything started working correctly again

**Comment by erig0** [comment]
firewalld 0.6.0 requires a very recent kernel. Your kernel is too old and does not support nftables fib matching. You can upgrade your kernel or try setting `IPv6_rpfilter=no` in `/etc/firewalld/firewalld.conf`.
