### ISSUE TITLE
RFE: new services into runtime config

### ISSUE THREAD

**Issue by Klaas-** [firewalld/firewalld#375]
Hi,
I am looking for a way to get a new service into runtime without reloading (ie while keeping current non-permanent config). I was expecting it to work the same as with permanent config but is not the case.
```
[root@notebook klaas]# cat << EOF > /usr/lib/firewalld/services/test.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>test</short>
  <description>Just a test</description>
  <port protocol="tcp" port="9999"/>
</service>
EOF
[root@notebook klaas]# sleep 10
[root@notebook klaas]# firewall-cmd --permanent --add-service=test
success
[root@notebook klaas]# firewall-cmd --add-service=test
Error: INVALID_SERVICE: test
[root@notebook klaas]# rpm -qa|grep firewalld
firewalld-0.5.3-2.fc28.noarch
firewalld-filesystem-0.5.3-2.fc28.noarch
```

Is there a way to achieve this?

Greetings
Klaas

**Comment by erig0** [comment]
Currently the watcher only updates the _permanent_ configuration. It will not update the runtime configuration of the primitives. A such a ---reload is required.

**Comment by erig0** [comment]
I don't think implementing this feature is worth the effort. Newer versions of firewalld maintain connections during --reload so the reload penalty is pretty low. It's unclear what should be done if the new service is invalid. There is no way to convey that to the user.

One thing that does get wiped during a --reload is runtime only direct rules and interface to zone bindings, but you can change those to remain by setting FlushAllOnReload=no in firewalld.conf.
