### ISSUE TITLE
src dir binaries work but make install binaries do not

### ISSUE THREAD

**Issue by bltdrivewentawol** [firewalld/firewalld#382]
After doing a "make install" the firewalld, firewall-applet, firewall-config fail to launch with this error:

$ firewalld
```
Traceback (most recent call last):
  File "/usr/sbin/firewalld", line 33, in <module>
    from firewall import config
ModuleNotFoundError: No module named 'firewall'
```

$ firewall-config
```
Traceback (most recent call last):
  File "/usr/bin/firewall-config", line 45, in <module>
    from firewall import config
ModuleNotFoundError: No module named 'firewall'
```

Steps to reproduce:
1. ./autogen.sh PYTHON=/usr/bin/python3
2. make
3. make install
4. firewalld --nofork --debug
```
Traceback (most recent call last):
  File "/usr/sbin/firewalld", line 33, in <module>
    from firewall import config
ModuleNotFoundError: No module named 'firewall'
```

In the git folder (or more specifically the build folder) the binaries in the src directory work without error:
```
$ ls -l
-rwxr-xr-x 1 root root  41578 Sep  9 22:53 firewall-applet
-rwxr-xr-x 1 root root 116160 Sep  9 22:53 firewall-cmd
-rwxr-xr-x 1 root root 332129 Sep  9 22:53 firewall-config
-rwxr-xr-x 1 root root   7028 Sep  9 22:53 firewalld
-rwxr-xr-x 1 root root 103587 Sep  9 22:53 firewall-offline-cmd
```

**Comment by bltdrivewentawol** [comment]
So it appears this fixes the issue:
```
$ sudo cp -r /home/user/GIT/firewalld/src/firewall /usr/lib/python3/dist-packages
```
This may need to be added to the "make install" script?

**Comment by erig0** [comment]
Are you building a release version or master branch?

**Comment by bltdrivewentawol** [comment]
Preferably not, as at the moment I have other engagements needing attention first.
If needed though, it could be possible down the road.

**Comment by bltdrivewentawol** [comment]
I apologize for completely not interpreting your question correctly...
<hand slaps forehead>

Answer:
 *** This is a master branch. ***

I was able to duplicated this problem again today.

New System Info:
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.8 (stretch)
Release:	9.8
Codename:	stretch

$ python3 --version
Python 3.5.3

**Comment by erig0** [comment]
This is a really old bug and almost certainly fixed. Awhile back changes were made to use the python interpreter passed to configure via `PYTHON`. Please reopen if it's still an issue.
