### ISSUE TITLE
Unexpectedly added masquerade to all interfaces

### ISSUE THREAD

**Issue by fossilet** [firewalld/firewalld#384]
I use two zones, external and internal. Masquerading is enabled by default in external zone only, but actually all my interfaces, even the interface in internal zone and VPN interfaces are enabled explicitly. This is verified by magically connected networks which require masquerading on one interface to interconnect. It can also be see iptables rules:

```
[root@router2 ~]# iptables-save | grep MASQUERADE
-A POST_external_allow ! -o lo -j MASQUERADE
```

**Comment by erig0** [comment]
If you want to limit masquerading by the source then you need to use a rich rule.
e.g.
```
# firewall-cmd --zone=external --add-rich-rule='rule source address=10.0.0.0/24 masquerade'
```

**Comment by fossilet** [comment]
I only enabled masquerading in one zone, and `firewall-cmd` lists masquerading as no in other zone:

```[root@router ~]# firewall-cmd --list-all
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens160
  sources: 
  services: ssh dns
  ports: 
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	
[root@router ~]# firewall-cmd --list-all --zone=internal
internal (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources: 
  services: ssh mdns samba-client dhcpv6-client dhcp dns
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

But it is in fact enabled on interface `ens192`, and on my other VPN interface. Is this really expected behavior?

**Comment by erig0** [comment]
It's enabled on the outgoing zone. Packets only reach the chain POST_external_allow if the outbound interface is an interface assigned to the "external" zone. Take a look at the chain POSTROUTING_ZONES in the nat table.

**Comment by fossilet** [comment]
These are the relevant rules:
```
-A POSTROUTING -j POSTROUTING_direct
-A POSTROUTING -j POSTROUTING_ZONES_SOURCE
-A POSTROUTING -j POSTROUTING_ZONES
-A POSTROUTING_ZONES -o ens192 -g POST_internal
-A POSTROUTING_ZONES -o ens160 -g POST_external
-A POSTROUTING_ZONES -g POST_external
-A POST_external -j POST_external_log
-A POST_external -j POST_external_deny
-A POST_external -j POST_external_allow
-A POST_external_allow ! -o lo -j MASQUERADE
```

I do not understand the magic here. `ens192` is in a masquerade:no zone, the other VPN interface is even not managed by firewalld or NetworkManager, but masquerading are enabled on these interfaces. Why is this not a bug? This is obvious unexpected.

**Comment by erig0** [comment]
The masquerading is on the `external` zone. When a packet passes from the `internal` to the `external` zone masquerading is applied by this rule:
```
-A POST_external_allow ! -o lo -j MASQUERADE
```
That's how it's suppose to work. If you want to restrict the masquerading you can use the rich rule as I pointed out above, https://github.com/firewalld/firewalld/issues/384#issuecomment-420669431.

**Comment by fossilet** [comment]
What about my VPN interface? It is not even any zone despite masquerading enabled. `-A POST_external_allow ! -o lo -j MASQUERADE` should be`-A POST_external_allow ! -o ens160 -j MASQUERADE`.

**Comment by erig0** [comment]
> What about my VPN interface? It is not even in any zone despite masquerading enabled.

I don't what your network or routes look like. But it's probably still passing through the external zone, which means masquerade gets applied.

> -A POST_external_allow ! -o lo -j MASQUERADE should be-A POST_external_allow -o ens160 -j MASQUERADE

This is unnecessary. Packets only reach the `POST_external_allow chain` if they first match this rule:
```
-A POSTROUTING_ZONES -o ens160 -g POST_external
```
which means it's already qualified by the `-o ens160`.

**Comment by b-a-t** [comment]
I came across this bug report trying to figure out what's going wrong in our `firewalld` setup and it seems we have exactly the same problem that @fossilet describes.

I can put relevant configuration snippets, but they'll be almost 1:1 to what he presented.

```
$ firewall-cmd --list-all
external (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: ssh openvpn ipsec http https
  ports: 10050/tcp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
and
```
$ firewall-cmd --list-all --zone=trusted
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: ens224 tun0
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
for the direct rule like:
```
<rule priority="0" table="nat" ipv="ipv4" chain="PREROUTING">-p tcp --dport 17000 -i ens192 -j DNAT --to 10.40.10.101:17000</rule>
```
For the direct port forwarding from external `ens192` via trusted `ens224` I observe:
```
tcp      6 431997 ESTABLISHED src=193.x.x.x dst=88.y.y.y sport=49757 dport=17000 src=10.40.10.101 dst=10.40.10.1 sport=17000 dport=49757 [ASSURED] mark=0 use=2
```
Obviously there is a masquerading (unexpectedly) in effect on the `trusted` interface `ens224`.

This is definitely not what you'd expect for the simple almost default `firewalld` configuration...

And I think this is either a bug or very obscure and unexpected side effect of the generated configuration.
