### ISSUE TITLE
update release at ubuntu universe?

### ISSUE THREAD

**Issue by dkebler** [firewalld/firewalld#386]
The current version for 16.04 xenial is way old https://www.ubuntuupdates.org/package/core/xenial/universe/updates/firewalld.

Is anyone on the project pushing newer releases to unbuntu universe?  Given the security risks I'd prefer to use a more current release.

If not ubuntu universe than a ppa would be ok.

**Comment by erig0** [comment]
Please file a bug with Ubuntu for packaging issues.

**Comment by dkebler** [comment]
not a packaging issue but if no one submits new releases to Ubuntu then well they never appear.  I understand that firewalld was written primary for RHEL 7, CentOS 7
Fedora 18 and newer so maybe their package managers have the later releases and maybe you just don't care to support Ubuntu explicitly.  That's ok understood.  Given that as you have noticed I am attempting to get latest running on xenial from source.  I have run this old version fine just don't feel comfortable running a firewalld version that is now 3+ years old.

**Comment by erig0** [comment]
> not a packaging issue but if no one submits new releases to Ubuntu then well they never appear

This is exactly a packaging issue. File a request with Ubuntu to update the package. The firewalld maintainers simply don't have the bandwidth to package for every distribution.

Ubuntu Xenial uses a 4.4 kernel. For best results the nftables backend requires a 4.18 kernel.
