### ISSUE TITLE
dependency errors

### ISSUE THREAD

**Issue by dkebler** [firewalld/firewalld#387]
At least for the latest release your documentation here https://firewalld.org/documentation/working-with-the-source.html is out of date (I am on ubuntu xenial)

there is no glib2 package as listed (no candidate)  I had to load libglib2.0-dev
https://askubuntu.com/questions/204643/getting-missing-dependency-for-compilation-glib-compile-schemas

there is no package python3-gobject anymore I loaded python3-gi
and based on autogen script error it looks like you are now using nft(nftables) instead of `iptables` and `ebtables` https://wiki.archlinux.org/index.php/nftables  so I had to install `nftables`

With those changes I was able to run the autogen script without error

the build from source docs should like different dependencies for different releases as they change.

**Comment by erig0** [comment]
Looks like the website documentation is out of date. The in-tree README is probably more authorative: https://github.com/firewalld/firewalld/blob/master/README. It mentions nftables.

Unfortunately some distros name packages differently.

- python3-gobject is sometimes python3-gi
- glib2-devel is sometimes libglib2.0-dev

We should mention these alternative package names in the README and website.

**Comment by dkebler** [comment]
was never able to get firewalld to make/build on ubuntu even bionic.
