### ISSUE TITLE
registration/login of forum broken

### ISSUE THREAD

**Issue by dkebler** [firewalld/firewalld#388]
Can't use any social media login nor register at forum site

**Comment by erig0** [comment]
I'm not sure to which site you're referring. Please provide a link.

**Comment by erig0** [comment]
Oh. You're talking about the mailing lists. They still function, but don't see a lot of traffic. I was able to login with my Fedora FAS account, but others failed.

The website has its own repo, [firewalld/firewalld.github.io](https://github.com/firewalld/firewalld.github.io)
