### ISSUE TITLE
nftables backend only properly supports LogDenied 'off' and 'all'

### ISSUE THREAD

**Issue by henryptung** [firewalld/firewalld#391]
Example line: (there are several others as well) https://github.com/firewalld/firewalld/blob/f329311ac858a0d96d0dac99d7227c6dae643b75/src/firewall/core/nftables.py#L428

The created log rules do not reference the LogDenied value, and thus don't contain the necessary `pkttype` qualifier for cases other than `all`.

**Comment by erig0** [comment]
Agreed. This should use `%%LOGTYPE%%` which gets replaced later on based on the value of log_denied.
