### ISSUE TITLE
FirewallBackend=nftables (default since 0.6.0) breaks NAT networks in libvirt

### ISSUE THREAD

**Issue by liskin** [firewalld/firewalld#397]
From <https://firewalld.org/2018/07/nftables-backend>:

> The main consequence for users is that firewall rules created outside of firewalld (e.g. libvirt, docker, user, etc) will take precedence over firewalld’s rules.

but unfortunately also:

> For firewalld this means packets may be accepted early by custom iptables or nftables rules, but will still be subject to firewalld’s rules."

libvirt starts dnsmasq:

    # ss -lpn '( sport = 53 or sport = 67 )' | grep dnsmasq
    udp    UNCONN   0        0            192.168.122.1:53            0.0.0.0:*      users:(("dnsmasq",pid=3990102,fd=5))
    udp    UNCONN   0        0           0.0.0.0%virbr0:67            0.0.0.0:*      users:(("dnsmasq",pid=3990102,fd=3))
    tcp    LISTEN   0        32           192.168.122.1:53            0.0.0.0:*      users:(("dnsmasq",pid=3990102,fd=6))

and adds some iptables rules:

    # iptables-save | grep 'INPUT.*virbr.*ACCEPT'
    -A INPUT -i virbr0 -p udp -m udp --dport 53 -j ACCEPT
    -A INPUT -i virbr0 -p tcp -m tcp --dport 53 -j ACCEPT
    -A INPUT -i virbr0 -p udp -m udp --dport 67 -j ACCEPT
    -A INPUT -i virbr0 -p tcp -m tcp --dport 67 -j ACCEPT

As mentioned above, these rules aren't enough for the packet to be accepted, nftables would need to be configured to accept 53/67 from virbr0 as well.
https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains explains:

> if a packet gets accepted/dropped and there is a later chain in the same hook which is ordered with a later priority, the packet will be evaluated *again*"

According to https://bbs.archlinux.org/viewtopic.php?id=239362, this breaks
docker as well. :-(

**Comment by erig0** [comment]
This is not something we can fix in firewalld. It comes down to how netfilter works in the kernel. 
There are a few options (in order of complexity):
1. libvirt/docker/etc properly integrate with firewalld by using firewalld's primitives: zones, services, etc.
The firewalld developers are currently discussing this option with libvirt developers. This likely the long-term solution.
2. Revert to using the iptables backend. See man `firewalld.conf`.
3. Add the libvirt/docker interface to the `trusted` zone.  
This may have security implications - previously libvirt traffic was filtered as per the default zone.
4. Stop firewalld while libvirt/docker are in use

I will leave this report open, but at the moment there isn't much we can do on firewalld's end.

**Comment by liskin** [comment]
@erig0 Thanks for the quick answer. I reverted to iptables and will wait what comes out of the discussion with libvirt developers.

**Comment by darkbasic** [comment]
> libvirt properly integrate with firewalld by using firewalld's primitives: zones, services, etc.
The firewalld developers are currently discussing this option with libvirt developers. This is likely the long-term solution.

Can you please point me to that discussion? Thanks

**Comment by erig0** [comment]
> Can you please point me to that discussion? Thanks

Unfortunately it occurred on an non-public mailing list. The chosen quick fix is for libvirt to provide it's own zone with an "accept" policy - this is similar to workaround number 3 in the list above. We're still discussing the long-term fix.

**Comment by erig0** [comment]
libvirt 0.5.1 has native integration with firewalld and as such works well with the nftables backend. Closing this bug.

**Comment by lafrech** [comment]
> libvirt 0.5.1

Pretty sure this should read 5.1.0.

Sorry fir the nitpick. I got confused for a while.

**Comment by erig0** [comment]
> > libvirt 0.5.1
> 
> Pretty sure this should read 5.1.0.
> 
> Sorry fir the nitpick. I got confused for a while.

Right, thanks for catching. Fixed.
