### ISSUE TITLE
firewall rules don't work after change to nftables backend

### ISSUE THREAD

**Issue by pkreuzt** [firewalld/firewalld#399]
After upgrade to firewalld 0.6.2, in which backend changed to nftables by default, a custom script I use to enable multicast when needed stoppped working. Its content:

#!/bin/bash
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p igmp -j ACCEPT
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -d 239.0.0.0/8 -j ACCEPT

It reports "success" on both commands, but IGMP is not really working. Changing firewalld backend back to iptables in /etc/firewalld/firewalld.cond makes the commands work as expected, so it seems there's a problem in nftables backend. FYI I'm  on a 4.18 kernel.

**Comment by hwoarang** [comment]
I am guessing that with nftables as default backend, there is no provision to manage the direct rules with are 'iptables' by default.

**Comment by erig0** [comment]
This is expected. Both of those rules can be added via firewalld primitives:
```
# firewall-cmd --add-protocol=igmp
# firewall-cmd --add-rich-rule='rule source address="239.0.0./8" accept'
```

See the blog post for why this is expected: https://firewalld.org/2018/07/nftables-backend

> Direct interface precedence
> 
> 
> In previous versions of firewalld rules added via the direct interface were still subject to firewalld’s rules that occur early in the ruleset. Most notably is the early acceptance of packets that are part of existing connections. This has led to confusion for users, for example see github issue 44.
> 
> With the nftables backend direct rules are deliberately given a higher precedence than all other firewalld rules. Now when a user adds a direct rule to drop traffic existing connections will also be affected.

**Comment by pkreuzt** [comment]
First, the second rule you wrote is missing family. Correcting it to 

firewall-cmd --add-rich-rule='rule family="ipv4" destination address="239.0.0.0/8" accept'

it throws an error on syslog:

ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
ERROR: '/usr/sbin/nft add rule inet firewalld filter_IN_public_allow meta nfproto ipv4 ip6 daddr 239.0.0.0/8 accept' failed: Error: conflicting protocols specified: ip vs. ip6#012add rule inet firewalld filter_IN_public_allow meta nfproto ipv4 ip6 daddr 239.0.0.0/8 accept#012

**Comment by erig0** [comment]
@pkreuzt, Ugh. That's a bug. I just pushed a fix.
