### ISSUE TITLE
ERROR: Failed to apply rules.

### ISSUE THREAD

**Issue by adaaaaaa** [firewalld/firewalld#406]
command:"systemctl  status firewalld" throw out an error

10月 11 08:36:32 captain-pc systemd[1]: Starting firewalld - dynamic firewall daemon...
10月 11 08:36:32 captain-pc systemd[1]: Started firewalld - dynamic firewall daemon.
10月 11 08:36:32 captain-pc firewalld[518]: ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
10月 11 08:36:32 captain-pc firewalld[518]: ERROR: '/usr/bin/nft add rule inet firewalld filter_IN_block %%reject%%' failed: Error: syntax error, unexpected junk
                                             add rule inet firewalld filter_IN_block %%reject%%

what'wrong with it?

**Comment by erig0** [comment]
Are you using a "block" zone? Or a rich rule with "reject" ?

**Comment by erig0** [comment]
NM. I see from your logs that you are indeed using the "block" zone.

**Comment by erig0** [comment]
Thanks for reporting. The fix will be available in v0.6.3.
