### ISSUE TITLE
Why are ip_tables, ip6_tables, eb_tables, and ipset kernel modules needed with FirewallBackend=nftables?

### ISSUE THREAD

**Issue by equaeghe** [firewalld/firewalld#419]
From the documentation, I understood that with firewalld 0.6.3 can use nftables and not rely on any of the ‘old’ infrastructure. However, if I remove all this old infrastructure (ip_tables, ip6_tables, eb_tables, and ipset kernel modules & friends) and use `FirewallBackend=nftables` in `/etc/firewalld/firewalld.conf`, firewalld complains:

```
WARNING: ipset not usable, disabling ipset usage in firewall.
ERROR: '/sbin/iptables-restore -n' failed: modprobe: FATAL: Module ip_tables not found…
ERROR: '/sbin/ip6tables-restore -n' failed: modprobe: FATAL: Module ip6_tables not found…
ERROR: '/sbin/ebtables -t nat -F' failed: modprobe: FATAL: Module ebtables not found…
```

So I guess I do need some of the old infrastructure still, but then which (kernel modules; I prefer to only build the ones I need)? Or perhaps this is related to a compile-time choice my distribution has made?

**Comment by erig0** [comment]
iptables, et al. are still needed to support the --direct interface. You will still need all the iptables, ip6tables, ebtables, ipset kernel modules.
