### ISSUE TITLE
rule add triggers assertion in nft or gmp code

### ISSUE THREAD

**Issue by equaeghe** [firewalld/firewalld#420]
Using a standard firewalld 0.6.3 installation, I get an error where a rule add triggers an assertion in nft or gmp code:

```
ERROR: '/sbin/nft add rule inet firewalld raw_PRE_home_allow udp dport 137 ct helper netbios-ns' failed: nft: gmputil.c:67: mpz_get_uint32: Assertion `cnt <= 1' failed.
```

This may be an upstream (nft, even gmp) issue, but because I'm not sure, I'm reporting this here first.

**Comment by equaeghe** [comment]
Upstream report: https://bugzilla.netfilter.org/show_bug.cgi?id=1288

**Comment by erig0** [comment]
This is not a firewalld bug. It's either a bug in nftables or libgmp. In your netfilter report you should add your nftables and libgmp versions.
