### ISSUE TITLE
Add an ospf service

### ISSUE THREAD

**Issue by brianjmurrell** [firewalld/firewalld#424]
It would be nice to have an ospf service, which brings up a somewhat related issue...

It would be nice to be able to list multiple "rules" within a service.  OSPF is a good example as it includes:

```
<service>
  <short>OSPF</short>
  <description></description>
  <port protocol="ospf" port=""/>
  <destination ipv4="224.0.0.5"/>
</service>
```

as well as:

```
<service>
  <short>OSPF-igmp</short>
  <description></description>
  <port protocol="igmp" port=""/>
  <destination ipv4="224.0.0.5"/>
</service>
```

but it would be nice to have those in the same file.

**Comment by erig0** [comment]
There is no need for ospf or igmp as they have their own protocol number. Just do the following:
```
# firewall-cmd --add-protocol=ospf
# firewall-cmd --add-protocol=igmp
```
