### ISSUE TITLE
rpfilter_DROP PROTO=ICMPv6 TYPE=131 CODE=0

### ISSUE THREAD

**Issue by brianjmurrell** [firewalld/firewalld#428]
I have logging enabled for multicast on my `firewalld` installation.

I'm seeing a raft of:

```
20:04:07 kernel rpfilter_DROP: IN=enp2s0 OUT= MAC= SRC=fe80:0000:0000:0000:021f:c6ff:fec4:926a DST=ff02:0000:0000:0000:0000:0001:ffc4:926a LEN=72 TC=0 HOPLIMIT=1 FLOWLBL=0 PROTO=ICMPv6 TYPE=131 CODE=0
```

But AFAICT this is legitimate traffic.

**Comment by erig0** [comment]
@brianjmurrell, Are you on a 4.16 or 4.17 kernel?

**Comment by brianjmurrell** [comment]
I was on a 4.18 kernel as of Nov. 5, so at the time of writing this bug report, it would have been 4.18.

> Please reopen this report of the above does not resolve the issue.

I don't seem to have any ability to reopen.

**Comment by erig0** [comment]
> I was on a 4.18 kernel as of Nov. 5, so at the time of writing this bug report, it would have been 4.18.

The report above is actually a MLD report. Which likely means you can ignore it - unless the box running firewalld is also a multicast sender. I don't know why the kernel's rpfilter doesn't allow the packet, but I don't think it makes sense for firewalld to explicitly allow these as most users don't care about them.

You can squelch the logs by using `log-denied=unicast` to ignore logging for multicast/broadcast.
Alternatively, set `IPv6_rpfilter=no` if you actually want to allow these packets.
