### ISSUE TITLE
How to use firewall as a python package

### ISSUE THREAD

**Issue by BedivereZero** [firewalld/firewalld#433]
Is here any document about how to using python package 'firewall'.
In my service, I set firewall like this:
```
import subprocess
subprocess.call('firewall-cmd --add-server=http', shell=True)
```

**Comment by erig0** [comment]
No, there is no documentation. The preferred way for applications to interact with firewalld is through the [dbus interface](https://firewalld.org/documentation/man-pages/firewalld.dbus.html).

**Comment by erig0** [comment]
Closing, as question was answered above.
