### ISSUE TITLE
FreeIPA service definitions are outdated

### ISSUE THREAD

**Issue by tiran** [firewalld/firewalld#435]
firewalld comes with four pre-defined service definitions for FreeIPA:

* freeipa-ldap with HTTP, HTTPS, Kerberos, LDAP and NTP
* freeipa-ldaps with HTTP, HTTPS, Kerberos, LDAPS, and NTP
* freeipa-replication with 7389/TCP
* freeipa-trust with Samba and AD ports

However the service definitions and documentation are outdated:

* Port 7389 and service ``freeipa-replication`` are no longer needed since RHEL 7.0 and Fedora 18. Port 7389/TCP was used for Dogtag's LDAP server. FreeIPA 3.1 consolidated the 389-DS databases and now Dogtag and IPA share the same LDAP server instance.
* FreeIPA requires both LDAP and LDAPS to work properly. Iit doesn't make any sense to have separate services ``freeipa-ldap`` and ``freeipa-ldaps``. FreeIPA clients and master-master replication both require port 389/TCP (LDAP) to work. The LDAP protocol is not a security problem, because FreeIPA doesn't use plaintext LDAP but STARTTLS and/or GSSAPI to authenticate and protect. Dogtag PKI also uses LDAPS.
* FreeIPA 4.7 and newer no longer install a NTP instance on each master.

I propose a single freeipa service ``freeipa.xml`` that combines LDAP and LDAPS but leaves out NTP:

```freeipa.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>FreeIPA server</short>
  <description>FreeIPA is an integrated identity and authentication solution with Kerberos, LDAP, PKI, and web UI. Enable this option if you plan to provide a FreeIPA server. Enable the 'dns' service if this FreeIPA server provides DNS services and 'ntp' service if this FreeIPA server provides NTP services.</description>
  <!-- CRL and OCSP -->
  <port protocol="tcp" port="80"/>
  <!-- API and web UI -->
  <port protocol="tcp" port="443"/>
  <!-- Kerberos and kpasswd -->
  <port protocol="tcp" port="88"/>
  <port protocol="udp" port="88"/>
  <port protocol="tcp" port="464"/>
  <port protocol="udp" port="464"/>
  <!-- LDAP and LDAPS -->
  <port protocol="tcp" port="389"/>
  <port protocol="tcp" port="636"/>
</service>
```

**Comment by erig0** [comment]
@tiran, does it make sense to add a major version to the freeipa service definition just in case the ports, etc change again? e.g. freeipa-4.xml. Similarly we have "nfs" and "nfs3".

**Comment by tiran** [comment]
@erig0 Yeah, that makes sense.
