### ISSUE TITLE
iptables-restore -w -n

### ISSUE THREAD

**Issue by unioncos** [firewalld/firewalld#440]
After the CentOS  7.6.1810 upgrade on firewall-cmd --reload I NOW get . . . 

ERROR: COMMAND_FAILED: Direct: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 4 failed

The man page at http://man7.org/linux/man-pages/man8/iptables-restore.8.html show a " -w " as an option for "WAIT" for exclusive lock - and I have to guess it is not happening and then fails as a result 

If I check the iptables -L they all reload and the rich text rules in the public.xml file do also - which is where I usually just add a rule by inserting a new IP or CIDR  into the file by  copying an existing rule by cut and paste, and I have never had any previous problem

Where is this command set - in what config or script command -  . . .  and how can I address this to stop the error message ??

**Comment by erig0** [comment]
> ERROR: COMMAND_FAILED: Direct: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 4 failed

This indicates a rule failed to apply. You can get more information by setting `IndividualCalls=yes` in `/etc/firewalld/firewalld.conf`. Or you can add `--debug=3` in `/etc/sysconfig/firewalld`.

**Comment by unioncos** [comment]
OK the IndividualCalls=yes in /etc/firewalld/firewalld.conf hung that terminal

I removed the offending direct.xml rule and opened a new terminal  window with a " firewall-cmd --reload " command and it returned " success "

**Comment by unioncos** [comment]
Thanks . . . 

I don't suppose you could help me get ris of the nf_cpntrack error message 

"  WARNING: Failed to get and parse nf_conntrack_helper setting "

My /etc/modprobe.d/firewalld-sysctls.conf files  says 

install nf_conntrack /usr/sbin/modprobe --ignore-install nf_conntrack $CMDLINE_OPTS && /usr/sbin/sysctl --quiet --pattern 'net[.]netfilter[.]nf_conntrack.*' --system

Most references to it show it is depreciated - so if true how do I get rid of the attempts of firewald to load it ??

**Comment by erig0** [comment]
> " WARNING: Failed to get and parse nf_conntrack_helper setting "

That seems to imply that module nf_conntrack in not loaded, but it should be. What happens if you fully restart firewalld? e.g. `systemctl restart firewalld`.

`/etc/modprobe.d/firewalld-sysctls.conf` is benign in this case.

**Comment by erig0** [comment]
Closing, as original report was due to invalid direct rule.

**Comment by unioncos** [comment]
There is no conntrak_helper module at all in the directory and never has been 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 12/14/2018, 10:43 AM Eric Garver <notifications@github.com> wrote:

" WARNING: Failed to get and parse nf_conntrack_helper setting "

That seems to imply that module nf_conntrack in not loaded, but it should be. What happens if you fully restart firewalld? e.g. systemctl restart firewalld.
/etc/modprobe.d/firewalld-sysctls.conf is benign in this case.

**Comment by erig0** [comment]
> There is no conntrak_helper module at all in the directory and never has been

The module is `nf_conntrack`. The sysctl and /proc entry  is `nf_conntrack_helper`

**Comment by unioncos** [comment]
Yes there is none... the error message is "no such file or directory" 
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 12/19/2018, 5:47 AM Eric Garver <notifications@github.com> wrote:

There is no conntrak_helper module at all in the directory and never has been

The module is nf_conntrack. The sysctl and /proc entry  is nf_conntrack_helper
