### ISSUE TITLE
[multizone][iptables][security][v0.6.3] Undocumented zone drifting

### ISSUE THREAD

**Issue by Arano-kai** [firewalld/firewalld#441]
It is possible to apply unwanted rules, if no match happened in zone, selected by source.
Since `jump` is used for descent to `INPUT_ZONES_SOURCE` and `INPUT_ZONES` and `goto` used for descent to specific zone, decisions will be applied from zone, selected by interface in case no decisions made in source-based zone. This may lead to security breakage, if user not aware of that behavior.

Tested on `iptables` backend with firewalld `0.4.4.2-1` (Debian stretch) and `0.6.3-4` (Debian sid).

Relevant to #192, but describes flaw in resulting ruleset.

**Comment by erig0** [comment]
@Arano-kai, thanks for reporting. This was actually on my radar to fix, but thanks for opening the issue for tracking. I think the best approach is to terminate all packets at the end of the chain. There is no reason "default" needs to fallback to the top level chains.
