### ISSUE TITLE
nf_conntrack_helper file missing

### ISSUE THREAD

**Issue by unioncos** [firewalld/firewalld#443]
This is the same as https://github.com/firewalld/firewalld/issues/353

However I am running CentOS 7 (latest) and it has firewalld version 0.5.3 and it running OpenVZ

# uname -a
Linux main 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

Is my kernel

Is there a workaround to fix the error other than an upgrade to version 0.6.3

Dec 18 10:38:59 main firewalld[25982]: ERROR: Failed to read file "/proc/sys/net/netfilter/nf_conntrack_helper": [Errno 2] No such file or directory: '/proc/sys/net/netfilter/nf_conntrack_helper'
Dec 18 10:38:59 main firewalld[25982]: WARNING: Failed to get and parse nf_conntrack_helper setting

**Comment by erig0** [comment]
> Is there a workaround to fix the error other than an upgrade to version 0.6.3

The workaround is in the comments of issue #353 that you linked - preload the module.

**Comment by unioncos** [comment]
Yes I aware it is an old kernel - it is a hosting company issue with OpenVZ - so I cannot fix it without upgrading my service with them to another premium service where I can upgrade to my own kernels if I want - which is fair and I am so happy with them at the price I pay  I do not want to say their name - I do not want everybody flocking to them - seriously !!

so the work around did not work either and will not

[root@main ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by erig0** [comment]
You might be able to avoid the probe for nf_conntrack_helper by setting `AutomaticHelpers=no` in `/etc/firewalld/firewalld.conf`. Alternatively try setting it to yes.

**Comment by BlackMage2** [comment]
I'm sorry, that does not work for me.
