### ISSUE TITLE
untracked connections noticed in ruleset

### ISSUE THREAD

**Issue by jshand2015** [firewalld/firewalld#444]
I'm not too sure if you are aware of YaST2's firewalld module, but i have noticed when i add a connection i want to be allowed inbound, i see in this rule it is untracked.  i am security conscious and would like to know if this is intentional or a bug?

**Comment by erig0** [comment]
It is intentional, refer to commit f329311ac858a0d96d0dac99d7227c6dae643b75. This was done to address Suse BZ 1105821.
