### ISSUE TITLE
Feature request: Modules with custom ports in services

### ISSUE THREAD

**Issue by henryptung** [firewalld/firewalld#451]
Currently, helpers that can be used for multiple protocols must be configured for all relevant ports simultaneously. This means that every zone using the helper will activate it for **all** those ports, even if the zone only wants to use the helper on one service.

It would be helpful if a service can invoke a module, but customize it for specific ports (i.e. replace the "normal" helper configuration with its own). Defining a custom helper doesn't seem like it works, because conntrack doesn't recognize the custom helper name.

Example use case: using nf_conntrack_netbios_ns for other UDP broadcast services.

**Comment by henryptung** [comment]
On second thought, this issue looks much deeper than I first thought. It seems like helpers are being attached to the `prerouting` hook, but based on examples, helpers like `netbios-ns` need to be attached to the `output` hook since they detect outgoing broadcasts and set up expectations for reply packets:

https://www.google.com/search?q=%22j+CT%22+helper+netbios-ns

If there's no way to configure helpers to attach to raw_OUTPUT rather than raw_POSTROUTING, this seems like a fundamental gap in firewalld handling. Will create a separate issue for this.

**Comment by erig0** [comment]
@henryptung, you are correct. To really support client side helpers, we need to first support OUTPUT filtering. Secondly, firewalld already allows the user to create customer helpers, see man page FIREWALLD.HELPER(5).

I'm closing this one in favor for #452 as that addresses the real issue.
