### ISSUE TITLE
Error on Running Firewalld After Clean Install of Debian 9

### ISSUE THREAD

**Issue by AliAlGallaf** [firewalld/firewalld#462]
I've noticed the following errors after clean install of firewalld on Debian 9.

> $ sudo systemctl status firewalld

> ● firewalld.service - firewalld - dynamic firewall daemon
>    Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sun 2019-02-17 20:34:41 CET; 3s ago
>      Docs: man:firewalld(1)
>  Main PID: 19382 (firewalld)
>     Tasks: 2 (limit: 4915)
>    CGroup: /system.slice/firewalld.service
>            └─19382 /usr/bin/python3 -Es /usr/sbin/firewalld --nofork --nopid
> 
> Feb 17 20:34:41 server systemd[1]: Starting firewalld - dynamic firewall daemon...
> Feb 17 20:34:41 server systemd[1]: Started firewalld - dynamic firewall daemon.
> Feb 17 20:34:42 server firewalld[19382]: ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
> Feb 17 20:34:42 server firewalld[19382]: ERROR: '/sbin/ebtables -t broute -F' failed:
> Feb 17 20:34:42 server firewalld[19382]: WARNING: '/sbin/ip6tables-restore -n' failed:
> Feb 17 20:34:42 server firewalld[19382]: ERROR: Failed to apply rules. A firewall reload might solve the issue if the firewall has been modified using ip*tables or ebtables.
> Feb 17 20:34:42 server firewalld[19382]: ERROR: '/sbin/ebtables -t filter -D FORWARD -j FORWARD_direct' failed:
> Feb 17 20:34:42 server firewalld[19382]: ERROR: COMMAND_FAILED

**Comment by erig0** [comment]
The BROUTE table is not supported on ebtables version that are backed by nftables. As such, this support was dropped in firewalld in commit, 0e78dea21ffb03ea2e51df6158471b9cbd6652c9. v0.6.2 or later contains the changes. Please file a ticket with Debian to get the package updated.
