### ISSUE TITLE
masquerade source address in rich rule is ignored with nftables backend

### ISSUE THREAD

**Issue by danc86** [firewalld/firewalld#470]
If you add a rich rule to a zone, like this:

```
rule family="ipv4" source address="172.17.0.0/16" masquerade
```

with the nftables backend the masquerade is not limited to the given source network 172.17.0.0/16, even though the documentation indicates it should be.

In the nftables ruleset generated by firewalld I can see a `masquerade` rule is created in the right place:

```
	chain nat_POST_lan_allow {
		oifname != "lo" masquerade
	}
```

but it is missing a match for the given source. I would expect the nftables chain to have something like:

```
oifname != "lo" ip saddr 172.17.0.0/16 masquerade
```

**Comment by erig0** [comment]
@danc86, what version are you using? I think this fixed in aee4948e86fde6df8205b07f4da58e2a8c07377c, but has not been part of an official release yet.

**Comment by erig0** [comment]
Closing as I'm pretty sure it's already been fixed. Please comment if you find otherwise and I'll reopen.

**Comment by danc86** [comment]
Oh yes I am using the 0.6.3 release. Thanks for the info.
