### ISSUE TITLE
firewall-cmd.at test failing

### ISSUE THREAD

**Issue by seb128** [firewalld/firewalld#477]
The 0.6.3 testsuite is currently failing on Ubuntu, one of the problem is

```
src/src/tests/testsuite.dir/at-groups/49/stdout	2019-03-14 11:42:39.580094416 +0000
@@ -1,4 +1,4 @@
 -p IPv6 -j DROP
--p IPv6 --ip6-proto udp --ip6-sport ! 12345 -j DROP
+-p IPv6 --ip6-proto udp ! --ip6-sport 12345 -j DROP
 -j RETURN
 
49. firewall-cmd.at:729: 49. direct ebtables (firewall-cmd.at:729): FAILED (firewall-cmd.at:734)
```

**Comment by erig0** [comment]
Already fixed by 6ec2195e544dda2a923a0393bf463bf83593c322. It will be part of the next stable release.

ebtables upstream has since reverted this change in output syntax. So you can either wait on the firewalld fix, or a new ebtables version.

**Comment by seb128** [comment]
Wouldn't it make sense to revert that change from firewalld if the new ebtables was a bug and not wanted and got reverted? Otherwise you are going to get the reverse problem with your next tarball when an ebtables gets out.

**Comment by seb128** [comment]
Oh, and thanks for the commit reference, that's useful ;)

**Comment by seb128** [comment]
K, looking at the commit again I see it tries to do the right thing and adapt to the ebtables cases. 
It's a bit weird because our ebtables version does include http://git.netfilter.org/ebtables/commit/?id=ca223bf4 which it looks like should be what fixes the ordering issue? I'm going to try to backport the firewalld test fix and see how that goes

**Comment by erig0** [comment]
The change was introduced with `5f508b76a0ce ("ebtables: use extrapositioned negation consistently")` and reverted in commit `35b22e82fa62 ("Revert "ebtables: use extrapositioned negation consistently"")`.

The firewalld commit normalizes the ebtables output. The broken versions are out there and will continue to be out there. So we'll retain the output normalization in firewalld.
