### ISSUE TITLE
Error: remove-rich-rule fails to remove forward-port directive

### ISSUE THREAD

**Issue by instreest** [firewalld/firewalld#482]
An error occurred when I executed remove-rich-rule to remove forward-port directive.
>Error: %x format: a number is required, not NoneType

OS / ENVIRONMENT
CentOS Linux release 7.6.1810 (Core)
firewalld 0.5.3 (firewall-cmd --version)

The reproduction code is as follows.

```Shell
# firewall-cmd --permanent --add-rich-rule='rule family="ipv4" forward-port port="49152" protocol="tcp" to-port="49153"'
success
# firewall-cmd --reload
success
# firewall-cmd --remove-rich-rule='rule family="ipv4" forward-port port="49152" protocol="tcp" to-port="49153"'
Error: %x format: a number is required, not NoneType
```

I could avoid this as follows.

```Shell
# firewall-cmd --permanent --remove-rich-rule='rule family="ipv4" forward-port port="49152" protocol="tcp" to-port="49153"'
success
```

Does not reproduce the issue when not reloaded.

```Shell
# firewall-cmd --add-rich-rule='rule family="ipv4" forward-port port="49152" protocol="tcp" to-port="49153"'
success
# firewall-cmd --remove-rich-rule='rule family="ipv4" forward-port port="49152" protocol="tcp" to-port="49153"'
success
```

When I searched for a similar issue, I found Ansible issue.
but It has not been resolved.
[firewalld module fails to remove forwarding](https://github.com/ansible/ansible/issues/43025)

**Comment by erig0** [comment]
Thanks for reporting. I can reproduce this on the lastest master.

**Comment by instreest** [comment]
Thank you for your help!
