### ISSUE TITLE
firewall-cmd --reload hook or callback

### ISSUE THREAD

**Issue by hisorange** [firewalld/firewalld#483]
Hello guys!

Happy to see this cool project, I just want to ask about one small thing, some of our customers using firewalld and their sys admins often calls the __firewall-cmd --reload__ which causes a small issue for us, it seems like this command purges the iptables rules what we have added to it and we could not find a way to detect when this happens. 

Our software defines couple hundred rules and injects them into the iptables and we check the rules every 10 minute and time by time we find that our rules are deleted. Which is perfectly fine, but we would love to react faster to this issue, and looking into a way to see when they called the reload arg. 

Is there any callback or hook point where we could inject our execution into, or do you guys know any way to catch this event?

Thanks for the help!

**Comment by erig0** [comment]
> --reload ... purges the iptables rules what we have added to it and we could not find a way to detect when this happens.

Correct. On reload a full flush of firewalld rules occurs, followed by a reload of all rules.

> Is there any callback or hook point where we could inject our execution into, or do you guys know any way to catch this event?

Yes. Firewalld emits a dbus signal when a reload occurs. See man page FIREWALLD.DBUS(5), *Signals* section. Signal is `Reloaded()`.
