### ISSUE TITLE
XSD for services XML

### ISSUE THREAD

**Issue by traek** [firewalld/firewalld#488]
This isn't an issue per se but it would be nice to have the ability to ensure custom services conform to the documentation found at https://firewalld.org/documentation/man-pages/firewalld.service.

**Comment by erig0** [comment]
This can be verified by using the `--check-config` option.

```
# firewall-cmd --help |grep check-config
  --check-config       Check permanent configuration for errors

# firewall-offline-cmd --help |grep check-config
      --check-config   Check system and default configuration
```

**Comment by traek** [comment]
Sorry I wasn't more explicit in my request. The reason behind wanting an XSD is so I can author properly in the XML editor and have confidence it will pass said validation. I have a lot of these to do and often pull in XSDs when I'm doing large efforts like this. Since the XML spec already provides a mechanism for validating, I don't think this is an unreasonable request. In fact, I think it'd be an elegant solution if the check-config simply used an XSD (embedded or on disk) to do that check-config.

**Comment by ciez** [comment]
.xsd schema for any .xml document is very useful indeed as it helps to write correct .xml document rather than go through an iterative try & guess process.
