### ISSUE TITLE
Option to clamp MSS to pMTU

### ISSUE THREAD

**Issue by colmbuckley** [firewalld/firewalld#493]
In my experience, TCP connectivity issues can arise when a SNAT masquerade is applied between interfaces with different native MTUs (example: "internal" zone Ethernet with an MTU of 1500 or even 9000 vs. "external" PPP connection with MTU of 1492). The recognized option to address this is the "clamp-mss-to-pmtu" ability in Linux netfilter; however firewalld has no standard way to apply this to masqueraded connections.

A Direct rule like `firewall-cmd --permanent --direct --add-passthrough ipv4 -t mangle -I FORWARD -p tcp --syn -j TCPMSS --clamp-mss-to-pmtu` does work, but it would be cleaner to have this as an option (either a global option in firewalld.conf, or a per-interface configuration).

**Comment by colmbuckley** [comment]
The nftables equivalent is `nft add rule ip filter FORWARD oifname ppp0 tcp flags syn tcp option maxseg size set rt mtu` but of course there's no Direct support for nft rules yet.

**Comment by colmbuckley** [comment]
Here's how I'd see this working; if I have time to spend digging through the source I might be able to devise a prototype:

- Have an option `ClampMSStoPMTU` in `firewalld.conf` (I suggest defaulting to `True`)
- When building zone masquerade rules, if this option is **set**:
  - for ipXtables: add `-t mangle -A FORWARD -o interface -p tcp --syn -j TCPMSS --clamp-mss-to-pmtu`
  - for nftables: add `ip mangle FORWARD oifname interface tcp flags & (fin|syn|rst|ack) == syn tcp option maxseg size set rt mtu`

... replacing the interface test with whatever test is sufficient to identify traffic to this zone. If this is complex, I think it would be sufficient to just put a single rule in the mangle table affecting all interfaces. Not 100% sure if the top-level mangle table is the best place for it, or if we should use one of the mangle chains in the firewalld table.

**Comment by colmbuckley** [comment]
The `build_default_rules` functions are bit intimidating; could possibly do with a bit of refactoring. When we have FORWARD chains (either in filter_ or mangle_) I guess we need to set up both the input and output zones and sources chains. Actually adding the tcpmss option to these chains is fairly easy.

I don't have a huge amount of time to spend on this, unfortunately.

**Comment by elajoie** [comment]
Implementing this now in a home router setup.  Any progress I can sign up to test?

Your workaround is still working great in RHEL 8.1.

**Comment by erig0** [comment]
> Implementing this now in a home router setup. Any progress I can sign up to test?

No. It's not being actively developed.

**Comment by colmbuckley** [comment]
Yeah; the --direct rule should continue to work, as long as iptables emulation continues to work well in nftables.

@erig0 Are you planning any ability to directly add **nftables** rules, as opposed to iptables syntax?

**Comment by erig0** [comment]
> @erig0 Are you planning any ability to directly add **nftables** rules, as opposed to iptables syntax?

No. I'd rather enhance rich rules. IMO, exposing direct access to the underlying firewall backend defeats the purpose of being an abstraction. In the future firewalld may support other backends (e.g. ebpf).

**Comment by elajoie** [comment]
Do we have a way via rich rules to do this today when using nft underneath?

**Comment by colmbuckley** [comment]
The existing iptables emulation in nftables allows it to work properly; at least in my Debian install.

**Comment by elajoie** [comment]
I'll keep using what you proposed "ip mangle FORWARD tcp flags syn tcp option maxseg size set rt mtu" for a Linux router guide I'm working on.  I'd love to hear from you guys if another way comes to exists which is more elegant or future proof.

**Comment by erig0** [comment]
> Do we have a way via rich rules to do this today when using nft underneath?

No. That's why this issue remains open.

**Comment by colmbuckley** [comment]
Just to clarify something: on Debian at least, if nftables is installed without iptables, nftables is configured to emulate iptables, and translate iptables rules into nft rules. In particular, the `-p tcp --syn -j TCPMSS --clamp-mss-to-pmtu` iptables rule is correctly translated to a suitable nftables rule.

I don't know whether this also works on RHEL.

**Comment by barinet** [comment]
I'm using "meta oiftype ppp tcp flags syn tcp option maxseg size set rt mtu" in "inet filter forward". I'm using a script to insert it into filter_FORWARD_IN_ZONES whenever firewalld reloads, because I need to insert other rules too, but I think you could simply put this one in nftables.conf, since firewalld tables will run after the default priority ones.

**Comment by MartB** [comment]
When is this going to end up in a release?

See: https://firewalld.org/2020/10/tcp-mss-clamp

**Comment by erig0** [comment]
@MartB, I try to do feature releases every six months. However, the items for the next release, v1.0.0, are not yet complete.

You can see v1.0.0 status on the project board: https://github.com/orgs/firewalld/projects/1#card-34560478

**Comment by MartB** [comment]
@erig0 i might have missed the word `feature` in the link i provided.
Sorry for the noise, thanks for your work!

Kind regards
