### ISSUE TITLE
firewalld Error: INVALID_MAC: when adding rich rule 

### ISSUE THREAD

**Issue by compadvance** [firewalld/firewalld#494]
When trying to block this MAC E0:07:1B:FF:FA:EF:84:16:F9:2B:78:3D:08:00 using --add-rich-rule to the zone I am having error that this MAC is invalid ! 
am I missing something or its a bug , thanks for any suggestions

**Comment by erig0** [comment]
That's because the MAC is invalid. MAC addresses are 48 bits long (6 bytes).
```
E0:07:1B:FF:FA:EF:84:16:F9:2B:78:3D:08:00
|----- MAC 1 ----|----- MAC 2 -----|- ETH_TYPE -|
  (desination)      (source)
```
