### ISSUE TITLE
0.5: firewall-cmd --reload Error: reverse_rule() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by mdone-cloudian** [firewalld/firewalld#495]
We're testing CentOS-7.6 (that's why the old-ish version) on containers, and we're getting this:

```
# firewall-cmd --reload
Error: reverse_rule() takes exactly 2 arguments (1 given)
```

The background issue is that `firewalld` fails to apply the changes, and when it tries to rollback, it calls `reverse_rules()`. This *function* is [defined](https://github.com/firewalld/firewalld/blob/stable-0.5/src/firewall/core/ipXtables.py#L498) like one usually defines *methods* in Python:

```python
def reverse_rule(self, args):
```

In fact, `self` is not used at all in that function, so I guess it's a force-of-habit thing.

**Comment by mdone-cloudian** [comment]
I reported this in CentOS's bug tracker: https://bugs.centos.org/view.php?id=16203

**Comment by erig0** [comment]
This has been fixed since v0.6.0, see commit 1fea41d5e8d806db5c2380cffde13059d9fa9e7a.

**Comment by mdone-cloudian** [comment]
Could this be backported to 0.5 or is it not maintained any longer?

**Comment by erig0** [comment]
0.5 is no longer maintained. 0.6.x and 0.7.x are the current active releases.

**Comment by mdone-cloudian** [comment]
Ok, tahnks for the info.
