### ISSUE TITLE
'Active bindings' part of UI is not working

### ISSUE THREAD

**Issue by yrro** [firewalld/firewalld#499]
Under "active bindings" I see an indented entry for my currently active
network conection. On the row beneath is a duplicate of this entry, but
clicking on it doesn't do anything. And if I move the mouse into this
entry from beneath, it changes to say "Sources" instead.

At the same time, `firewall-config` outputs the following:

    (firwall-config:12867): Gtk-WARNING **: 14:36:45.228: Failed to set
    text from markup due to error parsing markup: Unknown tag
    'interface' on line 1 char 20

In the Options → Change Zones of Connections... menu, there's a menu
entry called `<interface>` in the same position as the faulty item in
"active bindings".

I guess `<interface>` is a string replacement that isn't happening, and
Gtk is trying to interpret that as Pango markup.

I've seen this with 0.6.3 and 0.7.0 on Debian and 0.6.4 on Fedora.

**Comment by thom311** [comment]
> (firwall-config:12867): Gtk-WARNING **: 14:36:45.228: Failed to set
text from markup due to error parsing markup: Unknown tag
'interface' on line 1 char 20

this is an actual bug, not a translation problem. Whatever text there is, it must not be interpreted as markup.

The PR #500 addresses the symptom, not the cause.

**Comment by yrro** [comment]
I agree, all text added to the bindings store must be escaped, since the cell renderer is told to interpret column 0 as markup, not as text.
