### ISSUE TITLE
Possible memory leak in firewall-applet?

### ISSUE THREAD

**Issue by aidanharris** [firewalld/firewalld#502]
![Screenshot from 2019-07-28 10:17:22](https://user-images.githubusercontent.com/3309784/62004850-e8d3bc80-b119-11e9-9405-6e4325e1e401.png)

Is this a known issue (using firewalld 0.6.3 when I see that the latest release is 0.7.1 so it's possible some changes have been made since)?

**Comment by erig0** [comment]
It's not a known issue. It's odd that you have multiple instances of firewall-applet running. If you can reproduce on a recent version then please reopen this issue.
