### ISSUE TITLE
firewalld and Docker chains

### ISSUE THREAD

**Issue by till** [firewalld/firewalld#503]
First off, let me say that I'm a fan of firewalld. Configuration is nice, even for people like myself who don't consider themselves cracks at it — zones, services, sources — easy to grasp! 🎉

---

We have a different "play nice" issue (#461) with firewalld and Docker. I wanted to create a new ticket, but allow me to explain:

 - we have a swarm cluster deployed (2 nodes, 1 manager, 1 worker)
 - we run our deployments on CentOS7 with Ansible (a mix of `firewalld` and `iptables` modules right now, see 👇 )
 - whenever we make a change via Ansible to firewalld and run `firewall-cmd --reload`, the `DOCKER-INGRESS` chain is gone

Log messages:

```
firewalld[3418]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -nL DOCKER-INGRESS' failed: iptables: No chain/target/match by that name.
firewalld[3418]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -nL DOCKER-INGRESS' failed: iptables: No chain/target/match by that name.
firewalld[3418]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -C DOCKER-INGRESS -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
firewalld[3418]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w2 -t filter -C DOCKER-INGRESS -j RETURN' failed: iptables: Bad rule (does a matching rule exist in that chain?).
```

This is similar to problems with `DOCKER-USER` which also gets wiped when we reload firewalld. I don't want to blame either piece of software — Docker or firewalld for the record.

But is there a way to honour or ignore these chains? I know firewalld is an abstraction on top of iptables and what we did so far was then put rules back into the required chain when necessary, but this approach is very service specific and doesn't scale too well.

Another _solution_ (probably also mentioned already in other tickets) is to restart Docker, and let it re-init itself with the designated chains. This approach is only slightly better. Better, because we don't seem to have to maintain service specific configurations in firewalls, but also worse, because it means downtime of our containers.

**Comment by erig0** [comment]
We recently stopped throwing logs for "check" type passthrough commands, 7662061f1640a0b635ef693dd505a293773f6e2f. But I think this simple check will fail to mask the log in your case because of the "-nL" (as opposed to "-n -L").

**Comment by erig0** [comment]
FWIW, podman seems to integrate with firewalld better than docker.

**Comment by till** [comment]
@erig0 Not entirely sure what you mean "masking the log"? More interested in how to preserve existing chains which are done _outside_ firewalld.

RE: Podman — We're aware of it. Another interesting albeit young project. We're currently using Docker Compose & Docker Swarm extensively, there's no simple way to achieve this with Podman yet. For k8s this a different story.

**Comment by erig0** [comment]
> @erig0 Not entirely sure what you mean "masking the log"? More interested in how to preserve existing chains which are done _outside_ firewalld.

By "masking the log" I mean that firewalld will not generate a log if docker (or other program) is using the iptables "-C" or "-L" options in the direct interface calls. "-C" and "-L" are query type commands, so the log doesn't make sense.

As far as preserving the existing chains outside of firewalld, we can't really change that with the iptables backend. However, the nftables backend does limit rule updates/flushes/deletes to the firewalld table/namespace, but docker doesn't play well with firewalld (see #461).

**Comment by till** [comment]
@erig0 Thanks, Eric. Appreciate the input. I'll have a look at `nftables` first this week. And thanks for the hint about the `trusted` zone.

Btw, with `firewalld`and `iptables` in the mix, the last resort is to always restart `dockerd`. So there's that, but that can have an impact to our platform/customers.

**Comment by AntoCanza** [comment]
@erig0 thanks for infos.
i was wondering if there is also the possibility to Trust the network address. let me explain bit better.
I'm installing docker into:
```shell
[antonio@192 ~]$ cat /etc/centos-release
CentOS Linux release 8.1.1911 (Core)

[antonio@192 ~]$ sudo firewall-cmd --version
0.7.0

[antonio@192 ~]$ sudo docker --version
Docker version 19.03.11, build 42e35e61f3
```

if i run:
```shell
docker run busybox ping -c 10 google.com
```
the ping isn't working, as soon as i do:
```shell
firewall-cmd --permanent --zone=trusted --change-interface=docker0
firewall-cmd --complete-reload
systemctl restart docker
```

now, if we have a more complex app, with many networks defined into docker-compose.yml files we can see that the interface name is auto generated at run time (example: br-f208abd8081b). 

if i try to apply rules with:
```shell
firewall-cmd --permanent --zone=trusted --add-rich-rule='rule family=ipv4 source address=172.20.0.0/16 accept'
```
or
```shell
firewall-cmd --permanent --zone=trusted --add-rich-rule='rule family=ipv4 source address=172.0.0.0/8 accept'
```

containers that are using that network are not able to communicate, is there a way to apply rules on the network address and make docker run correctly?
the id br-something will be different any time that the docker-compose down and docker-compose up commands are fired.

**Comment by erig0** [comment]
@AntoCanza, docker (moby) recently gained some firewalld integration. See moby/libnetwork#2548. I think this will address your issue.

**Comment by monreal** [comment]
Changing FirewallBackend in /etc/firewalld/firewalld.conf to iptables seems to be a workaround for now.

**Comment by delfer** [comment]
Debian GNU/Linux 10 (buster)
Docker Engine - Community 19.03.8
iptables v1.8.2 (nf_tables)
firewalld 0.6.3-5

I'm also got

```
ERROR: Failed to program NAT chain: Failed to inject DOCKER in PREROUTING chain: iptables failed: iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER: iptables v1.8.2 (nf_tables): Chain 'DOCKER' does not exist
```

This is because I've installed firewalld and didn't restart the Docker daemon.
`systemctl restart docker` helps
