### ISSUE TITLE
"systemctl reload" does not bring into effect permanent rules

### ISSUE THREAD

**Issue by yxorp** [firewalld/firewalld#505]
I am setting permanent rules whilst firewalld is active and running, this is done using the _--permanent_ flag. Once I've set all my rules I want them to become active. I understand that firewalld has two levels of configuration, that is run-time and permanent. From what I understood the firewalld documentation states that a _systemctl reload_ of _firewalld_ would bring permanent rules into effect but this is not the case. I am having to use _systemctl restart_ to achieve this.

I feel like this may be a bug. 

OS: CentOS Linux release 7.6.1810 (Core)
firewalld version: firewalld-0.5.3-5.el7.noarch

**Comment by erig0** [comment]
Unless you provide an example we have no way to produce. It seems to be working on my end.

**Comment by yxorp** [comment]
Just checked the default _firewalld.conf_ on my machine and it seems like it does not have the `FlushAllOnReload` configuration. So I presume this is the intended behaviour without that configuration enabled. Will close as notabug.
