### ISSUE TITLE
Create rpfilter rules for ipv4

### ISSUE THREAD

**Issue by yrro** [firewalld/firewalld#506]
I believe firewalld should configure `rpfilter` rules for IPv4 like it already does for IPv6.

As a remote worker, I connect to my office network with a VPN. Unknown to me, a machine on my home network has been taken over by an attacker. The attacker is able to use a tool like Scapy to craft a packet with a source address on my work network, and sent it to my laptop. The packet is received on an interface in the `home` network.

The packet is not dropped by the kernel outright, because `rp_filter` is set to 2 ("loose") filtering on Fedora (and not enabled at all on Debian). It is accepted for forwarding because the interface's `forwarding` sysctl is enabled (I don't know by what...) And, I guess because I have Docker, Libvirt and LXC installed, the global `ip_forward` sysctl has been enabled (for my convenience :smile:). And so the kernel happily retransmits the malicious packet to my work network.

I believe the average user, who is not (knowingly 😉) building a router out of their Linux system, is better off if firewalld protects them from malicious ipv4 packets as it already does with ipv6.

I think it's out of scope to touch either the `rp_filter` or `ip_forward` kernel parameters; far too many other programs already mess around with them and there's no guarantee, particularly in the case of `ip_forward`, that they would stay set.

Currently I've created the following direct rules to mimic what I'd like to see firewalld doing:

```
<direct>
  <rule ipv="ipv4" table="raw" chain="PREROUTING" priority="0">-m rpfilter --invert -j LOG --log-level 4 --log-prefix 'rpfilter_DROP: '</rule>
  <rule ipv="ipv4" table="raw" chain="PREROUTING" priority="1">-m rpfilter --invert -j DROP</rule>
</direct>
```

I'm happy to have a go at implementing this properly in firewalld myself, if you would accept the feature.

**Comment by yrro** [comment]
PR ready for review

**Comment by yrro** [comment]
FYI, I had a version of this that changed the IPv{4,6}_rpfilter options to take "off", "loose", "strict" so that the user could choose what level of isolation they want. But it breaks the API since those properties are no longer exposed as booleans but strings, and in any case it appears that the nftables backend implementing loose mode was an oversight rather than desired behaviour.

**Comment by erig0** [comment]
> FYI, I had a version of this that changed the IPv{4,6}_rpfilter options to take "off", "loose", "strict" so that the user could choose what level of isolation they want. But it breaks the API 

See #1339.

**Comment by yrro** [comment]
#1339 will definitely make this easier, thanks for pointing me that way.

I've not worked on this PR for a long time.  I'm going to close this PR for the time being, because switching IPv4 reverse path filtering over to being handled by xtables is probably a change you'd want to consider carefully before merging, and it's just cluttering up your list of PRs in the mean time. :)
