### ISSUE TITLE
no change to ruleset after IPv6 disabled system-wide

### ISSUE THREAD

**Issue by jshand2015** [firewalld/firewalld#508]
i have added the command ipv6.disable=1 to grub settings and i have found that ipv6 no longer exists system-wide.  however, when i check the nft list ruleset, i find that ipv6 rules are still active.  just a note.  i have no internet connection issues at all

**Comment by erig0** [comment]
It's a not causing any harm. The ipv6 rules won't match. firewalld _could_ avoid generating those IPv6 rules, but it's not worth it in my opinion.

Out of curiosity, why are you disabling IPv6?

**Comment by dirtyharrycallahan** [comment]
A common reason is for security. Disable features not used to shrink the attack surface or until a mitigation strategy is in place.

**Comment by erig0** [comment]
This is not worth the added complexity. The nft rules are harmless. An alternative is to use the iptables `FirewallBackend`. In that case the ip6tables rules will not be added.
