### ISSUE TITLE
firewall-cmd --reload or --complete-reload does not load permanent config

### ISSUE THREAD

**Issue by james-oconnor-opengear** [firewalld/firewalld#511]
We are directly writing to the config for the firewall zone to both add and remove an interface.  Calling firewall-cmd --reload or --complete-reload does not load the permanent config for the zones to the runtime config.  After  --complete-reload you see the changes with the --permanent flag  for:
 # firewall-cmd --list-all --zone=wan
but without it the zone interfaces will still be unchanged.

Also we have tried using the SIGHUP instead, but only with the same effect.

The only way so far has been to reload the firewalld service, but your documentation reads like the --reload should work.  Is this just a misunderstanding and we will need to always restart the service if we do not want to update the runtime configuration first, then push it to the permanent config?

# firewall-cmd --version
0.6.3

zone config:
`<zone>
  <short>WAN</short>
  <description>Untrusted connections from the Wide Area Network</description>
  <interface name="net2"/>
  <interface name="wwan0"/>
  <service name="ssh"/>
  <service name="https"/>
  <service name="dhcpv6-client"/>
  <service name="ssh_serial01"/>
</zone>`

**Comment by erig0** [comment]
I think you're hitting old behavior of firewalld that caused it to retain interface to zone bindings during a reload. This behavior changed in v0.7.0 so those assignments are wiped and the ones from the permanent configuration are used.

See `FlushAllOnReload` from commit 242bc4e2e20c6944164fe2495598982b1cfcc4fe and mentioned in the [v0.7.0 release notes](https://firewalld.org/2019/06/firewalld-0-7-0-release).
