### ISSUE TITLE
src/tests/atconfig not cleaned up on "make clean"

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#523]
When running `make check`, the build system creates `src/tests/atconfig`.
This file should be cleaned up when running `make clean`

**Comment by mbiebl** [comment]
```
$ ls src/tests/atconfig
ls: cannot access 'src/tests/atconfig': No such file or directory
$ ./configure
...
$ ls -la src/tests/atconfig    
-rw-r--r-- 1 michael michael 731 Oct  8 21:46 src/tests/atconfig

$ make clean
$ ls -la src/tests/atconfig 
-rw-r--r-- 1 michael michael 731 Oct  8 21:46 src/tests/atconfig

$ make distclean
$ ls -la src/tests/atconfig 
-rw-r--r-- 1 michael michael 731 Oct  8 21:46 src/tests/atconfig
```

**Comment by erig0** [comment]
Right. We should either fully ship a working testsuite with "make dist" as advised by the autoconf docs [1] or we should not ship anything and require a ./configure. This applies to; `testsuite`, `package.m4`, `atconfig`.

[1] https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/Making-testsuite-Scripts.html

**Comment by erig0** [comment]
> Right. We should either fully ship a working testsuite with "make dist" as advised by the autoconf docs [1]

I'm working on this, btw.
