### ISSUE TITLE
How to accept traffic from direct rules using nftables backend

### ISSUE THREAD

**Issue by AdmiralNemo** [firewalld/firewalld#527]
With the new _nftables_ backend, there does not seem to be a straightforward way to accept packets in a direct rule (or a rule created in another table by `nft`).

I have a situation where I can only accept traffic that is protected with IPsec/ESP.  To accomplish this, I previously added a direct rule like this:

     firewall-cmd --direct --add-rule ipv4 filter INPUT 10 -m policy --pol ipsec --dir in -m tcp -p tcp --dport 50505 -j ACCEPT

This no longer works because packets marked as ACCEPT by `iptables` rules are ultimately still rejected by rules in `nftables`.

I can work around this by creating another direct rule to drop traffic on that port, and then adding the port to firewalld:

    firewall-cmd --direct --add-rule ipv4 filter INPUT 20 -m tcp -p tcp --dport 50505 -j REJECT
    firewall-cmd --add-port 50505/tcp

This is cumbersome, requiring 3 rules where only 1 was necessary before.

Besides this workaround, or switching the `FirewallBackend` to `iptables`, do I have any other options?  Will there ever be a way to inject native nftables rules, akin to the direct interface?

**Comment by erig0** [comment]
This is a result of how netfilter in the kernel works. There is nothing we can do. See Behavioral Change "Packet accept/drop precedence" in [this post](https://firewalld.org/2018/07/nftables-backend).

You're only option is to also allow the traffic through firewalld via non-direct rules (--add-port, rich rule, etc)

**Comment by erig0** [comment]
> Will there ever be a way to inject native nftables rules, akin to the direct interface?

No plan. I think it's a better investment it expand rich rules feature set.

**Comment by erig0** [comment]
> > This is a result of how netfilter in the kernel works. There is nothing we can do. See Behavioral Change "Packet accept/drop precedence" in [this post](https://firewalld.org/2018/07/nftables-backend).
> 
> Yes, I understand how that works. I've seen that post. It's not helpful.

If the post helped you understand, then I'd consider it helpful.

> > You're [sic] only option is to also allow the traffic through firewalld via non-direct rules (--add-port, rich rule, etc)
> 
> These are severely limited, and do not offer anywhere close to the functionality I was using in previous versions of firewalld. This is a pretty serious regression in functionality, to the point where I am not sure what benefit firewalld even offers now.

You're welcome to use the iptables backend. It's still supported.

**Comment by mohag** [comment]
IS there a way to allow all forwarded traffic for interfaces matching a wildcard with the nft backend?

E.g. this:
`firewall-cmd --direct --add-rule ipv4 filter FORWARD 99 -i cali+ -j ACCEPT`

(those interfaces are constantly dynamically created)

I could not find a way to do that without a direct rule.

**Comment by erig0** [comment]
> IS there a way to allow all forwarded traffic for interfaces matching a wildcard with the nft backend?

Yes. Use a policy.

```
# firewall-cmd --permanent --new-policy allowAllFwd
# firewall-cmd --permanent --policy allowAllFwd --add-ingress-zone cali+
# firewall-cmd --permanent --policy allowAllFwd --add-egress-zone ANY
# firewall-cmd --permanent --policy allowAllFwd --set-target ACCEPT
# firewall-cmd --reload
```

**Comment by rgaduput** [comment]
> > IS there a way to allow all forwarded traffic for interfaces matching a wildcard with the nft backend?
> 
> Yes. Use a policy.
> 
> ```
> # firewall-cmd --permanent --new-zone cali
> # firewall-cmd --permanent --zone cali --add-interface cali+
> 
> # firewall-cmd --permanent --new-policy allowAllFwd
> # firewall-cmd --permanent --policy allowAllFwd --add-ingress-zone cali
> # firewall-cmd --permanent --policy allowAllFwd --add-egress-zone ANY
> # firewall-cmd --permanent --policy allowAllFwd --set-target ACCEPT
> # firewall-cmd --reload
> ```
@erig0 @mohag 
I have used this policy approach to replace below direct rules but i still see that traffic being dropped by firewall without forwarding to `cali+` interfaces. 
Any suggestions to fix it ?

```
firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 99 -i cali+ -j ACCEPT
firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 99 -o cali+ -j ACCEPT
```

```
[173544.177749] filter_FWD_public_REJECT: IN=eth0 OUT=cali38950864fb7 MAC=02:00:0a:71:20:3c:02:00:0a:71:20:bf:08:00 SRC=10.113.32.191 DST=10.244.249.65 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=43332 DF PROTO=TCP SPT=53652 DPT=9443 WINDOW=32120 RES=0x00 SYN URGP=0 MARK=0x10000
[173581.031862] filter_FWD_public_REJECT: IN=eth0 OUT=cali38950864fb7 MAC=02:00:0a:71:20:3c:02:00:0a:71:20:bf:08:00 SRC=10.113.32.191 DST=10.244.249.65 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=31197 DF PROTO=TCP SPT=35148 DPT=9443 WINDOW=32120 RES=0x00 SYN URGP=0 MARK=0x10000
```

**Comment by mohag** [comment]
> > > IS there a way to allow all forwarded traffic for interfaces matching a wildcard with the nft backend?
> 
> @erig0 @mohag I have used this policy approach to replace below direct rules but i still see that traffic being dropped by firewall without forwarding to `cali+` interfaces. Any suggestions to fix it ?

What mostly works for figuring out what is messing with the traffic is some nftables tracing: (You van filter the trace a bit more as well)
```
nft add chain ip filter trace_chain { type filter hook prerouting priority -1\; }
nft add rule ip filter trace_chain meta nftrace set 1
```
and then `nft monitor trace`

My current config for Calico (parts in Ansible format....) (for kubeadm managed kubernetes):
- Create services for: typha (5473/tcp), vxlan (4789/udp) and ip-in-ip (ip protocol ipv4 / ipencap from /etc/protocols, depending on distro).
- Create ipsets for control plane and worker nodes ([I use this for services and ipsets](https://blog.mohag.net/2018/05/managing-firewalld-ipsets-and-services.html))
- Open ip-in-ip, vxlan (for ipv6) and typha within cluster:
```yaml
- name: IP-in-IP for Calico
  ansible.posix.firewalld:
    rich_rule: rule service name="ip-in-ip" source ipset="{{ item }}" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - kubernetes-control-plane-ipv4
  - kubernetes-control-plane-ipv6
  - kubernetes-worker-ipv4
  - kubernetes-worker-ipv6
- name: VxLAN for Calico IPv6
  ansible.posix.firewalld:
    rich_rule: rule service name="vxlan" source ipset="{{ item }}" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - kubernetes-control-plane-ipv4
  - kubernetes-control-plane-ipv6
  - kubernetes-worker-ipv4
  - kubernetes-worker-ipv6
- name: Typha for Calico
  ansible.posix.firewalld:
    rich_rule: rule service name="typha" source ipset="{{ item }}" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - kubernetes-control-plane-ipv4
  - kubernetes-control-plane-ipv6
  - kubernetes-worker-ipv4
  - kubernetes-worker-ipv6
```
- Open the forward rules (skipping the pre-firewalld ones here) via adding stuff to trusted zone:
```yaml
- name: check for preexisting interface to trusted zone allocation on jammy
  ansible.builtin.command:
    argv:
    - firewall-cmd
    - --list-interfaces
    - --zone=trusted
  register: _check
  changed_when: false

- name: Calico - FirewallD inter-operation - jammy
  block:
    - name: Add calico interfaces to trusted zone (immediate)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --change-zone=cali+
        - --zone=trusted

    - name: Add calico vxlan interfaces to trusted zone (immediate)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --change-zone=vxlan-v6.calico
        - --zone=trusted

    - name: Add tunl0 interface to trusted zone (immediate)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --change-zone=tunl0
        - --zone=trusted

    - name: Add calico interfaces to trusted zone (permanent)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --permanent
        - --change-zone=cali+
        - --zone=trusted

    - name: Add calico vxlan interfaces to trusted zone (permanent)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --permanent
        - --change-zone=vxlan-v6.calico
        - --zone=trusted

    - name: Add tunl0 interfaces to trusted zone (permanent)
      ansible.builtin.command:
        argv:
        - firewall-cmd
        - --permanent
        - --change-zone=tunl0
        - --zone=trusted
  when:
  - not 'cali+' in _check.stdout or not 'tunl0' in _check.stdout or not 'vxlan-v6.calico' in _check.stdout
```
I suspect you are missing tunl0 or the vxlan interfaces.... (I'm not using vxlan on ipv4, so I don't have the rules for that)

**Comment by rgaduput** [comment]
thank you @mohag . 
I have tried adding `cali+` and `tul0` into `trusted` zone (I do not have vxlan usage), but still it did not help for some reason.
When i try to perform the tracing I see that it does go through all relevant chains but end up rejected by `filter_FWD_public_REJECT`.
If i add `cali+` into `public` zone it does work But I can't have it as `public` zone because its purpose is different. (I am new to it, trying to understand the flow better)

```
firewall-cmd --info-zone=trusted
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: cali+ tunl0
  sources:
  services:
  ports:
  protocols:
  forward: yes
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```


<details>
<summary>nft monitor trace</summary>


```
trace id cb6bc762 ip filter trace_chain packet: iif "eth0" ether saddr 02:00:0a:71:20:3b ether daddr 02:00:0a:71:20:2e ip saddr 10.244.19.246 ip daddr 10.244.173.131 ip dscp cs0 ip ecn not-ect ip ttl 63 ip id 44107 ip length 60 tcp sport 11928 tcp dport 53 tcp flags == syn tcp window 33120
trace id cb6bc762 ip filter trace_chain rule meta nftrace set 1 (verdict continue)
trace id cb6bc762 ip filter trace_chain rule meta nftrace set 1 (verdict continue)
trace id cb6bc762 ip filter trace_chain policy accept
trace id cb6bc762 inet firewalld filter_PREROUTING packet: iif "eth0" ether saddr 02:00:0a:71:20:3b ether daddr 02:00:0a:71:20:2e ip saddr 10.244.19.246 ip daddr 10.244.173.131 ip dscp cs0 ip ecn not-ect ip ttl 63 ip id 44107 ip protocol tcp ip length 60 tcp sport 11928 tcp dport 53 tcp flags == syn tcp window 33120 
trace id cb6bc762 inet firewalld filter_PREROUTING rule meta nfproto ipv6 fib saddr . mark . iif oif missing log prefix "rpfilter_DROP: " drop (verdict continue)
trace id cb6bc762 inet firewalld filter_PREROUTING policy accept 
trace id cb6bc762 ip mangle FORWARD packet: iif "eth0" oif "calib0f36ec04d7" ether saddr 02:00:0a:71:20:3b ether daddr 02:00:0a:71:20:2e ip saddr 10.244.19.246 ip daddr 10.244.173.131 ip dscp cs0 ip ecn not-ect ip ttl 62 ip id 44107 ip length 60 tcp sport 11928 tcp dport 53 tcp flags == syn tcp window 33120 
trace id cb6bc762 ip mangle FORWARD policy accept 
trace id cb6bc762 ip filter FORWARD packet: iif "eth0" oif "calib0f36ec04d7" ether saddr 02:00:0a:71:20:3b ether daddr 02:00:0a:71:20:2e ip saddr 10.244.19.246 ip daddr 10.244.173.131 ip dscp cs0 ip ecn not-ect ip ttl 62 ip id 44107 ip length 60 tcp sport 11928 tcp dport 53 tcp flags == syn tcp window 33120 
trace id cb6bc762 ip filter FORWARD rule  counter packets 296598 bytes 47535301 jump cali-FORWARD (verdict jump cali-FORWARD)
trace id cb6bc762 ip filter cali-FORWARD rule  counter packets 296666 bytes 47539381 meta mark set mark and 0xfff1ffff (verdict continue)
trace id cb6bc762 ip filter cali-FORWARD rule  mark and 0x10000 == 0x0 counter packets 296666 bytes 47539381 jump cali-from-hep-forward (verdict jump cali-from-hep-forward)
trace id cb6bc762 ip filter cali-FORWARD rule oifname "cali*"  counter packets 157155 bytes 14960144 jump cali-to-wl-dispatch (verdict jump cali-to-wl-dispatch)
trace id cb6bc762 ip filter cali-to-wl-dispatch rule oifname "calib0f36ec04d7"  counter packets 77412 bytes 7371873 goto cali-tw-calib0f36ec04d7 (verdict goto cali-tw-calib0f36ec04d7)
trace id cb6bc762 ip filter cali-tw-calib0f36ec04d7 rule  counter packets 34416 bytes 3263792 meta mark set mark and 0xfffeffff (verdict continue)
trace id cb6bc762 ip filter cali-tw-calib0f36ec04d7 rule  counter packets 34416 bytes 3263792 jump cali-pri-kns.kube-system (verdict jump cali-pri-kns.kube-system)
trace id cb6bc762 ip filter cali-pri-kns.kube-system rule   counter packets 68574 bytes 6503474 meta mark set mark or 0x10000 (verdict continue)
trace id cb6bc762 ip filter cali-pri-kns.kube-system rule  mark and 0x10000 == 0x10000 counter packets 68574 bytes 6503474 return (verdict return)
trace id cb6bc762 ip filter cali-tw-calib0f36ec04d7 rule   mark and 0x10000 == 0x10000 counter packets 34416 bytes 3263792 return (verdict return)
trace id cb6bc762 ip filter cali-FORWARD rule  counter packets 69093 bytes 6537943 jump cali-to-hep-forward (verdict jump cali-to-hep-forward)
trace id cb6bc762 ip filter cali-FORWARD rule  counter packets 69093 bytes 6537943 jump cali-cidr-block (verdict jump cali-cidr-block)
trace id cb6bc762 ip filter FORWARD rule ct state new  counter packets 69026 bytes 6533923 jump KUBE-PROXY-FIREWALL (verdict jump KUBE-PROXY-FIREWALL)
trace id cb6bc762 ip filter FORWARD rule  counter packets 69026 bytes 6533923 jump KUBE-FORWARD (verdict jump KUBE-FORWARD)
trace id cb6bc762 ip filter KUBE-FORWARD rule  ct state related,established counter packets 0 bytes 0 accept (verdict continue)
trace id cb6bc762 ip filter FORWARD rule ct state new  counter packets 69026 bytes 6533923 jump KUBE-SERVICES (verdict jump KUBE-SERVICES)
trace id cb6bc762 ip filter KUBE-SERVICES rule meta l4proto tcp ip daddr 10.105.70.36  tcp dport 50002 counter packets 0 bytes 0 reject (verdict continue)
trace id cb6bc762 ip filter FORWARD rule ct state new  counter packets 69026 bytes 6533923 jump KUBE-EXTERNAL-SERVICES (verdict jump KUBE-EXTERNAL-SERVICES)
trace id cb6bc762 ip filter KUBE-EXTERNAL-SERVICES rule meta l4proto tcp  fib daddr type local tcp dport 32256 counter packets 0 bytes 0 drop (verdict continue)
trace id cb6bc762 ip filter FORWARD rule   mark and 0x10000 == 0x10000 counter packets 69025 bytes 6533863 accept (verdict accept)
trace id cb6bc762 inet firewalld filter_FORWARD packet: iif "eth0" oif "calib0f36ec04d7" ether saddr 02:00:0a:71:20:3b ether daddr 02:00:0a:71:20:2e ip saddr 10.244.19.246 ip daddr 10.244.173.131 ip dscp cs0 ip ecn not-ect ip ttl 62 ip id 44107 ip protocol tcp ip length 60 tcp sport 11928 tcp dport 53 tcp flags == syn tcp window 33120 
trace id cb6bc762 inet firewalld filter_FORWARD rule jump filter_FORWARD_ZONES (verdict jump filter_FORWARD_ZONES)
trace id cb6bc762 inet firewalld filter_FORWARD_ZONES rule iifname "eth0" goto filter_FWD_public (verdict goto filter_FWD_public)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FORWARD_POLICIES_pre (verdict jump filter_FORWARD_POLICIES_pre)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FWD_public_pre (verdict jump filter_FWD_public_pre)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FWD_public_log (verdict jump filter_FWD_public_log)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FWD_public_deny (verdict jump filter_FWD_public_deny)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FWD_public_allow (verdict jump filter_FWD_public_allow)
trace id cb6bc762 inet firewalld filter_FWD_public_allow rule oifname "eth0" accept (verdict continue)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FWD_public_post (verdict jump filter_FWD_public_post)
trace id cb6bc762 inet firewalld filter_FWD_public rule jump filter_FORWARD_POLICIES_post (verdict jump filter_FORWARD_POLICIES_post)
trace id cb6bc762 inet firewalld filter_FWD_public rule log prefix "filter_FWD_public_REJECT: " (verdict continue)
trace id cb6bc762 inet firewalld filter_FWD_public rule reject with icmpx admin-prohibited (verdict drop)   
```



</details>

**Comment by mohag** [comment]
> thank you @mohag . I have tried adding `cali+` and `tul0` into `trusted` zone (I do not have vxlan usage), but still it did not help for some reason. When i try to perform the tracing I see that it does go through all relevant chains but end up rejected by `filter_FWD_public_REJECT`. If i add `cali+` into `public` zone it does work But I can't have it as `public` zone because its purpose is different. (I am new to it, trying to understand the flow better)

The zone name should be in the "chain" / rule... name... There is "public" in there currently (maybe due to it entering on eth0....)

Some blank entries removed.
```
root@rancher1 ~ # firewall-cmd --info-zone=trusted
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces: cali+ tunl0 vxlan-v6.calico
  forward: yes
  masquerade: no
  rich rules:
root@rancher1 ~ # firewall-cmd --info-zone=public
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: cockpit dhcpv6-client ssh
  ports: 9100/tcp
  protocols:
  forward: yes
  masquerade: no
  rich rules:
   <snip>
```
I might need to check the rest of my setup as well - there might be a rule somewhere else that affects that...

You can try and follow the traffic through a `nft list ruleset`, but that tend to be a bit overwhelming on a Kubernetes node...

I have this: (so public seems to be involved for stuff entering on a non-public interface)
```
        chain filter_FORWARD_ZONES {
                iifname "eth0" goto filter_FWD_public
                iifname "tunl0" goto filter_FWD_trusted
                iifname "vxlan-v6.calico" goto filter_FWD_trusted
                iifname "cali*" goto filter_FWD_trusted
                goto filter_FWD_public
        }
```

**Comment by rgaduput** [comment]
Its strange because `filter_FORWARD_ZONES` chain looks as expected.
```
        chain filter_FORWARD_ZONES {
                iifname "cali*" goto filter_FWD_trusted
                iifname "tunl0" goto filter_FWD_trusted
                iifname "eth0" goto filter_FWD_public
                goto filter_FWD_drop
        }
```
chain `filter_FWD_trusted`
```
        chain filter_FWD_trusted {
                jump filter_FORWARD_POLICIES_pre
                jump filter_FWD_trusted_pre
                jump filter_FWD_trusted_log
                jump filter_FWD_trusted_deny
                jump filter_FWD_trusted_allow
                jump filter_FWD_trusted_post
                jump filter_FORWARD_POLICIES_post
                accept
        }
```
though `cali*` is before the `filter_FWD_public` in the `filter_FORWARD_ZONES` chain for some reason packets always end up on `filter_FWD_public`. I guess you are right the only explanation is that because `iifname "eth0"` which is matching with incoming packet. But what i do not understand is isn't it how the traffic always reaches the node (on node management interface) from pod (with Calico encapsulation), even in your case ?

After many tries I have managed to make the communication work with different approach (I do not if there are any caveats with this approach) mentioned here https://github.com/rancher/rancher/issues/28840#issuecomment-787404822

```
firewall-cmd --permanent --delete-zone=kubernetes_pods
firewall-cmd --permanent --new-zone=kubernetes_pods
firewall-cmd --permanent --zone=kubernetes_pods --set-target=ACCEPT
firewall-cmd --permanent --zone=kubernetes_pods --add-source=<POD SUBNET CIDR>
firewall-cmd --permanent --zone=kubernetes_pods --add-source=ipset:<IP_SET_OF_K8S_MASTER_AND_WORKERS>
firewall-cmd --reload
```

**Comment by mohag** [comment]
> Its strange because `filter_FORWARD_ZONES` chain looks as expected.
> 
> ```
>         chain filter_FORWARD_ZONES {
>                 iifname "cali*" goto filter_FWD_trusted
>                 iifname "tunl0" goto filter_FWD_trusted
>                 iifname "eth0" goto filter_FWD_public
>                 goto filter_FWD_drop
>         }
> ```
`iifname` is input interface.... (so traffic coming from eth0 goes down the filter_FWD_public chain...

> though `cali*` is before the `filter_FWD_public` in the `filter_FORWARD_ZONES` chain for some reason packets always end up on `filter_FWD_public`. I guess you are right the only explanation is that because `iifname "eth0"` which is matching with incoming packet. But what i do not understand is isn't it how the traffic always reaches the node (on node management interface) from pod (with Calico encapsulation), even in your case?

Pod to node should not have a eth0 source... (maybe for pods with `hostNetwork: true`) (I'm not sure how that (hostNetwork > CNI) traffic works, but it does) (it might be the rules added by other parts of the environment) (The loopback interface might be involved as well)

External traffic should normally reach pods through (LoadBalancer / NodePort) [services](https://kubernetes.io/docs/concepts/services-networking/service/), which involves more rules added by (AFAIK) kube-proxy (depending on its mode) (It also has an ipvs mode) (there is also an alpha feature flag `NFTablesProxyMode` that should help in the future...) (nftables rules are mostly kept in separate tables, which makes stuff coexisting a lot simpler)

Traffic out from pods to outside the CNI network depend on CNI - in my case Calico is configured to NAT the traffic to the node IP. (and Calico adds a lot of rules for that) (but the input interface for the forward rules would throw that into the trusted zone)
