### ISSUE TITLE
feature request：Rich Rule Priorities in distributions 

### ISSUE THREAD

**Issue by itxx00** [firewalld/firewalld#530]
Hi， as in this post https://firewalld.org/2018/12/rich-rule-priorities ，"the feature may be backported to distributions that do that sort of thing."
is there any plan to backport this magic into el7 ?  thanks.

**Comment by erig0** [comment]
> Hi， as in this post https://firewalld.org/2018/12/rich-rule-priorities ，"the feature may be 
backported to distributions that do that sort of thing."

That's up to the distributions. Please file a bug report with them.

> is there any plan to backport this magic into el7 ? thanks.

Not that I know. But it's in el8.
