### ISSUE TITLE
Unexpected behavior after upgrade to 0.6.5

### ISSUE THREAD

**Issue by larsoy1** [firewalld/firewalld#535]
After upgrade from 0.6.2 to 0.6.5 on Fedora, services not allowed in source zone but allowed in interface zone are no longer available from one of two interfaces.

The zones:

ute (active)
  target: default
  interfaces: enp2s0
  services: http https imaps smtp

inne (active)
  target: default
  interfaces: enp3s0
  services: http https imap imaps pop3 pop3s smtp ssh

ssh-zone (active)
  target: default
  sources: x.x.x.x/14 y.y.y.y/24
  services: ssh

After upgrade, only ssh is accepted from x.x.x.x and y.y.y.y on enp2s0. Services http https imaps smtp are still available from all other addresses than x.x.x.x or y.y.y.y on enp2s0. Downgrade to 0.6.2 causes firewalld to return to expected behavior. enp3s0 seems not affected by the upgrade/downgrade at all (even more strange).

I have run out of explanations. Is this a bug?

**Comment by erig0** [comment]
> I have run out of explanations. Is this a bug?

No. In fact you were unknowingly making use of a bug. The zone "fall through" behavior should not have been occurring. It was fixed on commit, 70993581d79beb40a3d23bd8cbfb776ad5df5dca (backported to v0.6.5). See issues #258 and #441.

In your case you'll have to also add `http https imaps smtp` to the `ssh-zone`.

**Comment by larsoy1** [comment]
Thank you for a quick and informative reply.
