### ISSUE TITLE
firewalld-applet zone issue

### ISSUE THREAD

**Issue by jshand2015** [firewalld/firewalld#538]
hi there,

just letting you know i have found an issue with the applet.  the issue is that when you change default zones within the applet, it changes the zone within firewalld itself, even though i have set lockdown to enabled.  is this a bug or intentional?  further info, whe i set the firewall's default zone i did it with firewall-config and set it to make my wireless's default zone to drop and saved those settings before i made lockdown enabled

**Comment by erig0** [comment]
To change the default zone did you do "Edit Firweall Settings" ? If so, then this is expected. It launches firewall-config which is on the lockdown whitelist.

**Comment by erig0** [comment]
Closing due to above requested info not being given. Please reopen if it's still an issue and you can answer the above.
