### ISSUE TITLE
requires nftables 0.9.3 which is not released yet

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#540]
The latest upstream release requires nftables >= 0.9.3 but the latest version available at
http://git.netfilter.org/nftables/ is 0.9.2

**Comment by erig0** [comment]
> The latest upstream release requires nftables >= 0.9.3 but the latest version available at
> http://git.netfilter.org/nftables/ is 0.9.2

I thought nftables 0.9.3 was going to be released before I got firewalld v0.8.0 out the door. Sorry I forgot to verify.

There were a handful of fixes after 0.9.2 that are required for the libnftables JSON stuff to work properly. I'll try to enumerate them below. I'm also in contact with the nftables developers to request 0.9.3 be released.

```
8ecb88558959 ("src: restore --echo with anonymous sets")
860671662d3f ("mnl: fix --echo buffer size again")
e64c42b19a9e ("parser_json: fix crash on insert rule to bad references")
2e57d4ff79fa ("cache: fix --echo with index/position")
```

**Comment by erig0** [comment]
@mbiebl, upstream plans to cut new releases next week once kernel 5.4 is released.

**Comment by mbiebl** [comment]
Ok, thanks

**Comment by djlucas** [comment]
Opened https://bugs.archlinux.org/task/64684

**Comment by erig0** [comment]
v0.9.3 has been released. Distros can simply rebase the package to this version.
https://www.spinics.net/lists/netfilter-devel/msg64289.html
