### ISSUE TITLE
irewalld.service - firewalld - dynamic firewall daemon

### ISSUE THREAD

**Issue by balamurugan0714** [firewalld/firewalld#544]
**_sudo systemctl status firewalld_**
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-11-21 14:39:56 IST; 17s ago
     Docs: man:firewalld(1)
  Process: 26161 ExecStart=/usr/sbin/firewalld --nofork --nopid (code=exited, status=1/FAILURE)
 Main PID: 26161 (code=exited, status=1/FAILURE)

 Starting firewalld - dynamic firewall daemon...
 firewalld.service: Main process exited, code=exited, status=1/FAILURE
 firewalld.service: Failed with result 'exit-code'.
Failed to start firewalld - dynamic firewall daemon.

**Comment by erig0** [comment]
There is no actionable information here. If you provide more information; logs, OS, configuration we can reopen.
