### ISSUE TITLE
Docker containers don't comunicate between them

### ISSUE THREAD

**Issue by taviroquai** [firewalld/firewalld#546]
Hi all, I hope anyone can help me on this.

I've just installed docker on a CentOS 8 host to run CKAN within containers.

The containers need to comunicate between them and only after running the following comand, I had success:
```bash 
$ firewall-cmd --set-default-zone=trusted
```

The host is not exposed to Internet yet, but it will be, so I guess by that time I need to change to dmz zone.

This is the docker-compose.yml file:
https://github.com/ckan/ckan/blob/2.8/contrib/docker/docker-compose.yml

Before running the above command, this was the error when a container tried to connect to another container with PostgreSQL:

> ckan          | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: No route to host
> ckan          |         Is the server running on host "db" (172.18.0.3) and accepting
> ckan          |         TCP/IP connections on port 5432?
> ckan          |
> ckan exited with code 1

Note the message "**no route to host**".

My question is: I want to set the firewall to the public or dmz as default zone. What commands do I have to run to make the containers comunicate between them.

Here is the current firewalld config.
I purposely ommited some zones here, let me know if you need them too. Thanks!

> dmz
>   target: default
>   icmp-block-inversion: no
>   interfaces:
>   sources:
>   services: ssh
>   ports:
>   protocols:
>   masquerade: no
>   forward-ports:
>   source-ports:
>   icmp-blocks:
>   rich rules:
> 
> 
> libvirt (active)
>   target: ACCEPT
>   icmp-block-inversion: no
>   interfaces: virbr0
>   sources:
>   services: dhcp dhcpv6 dns ssh tftp
>   ports:
>   protocols: icmp ipv6-icmp
>   masquerade: no
>   forward-ports:
>   source-ports:
>   icmp-blocks:
>   rich rules:
>         rule priority="32767" reject
> 
> public
>   target: default
>   icmp-block-inversion: no
>   interfaces:
>   sources:
>   services: cockpit dhcpv6-client http https ssh
>   ports: 5000/tcp
>   protocols:
>   masquerade: no
>   forward-ports:
>   source-ports:
>   icmp-blocks:
>   rich rules:
> 
> 
> trusted (active)
>   target: ACCEPT
>   icmp-block-inversion: no
>   interfaces: docker0 ens160
>   sources:
>   services:
>   ports: 5000/tcp 5432/tcp
>   protocols:
>   masquerade: yes
>   forward-ports:
>   source-ports:
>   icmp-blocks:
>   rich rules:
> 
> 
> work
>   target: default
>   icmp-block-inversion: no
>   interfaces:
>   sources:
>   services: cockpit dhcpv6-client ssh
>   ports:
>   protocols:
>   masquerade: no
>   forward-ports:
>   source-ports:
>   icmp-blocks:
>   rich rules:
>

**Comment by erig0** [comment]
See https://github.com/firewalld/firewalld/issues/534#issuecomment-543722950. Closing as duplicate.

**Comment by taviroquai** [comment]
@erig0 thanks.

I think I solved this problem by:
 - setting the default zone to public
 - add docker0 interface to public zone
 - adding masquerade to public zone

This is what is working for me. Not sure if this is the right thing to do.

```
$ sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: docker0 ens160
  sources:
  services: cockpit dhcpv6-client http https ssh
  ports: 5000/tcp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

```
