### ISSUE TITLE
Cannot list firewalld config [WORKEDAROUND] Documentation is insufficient

### ISSUE THREAD

**Issue by draker42** [firewalld/firewalld#548]
Hi, 
Apologies for the earlier rant. I was a bit teed off. 
How is it easily possible to list the current state of the firewall on the cmd line (not 'active' vs. 'disable', but a listing of ports, possibly equivalent to 'iptables --line -v -n -L INPUT')?
Where is this in the documentation? I spent time looking, but was unsuccessful. 
Disabling firewalld ultimately proved the solution, even though I found the easy instructions to allow a port through; I dislike a system when I cannot see its guts, and iptables seems to work fine for me...
Thanks,
-D.

**Comment by erig0** [comment]
> Hi,
> Apologies for the earlier rant. I was a bit teed off.
> How is it easily possible to list the current state of the firewall on the cmd line (not 'active' vs. 'disable', but a listing of ports, possibly equivalent to 'iptables --line -v -n -L INPUT')?

Maybe you're looking for `--list-all-zones`. It will list everything for all zones.

> Where is this in the documentation? I spent time looking, but was unsuccessful.

man page `firewall-cmd`

**Comment by erig0** [comment]
If the documentation I reference above is not sufficient please comment and I can reopen this issue.
