### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [firewalld/firewalld#562]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github and gitlab hosted projects, Weblate open pull request. For other git hosting, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by erig0** [comment]
@Jibec, How do I go about creating a firewalld project in Weblate? Clicking "Add a new translation project" results in "You currently do not have permission to create projects. "

**Comment by Jibec** [comment]
I'll do it for you so you don't have to learn everything by yourself. I'll also need the names of the people to set as admin (you'll have to connect at least once to the platform)

**Comment by erig0** [comment]
Admins should be myself (@erig0) and @n0-1.

**Comment by Jibec** [comment]
fine, to start the migration:

please merge latest translations from Zanata
please delete empty po files (= with no translation)
please commit pot file

once done, a few minutes and I'll create the project, and add you as admin

**Comment by erig0** [comment]
> fine, to start the migration:
> 
> please merge latest translations from Zanata (this looks done)
Done.
> please delete empty po files (= with no translation)
None found. Done.
> please commit pot file
Done.

**Comment by Jibec** [comment]
thanks a lot, migration is done: https://translate.stg.fedoraproject.org/projects/firewalld/master/

weblate will open a PR
weblate will update each po files each time you update the pot file (update it as much as you want)
webalte will use git squash per author to limit the number of commits

erig0 is admin, please ping me once phil connected to the platform so I can see the user in our list
for any support, please reach fedora translation mailing list

**Comment by erig0** [comment]
> weblate will open a PR

When/How does it know to open a PR?

**Comment by Jibec** [comment]
You can trigger it manually in your component (see repository maintenance).

Weblate will automatically open it:
Three days after first edit of a user.
Earlier if one language reach 100%.

The PR stays open until you merge it.


-------- Courriel d’origine --------
De : Eric Garver <notifications@github.com>
Envoyé : 13 janvier 2020 21:38:14 GMT+01:00
À : firewalld/firewalld <firewalld@noreply.github.com>
Cc : Jean-Baptiste <jean-baptiste@holcroft.fr>, State change <state_change@noreply.github.com>
Objet : Re: [firewalld/firewalld] please migrate to the new Fedora translation platform (#562)

> weblate will open a PR

When/How does it know to open a PR?

**Comment by erig0** [comment]
> You can trigger it manually in your component (see repository maintenance)

I was able to trigger commits, but "push" appears to do nothing - presumably because Weblate has no push access to this github repo. There is no "open PR" or equivalent.

**Comment by Jibec** [comment]
I just had a look, it's indeed weird, I'll reach weblate's support team

**Comment by Jibec** [comment]
fixed: https://github.com/firewalld/firewalld/pull/565

**Comment by erig0** [comment]
> fixed: #565

Thanks. So in the future any time I "push" a change in Weblate it will open a PR?

**Comment by Jibec** [comment]
If no open PR exists, yes, it will open a new one.

**Comment by erig0** [comment]
@Jibec, perfect! It appears to be working as expected now. It opened a PR as soon a I hit "commit" in Weblate. I think I'm all set now - thanks for your help.

**Comment by erig0** [comment]
> erig0 is admin, please ping me once phil connected to the platform so I can see the user in our list

This is the last thing I need from you. Phil has signed into Weblate, so you should be able to add him as admin.
