### ISSUE TITLE
Error during reload/restart

### ISSUE THREAD

**Issue by rivo64** [firewalld/firewalld#567]
Hi,

 First i'd like to apologize for my bad english and if i made a mistake opening this issue here.

After a restart of firewalld my firewall machine was left with incorrect iptables configuration.

To try investigate what happened i stopped the service and manually started (firewalld --debug 10 --no-fork) and successfully added a simple permanent rule:  firewall-cmd --permanent --add-rich-rule "rule family=ipv4 source ipset=Teste mark set=2".

After issuing a (firewall-cmd --reload), got the following in the debug
...
2020-01-15 08:41:13 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /usr/sbin/iptables-restore /run/firewalld/temp.aqo4v6px: 2401
...
      41: *mangle
      42: -A PRE_public_allow -m set --match-set Teste src -j MARK --set-xmark 2
      43: -N PRE_public
      44: -N PRE_public_pre
      45: -N PRE_public_log
      46: -N PRE_public_deny
      47: -N PRE_public_allow
      48: -N PRE_public_post
      49: -A PRE_public -j PRE_public_pre
      50: -A PRE_public -j PRE_public_log
      51: -A PRE_public -j PRE_public_deny
      52: -A PRE_public -j PRE_public_allow
      53: -A PRE_public -j PRE_public_post
      54: -A PREROUTING_ZONES -i + -g PRE_public
      55: COMMIT
...
2020-01-15 08:41:13 ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore: line 42 failed
...

It generates the rule before creating the PRE_public_allow chain causing iptables-restore to fail.

By the way i'm running firewalld-0.7.2-1.fc31.noarch and iptables-1.8.3-7.fc31.x86_64.

Best regards,
 Rodrigo.

**Comment by erig0** [comment]
Thanks for the quality report. It made it easy to track down.
