### ISSUE TITLE
[RFE] nftables filter_FORWARD: allow non-NATed router configurations

### ISSUE THREAD

**Issue by space88man** [firewalld/firewalld#569]
Firewalld+nftables filter_FORWARD chain prevents non-NATed routing - as alluded to in #555. Use case: RHEL 8/CentOS 8/Fedora as a router without NAT.

With the iptables backed, this used to be accomplished with direct rules with "-i iif -o oif -j ACCEPT".

This RFE is for a non-NATed router configuration, or intra-zone non-NAT routing. (From Cisco ASA lingo, this is interfaces with the same security level, where forwarding is allowed indiscriminately).

As pointed out in the other issue the `reject` rule prevents non-NAT forwarding.

```
table inet firewalld {
        chain filter_FORWARD {
                type filter hook forward priority 10; policy accept;
                ct state established,related accept
                ct status dnat accept
                iifname "lo" accept
                ip6 daddr { ::/96, ::ffff:0.0.0.0/96, 2002::/24, 2002:a00::/24, 2002:7f00::/24, 2002:a9fe::/32, 2002:ac10::/28, 2002:c0a8::/32, 2002:e000::/19 } reject with icmpv6 type addr-unreachable
                jump filter_FORWARD_IN_ZONES
                jump filter_FORWARD_OUT_ZONES
                ct state invalid drop
                reject with icmpx type admin-prohibited
        }
}
```

**Comment by erig0** [comment]
The typical work around is to add the necessary interface/sources to the `trusted` zone.

True FORWARD filtering is a [WIP](https://github.com/orgs/firewalld/projects/1#card-25963208). We already have RFEs for that, see #2. A such, marking this report as a duplicate.

**Comment by benblasco** [comment]
Thread dig, as I have now encountered this same issue.  Is there a better work around that can be put to use here? @space88man how did you deal with the problem?

**Comment by space88man** [comment]
> Thread dig, as I have now encountered this same issue. Is there a better work around that can be put to use here? @space88man how did you deal with the problem?

Newer versions of firewalld have intra-zone forwarding(by default) and policy objects which make this manageable now. (Uising Fedora 35 with firewalld 1.0.1, EL8 with 0.9.3).

**Comment by benblasco** [comment]
I am running f35 as well and trying to forward between the default FedoraServer zone and the libvirt zone. There's no way I can make it work, beyond moving the interfaces into the same zone and using the "forward" directive for intra zone routing. Do you have a policy object example you can share? I really appreciate you replying!

**Comment by benblasco** [comment]
For anybody following, I believe this blog by @erig0 will be helpful!

https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic

**Comment by erig0** [comment]
> For anybody following, I believe this blog by @erig0 will be helpful!
> 
> https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic

See also the preceding post: https://firewalld.org/2020/09/policy-objects-introduction

**Comment by benblasco** [comment]
Thank you @erig0 !

For anybody who finds this, here's a configuration that is working for me to allow routing between the FedoraServer zone and the libvirt zone (which is created by libvirt):

Host to VMs
```
firewall-cmd --permanent --new-policy hostToLibvirt
firewall-cmd --permanent --policy hostToLibvirt --set-target ACCEPT
firewall-cmd --permanent --policy hostToLibvirt --add-ingress-zone FedoraServer
firewall-cmd --permanent --policy hostToLibvirt --add-egress-zone libvirt
```

VMs to host
```
firewall-cmd --permanent --new-policy libvirtToHost
firewall-cmd --permanent --policy libvirtToHost --set-target ACCEPT
firewall-cmd --permanent --policy libvirtToHost --add-ingress-zone libvirt
firewall-cmd --permanent --policy libvirtToHost --add-egress-zone FedoraServer
```

Load the config
```
firewall-cmd --reload
```

I do however believe that this then negates any firewall configuration you have in the libvirt zone, although I am not sure I understand why as yet.  If anybody has any insights I am keen to learn.

**Comment by erig0** [comment]
> I do however believe that this then negates any firewall configuration you have in the libvirt zone, although I am not sure I understand why as yet. If anybody has any insights I am keen to learn.

Not true. The policies you created directly above apply to FORWARDed traffic from, e.g. zone "FedoraServer" to "libvirt".

Adding things to the "libvirt" zone applies to INPUT traffic originating from the "libvirt" zone. i.e. "libivirt" to HOST
e.g.
   # firewall-cmd --permanent --zone libvirt --add-service dns

**Comment by PMExtra** [comment]
@erig0 I think this issue is still unresolved, even though #2 has been closed.

I'm using `firewalld 1.3.3-1~deb12u1` on debian 12.

Now, the nftables rules are like this:
```
table inet firewalld {
        chain filter_FORWARD {
                type filter hook forward priority filter + 10; policy accept;
                ct state { established, related } accept
                ct status dnat accept
                iifname "lo" accept
                ct state invalid drop
                jump filter_FORWARD_ZONES
                reject with icmpx admin-prohibited
        }
}
```

I can't add any policy or rules before `ct state invalid drop`. So, work with non-NAT routing become impossible.

**Comment by erig0** [comment]
> I can't add any policy or rules before ct state invalid drop. So, work with non-NAT routing become impossible.

That doesn't make non-NAT routing impossible.

It means that connection tracking thinks the connection state is invalid. That may happen for various reasons, but usually not in a properly operating network.

**Comment by PMExtra** [comment]
@erig0 

In my network, I use a Debian 12 VM as a non-NAT side route to filter and offload some traffic.

Only the outbound packets will go through this side route. The inbound packets will enter through the regular gateway.

Therefore, connection tracking is not possible on this side route. Firewalld requires the forwarded packets in a valid connection tracking state, so the packets cannot be forwarded.

**Comment by PMExtra** [comment]
@erig0 

I think this is a viable solution. But I have to find another way to persist nftables rules.

Then I found `netfilter-persistent`, it has been a replacement for firewalld for me. Now I don't need firewalld to manage the netfilter rules.

Regardless, firewalld is a very good product, and I'm grateful to all the people who created and contributed to firewalld. Thank you very much for your patient answer, which helped me deepen my understanding of connection track and nftables.
