### ISSUE TITLE
Interactive mode to avoid locking yourself out

### ISSUE THREAD

**Issue by rbu** [firewalld/firewalld#57]
How do you feel about adding an interactive mode that automatically undoes any change unless the user confirms after the change is executed. The idea is totally stolen from ferm (and probably from some other tool before), but it's a great way to stop locking yourself out accidentally when testing new rules in development/staging.

`man ferm` writes:

```
--interactive
Apply the firewall rules and ask the user for confirmation. Reverts to the previous ruleset
if there is no valid user response within 30 seconds (see --timeout). This is useful for
remote firewall administration: you can test the rules without fearing to lock yourself out.

--timeout S
If --interactive is used, then roll back if there is no valid user response after this number
of seconds. The default is 30.

```

**Comment by erig0** [comment]
@rbu, Many add commands (rich rules included) can be supplemented with the "--timeout" option. Which will do a rollback after a given time. I think that's sufficient based on your request.
e.g.

    # firewall-cmd --remove-service=ssh --timeout
