### ISSUE TITLE
--direct --get-all-rules doesn't seem to work with nft

### ISSUE THREAD

**Issue by Rudi3** [firewalld/firewalld#570]
When querying all rules with `firewall-cmd --direct --get-all-rules`, I get an empty output.
Is this intentional with `nft`? If it is, it may cause some shock or confusion at first glance.

```
Firewalld Version: 0.8.0
OS: Archlinux
```

**Comment by erig0** [comment]
Have you added any direct rules? If not, then getting "empty" is expected for both the nftables and iptables backends.

**Comment by Rudi3** [comment]
Ah, sorry! No I haven't - I expected it to output the whole chain for some reason.
