### ISSUE TITLE
firewall-cmd direct rule add rules to chain "INPUT" instead of specified "INPUT_direct"

### ISSUE THREAD

**Issue by mpolitaev** [firewalld/firewalld#574]
Hello team!
See not obvious behaviour of firewall-cmd command and want make sure that it's expected.

When you try to add direct rule, for example to match your created ipset "test" to chain `INPUT_direct` like:
`firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -m set --match-set test src -j DROP`

Rule added actually to chain just `INPUT`, without `_direct` at the end, based on output of `iptables-save`
```
# Generated by xtables-save v1.8.2 on Thu Jan 30 06:35:01 2020
*filter
:INPUT ACCEPT [1242:418256]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1004:379922]
-A INPUT -m set --match-set test src -j DROP
COMMIT
# Completed on Thu Jan 30 06:35:01 2020
# Generated by xtables-save v1.8.2 on Thu Jan 30 06:35:01 2020
*security
:INPUT ACCEPT [1145:413586]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1004:379922]
COMMIT
# Completed on Thu Jan 30 06:35:01 2020
# Generated by xtables-save v1.8.2 on Thu Jan 30 06:35:01 2020
*raw
:PREROUTING ACCEPT [1260:426092]
:OUTPUT ACCEPT [1004:379922]
COMMIT
# Completed on Thu Jan 30 06:35:01 2020
# Generated by xtables-save v1.8.2 on Thu Jan 30 06:35:01 2020
*mangle
:PREROUTING ACCEPT [1260:426092]
:INPUT ACCEPT [1260:426092]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1004:379922]
:POSTROUTING ACCEPT [1004:379922]
COMMIT
# Completed on Thu Jan 30 06:35:01 2020
# Generated by xtables-save v1.8.2 on Thu Jan 30 06:35:01 2020
*nat
:PREROUTING ACCEPT [298:136331]
:INPUT ACCEPT [191:127191]
:POSTROUTING ACCEPT [2:152]
:OUTPUT ACCEPT [2:152]
COMMIT
# Completed on Thu Jan 30 06:35:01 2020
# Table `firewalld' is incompatible, use 'nft' tool.
```

Is this expected? If yes why not add rules just to `INPUT` chain directly?

**Comment by erig0** [comment]
> Is this expected? If yes why not add rules just to `INPUT` chain directly?

Yes. This is expected with the nftables backend. The "_direct" suffix is needed for the iptables backend because all the other rules are in the INPUT chain. But with nftables, there is nothing in iptables INPUT chain as all the other rules are in nftables.

**Comment by mpolitaev** [comment]
Now clear, thank you for explanation.
