### ISSUE TITLE
IPv6 DNAT/port-forwarding not working with firewalld and docker

### ISSUE THREAD

**Issue by ricardo-rod** [firewalld/firewalld#575]
**What happened**:
When I am trying to run an IPv6 cluster of kubernetes with docker, firewalld is receiving a bad set of commands. for nat and port forwarding from IPv6 to IPv4 and that is not going to work, I got runing the same cluster in debian and is working like a charm.

Thanks to kind team  #https://github.com/kubernetes-sigs/kind/issues/1283
```
020-02-03 13:58:05 DEBUG1: direct.passthrough('ipv4', '-t','nat','-C','DOCKER','-p','tcp','-d','::1','--dport','32768','-j','DNAT','--to-destination','172.17.0.2:6443','!','-i','docker0')
2020-02-03 13:58:05 DEBUG2: <class 'firewall.core.ipXtables.ip4tables'>: /usr/sbin/iptables -w10 -t nat -C DOCKER -p tcp -d ::1 --dport 32768 -j DNAT --to-destination 172.17.0.2:6443 ! -i docker0
2020-02-03 13:58:05 DEBUG2: '/usr/sbin/iptables -w10 -t nat -C DOCKER -p tcp -d ::1 --dport 32768 -j DNAT --to-destination 172.17.0.2:6443 ! -i docker0' failed: iptables v1.8.3 (legacy): host/network `::1' not found
Try `iptables -h' or 'iptables --help' for more information.`
```
Here is the log for your analysis.
[firewalld.log](https://github.com/firewalld/firewalld/files/4153659/firewalld.log)

There are multiple errors from the firewalld too saying that the rules do not exists as you can see in the logs.

If I shut down the firewall it works and that's something I must not do :(

**What you expected to happen**:
the DNAT and port-forwarding must be made from IPv6 to IPv6 and the ports too, that way maybe the entire network will work as expected, and not from IPv6 to IPv4 that will never work and it will always break the firewalld and docker, with Debian there is no problem.

**How to reproduce it (as minimally and precisely as possible)**:
Run an IPv6 docker:
```
$ cat /etc/docker/daemon.json`

{
    "bip": "172.17.0.1/20",
    "fixed-cidr": "172.17.0.0/20",
    "ipv6": true,
    "fixed-cidr-v6": "fc00:dead:beef::/64"
}
```
```
$ cat <<EOF >./kind_multinode_ipv6.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  ipFamily: ipv6
EOF

$ time kind create cluster --name multinode_ipv6 --config kind_multinode_ipv6.yaml
```

**Anything else we need to know?**:
The same behavior happens on fedora 29-30 and 31.

**Environment:**
$ sudo dnf info firewalld                

Last metadata expiration check: 0:12:31 ago on Tue 04 Feb 2020 09:27:47 AM AST.
Installed Packages
Name         : firewalld
Version      : 0.7.2
Release      : 1.fc31
Architecture : noarch
Size         : 1.9 M
Source       : firewalld-0.7.2-1.fc31.src.rpm
Repository   : @System
From repo    : fedora

- OS (e.g. from `/etc/os-release`):

NAME=Fedora
VERSION="31 (Workstation Edition)"
ID=fedora
VERSION_ID=31
VERSION_CODENAME=""
PLATFORM_ID="platform:f31"
PRETTY_NAME="Fedora 31 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:31"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=31
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=31
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Comment by erig0** [comment]
I don't follow why you think this is a firewalld bug. Docker sent a request to install an invalid iptables rule. firewalld will not do an validation on the direct passthrough rules - that would require firewalld to full understand iptables grammar and semantics. That's not feasible.

**Comment by ricardo-rod** [comment]
Well thank you in advance @erig0 I will open the bug with docker networking team.

**Comment by erig0** [comment]
> I've created the bug here to see if you have a workaround with this issue, because I know that the docker team have a messy implementation with IPv6.

Unfortunately not. Sorry.
