### ISSUE TITLE
firewall-cmd --get-ipset-types returns nothing

### ISSUE THREAD

**Issue by lkjell** [firewalld/firewalld#580]
`firewall-cmd --get-ipset-types` returns nothing.
When adding a new ipset through the GUI the type option is greyed out.

Is this because most ipset related commands need the --permanent flag, and since --get-ipset-types is a stand alone command it is not possible to combine these two flags?

version 0.8.1

**Comment by Bogdan107** [comment]
I have the same problem.

My system info:
```
# cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Gentoo/Linux"

# eselect profile show
Current /etc/portage/make.profile symlink:
  default/linux/amd64/17.1/no-multilib/hardened

# uname -sr
Linux 5.12.4-gentoo-x86_64

# eix -cI --format '<installedversions:NAMEVERSION>' ipset --or nftables --or firewalld
net-firewall/firewalld-0.9.3
net-firewall/ipset-7.11
net-firewall/nftables-0.9.8

# firewall-cmd --get-ipset-types
<only single clear line here>

# ipset help | grep support$ | awk -F " " '{print $1}' | sort -u
bitmap:ip
bitmap:ip,mac
bitmap:port
hash:ip
hash:ip,mac
hash:ip,mark
hash:ip,port
hash:ip,port,ip
hash:ip,port,net
hash:mac
hash:net
hash:net,iface
hash:net,net
hash:net,port
hash:net,port,net
list:set

# zgrep -i ip_set /proc/config.gz  
CONFIG_IP_SET=y
CONFIG_IP_SET_MAX=256
CONFIG_IP_SET_BITMAP_IP=y
CONFIG_IP_SET_BITMAP_IPMAC=y
CONFIG_IP_SET_BITMAP_PORT=y
CONFIG_IP_SET_HASH_IP=y
CONFIG_IP_SET_HASH_IPMARK=y
CONFIG_IP_SET_HASH_IPPORT=y
CONFIG_IP_SET_HASH_IPPORTIP=y
CONFIG_IP_SET_HASH_IPPORTNET=y
CONFIG_IP_SET_HASH_IPMAC=y
CONFIG_IP_SET_HASH_MAC=y
CONFIG_IP_SET_HASH_NETPORTNET=y
CONFIG_IP_SET_HASH_NET=y
CONFIG_IP_SET_HASH_NETNET=y
CONFIG_IP_SET_HASH_NETPORT=y
CONFIG_IP_SET_HASH_NETIFACE=y
CONFIG_IP_SET_LIST_SET=y
```

**Comment by erig0** [comment]
@lkjell, check if firewalld started correctly. If the configuration was invalid it may have given up and entered `failed` state before determining the available ipset types.

**Comment by jokeyrhyme** [comment]
I had a similar problem, although `firewalld` does successfully load, it failed to load IPSets: https://gitlab.com/jokeyrhyme/dotfiles/-/issues/64 

You can read through that issue for the details, but for me, all I had to do was install the `ipset` package and restart `firewalld` and IPSet functionality is now working for me

**Comment by erig0** [comment]
> I had a similar problem, although `firewalld` does successfully load, it failed to load IPSets: https://gitlab.com/jokeyrhyme/dotfiles/-/issues/64
> 
> You can read through that issue for the details, but for me, all I had to do was install the `ipset` package and restart `firewalld` and IPSet functionality is now working for me

In this example it was caused by `ipset` not being installed.

In the OP's example it was caused by a broken configuration so firewalld entered failed state before it discovered the available ipset types. In OP's case, the configuration needs fixed and firewalld restarted.
