### ISSUE TITLE
A comment on the use of firewalld

### ISSUE THREAD

**Issue by Wastrel-zz** [firewalld/firewalld#582]
I'm sorry to say this, but firewalld did not work for me. First I followed the instructions, and upon rebooting my firewall/proxy, I was unable to get to it with ssh and I had to get out my emergency monitor and keyboard to log in.
After that I was more careful. I found some more instructions. After enabling http and ssh, the ports were still closed to the internet, as far as I could tell. Netstat said they were listening. The firewall-cmd to list the working services listed them, but there was no outside access.
I removed firewalld and went totally old school, putting iptables commands in /etc/rc.local and now http and ssh from outside my home network are working. 
All this stuff about "zones" and some other things is pretty arcane. I suppose that firewalld is useful on a larger network of servers, where people are paid to figure out how it works.

**Comment by erig0** [comment]
Your comment/complaint has no actionable information. You've not mentioned the firewalld version, OS, or what your setup looks like. Furthermore issues are for bug reports and questions.
