### ISSUE TITLE
firewall-cmd --direct --query-rule doesn't allow checking Runtime/active rules

### ISSUE THREAD

**Issue by isqo** [firewalld/firewalld#592]
i found that's not possible to query the runtime/active rules of iptables with the `firewall-cmd --direct --query-rule ` command. What i observed is it only queries the permanent and ephemeral rules located in its configuration. is there any equivalent of `iptables -C` to check the active rules ?

**Comment by erig0** [comment]
There _is_ support to query runtime rules. From the `firewall-cmd(1)` man page:
```
[--permanent] --direct --query-rule { ipv4 | ipv6 | eb } table chain
priority args
    Return whether a rule with priority and the arguments args exists
    in chain chain in table table. Returns 0 if true, 1 otherwise. This
    option concerns only rules previously added with --direct
    --add-rule.
```

If you're refering to rules added via `--direct --passthrough` then you just need to use the `-C` option for iptables. e.g. `--direct --passthrough ipv4 -t filter -C INPUT ...`
