### ISSUE TITLE
Cross compiling breaks the python shebangs

### ISSUE THREAD

**Issue by aduskett** [firewalld/firewalld#597]
When cross-compiling, Python is built first and installed to a staging directory and the target. When cross-compiling firewalld, the Python shebangs end up with a full path the following files end up with Python shebangs that point to a full path of the cross-compiled interpreter:
IE: `#!/home/buildroot/output/host/bin/python`
This full path causes the following files to not run when ran from the command line on the cross-compiled device:

The following files are affected by this:
firewall-cmd
firewall-applet
firewall-config
firewall-offline-cmd
firewalld

One solution is to sed each file, however, it would be nice if the shebang files are instead relative:
IE: `/usr/bin/env python[2,3]`

Any help with this would be much appreciated!

**Comment by aduskett** [comment]
I actually thought this would be much more difficult than what it was:
https://github.com/firewalld/firewalld/pull/598

**Comment by erig0** [comment]
You can do this:
```
./configure PYTHON="/usr/bin/env python3"
```

**Comment by aduskett** [comment]
That we can.
