### ISSUE TITLE
firewalld stops logging after log file has been rotated

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#599]
Version: 0.8.2

The latest firewalld version ships a logrotate configuration file `/etc/logrotate.d/firewalld.logrotate`

When logrotate runs and rotates the files, firewalld stops logging to /var/log/firewalld.
A common way to fix this is to provide a way to signal the daemon, that its log file has been rotated and the daemon reopens the log file. Typical IPC mechanisms include sending SIGHUP to the daemon pid.

**Comment by erig0** [comment]
@mbiebl, This is why the rotate policy uses `copytruncate`. Did you verify that writing to the log actually stops or are you speculating?

**Comment by mbiebl** [comment]
I verified it

**Comment by erig0** [comment]
Hrm. I went about adding a test case to mock this (see below). But it passes as expected. Tomorrow I'll try using logrotate directly as you're doing.

--->8---

```
FWD_START_TEST([writing to log after copytruncate])
AT_KEYWORDS(gh599)

AT_SKIP_IF([! NS_CMD([which truncate >/dev/null 2>&1])])
AT_SKIP_IF([! NS_CMD([which wc >/dev/null 2>&1])])

dnl Verify we continue to write to the log file after it's truncated. That is,
dnl simulate logrotate's copytruncate.
NS_CHECK([truncate -s 0 ./firewalld.log])

dnl generate some logs, anything will do since we have debug enabled.
FWD_CHECK([--list-all], 0, [ignore], [ignore])

NS_CHECK([sh -c 'let "$(cat ./firewalld.log | wc -c) == 0"'])

FWD_END_TEST
```

**Comment by erig0** [comment]
It worked as expected on my RHEL-8 machine.
```
# logrotate -v -f /tmp/firewalld.logrotate
# cat /var/log/firewalld
** EMPTY **

# firewall-cmd --reload
success
# cat /var/log/firewalld 
2020-04-03 10:44:39 WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
```

**Comment by erig0** [comment]
@mbiebl, I don't know why you expect `--reload` to generate logs. Try something that generates an error, e.g. `firewall-cmd --add-service this_does_not_exist`

My testing shows this works as expected on debian sid.
```
root@debian-test1:~# logrotate -v -f /etc/logrotate.d/firewalld
root@debian-test1:~#  tail /var/log/firewalld
[..]
copying /var/log/firewalld to /var/log/firewalld.1                                    
truncating /var/log/firewalld
root@debian-test1:~# firewall-cmd --add-service this_does_not_exist
Error: INVALID_SERVICE: this_does_not_exist
root@debian-test1:~#  tail /var/log/firewalld 
2020-04-06 17:07:23 ERROR: INVALID_SERVICE: this_does_not_exist
```

**Comment by mbiebl** [comment]
I got libvirt related errors like
```
2020-04-06 23:29:19 WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?).

``` on reload which stopped after a logrotate. Maybe this was a red herring. 
Since you have tested this on Debian and I don't have the time to look further into this, let's close this at this point.

**Comment by erig0** [comment]
It looks like libvirt is attempting to delete a direct rule that doesn't exist. Unfortunately this is "normal". I think it always does a delete before re-adding the rule just in case it previously existed.
