### ISSUE TITLE
Removing rule requires service restart

### ISSUE THREAD

**Issue by erfansahaf** [firewalld/firewalld#601]
I was struggling with Docker and Firewalld for the past few days and suddenly I faced with a strange problem.

When I added a rule to my public zone to allow incoming traffic from a specific host (`xxx.xxx.xxx.xxx` IP), it worked just as I was expecting and the requests could pass through the firewall:

```
<rule family="ipv4">
    <source address="xxx.xxx.xxx.xxx"/>
    <port protocol="tcp" port="8070"/>
    <accept/>
</rule>
```

But the problem showed up when I tried to remove this recently created rule. After deleting the rule from `/etc/firewalld/zones/public.xml` file and executing `firewall-cmd --reload` to update the `iptables` rules, it was still accepting the incoming request from the `xxx.xxx.xxx.xxx` IP address.

For fixing this issue, I had to restart the `firewalld` process with `systemctl`:

```
$ systemctl restart firewalld
```

I don't know this is a bug or what. Just letting you guys know.

**Comment by erig0** [comment]
Was the request a _new_ connection or an existing connection? Connections are preserved during a `--reload` so altering the rule doesn't affect existing connections.

**Comment by erfansahaf** [comment]
@erig0 I didn't get what you meant about _existing_ connection. I made a new http request in a new tab if it counts as a _new_ connection.

I don't have access to iptables rules right now, but I think the problem can be reproduced.

**Comment by erig0** [comment]
> @erig0 I didn't get what you meant about _existing_ connection.

Examples of "existing connections" would be a single in progress HTTP request or an existing SSH connection.

> I made a new http request in a new tab if it counts as a _new_ connection.

Yes. That's a new connection.

**Comment by erfansahaf** [comment]
@erig0 So yes, I can confirm it was a _new_ connection.

**Comment by erig0** [comment]
Can you provide more information on the other rules in the zone? Are you sure the traffic isn't being allowed by a different rule or zone?

**Comment by erfansahaf** [comment]
@erig0 Unfortunately, this incident happened a couple of days ago and I do not have access to that machine anymore cuz I deleted it. Otherwise, I could provide the actual iptables rules but I can't.

About the other rules, I was messing with iptables for hours but I do not think those actions had caused this problem. I'm not sure about, btw.

**Comment by erig0** [comment]
Closing due to insufficient data.
