### ISSUE TITLE
ipv6_rpfilter blocks wireguard traffic

### ISSUE THREAD

**Issue by martinetd** [firewalld/firewalld#603]
`wg-quick` uses fwmark to route underlying encrypted traffic on the "real" interfaces, but with an ipv6 endpoint the return packet gets blocked with firewalld's rpfilter:
```
[146484.816657] rpfilter_DROP: IN=wlp0s20f3 OUT= \
MAC=62:2f:57:8e:96:18:00:24:d4:ba:bf:96:86:dd SRC=<serveripv6> DST=<localclientipv6> \
LEN=140 TC=0 HOPLIMIT=56 FLOWLBL=0 PROTO=UDP SPT=51820 DPT=51820 LEN=100
```

Long story short: having the rule in `raw` table is too early AND the current rule does not look at marks, so the packet reverse path isn't found.

See https://marc.info/?l=netfilter-devel&m=158646504331572&w=2 for gory details.

Possible solutions:
 - move the rule to `mangle` table and add mark lookup, for nftables this means going from:
```
        chain raw_PREROUTING {
                type filter hook prerouting priority raw + 10; policy accept;
                icmpv6 type { nd-router-advert, nd-neighbor-solicit } accept
                meta nfproto ipv6 fib saddr . iif oif missing log prefix "rpfilter_DROP: " drop
                jump raw_PREROUTING_ZONES
        }

        chain mangle_PREROUTING {
                type filter hook prerouting priority mangle + 10; policy accept;
                jump mangle_PREROUTING_ZONES
        }
```

to

```
        chain raw_PREROUTING {
                type filter hook prerouting priority raw + 10; policy accept;
                icmpv6 type { nd-router-advert, nd-neighbor-solicit } accept
                jump raw_PREROUTING_ZONES
        }

        chain mangle_PREROUTING {
                type filter hook prerouting priority mangle + 10; policy accept;
                meta nfproto ipv6 fib saddr . iif . mark  oif missing log prefix "rpfilter_DROP: " drop
                jump mangle_PREROUTING_ZONES
        }
```
(change of chain + add `. mark`)
for iptables backend, from `ip6tables -t raw -A PREROUTING -m rpfilter --invert -j DROP` to `ip6tables -t mangle -A PREROUTING -m rpfilter --validmark --invert -j DROP` (change of table + `--validmark`)

 - I'm still confused that the default on my system for ipv4 seems to be `net.ipv4.conf.default.rp_filter = 2`, which is `loose` return path filtering, but not for ipv6; so ipv6 could also change to loose filtering which would also work. For iptables that means adding `--loose`, I'm not sure on nftables syntax.

(Note that switching to strict rp_filter (=1) does not break wireguard on ipv4, so I would be in favor of moving the rule and adding mark check; I have done that locally as a workaround)

Thanks!

**Comment by erig0** [comment]
For the nftables backend I believe we can fix this by matching "mark"
and moving the rule to `mangle` as you mention. I'm in the process of
verifying this can be done safely.

But for the iptables backend (not the default) we may be out of luck.
From what I can tell the wireguard nft hooks and iptables hooks (not
changeable) will have the same priority. As such it's not deterministic
if the wireguard rules or firewalld rules will execute first. I suspect
it will depend upon the order of when wireguard and firewalld start
(iptables kernel modules loaded).

**Comment by martinetd** [comment]
Regarding the priority of wg-quick rules compared to iptables I agree; this works for me (inserting iptables module before wireguard rules reliably probably?) but we shouldn't rely on that.

Just like firewalld puts rules in 'priority raw + 10', I can try to ask wireguard to put the mangle rule in 'priority mangle - 10' or any negative number so the mark gets set before iptables, perhaps?
(Or if they don't want that at least get them to document the problem and advice to use the firewalld nft backend if possible ; since they use nft themselves it should be available...)

Anyway, thanks for checking if moving the nft rules is safe to do. I'll wait for that answer first before sending wireguards list a mail to worry about iptables...

**Comment by erig0** [comment]
On Mon, Apr 13, 2020 at 08:54:12AM -0700, Dominique Martinet wrote:
> Just like firewalld puts rules in 'priority raw + 10', I can try to
> ask wireguard to put the mangle rule in 'priority mangle - 10' or any
> negative number so the mark gets set before iptables, perhaps?

I agree. This is probably in wireguard's best interest to avoid issues
with iptables/nftables.

> Anyway, thanks for checking if moving the nft rules is safe to do.
> I'll wait for that answer first before sending wireguards list a mail
> to worry about iptables...

It may be a couple days due to the holiday.

**Comment by erig0** [comment]
>> Anyway, thanks for checking if moving the nft rules is safe to do. I'll wait for that answer first before sending wireguards list a mail to worry about iptables...

> It may be a couple days due to the holiday.

It seems this is safe to do. For nftables we can move the rpfilter check all the way to the `filter` table/priority. For iptables we can only go as far as `mangle` (as per `iptables-extensions` man page)

**Comment by martinetd** [comment]
Great! Thank you. Nice to know it would work all the way into `filter` for nftables.

What about the mark matching, would you also enable it?

**Comment by erig0** [comment]
> Great! Thank you. Nice to know it would work all the way into `filter` for nftables.
> 
> What about the mark matching, would you also enable it?

Yes.

**Comment by martinetd** [comment]
Hello,

it's been a while, but I had totally forgotten about this and just got a mail in private asking me if I had found a workaround.
Unfortunately my wg-quick patch never got accepted ( https://lore.kernel.org/wireguard/1588591647-7500-1-git-send-email-asmadeus@codewreck.org/ ) ; it just didn't get any discussion. With someone else having the problem now it might move again, I don't know.

OTOH moving rpfilter checks to a later table would also work so I came check in here as well -- has there been any more discussions on this? From the last few messsages there didn't seem to be much drawbacks, should I send a patch that updates where rules are set on nftables backend at least?

Thanks!

**Comment by zx2c4** [comment]
Sorry, I'll have another look at your patch.

**Comment by erig0** [comment]
@martinetd, moving rpfilter check seems safe. I just haven't had time to work on it. I'd happily merge a PR though.

**Comment by martinetd** [comment]
Thank you both!

@erig0 I don't have much time right now, but I'll take a long at it around the end of the month. Might as well get both sides adjusted if there is no harm.

**Comment by erig0** [comment]
See pull request #766.

**Comment by martinetd** [comment]
Thanks! I'm sorry I didn't find the time to follow up.

Looking at notes it looks like it also needed to be put in a "later" table, so the mark could be set before -- I'll make time to check it when I get home tonight or tomorrow.

**Comment by martinetd** [comment]
Sorry for the delay, the server I was using for that was gone since then so it took a bit more time than planned.
I now see the table changed as well.

I've just pulled the branch now & installed locally, tested both nft backend and iptables successfully (after confirming 0.8.6 didn't work)

Thanks!

**Comment by erig0** [comment]
> Sorry for the delay, the server I was using for that was gone since then so it took a bit more time than planned.
> I now see the table changed as well.
> 
> I've just pulled the branch now & installed locally, tested both nft backend and iptables successfully (after confirming 0.8.6 didn't work)

Thanks.

Did you have to do any firewalld configuration to get wireguard and firewalld to cooperate? e.g. adding the `wg0` to the `trusted` zone? AFAIK, this should only be necessary if you want to provide a service to clients on the VPN, e.g. SSH.

**Comment by martinetd** [comment]
The commit here is only needed on "clients" that add a default route via the wg interface (so the route to the server on the default table (through wg interface) didn't match where the reply came from (physical interface) and triggered rp filter), and I had no service here thus did not change anything in the firewalld configuration to have it work.

On servers it is as you say, you'd need to set up a zone/open up ports as required, but that is normal firewalld operation that should just work -- I believe that worked before.
You'd also need to open up the wireguard endpoint port on the physical interface if your machine is meant to be a server, but this as well isn't required if it is a client (conntrack allows replies) and I believe is most natural.
