### ISSUE TITLE
firewall drop my packages while my IP is in while list.

### ISSUE THREAD

**Issue by tlsalex** [firewalld/firewalld#611]
My IP is 223.73.xx.xx, and my rich rule as follow.
So my IP match the first rule definitely. but after I add the last rule, my ping package was drop.
It's so wired.  
BTW , how to list rich rules with the line number(or order number) -- ufw status numbered.
I guess the last rule is at the top  inside iptable actually , not the last one.

rule family="ipv4" source address="223.73.0.0/18" icmp-type name="echo-request" accept
rule family="ipv4" source address="xxx.0.0.0/8" icmp-type name="echo-request" accept
rule family="ipv4" source address="xx.0.0.0/8" icmp-type name="echo-request" accept
rule family="ipv4" source address="0.0.0.0/0" icmp-type name="echo-request" drop

**Comment by erig0** [comment]
That's because by default "deny" type rich rules will execute before "accept" type rich rules. You need to to use [rich rule priorites](https://firewalld.org/2018/12/rich-rule-priorities) to get the behavior you want.
