### ISSUE TITLE
Permit rule does not work

### ISSUE THREAD

**Issue by darwincr** [firewalld/firewalld#612]
Hi,

I have 1 hosts, at 192.168.7.201

It is connected to my host, a Server with a few interfaces including a tap device that has a VPN that connects to 192.168.7.0/24

The host has 2 Bridged Network Adapters 192.168.100.0/24 and 192.168.200.0/24
All networks are within "home" zone

There is a VM inside the second host and it has firewalld enabled,
I have added pot 5061 as a port in the zone configuration in firewalld

When I try to connect to 192.168.200.211:5061 from 192.168.7.201 it fails

To make it work i need to run a sudo iptables -F

How can I allow this port within firewalld?

**Comment by darwincr** [comment]
`Apr 23 17:42:20 DARWIN-SRV kernel: [19373.698057] STATE_INVALID_DROP: IN=br1 OUT= MAC=30:85:a9:96:46:a2:c4:ad:34:81:01:b4:08:00 SRC=136.147.100.130 DST=192.168.200.11 LEN=52 TOS=0x00 PREC=0x00 TTL=239 ID=30622 DF PROTO=TCP SPT=443 DPT=47438 WINDOW=5445 RES=0x00 ACK URG│
│Apr 23 17:42:20 DARWIN-SRV kernel: [19374.003950] FINAL_REJECT: IN=br1 OUT=vpn_se MAC=30:85:a9:96:46:a2:52:54:00:16:f1:7d:08:00 SRC=192.168.200.211 DST=192.168.7.201 LEN=48 TOS=0x00 PREC=0x00 TTL=127 ID=16469 DF PROTO=TCP SPT=52669 DPT=4443 WINDOW=8192 RES=0x00 SYN URG│
│Apr 23 17:42:21 DARWIN-SRV kernel: [19375.289549] FINAL_REJECT: IN=vpn_se OUT=br1 MAC=5e:db:7e:fb:27:b0:5e:92:c7:08:e3:8b:08:00 SRC=192.168.7.201 DST=192.168.200.211 LEN=52 TOS=0x02 PREC=0x00 TTL=127 ID=7064 DF 

PROTO=TCP SPT=49849 DPT=5061 WINDOW=8192 RES=0x00 CWR ECE │
│Apr 23 17:42:22 DARWIN-SRV kernel: [19375.558387] STATE_INVALID_DROP: IN=br1 OUT= MAC=30:85:a9:96:46:a2:c4:ad:34:81:01:b4:08:00 SRC=75.2.53.94 DST=192.168.200.11 LEN=52 TOS=0x00 PREC=0x00 TTL=244 ID=32873 DF 

PROTO=TCP SPT=443 DPT=46738 WINDOW=1984 RES=0x00 ACK URGP=0  │
│Apr 23 17:42:24 DARWIN-SRV kernel: [19377.690459] STATE_INVALID_DROP: IN=br1 OUT= MAC=30:85:a9:96:46:a2:c4:ad:34:81:01:b4:08:00 SRC=52.114.14.13 DST=192.168.200.11 LEN=40 TOS=0x00 PREC=0x00 TTL=110 ID=40520 DF 

PROTO=TCP SPT=443 DPT=41592 WINDOW=2053 RES=0x00 ACK URGP=0│
│Apr 23 17:42:27 DARWIN-SRV kernel: [19381.289424] FINAL_REJECT: IN=vpn_se OUT=br1 MAC=5e:db:7e:fb:27:b0:5e:92:c7:08:e3:8b:08:00 SRC=192.168.7.201 DST=192.168.200.211 LEN=48 TOS=0x00 PREC=0x00 TTL=127 ID=7065 DF 


PROTO=TCP SPT=49849 DPT=5061 WINDOW=8192 RES=0x00 SYN URGP│
│Apr 23 17:42:28 DARWIN-SRV kernel: [19381.786613] STATE_INVALID_DROP: IN=br1 OUT= MAC=30:85:a9:96:46:a2:c4:ad:34:81:01:b4:08:00 SRC=13.76.217.211 DST=192.168.200.11 LEN=52 TOS=0x00 PREC=0x00 TTL=109 ID=8062 DF PROTO=TCP SPT=443 DPT=40962 WINDOW=1026 RES=0x00 ACK URGP=0│
│Apr 23 17:42:31 DARWIN-SRV kernel: [19385.058275] FINAL_REJECT: IN=br1 OUT=vpn_se MAC=30:85:a9:96:46:a2:52:54:00:16:f1:7d:08:00 SRC=192.168.200.211 DST=192.168.7.201 LEN=52 TOS=0x02 PREC=0x00 TTL=127 ID=21180 DF PROTO=TCP SPT=52671 DPT=4443 WINDOW=819`

**Comment by erig0** [comment]
You're referencing multiple machines (host, VM) without saying where you performed actions and not showing configuration. This makes it hard to interpret. Please give configuration and be explicit about whether it's from the host or VM.

**Comment by darwincr** [comment]
Hi

Yes the machine that has firewalld is the KVM Hypervisor Host, other machines do not have any firewall

The configuration files are attached below, if i do a systemctl stop firewalld the connection works, if i start firewalld the connection to 5061 port is dropped with the logs referenced above


[firewalld.tar.gz](https://github.com/firewalld/firewalld/files/4527214/firewalld.tar.gz)

**Comment by erig0** [comment]
It looks like you're trying to add rules to the `home` zone and expecting it to filter/allow the traffic forward to the VMs. firewalld does not yet support forward filtering. To get what you want you'll have to use direct rules. See issue #2.

**Comment by darwincr** [comment]
Thanks for pointing it out the way to do it
Issue  solved using the below command

firewall-cmd --direct --add-rule ipv4 filter FORWARD 1 -p tcp --dport  5061 -j ACCEPT
