### ISSUE TITLE
RFE: rich rules mss-clamping

### ISSUE THREAD

**Issue by erig0** [firewalld/firewalld#618]
Currently there is no way to do MSS clamping outside of `--direct` rules. Once policy objects (FORWARD filtering) are implemented it makes sense to add MSS clamping support to rich rules. This is pretty much required for anyone that has a PPP uplink.

**Comment by barinet** [comment]
Thanks for opening this! I wonder if it would also be useful for other encapsulations: VPNs and the like, or indeed GRE or VXLAN--anything with a mismatched MTU.

**Comment by erig0** [comment]
> Thanks for opening this! I wonder if it would also be useful for other encapsulations: VPNs and the like, or indeed GRE or VXLAN--anything with a mismatched MTU.

Sure. We'll simply expose specifying the MSS clamping. We won't care (or even know) what tunnel technology is in use.

**Comment by erig0** [comment]
Duplicate of #493.
