### ISSUE TITLE
Add a list of mandatory kernel options and a minimum kernel version

### ISSUE THREAD

**Issue by aduskett** [firewalld/firewalld#623]
Hello;
I am currently porting firewalld to Buildroot, an embedded Linux SDK, and with the nftables backend, there are a LOT of kernel options that are necessary to enable to ensure that firewalld starts properly.

I asked on IRC and the consensus was "enable every nftables option" and while that works, it seems sub-optimal. Is there any way an exact list of needed kernel options can be added somewhere?

Also, is there a minimum kernel version needed for firewalld? I know the nftables backend requires 4.18 thanks to  https://firewalld.org/2018/07/firewalld-0-6-0-release, however, I do not see any minimum kernel version for the iptables backend.

Thanks!

Adam

**Comment by erig0** [comment]
Thanks for closing. I believe the latest README covers this.

https://github.com/firewalld/firewalld/blob/04548b4c3be23288ccaeee74f7b1fda5e9d5e047/README#L28-L42

**Comment by aduskett** [comment]
Not really, as that only covers the dependencies, not the needed kernel options. I closed this request because it was ignored for over a year.

**Comment by erig0** [comment]
> Not really, as that only covers the dependencies, not the needed kernel options. I closed this request because it was ignored for over a year.

Fair enough. I'm pretty much the lone developer and this wasn't exactly high in the priority list.

**Comment by aduskett** [comment]
It's no worries! I figured out most of them on my own, but I no longer contribute to Buildroot so it's not a priority for me anyways.
