### ISSUE TITLE
Unable to create new zone using the dbus interface

### ISSUE THREAD

**Issue by arkodg** [firewalld/firewalld#624]
Attempting to create a new zone called `docker` for docker networking interfaces for all distros
with `firewalld` enabled

Using https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.config.Methods.addZone as a reference

I'm hitting into this error when calling `addZone`
```
RRO[2020-05-05T20:21:02.869141449Z] Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib64/python3.6/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: addZone is not a valid method of interface org.fedoraproject.FirewallD1.config 
```
On my CentOS VM running `firewalld 0.6.3`
```
[vagrant@centos8 ~]$ sudo firewall-cmd -V
0.6.3
```
Relates to - https://github.com/moby/libnetwork/pull/2548

TIA !

**Comment by erig0** [comment]
I expect this is because the arguments you're passing are the wrong type. The `addZone()` function takes two arguments:
```
# gdbus introspect -y --xml --system --dest=org.fedoraproject.FirewallD1 --object-path /org/fedoraproject/FirewallD1/config |xmllint --xpath '//method[@name="addZone"]' - |xmllint --c14n -
<method name="addZone">
      <arg direction="in" name="zone" type="s"></arg>
      <arg direction="in" name="settings" type="(sssbsasa(ss)asba(ssss)asasasasa(ss)b)"></arg>
      <arg direction="out" type="o"></arg>
    </method>
```

If I call it as done in the libnetwork PR I get this error:
```
# gdbus call -y  --system --dest=org.fedoraproject.FirewallD1 --object-path /org/fedoraproject/FirewallD1/config --method org.fedoraproject.FirewallD1.config.addZone "foobar" version='1.0',target='ACCEPT'
Error parsing parameter 2 of type “(sssbsasa(ss)asba(ssss)asasasasa(ss)b)”: unknown keyword:
  version=1.0,target=ACCEPT
  ^^^^^^^                  
```


You **MUST** pass the correct about of arguments. That is, the entire tuple.
```
# gdbus call -y  --system --dest=org.fedoraproject.FirewallD1 --object-path /org/fedoraproject/FirewallD1/config --method org.fedoraproject.FirewallD1.config.addZone "foobar" "('1.0','foobar','foobar description',false,'ACCEPT',['ssh'],[],[],false,[],['docker0'],[],[],[],[],false)"
(objectpath '/org/fedoraproject/FirewallD1/config/zone/9',)
```

**Comment by erig0** [comment]
FWIW, newest firewalld (unreleased) adds a new API for creating zones. It takes a dictionary and only requires a subset of arguments.

```
# gdbus call -y  --system --dest=org.fedoraproject.FirewallD1 --object-path /org/fedoraproject/FirewallD1/config --method org.fedoraproject.FirewallD1.config.addZone2 "foobar" "{'version': <'1.0'>, 'target': <'ACCEPT'>}"
(objectpath '/org/fedoraproject/FirewallD1/config/zone/12',)
```

**Comment by arkodg** [comment]
@erig0 thanks for the help, got it to work
I was using the wrong object-path which you pointed out and had to pass an interface slice to the addZone API to get it to work , had to reverse engineer the dbus API arg type using `getZoneSettings`

Also you might want to update https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.config.Methods.addZone to include the 16th argument (`boolean`)

**Comment by erig0** [comment]
> @erig0 thanks for the help, got it to work
> I was using the wrong object-path which you pointed out and had to pass an interface slice to the addZone API to get it to work , had to reverse engineer the dbus API arg type using `getZoneSettings`
> 
> Also you might want to update https://firewalld.org/documentation/man-pages/firewalld.dbus.html#FirewallD1.config.Methods.addZone to include the 16th argument (`boolean`)

That was recently fixed by 7fbc6f6204a342f5ae92f10923093d2381c9b0ac.

**Comment by erig0** [comment]
@arkodg. BTW, I'm very pleased to see docker/moby is getting firewalld integration. Users will be happy. :+1:

**Comment by arkodg** [comment]
np, hoping you can take a look at the PR to recommend some sane zone settings

**Comment by erig0** [comment]
> np, hoping you can take a look at the PR to recommend some sane zone settings

Done.
