### ISSUE TITLE
ArchLinux Firewalld version 0.8.2

### ISSUE THREAD

**Issue by jshand2015** [firewalld/firewalld#625]
on my system, i have completely disabled ipv6 from the kernel command line in grub.

the issue i am facing is that even though i have completely disabled ipv6 with ipv6.disable=1 i am still seeing ipv6 firewall rules being set.  is there a way to turn this off?

**Comment by erig0** [comment]
> is there a way to turn this off?

No. But they're harmless. It's 2020. Disabling IPv6 is not a use case firewalld is interested in optimizing.
