### ISSUE TITLE
Service name is case sensitive?

### ISSUE THREAD

**Issue by yp05327** [firewalld/firewalld#629]
Hello,
I tried to run the following command on a Red Hat 7 server which is running on Microsoft Azure.
firewall-cmd --permanent --add-service=imap

But there's an error occurred. Sorry, i forgot to record this error.

Then i tried to change 'imap' into 'IMAP',  like this
firewall-cmd --permanent --add-service=IMAP

And it works. 
So the service name here is case sensitive?

Thanks.

**Comment by erig0** [comment]
> So the service name here is case sensitive?

Yes. It is case sensitive.
