### ISSUE TITLE
netbios assistants

### ISSUE THREAD

**Issue by mateMathieu** [firewalld/firewalld#630]
I would like to report a issue on a fresh KDE-neon install.
Installed Firewalld (0.4.4.5) and disabled the defaut firewall (ufw) on this ubuntu based distro.

Right out the box, the CIFS/samba stack is not going through the firewall. The discovery of the network returns a limitation by the firewall. (Dolphin 20.04.0.  KDE framework 5.70, Qt 5.14.2)

To make it work I have added the following entries:
Assistants -> Netbios --> Add Port 138 UDP.
Right away the discovery is working.

I also added Services WS-Discovery (5357 TCP, 5357 UDP and 3702 UDP) to ease local network discovery.
This is a little far from the subject, but adding webdav services would be nice.

I really like your work, and Firewalld takes a wonderful place within the plasma DE. Thansk for making it.  ;)

PS: I will post it on the KDE forum as well, this way you can search for it if you find it more related to the whole DE.

**Comment by mateMathieu** [comment]
mathieu@neon-Home:~$ grep -i NETBIOS /etc/services 
netbios-ns      137/tcp                         # NETBIOS Name Service
netbios-ns      137/udp
netbios-dgm     138/tcp                         # NETBIOS Datagram Service
netbios-dgm     138/udp
netbios-ssn     139/tcp                         # NETBIOS session service
netbios-ssn     139/udp

**Comment by erig0** [comment]
Have you tried the "samba-client" service?

**Comment by mateMathieu** [comment]
I have tried both.
It must have been a bad configuration on my side. I prefer to close it and keep investigating.
