### ISSUE TITLE
Make the integration with Fail2ban easier

### ISSUE THREAD

**Issue by ajayramaswamy** [firewalld/firewalld#642]
In current Fedora 32 the only way of using firewalld and fail2ban is rich rules. This causes many problems when the system boots and there are a lot of ips to be banned. It takes many minutes for the ruleset to be loaded

I have hacked up a modified nftables.conf in fail2ban to work well with firewalld and so far it looks good.

What I need from firewalld - 2 things
1. specify more details when creating ipsets with flags=dynamic flags=timeout flags=interval etc. The issue is that firewalld always creates ipsets as flags=interval so when adjaecent or nearby ips are banned at different times they get merged automatically then later on when you unban you cannot remove just one ip

2. in table firewalld provide a single hook chain in a specific place for processing blacklists whitelists and fail2ban sets. I have a server with multiple connections and depending on the order of which interface comes up the hook chain has to be deleted and readded so I restart fail2ban very late in the boot as a very ugly hack

related to this, find a better way of adding nft rules and chains via the firewalld.direct mechaism

A description of what is happening

first create a set
```
nft add set inet firewalld f2b-sshd { type ipv4_addr\; flags dynamic, timeout\; timeout 3600s \; }
```

then a chain for the rules
```
nft add chain inet firewalld process_fail2ban
```

then a rule for each set in that chain
```
nft add rule inet firewalld process_fail2ban ip saddr@f2b-sshd tcp dport {22, 80, 443, 9090}  log prefix "f2b-sshd " counter drop
```

and finally hook up that chain in to some place in firewalld builtin chains
```
nft insert rule inet firewalld filter_INPUT_ZONES jump process_fail2ban 
```

this point depends on number of zones that are active, order of interfaces etc

I have attached my current running config files for others to test and reproduce
action files go in /etc/fail2ban/action.d/
[nftables.local.txt](https://github.com/firewalld/firewalld/files/4733386/nftables.local.txt)
[nftables-common.local.txt](https://github.com/firewalld/firewalld/files/4733388/nftables-common.local.txt)

and jail goes in /etc/fail2ban/jail.d/
[jail.local.txt](https://github.com/firewalld/firewalld/files/4733389/jail.local.txt)

**Comment by erig0** [comment]
This issue contains many RFEs. In the future please file them separately.

[..]
> specify more details when creating ipsets with flags=dynamic flags=timeout flags=interval etc. The issue is that firewalld always creates ipsets as flags=interval so when adjaecent or nearby ips are banned at different times they get merged automatically then later on when you unban you cannot remove just one ip

I assume you mean via firewalld's `--add-entry`, but the example you gave below directly uses `nft` which firewalld has no control over.

For `--add-entry`, it was recently changed so "interval" flag is only used if it's absolutely necessary. See 2d1b0fe9fe. "interval" only used if type contains "net" or "port".


> in table firewalld provide a single hook chain in a specific place for processing blacklists whitelists and fail2ban sets. I have a server with multiple connections and depending on the order of which interface comes up the hook chain has to be deleted and readded so I restart fail2ban very late in the boot as a very ugly hack

Injecting hooks/rules into firewalld's tables is not the correct approach. fail2ban has two options:

1. Use firewalld's `ipset` primitives, e.g. `--add-entry`
2. Create its own nftables table out-of-band from firewalld with a higher precedence than firewalld's table. Firewalld will only ever touch the "firewalld" tables.

> related to this, find a better way of adding nft rules and chains via the firewalld.direct mechaism

This is by design. Direct rules are a hack. If you need more support from firewalld then we should enhance rich rules.

**Comment by ajayramaswamy** [comment]
Thank you for the clarification ...
The fail2ban author also recommended the same approach and so today I have deployed

> Create its own nftables table out-of-band from firewalld with a higher precedence than firewalld's table. Firewalld will only ever touch the "firewalld" tables.

let me see how it performs on my webserver and I will report if any issues come up
