### ISSUE TITLE
[Question] If host main interface is a bridge, shouldn't SNAT ignore bridge-slaves?

### ISSUE THREAD

**Issue by space88man** [firewalld/firewalld#661]
Scenario:
1. Zone FedoraWorkstation(interface nm-bridge 192.168.1.100/24) has masquerade on for podman(10.88.0.0/16), and libvirt(192.168.122.0/24)
2. FedoraWorkstation contains the host main interface but this is a bridged interface on 192.168.1.100/24
3. There are libvirt VMs on this bridge, so that they can have IP addresses on the same LAN as the host

The way firewalld configures nftables, these libvirt VMs with IP addresses 192.168.1.x (same LAN as host) are SNAT'ed to the host's IP address, even though the intention is for them to have their own IP address on the host's LAN. The SNAT should only apply to podman containers(10.88.0.0/16) and libvirt VMs on 192.168.122.0/24.

Question:
1. Is this the expected behaviour
2. Is there a way to tell firewalld to skip NAT'ing on bridge-slaves on the main interface?

```
# host's LAN
$ nmcli c show nm-bridge
connection.type:                        bridge

$ firewall-cmd --get-active-zones
FedoraWorkstation
  interfaces: nm-bridge

$ firewall-cmd --zone=FedoraWorkstation --query-masquerade
yes

$ ip link show type bridge_slave
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master nm-bridge state UP mode DEFAULT group default qlen 1000
    link/ether 30:85:a9:46:ae:9e brd ff:ff:ff:ff:ff:ff
    altname enp0s25
6: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:a6:e7:5b brd ff:ff:ff:ff:ff:ff
7: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master nm-bridge state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:54:00:f4:36:f6 brd ff:ff:ff:ff:ff:ff
8: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master nm-bridge state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:54:00:bd:80:bd brd ff:ff:ff:ff:ff:ff
```

vnet0, vnet1 belong to two libvirt VMs with IP addresses 192.168.1.31, 192.168.1.32. Outward connections from these two VMs are SNAT'ed to the host's IP address 192.168.1.100.

**Comment by erig0** [comment]
Doesn't podman setup masquerading itself? Why are enabling masquerade in zone FedoraWorkstation?

An alternative is to use a rich rule:
```
   # firewall-cmd --zone FedoraWorkstation --add-rich-rule='rule family=ipv4 source address=10.88.0.0/24 masquerade'
```

**Comment by space88man** [comment]
1. podman and libvirt are working (they have separate bridged interfaces) and the FedoraWorkstation zone is NAT'ing their traffic to the outside world as intended

1.  The interface `nm-bridge` in FedoraWorkstation zone is yet another bridge for a different libvirt network which is meant for VMs to have IP addresses on the same subnet as the host (†)

What I am observing is that the masquerade rule in chain `nat_POST_FedoraWorkstation_allow`  captures the (†) traffic well, which is not intended. I need a rule that states

> "for traffic between interfaces within `nm-bridge` then `accept` not `masquerade`"

**Comment by erig0** [comment]
>I need a rule that states
> 
> > "for traffic between interfaces(vnet0, vnet1, eno1) within `nm-bridge` then `accept` not `masquerade`"

Firewalld can't do that yet. You can use the rich rule I mentioned above though, which should be sufficient.

**Comment by space88man** [comment]
Thanks.
