### ISSUE TITLE
Firewalld Contradicting requirement dependencies with fail2ban

### ISSUE THREAD

**Issue by soufiane-bouchaara** [firewalld/firewalld#662]
Fail2Ban **v0.9.6**
firewall-cmd  **0.4.4.2**
firewall-cmd --state **running**
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.12 (stretch)
Release:	9.12
Codename:	stretch


```
Firewalld was installed without any errors and loaded without any errors, but the first restart without any config updates it throws an error 

So when running 
```
# systemctl restart firewalld.service
Failed to restart firewalld.service: Transaction contains conflicting jobs 'restart' and 'stop' for fail2ban.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status firewalld.service' for details.

```

Any clue ?

**Comment by erig0** [comment]
On Sat, Jun 27, 2020 at 11:43:44PM -0700, SOUFIANE BOUCHAARA wrote:
>Fail2Ban **v0.9.6**
>firewall-cmd  **0.4.4.2**
>firewall-cmd --state **running**
>
>Firewalld was installed without any errors and loaded without any errors, but the first restart without any config updates it throws an error
>
>So when running
>```
># systemctl restart firewalld.service
>Failed to restart firewalld.service: Transaction contains conflicting jobs 'restart' and 'stop' for fail2ban.service. Probably contradicting requirement dependencies configured.
>See system logs and 'systemctl status firewalld.service' for details.
>
>```
>
>Any clue ?
>

This looks like an issue with either the firewalld or fail2ban systemd 
service. That may be provided by your distribution. firewalld's upstream 
systemd service does not mention fail2ban. Check the installed systemd 
files.

**Comment by aboe76** [comment]
@erig0, it's on the fail2ban side, they maintain a systemd service file see this bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871993

It has a patch in there:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=871993;filename=0001-Fix-failure-to-restart-firewalld.patch;msg=20

**Comment by erig0** [comment]
Closing as per @aboe76 's comment. Thanks!
