### ISSUE TITLE
firewalld.service takes 40 seconds during boot.

### ISSUE THREAD

**Issue by tupio** [firewalld/firewalld#667]
Hi,
I have noted that firewalld.service is taking the most amount of time in the boot process. Is there any way that I can reduce its time.

## System
* OS: fedora 32

### systemd-analyse outputs

```
$ systemd-analyze blame
41.288s plymouth-quit-wait.service                                                               
40.529s firewalld.service                                                                        
26.892s udisks2.service                                                                          
26.856s ModemManager.service                                                                     
18.812s lvm2-monitor.service                                                                     
17.983s systemd-udev-settle.service                                                              
16.794s cups.service                                                                             
11.488s initrd-switch-root.service                                                               
10.614s sssd.service                                                                             
 9.068s avahi-daemon.service                                                                     
 8.859s rtkit-daemon.service    
```

```
$ systemd-analyze critical-chain firewalld.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

firewalld.service +40.529s
└─polkit.service @46.196s +1.712s
  └─basic.target @33.630s
    └─dbus-broker.service @34.522s +8.072s
      └─dbus.socket @33.591s
        └─sysinit.target @33.555s
          └─systemd-userdbd.service @1min 20.591s +546ms
            └─systemd-userdbd.socket @9.376s
              └─system.slice
                └─-.slice
```

**Comment by erig0** [comment]
Are you using an ipset with a large number of entries?

**Comment by erig0** [comment]
Make sure you have this Fedora nftables fix:

https://bugzilla.redhat.com/show_bug.cgi?id=1834853

**Comment by tupio** [comment]
Hi, thank you for your response. 
I couldn't find any entries for ipset. I don't know whether that bug is the issue but the bug is already closed and I have updated to the latest. I could find 169 files in /usr/lib/firewalld/services.

If you want more information please tell me on how to fetch it.

**Comment by erig0** [comment]
> I couldn't find any entries for ipset.

Do you have anything in `/etc/firewalld/ipsets/` ?

Are you using fail2ban or similar service?

**Comment by tupio** [comment]
> > I couldn't find any entries for ipset.
> 
> Do you have anything in `/etc/firewalld/ipsets/` ?

That is a empty folder

> Are you using fail2ban or similar service?

There is none of those.

**Comment by erig0** [comment]
This is definitely abnormal. There are many possibilities:
- nftables set bug I mentioned above (already ruled out)
- lock contention, i.e. something else doing many iptables operations

You appear to have other services with slow starts. Maybe there is something going on outside of firewalld.

**Comment by tupio** [comment]
Is there any way to collect debug information that could be useful.

**Comment by erig0** [comment]
On Tue, Jul 21, 2020 at 06:26:53PM -0700, Magic Man wrote:
>Is there any way to collect debug information that could be useful.

You can enable debug output in /etc/sysconfig/firewalld. Restart the 
service, then check `/var/log/firewalld` and/or `journalctl`.

**Comment by tupio** [comment]
When I tried that, the service failed to start and lost my internet connectivity. I had to restart the entire system to make it run again. The `journalctl` doesn't give other than it failed to start. This is done yesterday and doesn't have any logs right now. Should I run again?

**Comment by erig0** [comment]
On Wed, Jul 22, 2020 at 06:07:26AM -0700, Magic Man wrote:
>When I tried that, the service failed to start and lost my internet 
>connectivity. I had to restart the entire system to make it run again. 
>The `journalctl` doesn't give other than it failed to start. This is 
>done yesterday and doesn't have any logs right now. Should I run again?

It seems unlikely that enabling debug caused the failed start. More 
likely it was caused by whatever is also causing the delayed start.

I suggests trying again.

**Comment by tupio** [comment]
This is the portion of `/var/log/firewalld`. Interestingly the firewalled didn't crash this time.

[log2.txt](https://github.com/firewalld/firewalld/files/4963815/log2.txt)

**Comment by tupio** [comment]
Interestingly the problem vanished in this boot and only took 472ms to load.

**Comment by erig0** [comment]
> This is the portion of `/var/log/firewalld`. Interestingly the firewalled didn't crash this time.
> Interestingly the problem vanished in this boot and only took 472ms to load.
> 
> [log2.txt](https://github.com/firewalld/firewalld/files/4963815/log2.txt)

I don't see anything suspicious in the log. It all looks normal.

**Comment by tupio** [comment]
I think this issue can be closed. If the problem resurfaces I will reopen this.
Thank you for investing your time.
