### ISSUE TITLE
HTML in system tray tooltip title

### ISSUE THREAD

**Issue by nicolasfella** [firewalld/firewalld#668]
The system tray uses HTML markup in the tooltip title, which is not allowed by the [StatusNotifierItem spec](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/). It only mentions HTML markup in the tooltip text. This results in HTML code being visible when hovering the system tray icon in Plasma.

We received [several reports about this](https://bugs.kde.org/show_bug.cgi?id=422616) in Plasma so I'm reporting it here since Plasma is behaving correctly according to my understanding of the spec.

**Comment by nicolasfella** [comment]
Screenshot from one of the reports:

![image](https://user-images.githubusercontent.com/6377822/87975145-85316480-cacb-11ea-900d-f586ee7702db.png)

**Comment by alsoGAMER** [comment]
![image](https://user-images.githubusercontent.com/35269770/89133946-da846180-d520-11ea-9cd5-a171034ad568.png)
> same issue here

**Comment by mrostecki** [comment]
KDE doesn't support full HTML content in notifications anymore (for security reasons). Notifications need to follow the spec:

https://specifications.freedesktop.org/notification-spec/latest/ar01s04.html

I will prepare a fix for that.

**Comment by fkru** [comment]
Given TW20200922 with firewall-applet 0.9.0, is there any news regarding the aforementioned fix? Thx.

**Comment by Vogtinator** [comment]
> KDE doesn't support HTML content in notifications anymore (for security reasons).

Not true, it's only about the title. The text still allows HTML, as required by the SNI spec.

**Comment by vmsantos** [comment]
![image](https://user-images.githubusercontent.com/31750046/103041100-2d07fe00-4554-11eb-9498-51dbf19f0020.png)
Same here. Running firewalld 0.9.1 on KDE Plasma 5.20.4.

**Comment by jbarsan** [comment]
Hello guys, I have version 0.9.3 installed on my system with KDE 5.21 and the problem with the firewalld applet continues. Are there any predictions for the repair?
![errofirewalld](https://user-images.githubusercontent.com/16598742/112059832-27ae5580-8b3b-11eb-8ea8-25b83f33c9e6.png)
