### ISSUE TITLE
Running firewalld as unprivileged user

### ISSUE THREAD

**Issue by Exchizz** [firewalld/firewalld#669]
Hi,

I'm wondering why firewalld is runnnig as root and not as an unprivileged user ?  I'm aware firewalld needs to talk to iptables, nftables etc.

I've done the following steps in order to run firewalld as an unprv. user:

1.  Add the following lines to /etc/sudoers:
```
firewalld-user ALL=NOPASSWD: /usr/sbin/iptables-restore -w -L -n 
firewalld-user ALL=NOPASSWD: /usr/sbin/nft *
firewalld-user ALL=NOPASSWD: /sbin/modprobe nf_conntracker
```
2.  
```
sudo chown -R firewalld-user:firewalld-user /run/firewalld/
```

3.  Add sudo to /usr/lib/python3/dist-packages/firewall/core/prog.py:51 like shown below
```
    args = ["sudo",prog] + argv
```
However I'm struggling a bit with polkit, but from the steps above I can run firewalld as firewalld-user.  With the following command:
```
 /usr/sbin/firewalld --nofork --debug 10  --nopid --log-file /tmp/
```

Did anyone manage to do this in a better way?

**Comment by erig0** [comment]
> I'm wondering why firewalld is runnnig as root and not as an unprivileged user ? I'm aware firewalld needs to talk to iptables, nftables etc.

Newer versions (v0.8.0+) of firewalld use libnftables. They don't call the `nft` binary. As such the tricks you use here won't work.

**Comment by erig0** [comment]
Because of libnftables there is no plan to support running as an unprivileged user.
