### ISSUE TITLE
Firewall applet shows markup syntax on tooltip

### ISSUE THREAD

**Issue by YeldhamDev** [firewalld/firewalld#670]
The tooltip shown when hovering the applet shows unformatted tags:
![Screenshot_20200722_122828](https://user-images.githubusercontent.com/30739239/88310160-dc6b4b00-ccfe-11ea-9d4e-f6fe4b6a0d9b.png)

**Comment by fkru** [comment]
I can confirm the above-mentioned issue with openSUSE Tumbleweed 20200721, KDE Plasma 5.19.3, and firewall-applet 0.7.4.

**Comment by Vogtinator** [comment]
Dup of https://github.com/firewalld/firewalld/issues/668

**Comment by YeldhamDev** [comment]
@Vogtinator Oops, didn't see that one.
