### ISSUE TITLE
Config path needed for --check-config (for Ansible validation check)

### ISSUE THREAD

**Issue by AquaL1te** [firewalld/firewalld#671]
I'm running the following.
* ansible-2.9.10-1.fc32.noarch
* firewalld-0.8.3-1.fc32.noarch

Because the [Ansible firewalld module](https://docs.ansible.com/ansible/latest/modules/firewalld_module.html) lacks functionality such as enable/disable logging and setting a default zone, I use the [lineinfile](https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html) module to change these settings in /etc/firewalld/firewalld.conf.

It's a best practice to use the [validate](https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html#parameter-validate) option. What this does is a configuration check of the temporary file that Ansible created, before it overwrites the provided destination file path. This comes in handy to make sure the config is only overwritten when the syntax is fine. For firewalld this would translate to the command `firewall-cmd --check-config`.

However, firewalld doesn't provide an option to set a custom configuration path, by default it always checks /etc/firewalld/firewalld.conf. This is a problem, because Ansible is then not able to validate the temporary config file. Therefore, I can't do a validation check with Ansible. Would it be possible to provide a `--config-file` switch? Or an optional argument for `--check-config` which then points to the config which a user wants to check?

**Comment by erig0** [comment]
On Mon, Jul 27, 2020 at 11:23:02AM -0700, AquaL1te wrote:
>However, firewalld doesn't provide an option to set a custom
>configuration path,

But it does. See `--default-config` and `--system-config` in man pages
for firewall-offline-cmd and firewalld. These are used heavily in
firewalld's own testsuite.

**Comment by erig0** [comment]
Closing NOTABUG as we already support this.
