### ISSUE TITLE
Where to begin with a network clammed-up CentOS 8 Stream

### ISSUE THREAD

**Issue by mtkAtGH** [firewalld/firewalld#674]
This is an information pointer question.

About July 20, 2020 a fresh x86_64 CentOS 8 Stream was successfully installed through the net. The intended use was for DB server, and also as Workstation so server/workstation installation profile was chosen. All was well and the core booted and about 5 user-land apps were installed over the net and run successfully.

On start-up the boot image says "CentOS Linux (4.18.0-193.6.3.e18_2.x86_64) 8 (Core)" and
'uname -a' says: "Linux localhost.localdomain 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UCT 2020 X86_64 GNU/Linux"

A week into this working install, the external ISP Wifi router got changed and the CentOS network clammed up.

After a week of futile old style network configuration (gw='_gateway' all over), the issue persists and seems to be around the Firewall that is also part of Server/Workstation package!

'firewall-cmd --version' says "0.8.0"

So the question is where does one go to let CentOS 8 /  Firewalld 0.8.0 rediscover and reset the appropriate zones and source addresses which changed? The prior ones were established by the CentOS installer without any significant console user input.

**Comment by erig0** [comment]
> So the question is where does one go to let CentOS 8 / Firewalld 0.8.0 rediscover and reset the appropriate zones and source addresses which changed? The prior ones were established by the CentOS installer without any significant console user input.

The stock zones and configuration is in `/usr/lib/firewalld`. When a user/entity changes them they are copied to `/etc/firewalld`. You can revert to the stock configuration by removing everything in the subdirectories of `/etc/firewalld`.

**Comment by mtkAtGH** [comment]
Does this also entail re(moving) firewalld.conf?
'systemctl status firewalld' complains on its absence and then warns of drifting zones but firewalld remains clammed up.

The /etc/firewalld/zones directory is not repopulated on reboot, and there are systemctl status complaints:
firewalld[995]: WARNING: COMMAND_FAILED: '/usr/bin/iptables -w10 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?)

(and similar status lines for --protocol udp and also for --destination-port 53)

Is this more a CentOS 8 issue?

Apart from the DHCP client address assignment on the external interface LAN-169.254.0.XYZ/16, I do not see any semblance of auto discovery which seemed to have happened during installation.

Perhaps I should indicate CentOS/Firewlld external is two non-routeable hops from the real internet:->[LAN-169.254.0.1/16]->[LAN-192.168.1.1/24]->[LTE-192.168.1.100/24]<in the ISP Domain which changed from LTE-192.168.8.1/24>

**Comment by erig0** [comment]
> Does this also entail re(moving) firewalld.conf?

No. That's why I said "remove everything in subdirectories".

> 'systemctl status firewalld' complains on its absence and then warns of drifting zones but firewalld remains clammed up.

That's expected. `/etc/firewalld/firewalld.conf` should exist.

> The /etc/firewalld/zones directory is not repopulated on reboot

It shouldn't. It will only be populated once you change a zone's configuration.

> and there are systemctl status complaints:
> firewalld[995]: WARNING: COMMAND_FAILED: '/usr/bin/iptables -w10 -w --table filter --delete INPUT --in-interface virbr0 --protocol tcp --destination-port 67 --jump ACCEPT' failed: iptables: Bad rule (does a matching rule exist in that chain?)

libvirt is telling firewalld to delete a rule that doesn't exist. I think you can ignore this.

> Is this more a CentOS 8 issue?
> 
> Apart from the DHCP client address assignment on the external interface LAN-169.254.0.XYZ/16, I do not see any semblance of auto discovery which seemed to have happened during installation.

That's not a DHCP assignment. It's an IPv4 link-local address. https://en.wikipedia.org/wiki/Link-local_address#IPv4

**Comment by mtkAtGH** [comment]
Thanks for the response:
>
>    The /etc/firewalld/zones directory is not repopulated on reboot
>
> It shouldn't. It will only be populated once you change a zone's configuration.

So might this imply the initial 'working' configuration of firewalld was done by CentOS Stream's installer?

By now, I'm now a bit vague on the blow-by-blow installation but there was no engaging section on setting firewall zones, services, etc.

There might have been a Yes/No query on starting the firewall which I assume was guessed at 'favourably'.
Guessing in the dark here, but perhaps the installer was using a samba-like path out of and into CentOS?
I say this because the Win7 I'm using at the moment is in the same network segment and it traverses the three hops readily, whereas CentOS is shut tight (no ping, no traceroute, no name resolution from ISP routers etc). I'm a bit hesitant on redoing a multi-gig network install just to get things working again

I've looked briefly at tcpdump interface traffic from the CentOS side and all is silent on that western front.

I wonder if there are CentOS install persons who might know what my 'default install' problem is?

**Comment by erig0** [comment]
> So might this imply the initial 'working' configuration of firewalld was done by CentOS Stream's installer?

firewalld ships with its own default/working config. CentOS should be very close if not identical to the upstream defaults.

> I say this because the Win7 I'm using at the moment is in the same network segment and it traverses the three hops readily, whereas CentOS is shut tight (no ping, no traceroute, no name resolution from ISP routers etc). I'm a bit hesitant on redoing a multi-gig network install just to get things working again

Does your CentOS node work if firewalld is disabled?

**Comment by mtkAtGH** [comment]
> Does your CentOS node work if firewalld is disabled?

after running a # sudo systemctl stop firewalld nothing seemed to happen then
after adding a route to the nearest resolver DNS resolves and little else so
ran tcpdump on the active interface (enp1s0) there was plenty DNS related chatter some belonging to the Wn32 host.
But with the final tcpdump summary on exit was:
50 packets captured
64 packets received by filter
14 packets dropped by kernel
The second time the same stats were 10, 49, 8 respectively.

Not sure what the next line of attack on this should be. I do know that my routers / switches are not kosher, being recycles from discontinued ISP setups but there could be other more toxic packets floating about. the Win32 relies on WebRoot for anything that gets past the ISP device.

With firewalld stopped, is Kernel still filtering out 'incoherent/irrelevant' packets?

**Comment by erig0** [comment]
> > Does your CentOS node work if firewalld is disabled?
> 
> after running a # sudo systemctl stop firewalld nothing seemed to happen then

Does this imply you have a general networking issue?

> With firewalld stopped, is Kernel still filtering out 'incoherent/irrelevant' packets?

Probably, but I don't know what specifically is being dropped in your scenario.

**Comment by mtkAtGH** [comment]
Yes I have a network issue still, but a step closer to solution I'll see if tcpdump can help.

Thanks.

**Comment by mtkAtGH** [comment]
Here's a first round of troubleshooting:
With CentOS and Win32 both sporting firefox most activity is dns & http from Win32 which also broadcasts netbios datagrams
With Win32 disabled http disappears and no netbios dgms, but many Ads and session services keep looking for Win32
Nearest Router can resolve and ping outside world as seen from CentOS firefox looking direct through http without DNS.
Other combinations tried included restarting firewalld and tcpdumping SentOS firefos start up.
The only finding is that CentOS does not open netbios service which the stock ISP routers seem to be listening to
Perhaps CentOS is emulating firewalld default settings in its firewalld-free kernel config

It seems a netbios service zone might 'unclam' the CentOS network being serviced by stock Wifi routers?

Will wait for thoughts on advisability of doing this before trying.

If it results in apositive outcome, it still does not explain how CentOS networked after initial install.
I notice CentOS has been raising GNOME update alerts (not sure how it got them) but fails to actually performed the update owing to this nagging shutout from lack of outbound network access.

What I don't know is if opening netbios service is all that one needs or whether one would need the Enterprise CentOS kernel to make it useful

**Comment by mtkAtGH** [comment]
Also should note that in the troubleshoot where I turned firewalld, I realise it came up with zone home(active) which  listed the services: cockpit, dhcpv6-client mdns samba-client ssh.
Also /etc/sysconfig/firewalld directory is still empty, and the active zone (home) differs from the one CentOS installed (public)

With this, DNS is resolving. for example:
# ping www.oracle.com
PING e2581.dscx.akamaiedge.net (2.21.103.162) 56(84) bytes of data.
^C
6 packets transmitted, 0 received, 100% packet loss, time 156ms
I'll try and zero in on a new outbound http session from tcpdump logs

**Comment by erig0** [comment]
I'm seriously confused. I see a lot of really weird things here:
1. You're using link-local addresses (169.25.0.0/16) and expecting them to be routed. This shouldn't happen. They're non-routable for a good reason.
2. You keep mentioning netbios. This is needed for CentOS. Maybe you mean DNS?
3. CentOS stock install should not have any firewall rules if firewalld is disabled. So it shouldn't block anything.

**Comment by erig0** [comment]
Closing as it's clear you have a basic networking issue. We can continue discussing with the issue closed.

**Comment by mtkAtGH** [comment]
It was indeed a network topology induced problem.

Moving CentOS from two to one hop away from the extranet got it networking again with active firewalld 'home' zone

Thanks for helping me get to the root of the problem. {:))

**Comment by mtkAtGH** [comment]
PS: Just for the record, the Win7 continues to network from two hops away through the same wires

**Comment by mtkAtGH** [comment]
Just to confirm Closure (of #674) with this final resolution for me: Today 17/10/2020 I retried reconnecting to internet via the old TPLINK router and it still failed, then on a hunch decided to change its default LAN IP from 169.254.0.0/16 to 10.0.0.0/8. This necessitated a parallel change on centos://etc/networks entry from "networks:link-local 169.254.0.0" to "networks:link-local 10.0.0.0"; then EVERYTHING began working. Why this, I cannot say why; CentOS 8 Stream itself has had two updates since 31 July 2020 when this thread was closed, but it might be useful to include this final snippet into the archive of this closed thread. 

----- Original Message -----

**Comment by mtkAtGH** [comment]
Can now also respond to (1): My accidental resolution shows that intranet routing ALLOWS sub-netting of DNS non-routables (how else would an intranet work?) 
I could not raise this while I was still guilty of networking problem by association. 

I think someone somewhere did allow intranetworkingfor 10/8 and forgot to do the same for 169.254/16. Most probably on the CentOS side because there was a similar problem raised a year before with CentOS 7 I think. 


----- Original Message -----
