### ISSUE TITLE
Cannot create direct rules with wildcard interface names

### ISSUE THREAD

**Issue by sircubbi** [firewalld/firewalld#679]
When trying to create a rule which should match all interfaces, the wildcard in the interfacename gets wrongly quoted and therefore does not work.

Reproduceable on CentOS 8 (firewalld 0.8.0):
Create a new rule with `firewall-cmd --permanent --direct --add-rule eb filter FORWARD 10 -i "vnet*" -d BGA -j DROP`.

This creates the following configuration:
```
# cat /etc/firewalld/direct.xml
<?xml version="1.0" encoding="utf-8"?>
<direct>
  <rule ipv="eb" table="filter" chain="FORWARD" priority="10">-i 'vnet*' -d BGA -j DROP</rule>
</direct>
#
```

However when the ruleset is loaded the resulting rule looks like this:
```
# nft list table bridge filter
table bridge filter {
	chain INPUT {
		type filter hook input priority filter; policy accept;
	}

	chain FORWARD {
		type filter hook forward priority filter; policy accept;
		iifname "vnet\*" ether daddr 01:80:c2:00:00:00 counter packets 0 bytes 0 drop
	}

	chain OUTPUT {
		type filter hook output priority filter; policy accept;
	}
}
```

That rule does not match correctly, as the asterisk got quoted by firewalld.

Creating a manually rule via `nft add rule bridge filter FORWARD iifname "vnet*" ether daddr 01:80:c2:00:00:00 counter packets 0 bytes 0 drop` does work as expected.

I could not find any hint on how to properly create a wildcard-rule using firewall-cmd.

**Comment by erig0** [comment]
As per the iptables man page..
>[!] -i, --in-interface name
       Name of an interface via which a packet was received  (only  for
       packets  entering  the  INPUT,  FORWARD  and PREROUTING chains).
       When the "!" argument is used before  the  interface  name,  the
       sense  is  inverted.   If the interface name ends in a "+", then
       any interface which begins with this name will match.   If  this
       option is omitted, any interface name will match.

As such, use '+' instead of a '*'.

**Comment by sircubbi** [comment]
Just to add here: when using nftables you have to use "*". But you are right, issuing the rule with "+" does properly translate to "*" wenn firewalld is used with nftables. Did not know that, maybe that should be added to the documentation (at least I could not find anything about this issue or how to work around it).

Issue can be closed of course. Thanks.
