### ISSUE TITLE
Support country-code matches via GeoIP integration

### ISSUE THREAD

**Issue by pprindeville** [firewalld/firewalld#682]
On other firewall platforms I do country-based blocking (usually with silent drops so my logs don't fill up) on devices that tend to be aggressively scanned by countries with my state-sponsored APT's (China, North Korea, Russia, Bulgaria, Venezuela, Iran, etc).

This would be a useful capability to add here, even on servers in a DMZ with buttoned-down port-forwarding.

**Comment by pprindeville** [comment]
Of course, this implies that the user is willing to refresh the GeoIP database regularly so that the data doesn't become out-of-date.

**Comment by erig0** [comment]
This can easily be done with ipsets.

**Comment by pprindeville** [comment]
What external support is necessary?  Has the glue described in [GeoIP matching](https://wiki.nftables.org/wiki-nftables/index.php/GeoIP_matching) been integrated?

**Comment by erig0** [comment]
None. You'll have to update the ipset entries. There is no dynamic geoip lookup support.
An update would like like this:
```
# firewall-cmd --permanent --ipset=denylist --remove-entries-from-file=country.zone
# wget https://example.com/country.zone
# firewall-cmd --permanent --ipset=denylist --add-entries-from-file=country.zone

```
