### ISSUE TITLE
GRE tests are skipped if nf_conntrack_proto_gre is builtin

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#688]
When running the unit tests on Debian, all GRE related tests are skipped, like
```
 98: GRE proto helper                                skipped (pr323.at:4)
188: GRE proto helper                                skipped (pr323.at:4)
```
The problem afaics is that `CHECK_MODULE_PROTO_GRE` runs
`modinfo nf_conntrack_proto_gre` but on Debian this is not a module, but builtin:
```
$ grep CONFIG_NF_CT_PROTO_GRE /boot/config-5.7.0-3-amd64 
CONFIG_NF_CT_PROTO_GRE=y
```

**Comment by erig0** [comment]
Makes sense. The test verifies that the module is loaded properly when adding the GRE service. If there is no module (i.e. it's built in) then the test can't check. :)

**Comment by mbiebl** [comment]
Hm, right. pr323 has 
```
AT_CHECK([lsmod | grep nf_conntrack_proto_gre], 0, ignore)
```
Is there a reason why you explicitly check for the kernel being available as modules instead of simply testing the GRE functionality?

**Comment by erig0** [comment]
There was a bug that caused the module to _not_ be loaded if the service was enabled.

https://github.com/firewalld/firewalld/issues/263

**Comment by mbiebl** [comment]
Ah, ok. So this test is only for checking if the autoloading of the gre module works? In that case, it obviously makes sense to skip it if builtin.

**Comment by erig0** [comment]
Correct. Closing this issue.

**Comment by mbiebl** [comment]
Thanks and sorry for the noise. Should have investigated this more carefully
