### ISSUE TITLE
test rhbz1871298 timeouts on slow architectures

### ISSUE THREAD

**Issue by LocutusOfBorg** [firewalld/firewalld#691]
Hello, looks like in Ubuntu/arm64 we are getting a test failure on rhbz1871298.

I patched to increase the timeout from 45 seconds to 450 (not a good number, I know), but the test passed.

I don't know which value might be a good number, but can you please increase it a little bit?

http://launchpadlibrarian.net/497760591/firewalld_0.9.0-1_0.9.0-1ubuntu1.diff.gz

https://autopkgtest.ubuntu.com/packages/f/firewalld/groovy/arm64

cc @erig0

**Comment by LocutusOfBorg** [comment]
(it would be really nice, as test feature, to print the seconds passed for each test, so we can quickly understand how different architectures performs

**Comment by erig0** [comment]
Fixed via 1401c61620a69 (#969).
