### ISSUE TITLE
Raw chain really correct or a typo?

### ISSUE THREAD

**Issue by AquaL1te** [firewalld/firewalld#695]
Below is a chain build by firewalld (firewalld-0.8.4-1.fc32.noarch). The syntax of the generated rules seem to have $type_$hook for the names of the chains. However, raw_PREROUTING is of type filter. Does this chain really do raw processing? I do see raw in the priority of the filter hook. But I don't see this "raw + 10" or "filter + 10" in the [priority documentation](https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains). Could you explain what this does or link to the correct page in the docs? But back to the main question, shouldn't this be of [type raw](https://wiki.nftables.org/wiki-nftables/index.php/Mangle_packet_header_fields)?

```
        chain raw_PREROUTING {
                type filter hook prerouting priority raw + 10; policy accept;
                icmpv6 type { nd-router-advert, nd-neighbor-solicit } accept
                meta nfproto ipv6 fib saddr . iif oif missing log prefix "rpfilter_DROP: " drop
                jump raw_PREROUTING_ZONES
        }
```

**Comment by erig0** [comment]
The chain/type/hook are all correct. In nftables the hook priority handles what in iptables was traditionally done in separate tables, e.g. `raw`, `mangle`.

firewalld uses an offset from the "standard" priorities, e.g. `raw`. This is done to give determinism if iptables rules are also in existence. If firewalld used the standard priorities, e.g. `raw`, the order of execution of: iptables, other nftables rules, and firewalld would be undefined. with the `+ 10` it's guaranteed that firewalld's rules are executed _after_ iptables/nftables.

**Comment by alexisfrjp** [comment]
It'd have been nice to see the +10 offset somewhere in the documentation though.
