### ISSUE TITLE
ICMP packets allowed via icmp-block-inversion logged as blocked

### ISSUE THREAD

**Issue by bapride11** [firewalld/firewalld#696]
Version: 0.8.0
Distribution: CentOS 8

When using a zone with a default target of DROP, it is my understanding that to allow ICMP requests through one must use an icmp-block-inversion and explicit "block" rules to explicitly allow certain types of ICMP traffic. However, when combined with --set-log-denied=all, the effective rules written to nftables end up logging the allowed activity as blocked. This can lead to quite noisy logs when one considers fairly normal traffic such as neighbor solicitations, etc. An example of generated nftables chain is given below:

```
chain filter_IN_public_allow {
                icmp type echo-request meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmp type echo-request accept
                icmpv6 type echo-request meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmpv6 type echo-request accept
                icmp type echo-reply meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmp type echo-reply accept
                icmpv6 type echo-reply meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmpv6 type echo-reply accept
                icmpv6 type nd-neighbor-advert meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmpv6 type nd-neighbor-advert accept
                icmp type router-advertisement meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmp type router-advertisement accept
                icmpv6 type nd-router-advert meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmpv6 type nd-router-advert accept
                icmp type router-solicitation meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
                icmp type router-solicitation accept
                ...
}
```

It's very possible I'm misunderstanding the purpose here, but I wouldn't imagine one would normally want to log accepted packets as blocked.

**Comment by erig0** [comment]
> Version: 0.8.0
> Distribution: CentOS 8
> 
> When using a zone with a default target of DROP, it is my understanding that to allow ICMP requests through one must use an icmp-block-inversion and explicit "block" rules to explicitly allow certain types of ICMP traffic.

I highly discourage this method. A better approach is to use rich rules.

e.g.
```
# firewall-cmd --zone <zone> --add-rich-rule='rich icmp-type name="echo-request" accept'
```

> However, when combined with --set-log-denied=all, the effective rules written to nftables end up logging the allowed activity as blocked. This can lead to quite noisy logs when one considers fairly normal traffic such as neighbor solicitations, etc. An example of generated nftables chain is given below:
> 
> ```
> chain filter_IN_public_allow {
>                 icmp type echo-request meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmp type echo-request accept
>                 icmpv6 type echo-request meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmpv6 type echo-request accept
>                 icmp type echo-reply meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmp type echo-reply accept
>                 icmpv6 type echo-reply meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmpv6 type echo-reply accept
>                 icmpv6 type nd-neighbor-advert meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmpv6 type nd-neighbor-advert accept
>                 icmp type router-advertisement meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmp type router-advertisement accept
>                 icmpv6 type nd-router-advert meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmpv6 type nd-router-advert accept
>                 icmp type router-solicitation meta pkttype host log prefix ""filter_public_ICMP_BLOCK: ""
>                 icmp type router-solicitation accept
>                 ...
> }
> ```

This is a bug. Those logs should not be present.

**Comment by blkeller** [comment]
> > When using a zone with a default target of DROP, it is my understanding that to allow ICMP requests through one must use an icmp-block-inversion and explicit "block" rules to explicitly allow certain types of ICMP traffic.
> 
> I highly discourage this method. A better approach is to use rich rules.

Red Hat's RHEL 8 documentation [explicitly says](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalld_securing-networks#listing-and-blocking-icmp-requests_managing-icmp-requests) to use the icmp-block-inversion method to achieve this, exactly as @bapride11 outlined.  @erig0, are you saying that the Red Hat docs are wrong and should be corrected?  Can you please be more specific about why you discourage this method?

**Comment by erig0** [comment]
> > > When using a zone with a default target of DROP, it is my understanding that to allow ICMP requests through one must use an icmp-block-inversion and explicit "block" rules to explicitly allow certain types of ICMP traffic.
> > 
> > 
> > I highly discourage this method. A better approach is to use rich rules.
> 
> Red Hat's RHEL 8 documentation [explicitly says](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/using-and-configuring-firewalld_securing-networks#listing-and-blocking-icmp-requests_managing-icmp-requests) to use the icmp-block-inversion method to achieve this, exactly as @bapride11 outlined. @erig0, are you saying that the Red Hat docs are wrong and should be corrected? Can you please be more specific about why you discourage this method?

The RHEL docs are not wrong. This method can get the desired results. However, I think it's confusing and cumbersome compared to the rich rule. Using a "block" to _allow_ something is awkward. To each their own.

**Comment by mo-markcrossland** [comment]
> The RHEL docs are not wrong. This method can get the desired results. However, I think it's confusing and cumbersome compared to the rich rule. Using a "block" to allow something is awkward. To each their own.

You've got that right! This bit of firewalld is a mess!

**Comment by yrro** [comment]
Pull requests welcome against https://gitlab.com/redhat/centos-stream/docs/enterprise-docs/-/blob/master/rhel-8/modules/packet-filtering/ref_listing-and-blocking-icmp-requests.adoc I'm sure :)
