### ISSUE TITLE
[firewalld 0.9.999] testsuite: 153 failed

### ISSUE THREAD

**Issue by TorontoMedia** [firewalld/firewalld#702]
TCP maximum segment size clamp testsuite fails with 'rich_tcp_mss_clamp.at:44: exit code was 1, expected 0'.
[Testsuite Log](https://github.com/firewalld/firewalld/files/5451720/error.log) of 'make check TESTSUITEFLAGS="153 -v"'

**Comment by vrindle** [comment]
In order for the test to pass the --debug needs to be added which writes the output to firewalld.log and subsequently allows for FWD_GREP_LOG to capture the error properly. Without the debug flag this test is failling.

**Comment by erig0** [comment]
> In order for the test to pass the --debug needs to be added which writes the output to firewalld.log and subsequently allows for FWD_GREP_LOG to capture the error properly. Without the debug flag this test is failling.

I disagree. See this comment thread: https://github.com/firewalld/firewalld/pull/678#discussion_r513908981

**Comment by TorontoMedia** [comment]
I can verify that testsuite 153 passes with pull #704, thanks!
