### ISSUE TITLE
Policy HOST -> "SOME ZONE" is wrong

### ISSUE THREAD

**Issue by VadimSvyatsky** [firewalld/firewalld#705]
If the outbound policy uses a service or port based on tcp, connection is not established.
The likely reason is that there is no rule in the chain "OUTPUT" for states "RELATED,ESTABLISHED"

**Comment by erig0** [comment]
Can you share your configuration. Specifically any policies you've created.

**Comment by VadimSvyatsky** [comment]
<?xml version="1.0" encoding="utf-8"?>
<policy target="REJECT">
  <ingress-zone name="HOST"/>
  <egress-zone name="external"/>
  <rule family="ipv4" priority="1">
    <destination address="195.177.240.0/23"/>
    <service name="ntp"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="2">
    <destination address="195.177.240.0/23"/>
    <service name="dns"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="3">
    <destination address="195.177.240.0/23"/>
    <service name="smtp"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="http"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="5">
    <service name="https"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="6">
    <log prefix="debug: "/>
  </rule>
</policy>

**Comment by VadimSvyatsky** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<policy target="REJECT">
  <ingress-zone name="HOST"/>
  <egress-zone name="external"/>
  <rule family="ipv4" priority="1">
    <destination address="195.177.240.0/23"/>
    <service name="ntp"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="2">
    <destination address="195.177.240.0/23"/>
    <service name="dns"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="3">
    <destination address="195.177.240.0/23"/>
    <service name="smtp"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="http"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="5">
    <service name="https"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="6">
    <log prefix="debug: "/>
  </rule>
</policy>
`


In this configuration all udp-based services is working and all tcp-based services - is not working

**Comment by erig0** [comment]
Yes. The `OUTPUT` chain needs a generic `ct state established,untracked accept` statement just like other chains: `INPUT`, `FORWARD`. Thanks for reporting.

**Comment by erig0** [comment]
@VadimSvyatsky , I created PR #709 to fix this issue. It would be great if you could pull and test that PR.

**Comment by VadimSvyatsky** [comment]
Hello
I have applied pr #709 
and then i compiled the firewalld.
Everything works now.
This issue can be clossed.

**Comment by erig0** [comment]
Thanks for confirming. Merging the PR.

**Comment by mailinglists35** [comment]
if I'm using v1.2.1 in EL9, is this the right approach/workaround?

>sudo firewall-cmd --direct --add-rule ipv4 filter OUTPUT 0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

**Comment by mailinglists35** [comment]
hm, it seems it is already done in v.1.2.1, correct?
````
table inet firewalld {
[...]
        chain filter_FORWARD {
                [...]
                ct state { established, related } accept
        [...] 
        chain filter_OUTPUT {
                [...]
                ct state { established, related } accept
[...]
````
