### ISSUE TITLE
RFE: rich: support using ipset in destination

### ISSUE THREAD

**Issue by VadimSvyatsky** [firewalld/firewalld#706]
I propose to provide an opportunity to use "ipset" in the section "destination" in the "rich rules".

**Comment by derekdai** [comment]
#711

**Comment by VadimSvyatsky** [comment]
thanks
Can I suggest some more changes?


пт, 13 нояб. 2020 г. в 02:25, Eric Garver <notifications@github.com>:

**Comment by erig0** [comment]
> thanks Can I suggest some more changes?

Sure. Please file a new issue/RFE.

**Comment by VadimSvyatsky** [comment]
I have compiled the code from the branch "master".
And.............
Error: PARSE_ERROR: 'INT-EXT.xml': Missing attribute address for destination

**Comment by erig0** [comment]
Can you show the contents of `/etc/firewalld/zones/INT-EXT.xml` ?

**Comment by VadimSvyatsky** [comment]
<?xml version="1.0" encoding="utf-8"?>
<policy target="REJECT">
  <ingress-zone name="internal"/>
  <egress-zone name="external"/>
  <rule family="ipv4" priority="1">
    <source ipset="NAME-1"/>
    <destination ipset="NAME-2"/>
    <service name="ntp"/>
    <accept/>
  </rule>
</policy>



пт, 13 нояб. 2020 г. в 14:50, Eric Garver <notifications@github.com>:

**Comment by erig0** [comment]
I am unable to reproduce the error. Are you sure you built and installed the code from master properly?

**Comment by VadimSvyatsky** [comment]
Ок.

i will check myself


пт, 13 нояб. 2020 г. в 20:39, Eric Garver <notifications@github.com>:

**Comment by VadimSvyatsky** [comment]
1. What branch i must to use?
I use the branch "master" (git clone https://github.com/firewalld/firewalld
master)

2. What the syntax for the section "destination" with ipset?

пн, 16 нояб. 2020 г. в 09:43, Vadim Svyatsky <vadim.svyatsky@gmail.com>:

**Comment by VadimSvyatsky** [comment]
I understood - the chain in iptableы/nftables is being built.

But, The command "firewall-cmd --check-config" reports about incorrect syntax.


пн, 16 нояб. 2020 г. в 11:38, Vadim Svyatsky <vadim.svyatsky@gmail.com>:

**Comment by VadimSvyatsky** [comment]
firewall-cmd --list-all-policies
or
 firewall-cmd --info-policy="SOME NAME OF POLICY"
This commands does not work if policy has destination with ipset

пн, 16 нояб. 2020 г. в 11:57, Vadim Svyatsky <vadim.svyatsky@gmail.com>:

**Comment by erig0** [comment]
> 1. What branch i must to use? I use the branch "master" (git clone https://github.com/firewalld/firewalld master)

Yes. Master branch.

> 2. What the syntax for the section "destination" with ipset?

Example:
```
#firewall-cmd --permanent --add-rich-rule='rule family=ipv4 destination ipset=foobar accept'
```

**Comment by erig0** [comment]
It sounds like you have no installed firewalld properly. Simply running it from the git checkout is insufficient because it won't find the correct python classes - you'd have to set `PYTHONPATH`.

It's better to build the RPMs. This assumes you've installed all the build dependencies.
```
# ./autogen.sh
# ./configure PYTHON=/usr/bin/python3
# make
# make test-rpm
# dnf install /root/rpmbuild/RPMS/noarch/firewalld-0.9.999-1.el8.noarch.rpm \
              /root/rpmbuild/RPMS/noarch/python3-firewall-0.9.999-1.el8.noarch.rpm \
              /root/rpmbuild/RPMS/noarch/firewalld-filesystem-0.9.999-1.el8.noarch.rpm \
              /root/rpmbuild/RPMS/noarch/firewall-config-0.9.999-1.el8.noarch.rpm
```
