### ISSUE TITLE
rich: directive "include" for the services is not working

### ISSUE THREAD

**Issue by VadimSvyatsky** [firewalld/firewalld#707]
```
# firewall-cmd --permanent --service=test --add-include=http
success
# firewall-cmd --permanent --service=test --add-include=https
success
# firewall-cmd --permanent --service=test --add-include=ftp
success
# firewall-cmd --reload
```

I try to include this service "test" to the rich rule and control action (iptables -nvL)
Rule lines in iptables for this service are not set

**Comment by erig0** [comment]
Please share the XML of the `test` service.

i.e.
```
# cat /etc/firewalld/services/test.xml
```

**Comment by VadimSvyatsky** [comment]
sure.
Here is a simple test construct
`<?xml version="1.0" encoding="utf-8"?>
<service>
  <include service="http"/>
  <include service="https"/>
  <include service="ftp"/>
</service>
`

**Comment by erig0** [comment]
Are you sure you're using the `iptables` backend? firewalld defaults to `nftables`.

**Comment by VadimSvyatsky** [comment]
Hi.
I am absolutely sure of that.
backend = iptables

**Comment by erig0** [comment]
Can you share your `iptables-save` output?

**Comment by VadimSvyatsky** [comment]
Chain IN_dmz_post (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8 limit: avg 1666/sec burst 5
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 13 limit: avg 1666/sec burst 5
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 3
    0     0 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 12
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 ctstate NEW,UNTRACKED

**Comment by VadimSvyatsky** [comment]
<?xml version="1.0" encoding="utf-8"?>
<zone target="%%REJECT%%">
  <short>DMZ</short>
  <description>For computers in your demilitarized zone that are publicly-accessible with limited access to your internal network. Only selected
  <interface name="ens35"/>
  <icmp-block-inversion/>
  <rule family="ipv4" priority="1">
    <icmp-type name="echo-request"/>
    <accept>
      <limit value="100000/m"/>
    </accept>
  </rule>
  <rule family="ipv4" priority="2">
    <icmp-type name="timestamp-request"/>
    <accept>
      <limit value="100000/m"/>
    </accept>
  </rule>
  <rule family="ipv4" priority="3">
    <icmp-type name="destination-unreachable"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <icmp-type name="parameter-problem"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="test"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="http"/>
    <accept/>
  </rule>
</zone>

**Comment by VadimSvyatsky** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<zone target="%%REJECT%%">
  <short>DMZ</short>
  <description>For computers in your demilitarized zone that are publicly-accessible with limited access to your internal network. Only selected
  <interface name="ens35"/>
  <icmp-block-inversion/>
  <rule family="ipv4" priority="1">
    <icmp-type name="echo-request"/>
    <accept>
      <limit value="100000/m"/>
    </accept>
  </rule>
  <rule family="ipv4" priority="2">
    <icmp-type name="timestamp-request"/>
    <accept>
      <limit value="100000/m"/>
    </accept>
  </rule>
  <rule family="ipv4" priority="3">
    <icmp-type name="destination-unreachable"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <icmp-type name="parameter-problem"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="test"/>
    <accept/>
  </rule>
  <rule family="ipv4" priority="4">
    <service name="http"/>
    <accept/>
  </rule>
</zone>
`

**Comment by VadimSvyatsky** [comment]
As you can see, there are two services in the rules, but only one in iptables. No service with include directives

**Comment by erig0** [comment]
I can confirm service includes are broken if used from a rich rule.
