### ISSUE TITLE
SNAT rules applied via firewalld direct rules don't match when using nftables backend

### ISSUE THREAD

**Issue by Nodens-** [firewalld/firewalld#708]
I have been using these direct rules in order to do 1:1 NAT and expose servers with private addresses via wireguard gateway to the internet.

```
  <passthrough ipv="ipv4">-t nat -A PREROUTING -i eno1 -d xxx.xxx.xxx.xxx -j DNAT --to-destination 10.99.99.21</passthrough>
  <passthrough ipv="ipv4">-t nat -A POSTROUTING -s 10.99.99.21 -o eno1 -j SNAT --to xxx.xxx.xxx.xxx</passthrough>
```

Since the upgrade to F32 with nftables backend (but also applying to F33 since I upgraded the servers by now to F33) the above does not work. The DNAT rule is matched but the SNAT rule is not as seen with `iptables -t nat -L -n -v`
I tried deleting the direct rules so that iptables is not used at all and implement them in nftables like this:
```
nft list table nat
table ip nat {
        chain postrouting {
                type nat hook postrouting priority srcnat; policy accept;
                ip saddr 10.99.99.21 oif "eno1" snat to xxx.xxx.xxx.xxx
        }

        chain prerouting {
                type nat hook prerouting priority dstnat; policy accept;
                iif "eno1" ip daddr xxx.xxx.xxx.xxx dnat to 10.99.99.21
        }
}
```
This is also not working and has the same effect of the DNAT rule being matched and the SNAT not.

As soon as I switched backend to iptables and deleted all nftables tables (switching backend and restarting firewalld leaves the nftables tables in place on Fedora and their presence still caused this) , SNAT starts working again.

I did further testing and switched to iptables-nft and company alternatives, with direct rules on firewalld so that iptables is not used and firewalld uses nftables for everything. Same result.

Version-Release number of selected component (if applicable):
firewalld-0.8.4-1
nftables-0.9.3-6

I have reported this on the Fedora bug tracker as well, here: https://bugzilla.redhat.com/show_bug.cgi?id=1893212

**Comment by erig0** [comment]
Can you share your firewalld config, `--list-all-zones`? Do you also have masquerading enabled in a zone? Or maybe zone `external` is the default zone?

**Comment by erig0** [comment]
Do you have other direct rules?

**Comment by Nodens-** [comment]
No masquerading enabled.
```
FedoraServer (active)
  target: default
  icmp-block-inversion: no
  interfaces: eno1 wg0
  sources:
  services: ark dhcpv6-client dns http https mumble pzserver smtp ssh wireguard znc
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```
direct.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<direct>
  <rule ipv="ipv4" table="filter" chain="FORWARD" priority="0">-i wg0 -o eno1 -j ACCEPT</rule>
  <rule ipv="ipv4" table="filter" chain="FORWARD" priority="0">-i eno1 -o wg0 -j ACCEPT</rule>
  <rule ipv="ipv4" table="filter" chain="FORWARD" priority="0">-i eno1 -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT</rule>
  <rule ipv="ipv6" table="filter" chain="FORWARD" priority="0">-i wg0 -o eno1 -j ACCEPT</rule>
  <rule ipv="ipv6" table="filter" chain="FORWARD" priority="0">-i eno1 -o wg0 -j ACCEPT</rule>
  <rule ipv="ipv6" table="filter" chain="FORWARD" priority="0">-i eno1 -o wg0 -m state --state RELATED,ESTABLISHED -j ACCEPT</rule>
  <passthrough ipv="ipv4">-t nat -A PREROUTING -i eno1 -d xxx.xxx.xxx.xxx -j DNAT --to-destination 10.99.99.21</passthrough>
  <passthrough ipv="ipv4">-t nat -A POSTROUTING -s 10.99.99.21 -o eno1 -j SNAT --to xxx.xxx.xxx.xxx</passthrough>
  <passthrough ipv="ipv6">-t nat -A PREROUTING -i eno1 -d xxxx:xxxx:xxxxx:xxxx::x -j DNAT --to-destination fdb9:b611:5d5d:ffff::21</passthrough>
  <passthrough ipv="ipv6">-t nat -A POSTROUTING -s fdb9:b611:5d5d:ffff::21 -o eno1 -j SNAT --to-source xxxx:xxxx:xxxxx:xxxx::x</passthrough>
  <passthrough ipv="ipv4">-t nat -A PREROUTING -i eno1 -d yyy.yyy.yyy.yyy -j DNAT --to-destination 10.99.99.66</passthrough>
  <passthrough ipv="ipv4">-t nat -A POSTROUTING -s 10.99.99.66 -o eno1 -j SNAT --to yyy.yyy.yyy.yyy</passthrough>
  <passthrough ipv="ipv6">-t nat -A PREROUTING -i eno1 -d yyyy:yyyy:yyyy:yyyy::y -j DNAT --to-destination fdb9:b611:5d5d:ffff::66</passthrough>
  <passthrough ipv="ipv6">-t nat -A POSTROUTING -s fdb9:b611:5d5d:ffff::66 -o eno1 -j SNAT --to-source yyyy:yyyy:yyyy:yyyy::y</passthrough>
</direct>
```

**Comment by Nodens-** [comment]
As a sidenote, because I just did a quick test, if I enable masquerading on top of this, the SNAT rules begin to start counting matches and traffic goes actually through but the result on the other end is that both servers get NATed with the gateway's primary ip instead of the ones assigned by SNAT.

**Comment by erig0** [comment]
This makes sense. It's due to the fact that iptables and nftables rules are executed independently inside the kernel/netfilter. So your scenarios are:

1. iptables backend
    - your direct rules accept the packets in the FORWARD chain
    - further iptables rules in the FORWARD chain are not evaluated (due to accept)
    - firewalld rules are part of iptables, so they're not considered
2. nftables backend
    - your direct rules accept the packets in the FORWARD chain
    - further iptables rules in the FORWARD chain are not evaluated (due to accept)
    - packet is now subject to firewalld's nftables ruleset
    - zone is using "default" target, so packet is dropped in the FORWARD chain
    - due to drop POSTROUTING (SNAT) is never reached

There is no fix. You options are:

1. continue use iptables backend
2. upgrade to firewalld v0.9.0 or later and use [policy objects](https://firewalld.org/2020/09/policy-objects-introduction) to do your FORWARD filtering and NAT.

**Comment by Nodens-** [comment]
@erig0 Thank you for the detailed explanation. Understood for the most part.

What I still don't understand is why it doesn't work when using iptables-nft alternatives which translate the iptables rules to native nftables ones. Shouldn't that just work since all rules are being applied to nftables and iptables is not in play at all?

Policy objects sound great and it looks like the way forward as the direct rule situation was somewhat messy to begin with. Hopefully v0.9.0+ will land on Fedora soon.

**Comment by erig0** [comment]
> @erig0 Thank you for the detailed explanation. Understood for the most part.
> 
> What I still don't understand is why it doesn't work when using iptables-nft alternatives which translate the iptables rules to native nftables ones. Shouldn't that just work since all rules are being applied to nftables and iptables is not in play at all?

No, because that's not actually how iptables-nft works. It's a common misconception. I even wrote a blog hoping to clarify the situation. I hope it helps.

https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables/

> Policy objects sound great and it looks like the way forward as the direct rule situation was somewhat messy to begin with. Hopefully v0.9.0+ will land on Fedora soon.

It's already in rawhide. So it'll be in the f34 release.
