### ISSUE TITLE
--new-service cannot combine --set-short and --set-description

### ISSUE THREAD

**Issue by sjvudp** [firewalld/firewalld#723]
**What happened**: Defining a new service I tried to use both `--set-short=` and `--set-description=`.
Message: `firewall-cmd: error: argument --set-short: not allowed with argument --set-description`

**What you expected to happen**:
It should work

**How to reproduce it (as minimally and precisely as possible)**:
`firewall-cmd --permanent --new-service=xxx --set-description=foo --set-short=bar --add-port=123/tcp`
**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): 0.5.5-4.24.9
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 
- OS (e.g: `cat /etc/os-release`): SLES 15-SP2
- Others:

**Comment by erig0** [comment]
This is not intended to work. It should be denied as per #722.

**Comment by sjvudp** [comment]
As the argument given in #722 is not convincing at all, I really wonder why two attributes cannot be changed in one call.
Even awk can set more than one variable in one command: `awk -v a=1 -v b=2 'BEGIN { print a,b }' /dev/null`
