### ISSUE TITLE
lockdown: create argument aliases: `--*-lockdown-allowlist`

### ISSUE THREAD

**Issue by erig0** [firewalld/firewalld#726]
1. The lockdown list uses the term `whitelist` and should be replaced with `allowlist`.
Examples:
```
# firewall-cmd --list-lockdown-whitelist-commands
# firewall-cmd --query-lockdown-whitelist-user=user
```

2. We should also replace the XML element is `lockdown-whitelist`. Current it's `<whitelist>`.
3. Finally the `lockdown-whitelist` should be renamed to `lockdown-allowlist`.
    - Will probably have to search for `lockdown-allowlist` first, then fall back to `lockdown-whitelist`

**Comment by thom311** [comment]
I think lockdown should be deprecated and eventually dropped (#1266). This API should not be extended further.

**Comment by erig0** [comment]
Closing this in favor of #1266.
