### ISSUE TITLE
how to override rule in firewalld

### ISSUE THREAD

**Issue by vissneha** [firewalld/firewalld#737]
**What would you like to be added**:
REJECT all -- anywhere anywhere reject-with icmp-host-prohibited
**Why is this needed**:
i want to override the below rule REJECT all -- anywhere anywhere reject-with icmp-host-prohibited permanently .
Because of this rule i am not able to detect slp service on other node in network . I tried adding port and service but no success.

**Comment by vissneha** [comment]
Is there a way i can delete **REJECT     all  --  anywhere             anywhere             reject-with icmp-h
ost-prohibited** this rule permanently.

**Comment by erig0** [comment]
No. This rule is vital to firewalld's functionality. Without it many zones, e.g. `public`, would be completely open. They would not block any traffic.

**Comment by vissneha** [comment]
> No. This rule is vital to firewalld's functionality. Without it many zones, e.g. `public`, would be completely open. They would not block any traffic.

I understand your point Eric ... i tried adding ports and added service in firewall as well but that is still not working as soon as i remove this rule slp service start working.
I have a requirement which need slp service to be running.

MGMT-1:/etc # firewall-cmd --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: ssh dhcpv6-client mountd slp
  ports: 427/tcp 427/udp
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:



port and service already been added but i dont know it still not getting discoverd from other node.

**Comment by erig0** [comment]
Have you use `--set-log-denied=all` to show where exactyl the packets are being dropped in the rule set?
