### ISSUE TITLE
dist tarball is missing doc/xml/*.xml

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#740]
The latest release 0.9.2 tarball does not ship the source .xml files for its documentation, making it impossible to rebuild the man pages.
This results in the following build failure:
```
make  all-am
make[3]: Entering directory '/build/firewalld-0.9.2/config'
/usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas --strict --dry-run  --schema-file=org.fedoraproject.FirewallConfig.gschema.xml && mkdir -p . && touch org.fedoraproject.FirewallConfig.gschema.valid
make[3]: Leaving directory '/build/firewalld-0.9.2/config'
make[2]: Leaving directory '/build/firewalld-0.9.2/config'
Making all in doc
make[2]: Entering directory '/build/firewalld-0.9.2/doc'
Making all in xml
make[3]: Entering directory '/build/firewalld-0.9.2/doc/xml'
make[3]: *** No rule to make target 'firewall-applet.xml', needed by '../man/man1/firewall-applet.1'.  Stop.
make[3]: Leaving directory '/build/firewalld-0.9.2/doc/xml'
make[2]: *** [Makefile:360: all-recursive] Error 1
make[2]: Leaving directory '/build/firewalld-0.9.2/doc'
make[1]: *** [Makefile:401: all-recursive] Error 1
make[1]: Leaving directory '/build/firewalld-0.9.2'
dh_auto_build: error: make -j4 returned exit code 2
make: *** [debian/rules:6: build] Error 25
```

**Comment by mbiebl** [comment]
https://github.com/firewalld/firewalld/releases/download/v0.9.2/firewalld-0.9.2.tar.gz

**Comment by erig0** [comment]
On Mon, Jan 04, 2021 at 03:51:54PM -0800, Michael Biebl wrote:
> The latest release 0.9.2 tarball does not ship the source .xml files for its documentation, making it impossible to rebuild the man pages.

Yikes. Sorry about that. Thanks for reporting. I'll get it fixed ASAP.
Probably simply doing a new release.

**Comment by erig0** [comment]
I rebuilt the dist tarball and uploaded it to the github release page. There were no functional changes. I mistakenly used `--disable-docs` when building the dist. New sha256 is `f982c72d640b0677d510b73d9b05d377b4615c5ef36a3710c62350b39fb62efe`

**Comment by erig0** [comment]
@mbiebl, PSA. Don't ship v0.9.2. One of the fixes causes a large increase in memory usage. I'm working on a fix and will release new versions afterwards. I'll be deleting the releases from github. Sorry!

**Comment by mbiebl** [comment]
Thanks for the heads-up. Thankfully I haven't uploaded 0.9.2 yet, so no harm done.
