### ISSUE TITLE
firewalld adds REJECT catch-all rules even when all zones are configured to have DROP target

### ISSUE THREAD

**Issue by afunix** [firewalld/firewalld#746]
**What happened**:
I'm trying to prevent the host to reply with ICMP when a port is blocked.
The natural thing would be to DROP all the packets which are not permitted with iptables rules.
Documentation seems to advise to set zone's target to DROP to achieve that.
So I've configured targets for all zones to DROP, but still have REJECT rules added as last ones in respective chains of iptables.

```
# firewall-cmd --get-active-zones
internal
  sources: 10.2.3.4
public
  interfaces: eth0

# firewall-cmd --zone=internal --list-all | grep target
  target: DROP

# firewall-cmd --zone=public --list-all | grep target
  target: DROP

# iptables -S | grep REJECT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
```

**What you expected to happen**:
```
# iptables -S | grep REJECT
# iptables -S | grep DROP
...
-A INPUT -j DROP
...
-A FORWARD -j DROP
...
```

**How to reproduce it (as minimally and precisely as possible)**:
For every active zone:
```
firewall-cmd --zone=<zone> --set-target=DROP
firewall-cmd --reload
```

**Anything else we need to know?**:

**Environment**:
- Firewalld Version: 0.6.3  (0.6.3-12.el7)
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 
- OS: CentOS Linux 7 (Core)

**Comment by afunix** [comment]
That's misleading when reading iptables rules, but it looks like firewalld actually adds drop rules to zone specific chain.

**Comment by erig0** [comment]
@afunix, correct. The top all reject is for zones that use the `default` target. Any other target, e.g. `ACCEPT`, `DROP`, will cause them to take effect inside the zone's rules.
