### ISSUE TITLE
Allow Configuration of sepcial IPTables Rules

### ISSUE THREAD

**Issue by romulus-ai** [firewalld/firewalld#750]
**What would you like to be added**:

Currently Firewalld in CentOS 7 adds rules like the following i.e. to the Forward Chain:

17   DROP       all  --  anywhere             anywhere             ctstate INVALID
18   REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Independent from the defined Target, the Policy of this chain is always accept and the last rule added by Firewalld is always this REJECT rule. However in some cases, it is neccessary to be able to manipulate those kind of rules and to change the Policy of the Chain!

Could you please add a mechanism to change the Policy of the Chain and, much more important, to prevent Firewalld, adding such default rules like the REJECT Rule!

**Why is this needed**:

This is needed, since we are running Calico on this CentOS Nodes and since Version 3.16, Calico adds a ACCEPT Rule in the Forward Chain after the REJECT Rule. And this is a big problem, since it prevents whole networking in Kubernetes to work properly.
For us it is currently a showstopper and we have to drop firewalld and configure IPTables on our own.

**Comment by erig0** [comment]
> **What would you like to be added**:
> 
> Currently Firewalld in CentOS 7 adds rules like the following i.e. to the Forward Chain:
> 
> 17 DROP all -- anywhere anywhere ctstate INVALID
> 18 REJECT all -- anywhere anywhere reject-with icmp-host-prohibited
> 
> Independent from the defined Target, the Policy of this chain is always accept and the last rule added by Firewalld is always this REJECT rule. However in some cases, it is neccessary to be able to manipulate those kind of rules and to change the Policy of the Chain!
> 
> Could you please add a mechanism to change the Policy of the Chain and, much more important, to prevent Firewalld, adding such default rules like the REJECT Rule!

No. This rule is vital to firewalld's functionality. Without it packets would be let through and completely violate the core tenant of firewalld, i.e. firewall zones.

> **Why is this needed**:
> 
> This is needed, since we are running Calico on this CentOS Nodes and since Version 3.16, Calico adds a ACCEPT Rule in the Forward Chain after the REJECT Rule. And this is a big problem, since it prevents whole networking in Kubernetes to work properly.

This sounds like a bug in Calico, not firewalld.

Calico can either
1. Add the ACCEPT rule using the correct index.
2. integrate with firewalld by adding the relevant interface/addresses to the `TRUSTED` zone

> For us it is currently a showstopper and we have to drop firewalld and configure IPTables on our own.

As I said above. This is not an issue in firewalld. It's an integration issue that must be solved on Calico's side.
