### ISSUE TITLE
Is `--list-all-zones` and `--list-all-zone` the same?

### ISSUE THREAD

**Issue by YangQing1989** [firewalld/firewalld#753]
As we can see, there is no option named `--list-all-zone` at all.
```
[root@localhost~]# firewall-cmd -h | grep  list-all-zone  
  --list-all-zones     List everything added for or enabled in all zones [P]
```

But `firewall-cmd --list-all-zone` do actualy return results!

OS: `CentOS Linux release 7.9.2009 (Core)`

**Comment by freekdk** [comment]
Op dinsdag 2 februari 2021 10:19:07 CET schreef 杨青:
> As we can see, there is no option named `--list-all-zone` at all.
> ```
> [root@localhost~]# firewall-cmd -h | grep  list-all-zone
>   --list-all-zones     List everything added for or enabled in all zones [P]
> ```
> 
> But `firewall-cmd --list-all-zone` do actualy return results!
> 
> OS: `CentOS Linux release 7.9.2009 (Core)`

Even `firewall-cmd --list-all-z` will give the same result.
The reason is that when the name of an option starts to be unique it will be 
recognized.

-- 
fr.gr.

member openSUSE
Freek de Kruijf

**Comment by erig0** [comment]
Partial argument matching is a feature of python's argparse module. This is expected behavior. However, make sure you use the full argument in scripts as in the future an argument with a similar prefix may be added.
