### ISSUE TITLE
[Question] outbound/output rules and filtering status ?

### ISSUE THREAD

**Issue by moocan** [firewalld/firewalld#764]
Hello,

Sorry, I would like to know what is the status of outbound/ouput rules or filtering with firewalld and if there is any zone support for these outbound rules.

All related issues #32 #197 #237 are closed, output-filtering branch (https://github.com/t-woerner/firewalld/tree/output-filtering) seems to be 4 years old, if the example mentionned by @t-woerner in #237 is [this one](https://github.com/firewalld/firewalld/issues/32#issuecomment-276556534) by @etcinit in #32 even if this example requires a patch or not, which version because some comment say 0.5, if there is any zone support and how to do it or if the only way is always the direct rule like `firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -p tcp -m tcp --dport=9000 -j DROP` ?

I looked for some documentation or complete example but I can't find anything. 

Thank you in advance.
Regards

**Comment by erig0** [comment]
You're probably not using new enough version. policy objects were introduced in `v0.9.0`. You should check the upstream blog. It gets a post for every major new feature and every release.

e.g.
- https://firewalld.org/2020/09/policy-objects-introduction
- https://firewalld.org/2020/09/firewalld-0-9-0-release
- https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic

**Comment by moocan** [comment]
@erig0 
Hello,
We are using 0.9.3
Thank you so much for your answer and documentation.
We quickly obtained a working template.

May I ask you, if you know if firewall-config will incorporate visibility on policies, ingress-zone, egress-zone in the future (if it's planned or not) because our security policies requires that a GUI like this one show a maximum of evidences for audit purpose otherwise the GUI need to be removed to avoid getting partial results.

Thank you
Regards

**Comment by erig0** [comment]
> May I ask you, if you know if firewall-config will incorporate visibility on policies, ingress-zone, egress-zone in the future (if it's planned or not) because our security policies requires that a GUI like this one show a maximum of evidences for audit purpose otherwise the GUI need to be removed to avoid getting partial results.

I had not planned to add support in the GUI. The GUI does not see a lot of attention mostly due to a lack of resources. I would gladly takes patches that add support.
