### ISSUE TITLE
Blocked dbus call to firewalld while starting Dockerd

### ISSUE THREAD

**Issue by wotmshuaisi** [firewalld/firewalld#765]
**What happened**:

I could not start my dockerd daemon process. From dockerd goroutine stack log, It seems like [firewalld blocked dockerd process](https://github.com/docker/for-linux/issues/1209).
If I start dockerd manually, I can see it is hanging on "Loading containers: start.". I also tried to run "sudo firewall-cmd --list-all" it hangs there as well, after few minutes I got

```
ERROR:dbus.proxies:Introspect error on :1.3:/org/fedoraproject/FirewallD1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Anything else we need to know?**:

**Environment**:
- Firewalld Version: firewalld 0.9.3-1
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): FirewallBackend=nftables

**Comment by erig0** [comment]
That sounds like firewalld is not running.

**Comment by wotmshuaisi** [comment]
> That sounds like firewalld is not running. Alternatively, maybe `dbus-daemon` (or `dbus-broker`) needs to be restarted due to a dbus config change.


```
● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2021-xx-xx xx:xx:xx xxx; 15h ago
       Docs: man:firewalld(1)
   Main PID: 425 (firewalld)
      Tasks: 2 (limit: 18996)
     Memory: 46.9M
     CGroup: /system.slice/firewalld.service
             ├─425 /usr/bin/python /usr/bin/firewalld --nofork --nopid
             └─529 /usr/bin/ebtables --concurrent -L

Mar xx xx:xx:xx desktop-ds0kghr systemd[1]: Starting firewalld - dynamic firewall daemon...
Mar xx xx:xx:xx desktop-ds0kghr systemd[1]: Started firewalld - dynamic firewall daemon.
```

I've changed nothing on dbus config. restart dbus not helping.

**Comment by alecbcs** [comment]
I can confirm that starting with Docker 20.10.5, the presence of Firewalld on a system (enabled or not) restricts dockerd from starting up. Detailed logs [here](https://dev.getsol.us/T9661) in my initial post on the Solus Development Portal. The only way I was able to get Docker to finally start up was by wiping the Firewalld installation from my machine.

**Comment by wotmshuaisi** [comment]
@alecbcs Same solution. works very well to me.
