### ISSUE TITLE
new policies should probably default to accept?

### ISSUE THREAD

**Issue by martinetd** [firewalld/firewalld#770]
**What happened**:

Apologizes if this already had been treated, I didn't find any similar issue.

I just noticed my VMs no longer had access to internet after upgrading to master last week (previously on f33 version pre 0.9)

**What you expected to happen**:

I didn't expect upgrading to break something that works!
Since pre-0.9 firewalld versions were lax I believe the default should stay that way, or have some way to make this obvious on upgrade that one should configure policies as they like.

Now I'm aware of the feature I'm very exited about it, output and forward rules are definitely something that is worth configuring, but this is also very hard to use for end users who don't have firwalld logs on and looking at dmesg -- maybe default workstation setups will have a separate daemon notify users about things blocked the first time a new output port is used or something?
But anyway I want to configure this when I have time for it and not by surprise when I try to install something in a VM in a hurry for debugging an unrelated issue :D

**How to reproduce it (as minimally and precisely as possible)**:

If that matters, I have two zones, VMs (and sometimes bridged ethernet) in an "internal" zone, wireless (and sometimes direct ethernet interface) in a "public" zone; this has always worked great for me and I was pleasantly surprised when I first set it up :)

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): de07c998e7afe8285ec26b4e75850915e45bc87f
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): nft
- OS (e.g: `cat /etc/os-release`): fedora 33 with custom firewalld upgrade

**Comment by erig0** [comment]
This has nothing to do with policies. It's a result of f2896e43c3a5. Short answer is to use the `trusted` zone instead of `internal`.

**Comment by martinetd** [comment]
Sorry, I did fix it by adding explicit policies after reading notes about the update, but it's more about communication/making it easier to see what's happening than an actual specific fix.


I don't remember why I had picked the name internal back then, but looking at man firewalld.zones I guess external would have been more appropriate than public (which wouldn't have broken my setup according to the commit message), but I still believe internal is more appropriate than trusted as "All network connections are accepted" is scary: I've just got a list of things allowed to the host on the internal network (local http server, tftp, dhcp, dns..), I don't want everything to be open!
```
       public
           For use in public areas. You do not trust the other computers on networks to not harm your computer. Only
           selected incoming connections are accepted.

       external
           For use on external networks with masquerading enabled especially for routers. You do not trust the other
           computers on networks to not harm your computer. Only selected incoming connections are accepted.

[...]

       internal
           For use on internal networks. You mostly trust the other computers on the networks to not harm your computer.
           Only selected incoming connections are accepted.

       trusted
           All network connections are accepted.
```


Anyway as far as I'm concerned the problem is resolved by setting explicit forward policies, this issue was just opened to report the upgrade wasn't as obvious I would have expected -- I don't have a magic solution, but if you get more such reports when e.g. people upgrade to fedora 34 then there might be more to do :)

**Comment by erig0** [comment]
You had your VMs in the `internal` zone and your uplink/internet connection in the `public` zone? I don't expect that to have worked unless you change the `--set-target` of one of them. Can you show the configuration for those zones?

**Comment by martinetd** [comment]
> You had your VMs in the internal zone and your uplink/internet connection in the public zone?

Yes

> I don't expect that to have worked unless you change the --set-target of one of them. Can you show the configuration for those zones?

Hm, would adding masquerade explicitely to the public zone do it?

Here are the zone files:
```
# cat public.xml 
<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Public</short>
  <description>For use in public areas. You do not trust the other computers on networks to not harm your computer. Only selected incoming connections are accepted.</description>
  <service name="ssh"/>
  <service name="mdns"/>
  <service name="dhcpv6-client"/>
  <masquerade/>
</zone>

# cat internal.xml
<?xml version="1.0" encoding="utf-8"?>
<zone>
  <short>Internal</short>
  <description>For use on internal networks. You mostly trust the other computers on the networks to not harm your computer. Only selected incoming connections are accepted.</description>
  <service name="ssh"/>
  <service name="mdns"/>
  <service name="samba-client"/>
  <service name="dhcpv6-client"/>
  <service name="dhcp"/>
  <service name="tftp"/>
  <service name="http"/>
  <service name="dns"/>
  <service name="ntp"/>
  <port port="2049" protocol="tcp"/>
  <port port="564" protocol="tcp"/>
  <port port="80" protocol="tcp"/>
</zone>
```

**Comment by erig0** [comment]
> > You had your VMs in the internal zone and your uplink/internet connection in the public zone?
> 
> Yes
> 
> > I don't expect that to have worked unless you change the --set-target of one of them. Can you show the configuration for those zones?
> 
> Hm, would adding masquerade explicitely to the public zone do it?

Yup. That would do it.

As I noted earlier, this behavior was changed intentionally in f2896e4. As such I'm closing as NOTABUG.

**Comment by martinetd** [comment]
>> Hm, would adding masquerade explicitely to the public zone do it?
>
> Yup. That would do it.
> 
> As I noted earlier, this behavior was changed intentionally in f2896e4. As such I'm closing as NOTABUG.

Would having masquerade explicitly be grounds for a change in the default target though? That just looks surprising to me.

> You can explicitly allow the forwarding from internal to public by adding a policy:

Yes, that's what I've done (adding a policy and opening ports I want forwarded outside, which is even better now we can do it!)

**Comment by erig0** [comment]
> > > Hm, would adding masquerade explicitely to the public zone do it?
> > 
> > 
> > Yup. That would do it.
> > As I noted earlier, this behavior was changed intentionally in [f2896e4](https://github.com/firewalld/firewalld/commit/f2896e43c3a548a299f87675a01e1a421b8897b8). As such I'm closing as NOTABUG.
> 
> Would having masquerade explicitly be grounds for a change in the default target though? That just looks surprising to me.

Can you elaborate? I'm not certain what you're getting at.

**Comment by martinetd** [comment]
>> Would having masquerade explicitly be grounds for a change in the default target though? That just looks surprising to me.
>
> Can you elaborate? I'm not certain what you're getting at.

I'm just still surprised by the change of behaviour in this case with explicit masquerading.
If the commit could keep the default internal->external target to accept, having masquerade on any zone perhaps ought to make it behave like external in that respect?

I don't understand how the commit itself works exactly, nor the note in the commit message "Note: masquerade is unaffected for ingress zones that use ACCEPT." -- it doesn't look like there is any explicit exception for trusted or external, so I don't understand what is special about these which would make them work and not my public_where_I_just_--add-masquerade -- looking at https://github.com/firewalld/firewalld/blob/master/config/zones/external.xml the only difference seems to be `<forward/>` (which got added to the default public zone as well at the same time, but not already installed ones perhaps?) and adding that doesn't help so it's something else...?
For example I don't use libvirt but I know they create their own libvirt zone, although I have no idea how they do the masquerading out of it... Would that also break & require libvirt code to be changed to allow egress traffic? Some people advocate adding masquerade as rich ipv4 rule too https://serverfault.com/questions/933453/port-forwarding-with-firewall-cmd so I guess at least these would break, but catching all kind of rich rules is going to be whack-a-mole...


Well, once again I don't really care, my problem is fixed & I get more powerful filtering with policies, the issue is closed, let's let the lion lie until someone else reports similar "nat no longer works" issues.
Feel free to cc me if you'd like at that point and we can keep discussing if required, or you can decide what you think is best without outsiders like me butting in :)

**Comment by martinetd** [comment]
Thanks for the detailed answer

> The --set-target applies to the ingress zone. That is the zone the packet arrived on. For VM -> world traffic that means internal. The problem in your case is that internal does not use ACCEPT. It uses default.

Ah, that's what I was misunderstanding. In my head ingress should always just work by conntrack even if the target denies new explicit connections but I wasn't thinking forward.
That does make it difficult to automatically guess based on the masquerade tag since it's about every other zone.
I guess ultimately what I find weird is that there is only one target e.g. trusted can't be "trusted for packets that come from the zone to the host or other networks (what I think of as ingress), restricted for packets that go to interfaces in the zone (what I think of as egress)" so that led to adding the reject rules to all zones except trusted's FWDO where I would have found it more logical on all zones except external/masqueraded zone's FWDI for similar result in the ticket's case. But there must be a reason for that too.
