### ISSUE TITLE
Cache DBus Authentication

### ISSUE THREAD

**Issue by lbiaggi** [firewalld/firewalld#776]
**What would you like to be added**:
I haven't found a way to cache DBus authentication. I would like to be able to call DBus methods without having to authenticate every time I access an interface in a short period. 

**Why is this needed**:
I'm working on an alternative interface to firewalld, where you can use [plasma-firewall] (https://invent.kde.org/plasma/plasma-firewall) as a simplified interface for it. One of my biggest challenges is to find a way to communicate with the firewall without asking for the password in each action.

I don't think I will be able to accomplish it, without firewalld support to this request. 

Regards,
Lucas

**Comment by erig0** [comment]
See related PR #793. I think caching is viable using the interface and `sender` as a key. We'd have to cover cases for when dbus and/or polkit are restarted while firewalld is running.
