### ISSUE TITLE
firewall-cmd --reload wipe out all CNI DNAT rules

### ISSUE THREAD

**Issue by vincentmli** [firewalld/firewalld#779]
**What happened**:

run firewall-cmd --reload, all the third party CNI DNAT rules got removed, this affected third party Kubernetes pod network

-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A POSTROUTING -m comment --comment "CNI portfwd requiring masquerade" -j CNI-HOSTPORT-MASQ
-A CNI-DN-2fd3a01d804b10ca8ef8d -s 10.244.0.0/24 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-2fd3a01d804b10ca8ef8d -s 127.0.0.1/32 -p tcp -m tcp --dport 443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-2fd3a01d804b10ca8ef8d -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.244.0.209:9443
-A CNI-DN-2fd3a01d804b10ca8ef8d -s 10.244.0.0/24 -p tcp -m tcp --dport 8443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-2fd3a01d804b10ca8ef8d -s 127.0.0.1/32 -p tcp -m tcp --dport 8443 -j CNI-HOSTPORT-SETMARK
-A CNI-DN-2fd3a01d804b10ca8ef8d -p tcp -m tcp --dport 8443 -j DNAT --to-destination 10.244.0.209:8443
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"b49b0a44de70f64eba8aa8e922898234578ff04a025b8735b3ed8141be38e068\"" -m multiport --dports 443,8443 -j CNI-DN-2fd3a01d804b10ca8ef8d
-A CNI-HOSTPORT-MASQ -m mark --mark 0x2000/0x2000 -j MASQUERADE
-A CNI-HOSTPORT-SETMARK -m comment --comment "CNI portfwd masquerade mark" -j MARK --set-xmark 0x2000/0x2000

**What you expected to happen**:

save third party CNI DNAT rules after firewall-cmd --reload

**How to reproduce it (as minimally and precisely as possible)**:

deploy Nginx controller https://docs.nginx.com/nginx-controller/admin-guides/install/install-nginx-controller/. the Nginx controller will create CNI DNAT rules for pod access external to the cluster

**Anything else we need to know?**:

**Environment**:
Nginx controller in Centos 7

- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):
[root@localhost ~]# firewall-cmd --version
0.4.4.4

- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 

- OS (e.g: `cat /etc/os-release`):

[root@localhost ~]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Others:

**Comment by vincentmli** [comment]
found this https://github.com/firewalld/firewalld/issues/556

**Comment by erig0** [comment]
firewalld will reapply direct rules that were added via `--direct` CLI option (or via dbus). I'm guessing the nginx CNI adds rules directly via `iptables` so firewalld doesn't even know about them. In this case there is nothing firewalld can do. It has no knowledge of the CNI rules. Unfortunately firewalld must wipe iptables rules when it starts otherwise it has no chance of applying its rule set.

Options (I realize neither of these are good options):
1. avoid reloading firewalld after CNI rules have been added.
2. reload CNI after reloading firewalld
