### ISSUE TITLE
The Applet shows html-code instead of formatted content

### ISSUE THREAD

**Issue by WOTLmade** [firewalld/firewalld#783]
When moving the mouse over the applet icon in the system tray, there is html-code shown instead of formatted content.

![Screenshot_firewalld-applet_html-code](https://user-images.githubusercontent.com/7735500/114582392-d5b3a800-9c80-11eb-9b7a-2fe9a0fba601.jpg)

**Environment:**

openSUSE 15.2 standard KDE Desktop

**rpm -qi firewall-applet**
Name        : firewall-applet
Version     : 0.5.5
Release     : lp152.6.3
Architecture: noarch
Install Date: Mit 07 Apr 2021 17:41:15 CEST
Group       : Productivity/Networking/Security
Size        : 230766
License     : GPL-2.0-or-later
Signature   : RSA/SHA256, Sam 07 Dez 2019 02:41:39 CET, Key ID b88b2fd43dbdc284
Source RPM  : firewalld-0.5.5-lp152.6.3.src.rpm
Build Date  : Sam 07 Dez 2019 02:41:24 CET
Build Host  : cloud118
Relocations : (not relocatable)
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : http://www.firewalld.org
Summary     : Firewall panel applet
Description :
The firewall panel applet provides a status information of firewalld and also
the firewall settings.
Distribution: openSUSE Leap 15.2

**cat /proc/version** 
Linux version 5.3.18-lp152.69-default (geeko@buildhost) (gcc version 7.5.0 (SUSE Linux)) #1 SMP Tue Apr 6 11:41:13 UTC 2021 (d532e33)

**cat /etc/os-release** 
NAME="openSUSE Leap"
VERSION="15.2"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.2"
PRETTY_NAME="openSUSE Leap 15.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

**Comment by fkru** [comment]
Dup of https://github.com/firewalld/firewalld/issues/668#issue-662146258

**Comment by erig0** [comment]
> Dup of [#668 (comment)](https://github.com/firewalld/firewalld/issues/668#issue-662146258)

Yup. Closing.
