### ISSUE TITLE
Build error with GSETTINGS on RPi4 / Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by immauss** [firewalld/firewalld#786]
**What happened**:
build fails with:
~~~
Making all in config
make[1]: Entering directory '/root/Projects/firewalld-0.8.6/config'
Makefile:974: *** missing separator.  Stop.
make[1]: Leaving directory '/root/Projects/firewalld-0.8.6/config'
make: *** [Makefile:393: all-recursive] Error 1
~~~

**What you expected to happen**:
build to complete.

**How to reproduce it (as minimally and precisely as possible)**:
Ubuntu 20.04 LTS.
RaspberryPi4 4Gig RAM

./autogen.sh
./configure --disable-docs
make 

**Anything else we need to know?**:

While writing this, I also found this error in the configure output:
~~~
./configure: line 3261: GLIB_GSETTINGS: command not found
~~~

This is curious because:
~~~
root@pihole:~/Projects/firewalld-0.8.6# dpkg -l libglib2.0-bin
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version                Architecture Description
+++-==============-======================-============-=================================
ii  libglib2.0-bin 2.64.6-1~ubuntu20.04.3 arm64        Programs for the GLib library
root@pihole:~/Projects/firewalld-0.8.6# which gsettings
/usr/bin/gsettings
root@pihole:~/Projects/firewalld-0.8.6#

~~~

Shouldn't configure fail if it can't find something?

Also,
    On line 974 of 'config/Makefile' 
~~~
@GSETTINGS_RULES@
~~~
So that macro is not getting expanded?

**Environment**:
- Firewalld Version: I tried with the latest from git and the release 8.8.6 
- 
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`):  iptables
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04 
- Others:
   Yes, I know there is a package for ubuntu, but it still has the bug for direct rules (RHBZ - 1829104)... and I need some direct rules. (Thinking I should have put a RHEL based build on this Pi now ..... )

**Comment by erig0** [comment]
As per [README](https://github.com/firewalld/firewalld/blob/master/README#L52) you need to have `glib-devel` installed to build firewalld.

**Comment by immauss** [comment]
<sigh>
My bad.

Thanks Eric….
