### ISSUE TITLE
[RFE]: Add counters when firewalld rendered as nftables rules

### ISSUE THREAD

**Issue by dhbaird** [firewalld/firewalld#792]
**What would you like to be added**:
I would like an option that tells firewalld to render nftable rules with counters, so this would actually show something:
```
nft list ruleset | grep counter
```

If this is already possible, please advise. I searched the manpage and https://www.google.com/search?q=site:firewalld.org+counters and some other places and couldn't dig up any way to do this.

**Why is this needed**:
When using iptables-based firewall, counters simply exist by default. These counters are useful for seeing which rule paths get triggered and how utilized rule paths are. Very useful in debugging as it also shows which rules are not being reached.

Thanks.

**Comment by Talkless** [comment]
Yes this seems rather lacking...

I guess rich rule language could be extended with `counter`, but maybe one would like `firealld` to add `counter` for all zone-related generated rules of zone specified in one go? Or maybe for all rules of every zone "globally" (by asking in firewalld.conf)?

@erig0 Have you given thought on how this could look like?

**Comment by erig0** [comment]
IMO, a global knob in `/etc/firewalld.conf` makes the most sense, e.g. `RuleCounters=on`. Alternatively we could enable them if firewalld is started with `--debug`.

Keep in mind that firewalld is stateful. Most of the rules are only hit for the first packet, e.g. TCP SYN.

**Comment by dhbaird** [comment]
@erig0 at least as a stopgap measure, the global knob `RuleCounters=on` idea would be very useful, as it would at least restore parity with iptables and buy time to come up with more targeted solutions.

**Comment by gotthardp** [comment]
> Keep in mind that firewalld is stateful. Most of the rules are only hit for the first packet, e.g. TCP SYN. So counters are of limited usefulness.

Would it be a solution to assign a `fwmark` to each rule and then instead of
```
ct state established,related accept
```
have multiple lines like
```
ct state established,related ct mark 0x00000001 counter name "somename" accept
```

The drawback is that somebody else may need the fwmarks as well. But one could say counting the whole traffic (and not just the initial packets) requires marking.

**Comment by brianjmurrell** [comment]
> Keep in mind that firewalld is stateful. Most of the rules are only hit for the first packet, e.g. TCP SYN. So counters are of limited usefulness.

I completely disagree.  Please refer to the [original comment](https://github.com/firewalld/firewalld/issues/792#issue-870381575), and in particular:

> Why is this needed:
When using iptables-based firewall, counters simply exist by default. These counters are useful for seeing which rule paths get triggered and how utilized rule paths are. Very useful in debugging as it also shows which rules are not being reached.

So those of us that want this, it is not for any kind of traffic accounting, etc. which I assume is what your above _caveat_ is in reference to.  That's a completely different issue which you mention below…

> Some day, we may support real counters for established data traffic. That would mean adding support for stateless rules which is not really a goal of firewalld.

**Comment by brianjmurrell** [comment]
> Would it be a solution to assign a `fwmark` to each rule and then instead of

Please don't conflate this request into any kind of traffic accounting request.  That is not what this request is about.

Traffic accounting belongs is a completely separate ticket.

**Comment by erig0** [comment]
> > Keep in mind that firewalld is stateful. Most of the rules are only hit for the first packet, e.g. TCP SYN. So counters are of limited usefulness.
> 
> I completely disagree. Please refer to the [original comment](https://github.com/firewalld/firewalld/issues/792#issue-870381575), and in particular:

So you're saying that counters that only count the NEW connections, e.g. tcp handshake, are sufficient?

If traffic accounting is not want people are asking for, then that makes sense.

I still think that qualifies as "limited usefulness". ;)

**Comment by brianjmurrell** [comment]
> So you're saying that counters that only count the NEW connections, e.g. tcp SYN, are sufficient?

Yes.

> If traffic accounting is not want people are asking for, then that makes sense.

That, IMO, is not what this ticket is about.  That would be a completely different ticket.

> I still think that qualifies as "limited usefulness". ;)

Again, I will disagree.  Please re-read the original request [comment](https://github.com/firewalld/firewalld/issues/792#issue-870381575).  TL-DR: the counters are being used for ruleset debugging (and perhaps optimisation -- although I don't personally go that effort) in this case, not traffic accounting.

**Comment by dhbaird** [comment]
I just need parity with iptables. Having those counters is essential for evaluating which rules are being hit the most and which are not being hit at all, so I can understand the rules, not trying to do traffic accounting (in this case). What @brianjmurrell seems to be saying is inline with my expectations. I'm not opposed to some more sophisticated accounting, but that's also not the issue I intended to raise. It's not that accounting isn't useful, but it really is a different issue. Sorry for the confusion. Thanks!

**Comment by erig0** [comment]
This is implemented in #1134 and is ready to merge IMO.

**Comment by erig0** [comment]
> This is implemented in #1134 and is ready to merge IMO. But it would be cool if someone gave it a try.

I will merge the PR tomorrow unless someone has a reason to NAK it.

**Comment by dhbaird** [comment]
It looks pretty good from my quick review of it! Thanks @erig0!

**Comment by Talkless** [comment]
Thanks @erig0 !

Now off-topic about:
> Some day, we may support real counters for established data traffic. That would mean adding support for stateless rules which is not really a goal of firewalld.

Shorewall has accounting https://shorewall.org/Accounting.html and it's usable with, for example, Munin (or others) to render usage graphs per service, which allow to see trends what's going on (and when).
