### ISSUE TITLE
Cleaner default zones

### ISSUE THREAD

**Issue by xeor** [firewalld/firewalld#799]
**What would you like to be added**:
Using firewalld in an enterprise feels icky since you want a minimal setup, but still, there are zones that you can't really get rid of, like `home` and `work`. The current default zones are:

  * block dmz drop external home internal nm-shared public trusted work

but it should really be more like

  * block drop nm-shared public

**Why is this needed**:
Even seeing some of these zone-names inside an enterprise gives chill, triggering thoughts like "is firewalld really for us?", "is it ment for desktops only?", "which of these zones can I really remove?.... oh... no-one..!?!?"

**Comment by Sxderp** [comment]
I'm not sure I see the issue. Zones are just names. From what I understand there's nothing "special" about them. You can override them as you see fit, or just ignore them. The only zone active by default is public.

Zones don't do anything until you assign interfaces or IP space to them..

**Comment by xeor** [comment]
That's why I am bringing this up as an issue. Why do we need them if they are just sitting there in case they are needed, as an "trying to make a sane default for everyone". There should be a bare minimal setup of the firewall, minimal zones, and none attached services to any of the zones (not even ssh).

If you are dealing with a high-security system now, you will need to do a lot of cleanup first. Looping over all zones, deleting all services for each of them.

Imo, firewalld should separate out configuration, not bundling it with firewalld itself, but providing it as it's own thing. People can then install the bundles they want (defaulting to the one in use now)

**Comment by erig0** [comment]
Sorry. This is a WONTFIX. We're not going to remove zones that have existed since day one. They're being used by users. If a security minded distribution wants to break (or remove) the configuration up so that the config files are separate, then they can surely do that. But that's a downstream (distribution) change.
