### ISSUE TITLE
How can I configure a killswitch for OpenVPN?

### ISSUE THREAD

**Issue by cronos1998** [firewalld/firewalld#803]
Hi,

since this is neither a bug report nor an enhancement request, I hope it is okay I didn't follow the template.

There are some guides available on how to configure a killswitch for OpenVPN, but they don't really offer what I need.

Also, they seem very complicated and I wonder if there's not an easier solution.

Basically, I want to block all incoming and all outgoing traffic except VPN traffic on the tun0 interface.

The only traffic allowed outside of tun0 should be the initial connection to the VPN server (to be more specific, the ip address of the VPN server should be whitelisted)

I used to do this via iptables / ufw using the following commands:

ufw default deny outgoing
ufw default deny incoming
ufw allow out on tun0 from any to any
ufw allow out from any to 1.2.3.4

(of course, 1.2.3.4 is just an example for the ip address of the VPN server).

Can someone please tell me how I can get the same effect with firewalld?

Thank you

**Comment by erig0** [comment]
1. Set default zone to something restrictive, e.g. `drop`
    ```
    # firewall-cmd --set-default-zone drop
    ```
2. Make sure there are are no interfaces assigned to a zone. This makes sure everything falls to the `drop` zone.
    ```
    # firewall-cmd --permanent --zone <zone> --remove-interface <interface>
    ```
3. Add `vpn0` to your zone of choice, e.g. `trusted`
    ```
    # firewall-cmd --permanent --zone trusted --add-interface vpn0
    ```
