### ISSUE TITLE
insert rule between 2 rules

### ISSUE THREAD

**Issue by tlsalex** [firewalld/firewalld#805]
**What happened**:
when I insert a rich rule with priority 5 between rule 4 and rule 5 as bellow ,  both new rule and old rule has the same priority.
```
rule priority="4" family="ipv4" source address="xxxx" accept
rule priority="5" family="ipv4" source address="xxxx" accept
```
**What you expected to happen**:
New rule has priority of 5, the old rule will has priority of 6

**How to reproduce it (as minimally and precisely as possible)**:
`firewall-cmd --add-rich-rule='rule priority="5" family="ipv4" source address="xxxx" accept'`

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):Version      : 0.8.2
- 
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`):  FirewallBackend=nftables
- 
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 8.3.2011
- 
- Others:

**Comment by erig0** [comment]
That's exactly how it's suppose to work. Priorities of a rule do not change. Rich rules that have the same priority or not sorted in any particular order. It is a _priority_. It is _NOT_ an index.

Quoting firewalld.richlanguage(5):
> If the rule priority is provided, it can be in the range of -32768 to 32767 where lower values have higher precendence. **Rich rules are sorted by priority. Ordering for rules with the same priority value is undefined.** A negative priority value will be executed before other firewalld primitives. A positive priority value will be executed after other firewalld primitives. A priority value of 0 will place the rule in a chain based on the action as per the "Information about logging and actions" below.
