### ISSUE TITLE
Tooltip showing HTML code

### ISSUE THREAD

**Issue by marozsas** [firewalld/firewalld#812]
Hovering the mouse over the firewalld applet open a popup displaying the text in HTML code, not parsed ou rendered.

I expected to see a tooltip showing usefull information about firewall status in plain text,

Just load the firewalld applet/widget and hover the mouse pointer over it.

Its a old bug, never fixed. Looks like the framework has changed the behaviour and the widget not follow the new api.
  
**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):
firewalld-0.9.3-3.3.noarch
firewall-config-0.9.3-3.3.noarch
firewalld-lang-0.9.3-3.3.noarch
yast2-firewall-4.4.0-1.1.noarch
python3-firewall-0.9.3-3.3.noarch
firewall-applet-0.9.3-3.3.noarch

- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 
-FirewallBackend=iptables

- OS (e.g: `cat /etc/os-release`):
- NAME="openSUSE Tumbleweed"
# VERSION="20210616"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210616"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210616"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
- Others:
![Screenshot_20210626_115441](https://user-images.githubusercontent.com/22824252/123517013-57f31c00-d675-11eb-9301-43f948194f42.png)

**Comment by erig0** [comment]
Already fixed by 69489661ec8eca1c2ed3c6159024c271e7e6eb2b.
