### ISSUE TITLE
Duplicated service

### ISSUE THREAD

**Issue by marcosfrm** [firewalld/firewalld#831]
https://github.com/firewalld/firewalld/blob/28fe70a4d70332edfe95cc6404f455a9b11ee89b/config/services/ms-wbt.xml#L5

https://github.com/firewalld/firewalld/blob/28fe70a4d70332edfe95cc6404f455a9b11ee89b/config/services/rdp.xml#L5

`rdp` is a better name. Remove `ms-wbt`?

**Comment by erig0** [comment]
Removing would be a breaking change. Unless it's causing harm, then we should just change `ms-wbt` to simply `include` `rdp`. i.e. make it an alias.
