### ISSUE TITLE
Ipsec problem

### ISSUE THREAD

**Issue by enzzo-ux** [firewalld/firewalld#835]
Hi
I am asking for help, unfortunately, after a few days of fighting firewalld, I can't do it.
Updated server opensuse where iptables was previously
Ipsec (strongswan) running on the WAN (external) server
2 external and internal zones
external The external ip address to which the ipsec client connects
external services - http / ssh
SSH for ipsec client only.
internal - LAN, the ipsec client gets the address from the lan pool.
I want the ipsec client to have access to www and ssh of this server as well as other hosts in the lan network (all ports).
ICMP works from the ipsec client to the server and other hosts on the lan network. Http does not work on the server for the ipsec client.
If I add the ip of the ipsec client to the Trusted zone - ssh access does not work.
I can't diagnose anything in this firewall, I don't see the iptables -L -v option that is helpful in iptables.
Backed nftables.

**Comment by erig0** [comment]
Can you show some firewalld configuration? Particularly your zones and policies.
- `firewall-cmd --list-all-zones`
- `firewall-cmd --list-all-policies`

> I can't diagnose anything in this firewall, I don't see the iptables -L -v option that is helpful in iptables.

Modern firewalld uses `nftables`. You won't see the rules in `iptables`, because firewalld is not using `iptables`!

**Comment by enzzo-ux** [comment]
Thank you for your response.Problem has been solved. It was an invalid MTU.

However, due to poor diagnostic capabilities firewalld, I solved in a 
different way.

I was used to iptables where everything was clear.Is it easy to convert 
rules from nftables to iptables?


W dniu 09.08.2021 o 18:54, Eric Garver pisze:

**Comment by erig0** [comment]
> However, due to poor diagnostic capabilities firewalld, I solved in a different way.

I'm not sure what you need to help debug, but `--set-log-denied` will log packet drops.

> I was used to iptables where everything was clear. Is it easy to convert rules from nftables to iptables?

You can set `FirewallBackend=iptables` in `/etc/firewalld/firewalld.conf`. But I suggest sticking with nftables.

**Comment by erig0** [comment]
Closing. Issue was MTU related and not a firewalld issue.
