### ISSUE TITLE
INFO level logs are not sent to syslog or log file

### ISSUE THREAD

**Issue by mbiebl** [firewalld/firewalld#846]
I'm running firewalld 1.0.1 on Debian sid using systemd. `systemctl status` shows

```
● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-30 11:17:02 UTC; 20s ago
       Docs: man:firewalld(1)
   Main PID: 900 (firewalld)
      Tasks: 2 (limit: 1133)
     Memory: 23.4M
        CPU: 374ms
     CGroup: /system.slice/firewalld.service
             └─900 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

Aug 30 11:17:02 host systemd[1]: Starting firewalld - dynamic firewall daemon...
Aug 30 11:17:02 host systemd[1]: Started firewalld - dynamic firewall daemon.
running
```

`/var/log/firewalld` is emtpy.

Everything appears to be fine.

When running firewalld on the console, manually, I get
```
root@host:~# firewalld --nofork --nopid
2021-08-30 11:22:08 ipset not usable, disabling ipset usage in firewall. Other set backends (nftables) remain usable.
2021-08-30 11:22:08 iptables-restore and iptables are missing, IPv4 direct rules won't be usable.
2021-08-30 11:22:08 ip6tables-restore and ip6tables are missing, IPv6 direct rules won't be usable.
2021-08-30 11:22:08 ebtables-restore and ebtables are missing, eb direct rules won't be usable.
```

It appears, those log messages are completely lost and logged nowhere.
Such status messages should (at the very least) go to the journal so they are available when running `systemctl status firewalld.service` or `journalctl -u firewalld.service`

In comparison, when I look that status output of e.g. 0.6.3, I got

```
● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-30 11:20:51 UTC; 22s ago
       Docs: man:firewalld(1)
   Main PID: 917 (firewalld)
      Tasks: 2 (limit: 1133)
     Memory: 22.9M
        CPU: 673ms
     CGroup: /system.slice/firewalld.service
             └─917 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

Aug 30 11:20:51 host systemd[1]: Starting firewalld - dynamic firewall daemon...
Aug 30 11:20:51 host systemd[1]: Started firewalld - dynamic firewall daemon.
Aug 30 11:20:51 host firewalld[917]: WARNING: ipset not usable, disabling ipset usage in firewall.
```
and I had
```
root@host:~# cat /var/log/firewalld 
2021-08-30 11:20:51 WARNING: ipset not usable, disabling ipset usage in firewall.
```

**Comment by erig0** [comment]
See commit 4268db46e98fd. v1.0.0 made `iptables`, `ipset`, et al. optional. As such the log was changed to info level if the backend is set to `nftables`. If the backend is set to `iptables`, then you get the WARNING.

**Comment by erig0** [comment]
INFO level logs don't got to syslog or `/var/log/firewalld`, but they will go to stdout if you use `--no-fork`.

**Comment by mbiebl** [comment]
Ok, thanks for the clarification.

**Comment by erig0** [comment]
@mbiebl, do you think these INFO logs are useful to users? Or will it cause more confusion than gain?

**Comment by mbiebl** [comment]
hi @erig0 
Just to be completely sure: if the nftables backend is used, iptables/ipset/ebtables is not used anymore?

The log message reads like having these tools installed provides additional/optional functionality, even if nftables is the selected backend.

So yeah, seeing those log messages confused me (on Debian, where nftables is the default backend).

**Comment by erig0** [comment]
On Mon, Aug 30, 2021 at 11:57:19AM -0700, Michael Biebl wrote:
> hi @erig0 
> Just to be completely sure: if the nftables backend is used,
> iptables/ipset/ebtables is not used anymore?

Incorrect. They just become optional.

FirewallBackend=nftables, iptables is not present:
  - can NOT use iptables backend
  - can NOT use ipv4/ipv6 direct rules

FirewallBackend=nftables, iptables is present:
  - can use ipv4/ipv6 direct rules

FirewallBackend=nftables, ipset is not present:
  - firewalld "ipset"s only exist in nftables, they will NOT be
    duplicate to ipset. Normally this is done so they're usable from
    ipv4/ipv6 direct rules.

FirewallBackend=nftables, ipset is present:
  - firewalld "ipset"s are duplicate to ipset in addition to nftables.

FirewallBackend=nftables, ebtables is not present:
  - can NOT use eb direct rules

FirewallBackend=nftables, ebtables is present:
  - can use eb direct rules

> The log message reads like having these tools installed provides
> additional/optional functionality, even if nftables is the selected
> backend.

They do. See above.

> So yeah, seeing those log messages confused me (on Debian, where
> nftables is the default backend).

**Comment by mbiebl** [comment]
Hm, what would be your recommendation then? Still install iptables/ipset, even if nftables is the default backend?

What exactly is  this "direct rules" functionality and where and when is it used? Is this something that could be implemented with nftables?

**Comment by erig0** [comment]
> Hm, what would be your recommendation then? Still install iptables/ipset, even if nftables is the default backend?

Yes. It's optional, but still supported. For various reasons some users still use the iptables backend.

> What exactly is this "direct rules" functionality and where and when is it used? Is this something that could be implemented with nftables?

"direct rules" are the `--direct` and `--passthrough` options. It allows you to pass iptables/ebtables syntax to firewalld. firewalld acts as an intermediate. It doesn't not understand the direct rule syntax.

Direct rules are mostly obsolete due to firewalld now having forward/output filtering. There are some exceptions. Like things supported by `iptables-extensions`, but not natively supported by firewalld.
