### ISSUE TITLE
WS-Discovery service blocks unicast responses

### ISSUE THREAD

**Issue by gbsf** [firewalld/firewalld#848]
According to the spec, WSD probes must be responded using unicast (§ 5.3.1).
In addition, a service may choose to also listen to requests on its unicast address (§ 5.2.2).
Notably, I can't discover a Windows host in the same network unless I completely open port 3702/udp.

All that is to say that the destination match in `ws-discovery-udp` should probably be removed or replaced with a smarter conntrack helper.

https://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html

**Comment by erig0** [comment]
@marcosfrm, @mymatenige, what are your thoughts?

**Comment by marcosfrm** [comment]
UDP unicast responses are sent to the (random) source port from the query, no?

Testing Windows 10 -> wsdd2[1] under Wireshark never show UDP unicast to 3702, only TCP.

Can you run Wireshark to confirm?

[1] https://github.com/Netgear/wsdd2

**Comment by gbsf** [comment]
I guess you're running firewalld on the server-side, in my case Linux is the client. I ran a packet capture while making a WSD probe request (in green). The response comes as unicast (in red) and is filtered out.

(192.168.0.10 is the Windows box, .21 is the Linux one)

![lin_to_win](https://user-images.githubusercontent.com/9276001/131766711-71d73300-cc63-4123-a3d7-33dbadaa7f2c.png)

Just to confirm, I ran wsdd2 on my Linux machine and tried discovering it from Windows. As you can see, it also responds to the probe with an unicast packet. Only then the HTTP request is made using TCP.

![win_to_lin](https://user-images.githubusercontent.com/9276001/131766683-033f3b6f-cef9-4712-be4d-3e2b2e137e97.png)

---

On further thought, I guess my problem is that the Linux browser I'm using is reusing 3702 as the source port.
Either way, the problem is then that WSD needs a conntrack helper just like NetBIOS to handle the multicast-to-unicast flow. I think this is done using policies now?
As an end-user, some predefined policies for client use-cases would be welcome.

**Comment by marcosfrm** [comment]
Your Windows box query with a random source port; wsdd2 never send UDP unicast to port 3702. This is the behaviour I am seeing here too. But indeed this is probably Microsoft implementation... other clients may use 3702 as source port when quering via UDP multicast. What client is that?

firewalld does not support conntrackd, hence we probably need to relax the rule. In this case, can I drop the udp-tcp split? (the services are not in any released firewalld version afaik)

**Comment by marcosfrm** [comment]
> ETA: Since zones are now internally implemented as policies, can conntrack helpers be special-cased to be put in the output chain instead of the input? It would make enabling those kinds of services much more straightforward for end-users.

Yes. Opening 3702/udp completely  will not work if another client behaving like Windows emerges, unless we match source port, an awful solution...

**Comment by gbsf** [comment]
> Your Windows box query with a random source port; wsdd2 never send UDP unicast to port 3702. This is the behaviour I am seeing here too. But indeed this is probably Microsoft implementation... other clients may use 3702 as source port when querying via UDP multicast. What client is that?

I'm using Dolphin, which uses [kdsoap-ws-discovery-client](https://caspermeijn.gitlab.io/kdsoap-ws-discovery-client) behind the scenes.
But you are right, relying on source 3702 is an implementation detail and other clients might do things diferently.

**Comment by erig0** [comment]
What the consensus here?

AFAICS, this service works well for server side.
The client side is problematic due to multicast send and unicast reply. Ideally firewalld would have conntrackd support.

If we need to use `source-port` to allow 3702 I'd rather see a `ws-discovery-client` service.

**Comment by erig0** [comment]
> ETA: Since zones are now internally implemented as policies, can conntrack helpers be special-cased to be put in the output chain instead of the input? It would make enabling those kinds of services much more straightforward for end-users.

What you want is an outbound policy, e.g. `ingress-zone` contains `HOST`, then attach the service to the policy. Then the conntrack helper is applied to the outbound (client) traffic. This works for things like `tftp`.

**Comment by marcosfrm** [comment]
> What the consensus here?
> 
> AFAICS, this service works well for server side.

Yes. I would like to keep the destination addresses from inbound UDP multicast in place, since removing them does not guarantee future client implementation using random source port will work.

> The client side is problematic due to multicast send and unicast reply. Ideally firewalld would have conntrackd support.
> 
> If we need to use `source-port` to allow 3702 I'd rather see a `ws-discovery-client` service.

`ws-discovery-client`  I am afraid is the only way until firewalld gets conntrackd support.

**Comment by erig0** [comment]
> `ws-discovery-client` I am afraid is the only way until firewalld gets conntrackd support.

If someone wants to add this service I will merge it. I don't expect conntrackd support for some time.

**Comment by marcosfrm** [comment]
@gbsf give #850 a shot.
