### ISSUE TITLE
use dbus remotely connect firewalld dbus interface error

### ISSUE THREAD

**Issue by iseall** [firewalld/firewalld#851]
**through dbus remotely connect firewalld**:

```
DBUS_SESSION_BUS_ADDRESS="tcp:host=10.0.0.3,port=55557" DBUS_SESSION_BUS_PID=0 dbus-send --session --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getZones
```

**The prompt information is as follows**:
Error org.freedesktop.DBus.Error.Failed: GDBus.Error:org.freedesktop.DBus.Error.Failed: Could not determine UID for ':1.28'

Under normal circumstances, DBUS supports remote connection, using the name of FreeDesttop, you can connect，for example：
```
[root@test-machine ~]# DBUS_SESSION_BUS_ADDRESS=tcp:host=10.0.0.3,port=55557,family=ipv4 dbus-send --session --dest=org.freedesktop.DBus  --type=method_call --print-reply /org/freedesktop/DBus  org.freedesktop.DBus.ListNames
method return time=1631529400.498543 sender=org.freedesktop.DBus -> destination=:1.29 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.freedesktop.login1"
      string ":1.3"
      string "org.freedesktop.systemd1"
      string "org.fedoraproject.FirewallD1"
      string "org.freedesktop.PolicyKit1"
      string ":1.0"
      string ":1.29"
      string ":1.5"
      string ":1.2"
   ]
```
but connect firewalld dbus bus name and interface , failed. for example:
```
DBUS_SESSION_BUS_ADDRESS="tcp:host=10.0.0.3,port=55557" DBUS_SESSION_BUS_PID=0 dbus-send --session --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getZones
Error org.freedesktop.DBus.Error.Failed: GDBus.Error:org.freedesktop.DBus.Error.Failed: Could not determine UID for ':1.31'
```
**No problem through local connection**

```
dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getZones
method return time=1631529551.186347 sender=:1.43 -> destination=:1.44 serial=228 reply_serial=2
   array [
      string "block"
      string "dmz"
      string "drop"
      string "external"
      string "home"
      string "internal"
      string "public"
      string "trusted"
      string "work"
   ]

```

**Environment**:
- Firewalld Version firewalld-0.6.3:
- Firewalld Backend centos7 default version: 
- OS centos 7:

**Comment by erig0** [comment]
> **through dbus remotely connect firewalld**:
> 
> ```
> DBUS_SESSION_BUS_ADDRESS="tcp:host=10.0.0.3,port=55557" DBUS_SESSION_BUS_PID=0 dbus-send --session --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getZones
> ```
> 
> **The prompt information is as follows**:
> Error org.freedesktop.DBus.Error.Failed: GDBus.Error:org.freedesktop.DBus.Error.Failed: Could not determine UID for ':1.28'

firewalld needs to do some authorization on the dbus request. It currently tries two ways, in order of preference:

1. policy kit
2. UID checking

Neither of these are available over a TCP/IP dbus connection.

I'm not sure we even want to support managing firewalld over TCP/IP. What is your use case?

**Comment by iseall** [comment]
> > **through dbus remotely connect firewalld**:
> > ```
> > DBUS_SESSION_BUS_ADDRESS="tcp:host=10.0.0.3,port=55557" DBUS_SESSION_BUS_PID=0 dbus-send --session --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call /org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getZones
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **The prompt information is as follows**:
> > Error org.freedesktop.DBus.Error.Failed: GDBus.Error:org.freedesktop.DBus.Error.Failed: Could not determine UID for ':1.28'
> 
> firewalld needs to do some authorization on the dbus request. It currently tries two ways, in order of preference:
> 
> 1. policy kit
> 2. UID checking
> 
> Neither of these are available over a TCP/IP dbus connection.
> 
> I'm not sure we even want to support managing firewalld over TCP/IP. What is your use case?

I need to configure the firewalld rule for managing a batch of machines over the D-Bus API.

Uid Checking is the verification made by firewalld , not  D-Bus own verification. I have not passed the verification using `freedesktop.org` . It seems that I need to modify the verification rule to repacket a firewalld version.

**Comment by iseall** [comment]
firewalld  authorization is Is it verified by `self.parent.accessCheck(sender)`？

**Comment by erig0** [comment]
> firewalld authorization is Is it verified by `self.parent.accessCheck(sender)`？

Yes. As I said above. The access checker checks policy kit, then falls back to UID checking. Neither of which can be done when the dbus socket is TCP/IP.

If you want to manage firewalld remotely, then you're better off with something like Ansible.

**Comment by iseall** [comment]
When D-Bus information is transmitted over the TCP/IP mode, the sender received is irregular number, and the UID is not available, and D-Bus cannot obtain the corresponding information. 

ansible is mainly facing technicians, we want to do, rules can be handed over to non-technical personnel to complete large-scale management in the software interface. The Agent method is more cumbersome, I think this way. It seems to cancel firewalld authorization.

**Comment by erig0** [comment]
> When D-Bus information is transmitted over the TCP/IP mode, the sender received is irregular number, and the UID is not available, and D-Bus cannot obtain the corresponding information.

Correct.

> ansible is mainly facing technicians, we want to do, rules can be handed over to non-technical personnel to complete large-scale management in the software interface. The Agent method is more cumbersome, I think this way. It seems to cancel firewalld authorization.

Ansible doesn't have an agent on the remote side. It authenticates with SSH, then runs firewalld's python code on the remote side, which in turn means the policy kit and/or UID authorization check will succeed.

**Comment by erig0** [comment]
This is not something we can reasonably support. AFAIK, dbus over TCP/IP has no way to handle authentication.
https://www.freedesktop.org/wiki/Software/DBusRemote/

There seems to be some people using a combination of SSH port forwarding and `socat` to get remote access to a dbus session. Perhaps you can give that a try.

As for firewalld directly supporting remote dbus connections.. that's not something that we can feasibly support at the moment.

**Comment by iseall** [comment]
thanks for your helpin time
