### ISSUE TITLE
document how to block egress (output) traffic to specific IP addresses

### ISSUE THREAD

**Issue by ktdreyer** [firewalld/firewalld#898]
**What would you like to be added**:
Please document how to block (and unblock) egress connections.

**Why is this needed**:
If you Google search "firewalld block ip" or "firewalld block outbound IP" or "firewalld block egress", all the examples on the internet use `--direct`. For example:

```
firewall-cmd --direct --add-rule ipv4 filter OUTPUT 0 -d 10.0.0.100/32  -j REJECT
firewall-cmd --direct --remove-rule ipv4 filter OUTPUT 0 -d 10.0.0.100/32  -j REJECT
```

https://firewalld.org/2021/06/the-upcoming-1-0-0 explains that the "direct" interface is obsolete, so it would be great to document the proper way to do this.

**Comment by erig0** [comment]
See the example for policy `myOutputPolicy` here: https://firewalld.org/2020/09/policy-objects-introduction
