### ISSUE TITLE
firewall-cmd EXIT CODE

### ISSUE THREAD

**Issue by torms** [firewalld/firewalld#905]
Running 2 times this command I should get an exit code different from 0, maybe 16 (ZONE_ALREADY_SET)

`firewall-cmd --zone=drop --add-source=ip.ad.dre.ss/24; echo $?`

but the second time I get 

```
Warning: ZONE_ALREADY_SET: 'ip.ad.dre.ss/24' already bound to 'drop'
success
0
```
**Environment**:
- Firewalld Version: 0.9.3
- Firewalld Backend: FirewallBackend=nftables
- OS: CentOS Linux release 8.5.2111
- Other: [firewalld.log](https://github.com/firewalld/firewalld/files/7920667/firewalld.log)

**Comment by torms** [comment]
From the man page, how should this be interpreted?

```
OPTIONS
       Sequence options are the options that can be specified multiple times, the exit 
code is 0 if there is at least one item that succeeded. The ALREADY_ENABLED (11), 
NOT_ENABLED (12) and also ZONE_ALREADY_SET (16) errors are treated as succeeded.
```

**Comment by erig0** [comment]
If you need to know if the source is in the zone, then you can use `--query-source`.
```
# firewall-cmd --zone drop --query-source ip.ad.dre.ss/24
```
Which returns 0 if it is present, and non-zero (1) if it is not present. This lets you do stuff like this:

```
# firewall-cmd --zone drop --query-source ip.ad.dre.ss/24 \
  || firewall-cmd --zone drop --add-source ip.ad.dre.ss/24
```
