### ISSUE TITLE
Problems with DBUS Direct interface getallRules

### ISSUE THREAD

**Issue by lbiaggi** [firewalld/firewalld#906]
**What happened**: 
I'm receiving randomly replies from dbus interface direct interface with Python Exception <class 'TypeError'>: unsupported operand type(s) for +: 'NoneType' and 'str',

I already tried to set debug to level 10 and still not see anything, is there any action to trace it better?

Regards,
Lucas

**What you expected to happen**: Continuous messages calls did not be disrupted (in the past)

**How to reproduce it (as minimally and precisely as possible)**:  
Using [this branch](https://invent.kde.org/lbiaggi/plasma-firewall/-/tree/services_interface) keep adding services or direct rules until it happens. I attached one backtrace from yesterday.

**Anything else we need to know?**:
[bt.log](https://github.com/firewalld/firewalld/files/7924665/bt.log)
**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): 1.0.3
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): FirewallBackend=nftables
- OS (e.g: `cat /etc/os-release`): archlinux
- Others:

**Comment by erig0** [comment]
Can you be specific about what dbus API you're calling?

  `org.fedoraproject.FirewallD1`  (runtime)
or
   `org.fedoraproject.FirewallD1.config`  (permanent config)

**Comment by lbiaggi** [comment]
Sure,
I'm using `org.fedoraproject.FirewallD1 (runtime)`

**Comment by erig0** [comment]
I can't really tell what's going on. Can you show the dbus calls? You might be able to reproduce with dbus-send or gdbus.

**Comment by lbiaggi** [comment]
Ok,
What I'm doing regarding in the moment of the trace is: executing two these two asynchronous  (using QT dbus interfce)

`dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call \
/org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.direct.getAllRules`
and
`dbus-send --system --dest=org.fedoraproject.FirewallD1 --print-reply --type=method_call \
/org/fedoraproject/FirewallD1 org.fedoraproject.FirewallD1.zone.getServices string:""`

I tried firstly identity the error elevating the debug level to 10, and still, I did not see the message from the BT. 
These two calls works almost every time, but eventually, it crashes. I'm trying to understand why Python stack returns that NoneType + str in the dbus reply (stack 6), to threat these cases from my side.

Do you have any suggestion, about how can I trace it?

**Comment by erig0** [comment]
> I tried firstly identity the error elevating the debug level to 10, and still, I did not see the message from the BT. These two calls works almost every time, but eventually, it crashes. I'm trying to understand why Python stack returns that NoneType + str in the dbus reply (stack 6), to threat these cases from my side.
> 
> Do you have any suggestion, about how can I trace it?

Did you check /var/log/firewalld? That's likely to show the backtrace.

**Comment by lbiaggi** [comment]
Yes, and I did not find anything there :sob:, this one of the motives which I came here
