### ISSUE TITLE
nftables: ipset timeout flag is not set in the backend

### ISSUE THREAD

**Issue by syco** [firewalld/firewalld#908]
**What happened**: nftables sets don't have the timeout flag

**What you expected to happen**: nftables sets are created with the flag timeout

**How to reproduce it**:
```bash
firewall-cmd --permanent --new-ipset=ipv4_list --type=hash:net --family=inet --option=timeout=3600
firewall-cmd --complete-reload
nft list ruleset | less
```
Look for the section with
```
set ipv4_list {
        type ipv4_addr
        flags interval
}
```
The nftables documentation ([https://wiki.nftables.org/wiki-nftables/index.php/Element_timeouts]()) states this sections should also contain `flags timeout`.

**Environment**:
- Firewalld Version: 0.9.3
- Firewalld Backend: nftables
- OS: Debian GNU/Linux 11 (bullseye)

Also, if the backend is nftables, why ipset are also created? Isn't enough to create nftables sets?
Thanks

**Comment by erig0** [comment]
Thanks for reporting this.

> The nftables documentation (https://wiki.nftables.org/wiki-nftables/index.php/Element_timeouts) states this sections should also contain `flags timeout`.

Agree. I think we're just missing setting the flag.

**Comment by erig0** [comment]
> Also, if the backend is nftables, why ipset are also created? Isn't enough to create nftables sets? Thanks

It is not enough because you can still use the ipset in a `--direct` rule. firewalld v1.0.0 made `ipset` optional.

**Comment by pstadt** [comment]
Looks like #699 mentions the same problem.

**Comment by erig0** [comment]
> Looks like #699 mentions the same problem.

You are correct. I'm marking this issue as a duplicate and bumping priority of #699.
