### ISSUE TITLE
dbus property names for access rules (zones vs policies)

### ISSUE THREAD

**Issue by mpserafim** [firewalld/firewalld#916]
Hello,

I'm sorry, I don't know where to ask this.

The properties for access the "rules" setted on zones (org.fedoraproject.FirewallD1.config.zone) and policies (org.fedoraproject.FirewallD1.config.policy) has different names (rules_str and rich_rules), why is that?

And, policies doesn't have methods to add rich rules (like the zone's addRichRule), it will be implemented or better stick to the policy's update method?

Thanks.

**Comment by erig0** [comment]
> The properties for access the "rules" setted on zones (org.fedoraproject.FirewallD1.config.zone) and policies (org.fedoraproject.FirewallD1.config.policy) has different names (rules_str and rich_rules), why is that?

"rules_str" is a bit easy to confuse with direct rules (which are very different). I thought "rich_rules" was a better key for the dictionary.

> And, policies doesn't have methods to add rich rules (like the zone's addRichRule), it will be implemented or better stick to the policy's update method?

In general, firewalld is moving to dictionary based APIs. This makes in significantly easier to maintain and add new options for zones, policies, services, etc.
