### ISSUE TITLE
How can I forward traffic between zones and enable NAT

### ISSUE THREAD

**Issue by HuengchI** [firewalld/firewalld#917]
# **What happened**:

My network environment is as follows:

```
------------------             -------------------------
| Outside World  | <---------> |eth0:172.21.151.224/20 |
------------------             -------------------------
			       | Server A              |
------------------------       -------------------------
|eth0:192.168.100.90/24| <---> |eth2:192.168.100.10/24 |
-----------------------        -------------------------
| Server N             | 
------------------------
```

As you can see, server N resides on a LAN while server A has access the the Internet. I want to set a **NAT** service on server A's eth2 interface so that Server N can talk to the outside world.

So I configured firewalld on Server A like this:

| $ firewall-cmd --info-zone=zone0                             | $ firewall-cmd --info-zone=zone2                             |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| zone0 (active)<br/>  target: DROP<br/>  icmp-block-inversion: no<br/>  interfaces: eth0<br/>  sources:<br/>  services:<br/>  ports:<br/>  protocols:<br/>  forward: no<br/>  masquerade: no<br/>  forward-ports:<br/>  source-ports:<br/>  icmp-blocks:<br/>  rich rules: | zone2 (active)<br/>  target: DROP<br/>  icmp-block-inversion: no<br/>  interfaces: eth2<br/>  sources:<br/>  services:<br/>  ports:<br/>  protocols:<br/>  forward: no<br/>  **masquerade: yes**<br/>  forward-ports:<br/>  source-ports:<br/>  icmp-blocks:<br/>  rich rules: |

But it doesn't work. I can't ping 8.8.8.8 on the Server N, and got this message in the log:

```
[22658.568969] "filter_FWD_zone2_DROP: "IN=eth2 OUT=eth0 MAC=00:15:5d:00:0a:0d:00:15:5d:00:0a:10:08:00 SRC=192.168.100.90 DST=8.8.8.8 LEN=84 TOS=0x00 PREC=0x00 TTL=63 ID=23917 DF PROTO=ICMP TYPE=8 CODE=0 ID=36 SEQ=1
```

**It seems that we can only forward traffic intra a zone, like this:**

| $ firewall-cmd --info-zone=zone0                             |
| ------------------------------------------------------------ |
| zone0 (active)<br/>  target: DROP<br/>  icmp-block-inversion: no<br/>  interfaces: eth0 eth2<br/>  sources:<br/>  services:<br/>  ports:<br/>  protocols:<br/>  **forward: yes**<br/>  masquerade: no<br/>  forward-ports:<br/>  source-ports:<br/>  icmp-blocks:<br/>  rich rules:<br/>        rule family="ipv4" source address="192.168.100.0/24" masquerade |

# **What you expected to happen**:

Having all the interfaces in the same zone seems to reduce configuration flexibility. On server A the eth0 interface is connecting to the public world, so we need to close most ports on it, while the eth2 interface is connecting to the trusted network, so we can lower the defenses for convenience.

I expect to put these two interfaces in two zones and give my Server N access to the Internet.  

# **How to reproduce it (as minimally and precisely as possible)**:

1. create 2 new zones<br>`firewall-cmd --new-zone=zone0 --permanent`<br>`firewall-cmd --new-zone=zone2 --permanent`<br>`firewall-cmd --reload`
2. set zones' target to DROP<br>`firewall-cmd --set-target=DROP --zone=zone0 --permanent`<br>`firewall-cmd --set-target=DROP --zone=zone2 --permanent`<br>`firewall-cmd --reload`
3. add corresponding interfaces<br>`firewall-cmd --change-interface=eth0 --zone=zone0`<br>`firewall-cmd --change-interface=eth2 --zone=zone2`
4. turn on masquerade switch<br>`firewall-cmd --add-masquerade --zone=zone2`
5. examine the configuration<br>`firewall-cmd --info-zone=zone0`<br>`firewall-cmd --info-zone=zone2`
6. turn on log to track denied packet<br>`firewall-cmd --set-log-denied=all`
7. do a PING TEST in the LAN
8. examine the system log and you'll found denied packet log

# **Anything else we need to know?**:

As prompted by the log, I checked the relevant chains in nftables:

`$ nft list ruleset`

and found that they are all empty.

```
...
chain filter_FWD_zone2 {
        jump filter_FORWARD_POLICIES_pre
        jump filter_FWD_zone2_pre
        jump filter_FWD_zone2_log
        jump filter_FWD_zone2_deny
        jump filter_FWD_zone2_allow
        jump filter_FWD_zone2_post
        jump filter_FORWARD_POLICIES_post
        log prefix ""filter_FWD_zone2_DROP: ""
        drop
}
chain filter_FWD_zone2_pre {
}
chain filter_FWD_zone2_log {
}
chain filter_FWD_zone2_deny {
}
chain filter_FWD_zone2_allow {
}
chain filter_FWD_zone2_post {
}
...
```

  So I add a rule

```
table inet firewalld {
        chain filter_FWD_zone2_allow {
                ip saddr 192.168.100.0/24 accept
        }
}
```

by executing `nft add rule inet firewalld filter_FWD_zone2_allow  "ip saddr 192.168.100.0/24 accept"nft add rule inet firewalld filter_FWD_zone2_allow  "ip saddr 192.168.100.0/24 accept"`.

Now the packets can get through but without ip masqueraded. So I took it a step further and added a richrule to zone0 by executing `firewall-cmd --zone=zone0 --add-rich-rule='rule family="ipv4" source address="192.168.100.0/24" masquerade'`.

Everything worked even if I turned off the `masquerade` switch in zone2!

The final configurations are:

| $ firewall-cmd --info-zone=zone0                             | $ firewall-cmd --info-zone=zone2                             |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| zone0 (active)<br/>  target: DROP<br/>  icmp-block-inversion: no<br/>  interfaces: eth0<br/>  sources:<br/>  services:<br/>  ports:<br/>  protocols:<br/>  forward: no<br/>  masquerade: no<br/>  forward-ports:<br/>  source-ports:<br/>  icmp-blocks:<br/>  rich rules:<br/>        rule family="ipv4" source address="192.168.100.0/24" masquerade | zone2 (active)<br/>  target: DROP<br/>  icmp-block-inversion: no<br/>  interfaces: eth2<br/>  sources:<br/>  services:<br/>  ports:<br/>  protocols:<br/>  **forward: no<br/>  masquerade: no<br/>**  forward-ports:<br/>  source-ports:<br/>  icmp-blocks:<br/>  rich rules: |

Now MY purpose is complete: I can forward traffic between the two zones and enable NAT. However, since I changed nftables directly, which might confuse Firewalld in the future, this isn't a good practice.

**Environment**:

- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):

  ```
  $ dnf info firewalld
  Last metadata expiration check: 0:48:07 ago on Sat 19 Feb 2022 03:23:27 PM CST.
  Installed Packages
  Name         : firewalld
  Version      : 1.0.1
  Release      : 2.fc35
  Architecture : noarch
  Size         : 2.0 M
  Source       : firewalld-1.0.1-2.fc35.src.rpm
  Repository   : @System
  From repo    : anaconda
  Summary      : A firewall daemon with D-Bus interface providing a dynamic firewall
  URL          : http://www.firewalld.org
  License      : GPLv2+
  Description  : firewalld is a firewall service daemon that provides a dynamic customizable
               : firewall with a D-Bus interface.
  ```

- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): 

  ```
  $ cat /etc/firewalld/firewalld.conf | grep FirewallBackend
  # FirewallBackend
  FirewallBackend=nftables
  ```

- OS (e.g: `cat /etc/os-release`):

  ```
  $ cat /etc/os-release
  NAME="Fedora Linux"
  VERSION="35 (Workstation Edition)"
  ID=fedora
  VERSION_ID=35
  VERSION_CODENAME=""
  PLATFORM_ID="platform:f35"
  PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
  ANSI_COLOR="0;38;2;60;110;180"
  LOGO=fedora-logo-icon
  CPE_NAME="cpe:/o:fedoraproject:fedora:35"
  HOME_URL="https://fedoraproject.org/"
  DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
  SUPPORT_URL="https://ask.fedoraproject.org/"
  BUG_REPORT_URL="https://bugzilla.redhat.com/"
  REDHAT_BUGZILLA_PRODUCT="Fedora"
  REDHAT_BUGZILLA_PRODUCT_VERSION=35
  REDHAT_SUPPORT_PRODUCT="Fedora"
  REDHAT_SUPPORT_PRODUCT_VERSION=35
  PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
  VARIANT="Workstation Edition"
  VARIANT_ID=workstation
  ```

- Others:

**Comment by erig0** [comment]
You want policies. The were added in v0.9.0. Policies allows filtering traffic flowing between zones.

- https://firewalld.org/2020/09/policy-objects-introduction
- https://firewalld.org/2020/09/policy-objects-filtering-container-and-vm-traffic
