### ISSUE TITLE
Building Dockerfile doesn't work

### ISSUE THREAD

**Issue by vadorovsky** [firewalld/firewalld#921]
**What happened**:

`make dist` failed with:

```bash
Red Hat Universal Base Image 8 (RPMs) - BaseOS  612 kB/s | 797 kB     00:01    
Red Hat Universal Base Image 8 (RPMs) - AppStre 4.3 MB/s | 2.6 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea  22 kB/s |  16 kB     00:00    
No match for argument: intltool
No match for argument: docbook-style-xsl
No match for argument: python3-nftables
Package python3-gobject-base-3.28.3-2.el8.x86_64 is already installed.
Error: Unable to find a match: intltool docbook-style-xsl python3-nftables
Error: error building at STEP "RUN dnf -y install automake autoconf make intltool                    docbook-style-xsl python3-nftables                    python3-gobject-base libxslt glib2-devel": error while running runtime: exit status 1
make[1]: *** [Makefile:854: dist-container] Error 125
make[1]: Leaving directory '/home/vadorovsky/repos/firewalld'
make: *** [Makefile:605: dist] Error 2
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Just do `make dist` or `docker build`.

**Anything else we need to know?**:

I guess that some additional repo is missing?

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): master
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): n/a
- OS (e.g: `cat /etc/os-release`): Manjaro Linux
- Others:

**Comment by erig0** [comment]
Can you try again with `--no-cache` ?
e.g.
```
$ podman build -f Dockerfile  --no-cache
```

**Comment by erig0** [comment]
Since you're interested in using this container image..

It currently requires a dbus and polkit policy on the host. This is because it tries to integrate with the host dbus in order to integrate with the host's NetworkManager. I think it may be better to just start a dbus-daemon inside the container and forget about host integration. Do you have any thoughts on this?

**Comment by vadorovsky** [comment]
> Can you try again with `--no-cache` ? e.g.
> 
> ```
> $ podman build -f Dockerfile  --no-cache
> ```

Same error.

```bash
  podman build -f Dockerfile  --no-cache                                                       ✔ 
STEP 1/9: FROM registry.access.redhat.com/ubi8/ubi
Trying to pull registry.access.redhat.com/ubi8/ubi:latest...
Getting image source signatures
Copying blob 0d875a68bf99 done  
Copying blob 8dfe9326f733 done  
Copying config 52de04277b done  
Writing manifest to image destination
Storing signatures
STEP 2/9: LABEL description="Firewalld daemon and command line interface"
--> 2d9fa1a2491
STEP 3/9: MAINTAINER Firewalld Maintainers <firewalld-users@lists.fedorahosted.org>
--> a890a9ef09b
STEP 4/9: RUN dnf -y install automake autoconf make intltool                    docbook-style-xsl python3-nftables                    python3-gobject-base libxslt glib2-devel
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS  1.3 MB/s | 797 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre 4.6 MB/s | 2.6 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea  33 kB/s |  16 kB     00:00    
No match for argument: intltool
No match for argument: docbook-style-xsl
No match for argument: python3-nftables
Package python3-gobject-base-3.28.3-2.el8.x86_64 is already installed.
Error: Unable to find a match: intltool docbook-style-xsl python3-nftables
Error: error building at STEP "RUN dnf -y install automake autoconf make intltool                    docbook-style-xsl python3-nftables                    python3-gobject-base libxslt glib2-devel": error while running runtime: exit status 1
```

CentOS image has also the `CentOS Stream 8 - Extras` repo. Seems like some kind of Extras repo is needed for RHEL too?

> It currently requires a dbus and polkit policy on the host. This is because it tries to integrate with the host dbus in order to integrate with the host's NetworkManager. I think it may be better to just start a dbus-daemon inside the container and forget about host integration. Do you have any thoughts on this?

Sounds like a great idea. Are you thinking about creating a separate image and container for dbus?

**Comment by vadorovsky** [comment]
Seems like definitely something needs to be done about dbus. I managed to fix the container build error by switching to CentOS, but then I'm hitting:

```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.1158" is not allowed to own the service "org.fedoraproject.FirewallD1" due to security policies in the configuration file
```

**Comment by erig0** [comment]
> CentOS image has also the `CentOS Stream 8 - Extras` repo from which those missing packages get installed. Seems like some kind of Extras repo is needed for RHEL too?

I'm trying to figure out why it works for me. I'll try a different host distribution.

> Sounds like a great idea. Are you thinking about creating a separate image and container for dbus?

No. We should fix the current one.

**Comment by erig0** [comment]
Yikes. Turns out **podman will propagate yum repos from the host** to inside the container. I'll have to update the docker file to use centos8. The packages you note above are _not_ available UBI-8. Maybe the container should jump straight to centos-9 stream.

**Comment by erig0** [comment]
Hi @vadorovsky, can you give #922 a try?

**Comment by erig0** [comment]
> Hi @vadorovsky, can you give #922 a try?

bump.
