### ISSUE TITLE
All macvlans in a interface follow the same rules even when assigned to different zone

### ISSUE THREAD

**Issue by Mukundan314** [firewalld/firewalld#923]
**What happened**:

When multiple macvlans on same interface assigned to different zones, all macvlan use the same rules regardless of the zone it is assigned to (seems to be chosen at random from all zones the macvlans are assigned to)

**What you expected to happen**:

I expected all the macvlans to follow the rules in its corresponding zone.

**How to reproduce it (as minimally and precisely as possible)**:

- Create two macvlans on same interface
- Assign both macvlan to separate zones
- Use different rules in both zones
- See that both macvlans use the rules in one of the zone instead of it's assigned zone

**Anything else we need to know?**:

The macvlans were created with systemd-networkd

**Environment**:
- Firewalld Version: 1.0.3-2
- Firewalld Backend: nftables
- OS: Arch Linux

**Comment by Mukundan314** [comment]
relevant output in `ip a`:
```
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 74:d4:35:78:18:bd brd ff:ff:ff:ff:ff:ff
3: dmz@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 5a:e2:b1:98:59:37 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.9/24 metric 1024 brd 192.168.2.255 scope global dynamic dmz
       valid_lft 86385sec preferred_lft 86385sec
    inet6 fe80::58e2:b1ff:fe98:5937/64 scope link 
       valid_lft forever preferred_lft forever
4: home@enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e2:d6:03:4b:58:24 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.48/24 metric 1024 brd 192.168.2.255 scope global dynamic home
       valid_lft 86385sec preferred_lft 86385sec
    inet6 fe80::e0d6:3ff:fe4b:5824/64 scope link 
       valid_lft forever preferred_lft forever
```

## systemd-networkd files

```
# /etc/systemd/network/10-dmz.netdev

[NetDev]
Name=dmz
Kind=macvlan

[MACVLAN]
Mode=private
```

```
# /etc/systemd/network/20-dmz.network

[Match]
Name=dmz

[Network]
DHCP=yes

[DHCP]
SendHostname=True
Hostname=dmz.crimson
```

```
# /etc/systemd/network/30-home.netdev

[NetDev]
Name=home
Kind=macvlan

[MACVLAN]
Mode=private
```

```
# /etc/systemd/network/40-home.network

[Match]
Name=home

[Network]
DHCP=yes

[DHCP]
SendHostname=True
Hostname=home.crimson
```

```
# /etc/systemd/network/50-enp3s0.network

[Match]
Name=enp3s0

[Network]
LinkLocalAddressing=no
MACVLAN=dmz
MACVLAN=home

[Link]
RequiredForOnline=no
```

## firewalld config

```
$ sudo firewall-cmd --info-zone=dmz
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: dmz
  sources: 
  services: ssh
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
$ sudo firewall-cmd --info-zone=home
home (active)
  target: default
  icmp-block-inversion: no
  interfaces: home
  sources: 
  services: dhcpv6-client mdns samba samba-client samba-dc ssh wsd
  ports: 
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

**Comment by erig0** [comment]
Thanks. I follow what you're trying to do now.

Can you also share the backend (nftables) rule output?
```
# nft list ruleset
```

Or, if you're using the `iptables` backend:
```
# iptables -v -L -t filter
```

**Comment by Mukundan314** [comment]
nftables ruleset: https://gist.github.com/Mukundan314/75d58b270c53d8d666b7e302583b8147

**Comment by erig0** [comment]
Thanks. The generated rules look good. Zone's appear to be dispatched correctly based on the interface names.

Can you give more details about which zone the traffic goes to? Is it INPUT or FORWARD traffic? A way to debug may to add some rich rule logs.

**Comment by Mukundan314** [comment]
Logs captured with `LogDenied=unicast` in `/etc/firewalld/firewalld.conf`:
```
# after "smbclient '\\192.168.2.9\public'" is run on different machine:
Mar 09 22:13:23 crimson kernel: "filter_IN_dmz_REJECT: "IN=dmz OUT= MAC=5a:e2:b1:98:59:37:e0:d5:5e:05:c7:29:08:00 SRC=192.168.2.32 DST=192.168.2.9 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=4550 DF PROTO=TCP SPT=42274 DPT=445 WINDOW=64240 RES=0x00 SYN URGP=0 
Mar 09 22:13:23 crimson kernel: "filter_IN_dmz_REJECT: "IN=dmz OUT= MAC=5a:e2:b1:98:59:37:e0:d5:5e:05:c7:29:08:00 SRC=192.168.2.32 DST=192.168.2.9 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=15342 DF PROTO=TCP SPT=33774 DPT=139 WINDOW=64240 RES=0x00 SYN URGP=0 

# after "smbclient '\\192.168.2.48\public'" is run on different machine
Mar 09 22:13:27 crimson kernel: "filter_IN_dmz_REJECT: "IN=dmz OUT= MAC=5a:e2:b1:98:59:37:e0:d5:5e:05:c7:29:08:00 SRC=192.168.2.32 DST=192.168.2.48 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=64477 DF PROTO=TCP SPT=46060 DPT=445 WINDOW=64240 RES=0x00 SYN URGP=0 
Mar 09 22:13:27 crimson kernel: "filter_IN_dmz_REJECT: "IN=dmz OUT= MAC=5a:e2:b1:98:59:37:e0:d5:5e:05:c7:29:08:00 SRC=192.168.2.32 DST=192.168.2.48 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=17631 DF PROTO=TCP SPT=43046 DPT=139 WINDOW=64240 RES=0x00 SYN URGP=0 
```

Seeing that the `MAC` field in all the logs are the same, I assume that the problem is elsewhere on the network perhaps the router?

PS: I am currently primarily running my network on `ipv4` so pretty sure that `IPv6_rpfilter` shouldn't do anything though I did try disabling it and as expected it did not seem to affect anything.

**Comment by erig0** [comment]
The used MACs look weird indeed. I bet their is weird things going on with ARP.
Can you try these sysctls on the node running firewalld?
```
# sysctl -w net.ipv4.conf.all.arp_ignore=1
# sysctl -w net.ipv4.conf.all.arp_announce=2
```

You may need to flush the ARP cache on all nodes in the network. I assume upping/downing the network interface is sufficient.

For Linux, you can flush the arp cache like this:
```
# ip neigh flush all
```

**Comment by Mukundan314** [comment]
Thank you very much!

adding
```
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
```
to my sysctl config seems to have fixed the problem.

**Comment by erig0** [comment]
This is an interesting combination and others may want to know how to set it up. I think it would make a good blog post at https://firewalld.org/blog. If you have the time, you could open a pull request at [firewalld/firewalld.github.io](https://github.com/firewalld/firewalld.github.io).
