### ISSUE TITLE
No firewalld image on quay.io

### ISSUE THREAD

**Issue by thkukuk** [firewalld/firewalld#924]
**What happened**:
podman pull quay.io/firewalld/firewalld
Trying to pull quay.io/firewalld/firewalld:latest...
WARN[0001] failed, retrying in 1s ... (1/3). Error: initializing source docker://quay.io/firewalld/firewalld:latest: reading manifest latest in quay.io/firewalld/firewalld: unknown: Tag latest was deleted or has expired. To pull, revive via time machine
...

**What you expected to happen**:

README states: "podman pull quay.io/firewalld/firewalld:<ver>"
But there is no image.

**Comment by erig0** [comment]
Broken images were removed (see #921). A new one will be posted for the next set of releases.

**Comment by erig0** [comment]
v1.1.1 released and OCI images are available again: https://quay.io/repository/firewalld/firewalld?tab=tags
