### ISSUE TITLE
OCI container only works if firewalld is also installed on the system due to dbus and polkit

### ISSUE THREAD

**Issue by thkukuk** [firewalld/firewalld#925]
**What happened**:
If you start a firewalld container on a system without firewalld installed, you get an DBUS error:

2022-03-07 17:13:51 ERROR: Exception DBusException: org.freedesktop.DBus.Error.AccessDenied: Request to own name refused by policy

**What you expected to happen**:

The same as if the firewalld is installed into the system: container starts and can communicate with dbus.

**Comment by erig0** [comment]
Right. See #921 and the fix #922.

**Comment by erig0** [comment]
Reopened to allow this to close via #922 merge.
