### ISSUE TITLE
RFE: Support masquerade when the ingress zone has assigned interfaces

### ISSUE THREAD

**Issue by klausenbusk** [firewalld/firewalld#926]
**What would you like to be added**:

Enabling masquerade for a policy when the ingress zone has assigned interfaces is currently [not supported](https://github.com/firewalld/firewalld/blob/e7860d3c67cf7ec757ea4760fa37066bb3b2e8ce/src/firewall/core/io/policy.py#L886). This is due to the backends not supporting it at the time (`iptables` and `nftables`).

`nftables` gained the support in Linux v5.5 (https://github.com/torvalds/linux/commit/28f8bfd1ac948403ebd5c8070ae1e25421560059), so the restriction could be lifted now.

**Why is this needed**:

In some cases matching on both a interface and sources is preferable. In my case I want to masquerade traffic from my VMs with a policy and at the same time allow DHCP traffic from the VMs. Using the same zone is easier to grasp IMO.

**Comment by erig0** [comment]
As we discussed over IRC, I think this is a pretty small change.

firewalld v1.0.0+ officially supports Linux 5.3+. So this change would silently fail (zone dispatch won't match) on 5.3 and 5.4 kernels. That being said, I think users would appreciate this change. We'll just have to document the limitation on 5.3 and 5.4.
