### ISSUE TITLE
firewalld-0.8.2 issue 

### ISSUE THREAD

**Issue by sateesh0457** [firewalld/firewalld#929]
Hi Team,

              I have built firewalld natively on riscv target. Using respective link https://github.com/firewalld/firewalld.git.
 steps : installed dependencies 
etables 
libmnl 
apt-get install python3-dbus dbus python3 ebtables iptables python3-nftables  
apt-get install slip 
intltool 
python3-slip-dbus python3-six - service dep 
polkit 
python3-gobjects 
pip3 install slip 
pip3 install matplotlib 
pip3 install decorator - service  
python3-nftables 
pip3 install PyQt5 
pip3 install podman  
pip3 install nat filters  
apt-get install network-manager  
libftnl 

After installed successfully using systemctl command start services firewalld.

status after running service : 
[0;1;32m●[[0m firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: disabled)
     Active: [[0;1;32mactive (running)[[0m since Mon 2022-03-21 08:39:25 UTC; 15s ago
       Docs: man:firewalld(1)
   Main PID: 16206 (firewalld)
      Tasks: 2 (limit: 9552)
     Memory: 21.1M
     CGroup: /system.slice/firewalld.service
             └─16206 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

ISSUE: reload is failed and firewall-cmd always showing failed. 

I changed backend iptables for checking purpose sudo vi  usr/etc/firewalld/firewalld.conf  nftables and iptables both I am facing proble.

root@user-3:~# firewall-cmd --zone=public --add-port=80/tcp --permanent
success
root@user-3:~# firewall-cmd --reload
Error: COMMAND_FAILED: 'python-nftables' failed: Error: syntax error, unexpected '{'
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld_policy_drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_input", "type": "filter", "hook": "input", "prio": 9, "policy": "drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_forward", "type": "filter", "hook": "forward", "prio": 9, "policy": "drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_output", "type": "filter", "hook": "output", "prio": 9, "policy": "drop"}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_input", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_forward", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_output", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}]}
^

JSON blob:
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"add": {"table": {"family": "inet", "name": "firewalld_policy_drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_input", "type": "filter", "hook": "input", "prio": 9, "policy": "drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_forward", "type": "filter", "hook": "forward", "prio": 9, "policy": "drop"}}}, {"add": {"chain": {"family": "inet", "table": "firewalld_policy_drop", "name": "filter_output", "type": "filter", "hook": "output", "prio": 9, "policy": "drop"}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_input", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_forward", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}, {"add": {"rule": {"family": "inet", "table": "firewalld_policy_drop", "chain": "filter_output", "expr": [{"match": {"left": {"ct": {"key": "state"}}, "op": "in", "right": {"set": ["established", "related"]}}}, {"accept": null}]}}}]}

Test suite running status :

## --------------------------- ##

firewall-offline-cmd

  1: basic options                                   ok
  2: get/list options                                ok
  3: default zone                                    ok
  4: user zone                                       ok
  5: zone interfaces                                 ok
  6: zone sources                                   
 ok
  7: services                                        ok
  8: user services                                   ok
  9: ports                                           ok
 10: source ports                                    ok
 11: protocols                                       ok
 12: masquerade                                      ok
 13: forward ports                                   ok
 14: ICMP block                                      ok
 15: user ICMP types                                 ok
 16: ipset                                           ok
 17: user helpers                                    ok
 18: direct                                          ok
 19: direct nat                                      ok
 20: direct passthrough                              ok
 21: direct ebtables                                 ok
 22: lockdown                                        ok
 23: rich rules good                                 ok
 24: rich rules audit                                ok
 25: rich rules priority                             ok
 26: rich rules bad                                  ok
 27: config validation                               ok

features (FIREWALL_BACKEND)

 28: RFC3964_IPv4                                    ok
 29: service include                                 ok
 30: customer helpers                                ok
 31: lokkit migration                                ok

dbus

 32: firewalld.conf                                  FAILED (firewalld.conf.at:1)
 33: dbus api - services                             FAILED (service.at:1)

firewall-cmd (nftables)

 34: basic options                                   FAILED (firewall-cmd.at:5)
 35: get/list options                                FAILED (firewall-cmd.at:28)
 36: default zone                                    FAILED (firewall-cmd.at:44)
 37: user zone                                       FAILED (firewall-cmd.at:56)
 38: zone interfaces                                 FAILED (firewall-cmd.at:76)
 39: zone sources                                    FAILED (firewall-cmd.at:174)
 40: services                                        FAILED (firewall-cmd.at:226)
 41: user services                                   FAILED (firewall-cmd.at:270)
 42: ports                                           FAILED (firewall-cmd.at:352)
 43: source ports                                    FAILED (firewall-cmd.at:409)
 44: protocols                                       FAILED (firewall-cmd.at:446)
 45: masquerade                                      FAILED (firewall-cmd.at:474)
 46: forward ports                                   FAILED (firewall-cmd.at:507)
 47: ICMP block                                      FAILED (firewall-cmd.at:624)
 48: user ICMP types                                 FAILED (firewall-cmd.at:670)
 49: ipset                                           FAILED (firewall-cmd.at:693)
 50: user helpers                                    FAILED (firewall-cmd.at:884)
 51: direct                                          FAILED (firewall-cmd.at:912)
 52: direct nat                                      FAILED (firewall-cmd.at:985)
 53: direct passthrough                              FAILED (firewall-cmd.at:1009)
 54: direct ebtables                                 FAILED (firewall-cmd.at:1046)
 55: lockdown                                        FAILED (firewall-cmd.at:1091)
 56: rich rules good                                 FAILED (firewall-cmd.at:1158)
 57: rich rules audit                                FAILED (firewall-cmd.at:1187)
 58: rich rules priority                             FAILED (firewall-cmd.at:1195)
 59: rich rules bad                                  FAILED (firewall-cmd.at:1810)
 60: config validation                               FAILED (firewall-cmd.at:1846)

regression (nftables)

 61: --set-log-denied does not zero config           FAILED (rhbz1514043.at:1)
 62: invalid direct rule causes reload error         FAILED (rhbz1498923.at:1)
 63: combined zones name length check                FAILED (pr181.at:1)
 64: ICMP block inversion                            FAILED (gh287.at:1)
 65: individual calls                                FAILED (individual_calls.at:1)
 66: rule deduplication                              FAILED (rhbz1534571.at:3)
 67: invalid syntax in xml files                     FAILED (gh290.at:1)
 68: ICMP block present FORWARD chain                FAILED (icmp_block_in_forward_chain.at:1)
 69: GRE proto helper                                FAILED (pr323.at:1)
 70: ipset with timeout                              FAILED (rhbz1506742.at:1)
 71: no log untracked passthrough queries            FAILED (rhbz1594657.at:1)
 72: set-log-denied w/ ICMP block inversion          FAILED (rhbz1571957.at:1)
 73: query single port added with range              FAILED (rhbz1404076.at:1)
 74: service destination multiple IP versions        FAILED (gh366.at:1)
 75: ipset duplicate entries                         FAILED (rhbz1601610.at:1)
 76: unicode in XML                                  FAILED (gh303.at:1)
 77: forward-port toaddr enables IP forwarding       FAILED (gh335.at:1)
 78: remove forward-port after reload                FAILED (gh482.at:1)
 79: rich rule marks every packet                    FAILED (gh478.at:1)
 80: nftables helper objects                         FAILED (gh453.at:1)
 81: zone dispatch layout                            FAILED (gh258.at:1)
 82: rich rule src/dst with service destination      FAILED (rhbz1715977.at:1)
 83: direct remove-rules per family                  FAILED (rhbz1723610.at:1)
 84: zone sources ordered by name                    FAILED (rhbz1734765.at:1)
 85: missing firewalld.conf file                     FAILED (gh509.at:1)
 86: rich rule source w/ mark action                 FAILED (gh567.at:1)
 87: ipv6 address with brackets                      FAILED (rhbz1779835.at:1)
 88: ipset cleanup on reload/stop                    FAILED (gh330.at:1)

python (nftables)

 89: firewalld_test.py                               FAILED (python.at:3)
 90: firewalld_config.py                             FAILED (python.at:8)
 91: firewalld_rich.py                               FAILED (python.at:13)
 92: firewalld_direct.py                             FAILED (python.at:18)

features (nftables)

 93: RFC3964_IPv4                                    FAILED (rfc3964_ipv4.at:1)
 94: service include                                 FAILED (service_include.at:1)
 95: customer helpers                                FAILED (helpers_custom.at:1)

firewall-cmd (iptables)

 96: basic options                                   FAILED (firewall-cmd.at:5)
 97: get/list options                                FAILED (firewall-cmd.at:28)
 98: default zone                                    FAILED (firewall-cmd.at:44)
 99: user zone                                       FAILED (firewall-cmd.at:56)
100: zone interfaces                                 FAILED (firewall-cmd.at:76)
101: zone sources                                    FAILED (firewall-cmd.at:174)
102: services                                        FAILED (firewall-cmd.at:226)
103: user services                                   FAILED (firewall-cmd.at:270)
104: ports                                           FAILED (firewall-cmd.at:352)
105: source ports                                    FAILED (firewall-cmd.at:409)
106: protocols                                       FAILED (firewall-cmd.at:446)
107: masquerade                                      FAILED (firewall-cmd.at:474)
108: forward ports                                   FAILED (firewall-cmd.at:507)
109: ICMP block                                      FAILED (firewall-cmd.at:624)

still running make check.

Can anybody know how can I fix this issue please suggest me? 

Regards,
Sateesh

**Comment by erig0** [comment]
This looks like your firewall backends (nftables, iptables) are broken.

> Error: COMMAND_FAILED: 'python-nftables' failed: Error: syntax error, unexpected '{'

Maybe nftables is built _without_ JSON support. JSON support is required.

**Comment by sateesh0457** [comment]
Hi erig0,

                    I have installed JSON package support. still, I am facing the same issue. I am using python3-nftables version 0.9.7.
Tell me any alternatives to fix this issue.


Thanks & Regards,
Sateesh

**Comment by erig0** [comment]
nftables needs to be built (compile time) with JSON support. You can verify this by checking that the binary is linked with libjansson.
```
$ ldd $(which nft)
[..]
        libjansson.so.4 => /lib64/libjansson.so.4 (0x00007fd691078000)
[..]
```

**Comment by sateesh0457** [comment]
Hi erigo,

             I built separately  JSON,Jansson packages. I got libraries. using yocto framework nftables package built not version 0.9.7. But internally configuration level PKGCONFIG[jansson] = "--with-json,--without-json,jansson"  support is available. But using lld which [nft] command not available jansson.

But in the lib path separately it's showing libjansson library.
executing steps followed 
Build steps firewalld :

prerequisites : python3, python3-dbus,python3-slip,python3-slip-dbus,python3-gobjects,python3-decorator,nftables,ebtables,iptables,ipset,polkit,podman,docker,NetworkManager  
all these packages are installed.
 
$git clone https://github.com/firewalld/firewalld.git
$cd firewalld
$./autogen.sh
$.configure --disable-docs
$make 
$ make install 

Native build steps can please provide. 

Can you please provide build steps nftables? could you please provide some build steps to get this firewalld.


Thanking you in advance.

Regards,
Sateesh

**Comment by erig0** [comment]
You need to get a working nftables with JSON support.

**Comment by sateesh0457** [comment]
Hi Erig0,

              I tried using Yocto frame work now I am able to get libjansson linking library. But still I am facing issue. 
$ ldd /usr/sbin/nft 

	linux-vdso.so.1 (0x0000003fc9ccb000)
	libnftables.so.1 => /usr/lib/libnftables.so.1 (0x0000003fc9c09000)
	libreadline.so.8 => /usr/lib/libreadline.so.8 (0x0000003fc9bc8000)
	libc.so.6 => /lib/libc.so.6 (0x0000003fc9ac2000)
	/lib/ld-linux-riscv64-lp64d.so.1 (0x0000003fc9ccd000)
	libmnl.so.0 => /usr/lib/libmnl.so.0 (0x0000003fc9abc000)
	libnftnl.so.11 => /usr/lib/libnftnl.so.11 (0x0000003fc9a95000)
	libjansson.so.4 => /usr/lib/libjansson.so.4 (0x0000003fc9a8a000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x0000003fc9a2e000)
	libtinfo.so.5 => /lib/libtinfo.so.5 (0x0000003fc9a07000)

firewalld service status :

[0;1;32m●[[0m firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
     Active: [[0;1;32mactive (running)[[0m since Wed 2020-12-16 15:23:40 UTC; 10min ago
       Docs: man:firewalld(1)
   Main PID: 2597 (firewalld)
      Tasks: 2 (limit: 9552)
     Memory: 37.7M
     CGroup: /system.slice/firewalld.service
             └─2597 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

$firewall-cmd --state 
$failed

$firewall-cmd --reload
$Error: COMMAND_FAILED: 'handle'

getting error :   

Error: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory

internal:0:0-0: Error: Could not process rule: No such file or directory


Please help me now what I have missed.

Thanks & Regards,
Sateesh
