### ISSUE TITLE
Firewalld not rejecting the IP's

### ISSUE THREAD

**Issue by kirana1996** [firewalld/firewalld#943]
Hi,
  
             I'm new to this firewalld and i'm trying to block http service using firewalld-cmd command but still I am able to browse using 
http.
             What I'm expecting is that firewalld needs to block when I'm accessing something in the network or any particular website. 
            Can  somebody please help me how to block ip/website using firewalld.
            **Commands we have tried to block the IP**
                  firewall-cmd --permanent --zone=public --remove-service=http and https
                  firewall-cmd --reload
 and tried rich rule 
                 firewall-cmd --permanent --add-rich-rule='rule family="ipv4" source address="192.168.x.x" reject'
                 firewall-cmd --reload
                firewall-cmd --add-rich-rule='rule family=ipv4 source address=192.168.1.101/32 service name=telnet limit value=1/m    accept'
               firewall-cmd --reload

               
Thanks,

**Comment by erig0** [comment]
Adding a service to a zone will filter traffic _incoming_ from the zone to the _host_.

If you want to filtering _outgoing_ traffic (host to zone), then you need to use a policy.

https://firewalld.org/2020/09/policy-objects-introduction

**Comment by kirana1996** [comment]
Hi @erig0,
            I'm new to this,can you please give me step so i can create policy for block some ip/web. We can able to remove only ssh other than that noting.

**Comment by erig0** [comment]
This is directly from the blog post. Create a policy that affects outgoing packets:

```
# firewall-cmd --permanent --new-policy myOutputPolicy
# firewall-cmd --permanent --policy myOutputPolicy --add-ingress-zone HOST
# firewall-cmd --permanent --policy myOutputPolicy --add-egress-zone ANY
```

Then add your rich rules to the policy:

```
# firewall-cmd --permanent --policy myOutputPolicy --add-rich-rule='rule family="ipv4" source address="192.168.x.x" reject'
# firewall-cmd --permanent --policy myOutputPolicy --add-rich-rule='rule family=ipv4 source address=192.168.1.101/32 service name=telnet limit value=1/m accept'
```

Lastly, reload:

```
# firewalld-cmd --reload
```
