### ISSUE TITLE
Reject rich-rules not working when the destination port has a forwarding rule active in zone where rich rule apply

### ISSUE THREAD

**Issue by Raptor039** [firewalld/firewalld#951]
**What happened**:

When adding a rich-rules to reject an IP adress, this IP is not blocked if the related destination port is forwarded by a `firewall-cmd --add-forward-port` setting configured with firewall-cmd utility.

**What you expected to happen**:

Source IP that shoud be denied to establish a connection.

**How to reproduce it (as minimally and precisely as possible)**:

- Add an interface to public zone
- Remove ssh service from public zone
- Add a port forward from 2222 to 22 to public zone
- Add rich rule to deny some IP source, 1.2.3.4 for instance.

When requesting ssh to port 2222 from 1.2.3.4 adress that should be denied, the ssh connection open.

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`): 1.1.1 (installed from debian 11 backports)
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): nftables
- OS (e.g: `cat /etc/os-release`): debian 11 bullseye
- Others: I'm not a network specialist, maybe a faulty comprehension from me, sorry if this is the case.

**Comment by erig0** [comment]
firewalld will generically accept forwarded ports (nat) in the filter chains. This is to make sure the traffic passes the filtering phase.

If you want to limit the port forwarding then you should be using a rich rule to do the port forward, not `--add-forward-port`.
e.g.
```
# firewall-cmd ... --add-rich-rule='rule family=ipv4 source address=1.2.3.4 forward-port ...'
```
