### ISSUE TITLE
How to Drop 127.0.0.0/8 to specify port

### ISSUE THREAD

**Issue by spacexnasa** [firewalld/firewalld#955]
hello,i hava a question

as the title,how can i drop the source 127.0.0.0/8 to 127.0.0.0/8's specify port eg:2222
if use iptables i can use this
iptables -I INPUT 1 -p tcp --dport 2222 -s 127.0.0.0/8 -d 127.0.0.0/8 -j DROP
but firewall-cmd with direct,can not work
#############
ssh  -p 2222 127.0.0.1 ---- i hope firewalld can stop  someone to visit this port 
#############

-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N FORWARD_IN_ZONES
-N FORWARD_IN_ZONES_SOURCE
-N FORWARD_OUT_ZONES
-N FORWARD_OUT_ZONES_SOURCE
-N FORWARD_direct
-N FWDI_public
-N FWDI_public_allow
-N FWDI_public_deny
-N FWDI_public_log
-N FWDO_public
-N FWDO_public_allow
-N FWDO_public_deny
-N FWDO_public_log
-N INPUT_ZONES
-N INPUT_ZONES_SOURCE
-N INPUT_direct
-N IN_public
-N IN_public_allow
-N IN_public_deny
-N IN_public_log
-N OUTPUT_direct
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -j INPUT_direct
-A INPUT -j INPUT_ZONES_SOURCE
-A INPUT -j INPUT_ZONES
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i lo -j ACCEPT
-A FORWARD -j FORWARD_direct
-A FORWARD -j FORWARD_IN_ZONES_SOURCE
-A FORWARD -j FORWARD_IN_ZONES
-A FORWARD -j FORWARD_OUT_ZONES_SOURCE
-A FORWARD -j FORWARD_OUT_ZONES
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -j OUTPUT_direct
-A FORWARD_IN_ZONES -i ens192 -g FWDI_public
-A FORWARD_IN_ZONES -g FWDI_public
-A FORWARD_OUT_ZONES -o ens192 -g FWDO_public
-A FORWARD_OUT_ZONES -g FWDO_public
-A FWDI_public -j FWDI_public_log
-A FWDI_public -j FWDI_public_deny
-A FWDI_public -j FWDI_public_allow
-A FWDI_public -p icmp -j ACCEPT
-A FWDO_public -j FWDO_public_log
-A FWDO_public -j FWDO_public_deny
-A FWDO_public -j FWDO_public_allow
-A FWDO_public_allow -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
-A FWDO_public_allow -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
-A INPUT_ZONES -i ens192 -g IN_public
-A INPUT_ZONES -g IN_public
-A IN_public -j IN_public_log
-A IN_public -j IN_public_deny
-A IN_public -j IN_public_allow
-A IN_public -p icmp -j ACCEPT
-A IN_public_allow -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
-A IN_public_allow -p tcp -m tcp -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
-A IN_public_allow -p udp -m udp -m conntrack --ctstate NEW,UNTRACKED -j ACCEPT
-A OUTPUT_direct -m state --state RELATED,ESTABLISHED -j ACCEPT

centos 7.9 latest version
firewalld is system's default version

zone public
target default

**Comment by erig0** [comment]
> but firewall-cmd with direct,can not work

Why not? It passes the command verbatim to the iptables backend.

**Comment by spacexnasa** [comment]
> > but firewall-cmd with direct,can not work
> 
> Why not? It passes the command verbatim to the iptables backend.

you can try,can not work

**Comment by kircherlike** [comment]
I tried it today and it does work.

.......
[root@localhost ~]# firewall-cmd --direct --passthrough ipv4 -I INPUT 1 -p tcp --dport 2222 -s 127.0.0.0/8 -d 127.0.0.0/8 -j DROP
success
[root@localhost ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       tcp  --  127.0.0.0/8          127.0.0.0/8          tcp dpt:EtherNet/IP-1
......
Before adding a rule：
[root@localhost ~]# ssh -p 2222 127.0.0.1
ssh: connect to host 127.0.0.1 port 2222: Connection refused
......
Afteer adding a rule：
[root@localhost ~]# ssh -p 2222 127.0.0.1

......

**Comment by spacexnasa** [comment]
> firewall-cmd --direct --passthrough ipv4 -I INPUT 1 -p tcp --dport 2222 -s 127.0.0.0/8 -d 127.0.0.0/8 -j DROP

ok,i will try tomorrow

**Comment by erig0** [comment]
Closing. No response to needinfo and another user reports it works as expected.
