### ISSUE TITLE
Documentation error - firewalld.policy - multiple service tags aren't allowed, actually

### ISSUE THREAD

**Issue by cudevmaxwell** [firewalld/firewalld#957]
**What happened**:

A policy which looks like this:

```
<policy>
...
<rule family="ipv4">
    <destination address="1.1.1.1"/>
    <service name="http"/>
    <service name="https"/>
    <accept/>
  </rule>
...
</policy>
```
causes this error:

```
Invalid rule: More than one element in rule 'rule family="ipv4" destination address="1.1.1.1" service name="http"', ignoring.
```

even though the docs say:

```
service: Is an optional empty-element tag and can be used several times to have more than one service entry enabled
```

**What you expected to happen**:

The `service` tag should be repeatable.

**How to reproduce it (as minimally and precisely as possible)**:

Create a policy with rules with more than one `service` tag.

**Anything else we need to know?**:

**Environment**:
- Firewalld Version (if Fedora based `dnf info firewalld` or commit hash if developing from git `git log -n1 --format=format:"%H"`):
- Firewalld Backend (`cat /etc/firewalld/firewalld.conf | grep FirewallBackend`): nftables
- OS (e.g: `cat /etc/os-release`): RHEL 8.5

**Comment by erig0** [comment]
It can NOT be used multiple times inside a rich rule.
It CAN be used multiple times in a policy.

**Comment by cudevmaxwell** [comment]
Got it, thanks for clarifying. Closing.

**Comment by erig0** [comment]
If you have suggestions to make the docs clearer, then please open a PR. :)

**Comment by cudevmaxwell** [comment]
Haha no further suggestions other than 'drink coffee first' and 'read more slowly' which are really more personal reminders for myself.
