### ISSUE TITLE
INVALID conntrack packets (TCP traffic with FIN, PSH and URG flags) are allowed, but not masqueraded

### ISSUE THREAD

**Issue by rssmith442** [firewalld/firewalld#961]
**What happened**:
Im seeing an issue with Firewalld v. 1.0.4 on Fedora 35 where outbound masquerade is applied via a policy, but malformed packets (with the FIN, PSH and URG flags set) are not being NATed. It appears that all other traffic is being properly NATed via the policy with masquerade enable. This is resulting in leaking of internal addresses to the outer network (out the WAN interface). The policy with masquerade enabled has the ingress zone set to `ANY` and the egress zone set to `external`. The `external` zone has both the WAN interface assigned to it, and the WAN subnet definded as a source.

**What you expected to happen**:
I expect all traffic from that is sent from any zone to the `external` zone to have masquerade `NAT` applied to it.

**How to reproduce it (as minimally and precisely as possible)**:

**From a host inside the network (on the LAN side, which will match the `ANY` statement in the policy.) run **`nmap -v -sX <host outside the network>`**

**Anything else we need to know?**:

It appears that `conntrack` might not be estabilishing a state for this traffic, but i need to do some additional testing in order to confirm that.

**Environment**:
-Installed Packages
Name         : firewalld
Version      : 1.0.4
Release      : 1.fc35
Architecture : noarch
Size         : 2.0 M
Source       : firewalld-1.0.4-1.fc35.src.rpm

-FirewallBackend=nftables

-Fedora Linux 35 (Thirty Five)

-This is the policy i should be hitting, and NAT is working for all traffic except **`TCP packets with the FIN, PSH and URG flags set`**:
```
outbound (active)
  priority: -60
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: external
  services: 
  ports: 
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule family="ipv4" source address="10.0.0.0/16" port port="137" protocol="tcp" drop
	rule family="ipv4" source address="10.0.0.0/16" port port="138" protocol="tcp" drop
	rule family="ipv4" source address="10.0.0.0/16" port port="139" protocol="tcp" drop
	rule family="ipv4" source address="10.0.0.0/16" port port="137" protocol="udp" drop
	rule family="ipv4" source address="10.0.0.0/16" port port="138" protocol="udp" drop
	rule family="ipv4" source address="10.0.0.0/16" port port="139" protocol="udp" drop
```

**Comment by erig0** [comment]
Can you show `--list-all-policies` and `--list-all-zones`?

**Comment by erig0** [comment]
Additionally, can you add this rule and re-run the nmap scan? After which check `dmesg` for "NEW INVALID RULE".

firewalld node:
```
# nft add rule inet firewalld filter_FORWARD index 1 ct state invalid log prefix '"NEW INVALID RULE: "' drop
```

client:
```
# nmap -v -sX <host>
```


firewalld node:
```
# dmesg |grep "NEW INVALID RULE"
```

**Comment by rssmith442** [comment]
Please see the requested output in the attached text file.


[Firewall-cmd-all-zones-all-policies-961.txt](https://github.com/firewalld/firewalld/files/8775589/Firewall-cmd-all-zones-all-policies-961.txt)

Will add the rule and post the results soon.

**Comment by rssmith442** [comment]
Please see the dmesg output in the text file below
[dmesg-961.txt](https://github.com/firewalld/firewalld/files/8775793/dmesg-961.txt)
:

**Comment by erig0** [comment]
Thanks for providing the information. This proves my suspicions.

1. Connection tracking correctly considers these packets `INVALID`.
2. The packets are **not** NAT'd because they are **not** the "first packet in the connection". As per `nft` man page only the first packet will hit the NAT chains. This explains why masquerade does not occur.
3. The packets are allowed due to catch-all rules in the zones with `ACCEPT` `--set-target`.

This could be fixed by moving the `ct state INVALID` check to occur _before_ zone/policy dispatch. Doing so has implications that these packets would no longer be allowed. IMO, that's expected from a strict stateful firewall.

User that DO want to allow `INVALID` packets through could allow them by marking them `NOTRACK` before they hit firewalld's rules.
