### ISSUE TITLE
IPset - doc update

### ISSUE THREAD

**Issue by sghosh151** [firewalld/firewalld#971]
https://firewalld.org/documentation/ipset/

1. "An ipset for IP addresses is either usable for IPv4 or IPv6." 
      Should be: An ipset is composed of either IPv4 or IPv6 address.

2.  "number of rules for black or white listing for"
     Update language: allow or deny

**Comment by TorontoMedia** [comment]
@sghosh151 thank you for taking interest in firewalld having the proper documentation. 

This issue should be filed against the firewalld.org website which is in a separate repository and the can be found [here](https://github.com/firewalld/firewalld.github.io/blob/master/documentation/ipset/index.md).

Also IPSet can be composed of more then just ip addresses, so it should mention that a set of ip addresses can only be composed of IPv4 or IPv6 addresses.

**Comment by sghosh151** [comment]
@TorontoMedia thanks - my mistake
closing this issue.
opened a pull request against the website repo: https://github.com/firewalld/firewalld.github.io/pull/18
