### ISSUE TITLE
firewalld.service - firewalld - dynamic firewall daemon

### ISSUE THREAD

**Issue by youyoubud** [firewalld/firewalld#977]
When I try "sudo apt-get install XX" in ubuntu16.04, I got the error as follows:
`Do you want to continue? [Y/n] y
Setting up firewalld (0.4.0-1ubuntu0.1) ...
Job for firewalld.service failed because the control process exited with error code. See "systemctl status firewalld.service" and "journalctl -xe" for details..........] 
invoke-rc.d: initscript firewalld, action "start" failed.
* firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-06-24 20:17:05 CST; 5ms ago
  Process: 25869 ExecStart=/usr/sbin/firewalld --nofork --nopid (code=exited, status=1/FAILURE)
 Main PID: 25869 (code=exited, status=1/FAILURE)
Jun 24 20:17:05 XXX systemd[1]: Starting firewalld - dynamic firewall daemon...
Jun 24 20:17:05 XXX systemd[1]: firewalld.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 20:17:05 XXX systemd[1]: Failed to start firewalld - dynamic firewall daemon.
Jun 24 20:17:05 XXX systemd[1]: firewalld.service: Unit entered failed state.
Jun 24 20:17:05 XXX systemd[1]: firewalld.service: Failed with result 'exit-code'.
dpkg: error processing package firewalld (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 firewalld
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Then I checked the status of the firewalld with "systemctl status firewalld.service", I got:
`firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-06-24 20:17:05 CST; 3min 14s ago
  Process: 25869 ExecStart=/usr/sbin/firewalld --nofork --nopid (code=exited, status=1/FAILURE)
 Main PID: 25869 (code=exited, status=1/FAILURE)`

Then I tried "firewall-cmd --state", I got:
`Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 24, in <module>
    from gi.repository import GObject
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)`

Now I can't use any "sudo apt install" command because it will show the first error I described.
I really don't know why. It bothers me a lot.
Forgive my poor English.
Thanks for your help.

**Comment by erig0** [comment]
This looks like a distribution packaging issue. Or maybe python is looking in the wrong location (PYTHONPATH, virtualenv). It does not look like a firewalld bug. Please file a bug with your distribution.

This import error is from the `gi` module:
```
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)
```

The firewalld version (0.4.0) is also ancient and unsupported upstream (here).
