### ISSUE TITLE
Documentation is inconsistent on which protocols are accepted for rich language policies

### ISSUE THREAD

**Issue by dead-claudia** [firewalld/firewalld#991]
- https://firewalld.org/documentation/man-pages/firewalld.richlanguage.html says the protocol can only be `tcp` or `udp` for `port`, `forward-port`, and `source-port`.
- https://firewalld.org/documentation/man-pages/firewalld.policy.html says the protocol can be `tcp`, `udp`, `sctp`, and `dccp` for each of those.
- Both consistently state that what's valid for `protocol` depends on what's in `/etc/protocols`.

Which is reality for which? And do they actually just ultimately rely on `/etc/protocols` in the end as well, or is this validated within firewalld itself?

Also, do the related protocol fields correspond with this in zones and helpers as well? Or do they also simply use the hardcoded constants?

**Comment by TorontoMedia** [comment]
Thank you for reporting these errors in consistency. 

Protocols for `port`, `forward-port`, and `source-port` are limited to `tcp|udp|sctp|dccp` and that applies to `zones`  and `helpers` too.

For element `protocol`, it must be an integer between 0 and 255 or a valid protocol in `/etc/protocol`.
